### ISSUE TITLE
Pangolin X11: Indirect GLX rendering context obtained

### ISSUE THREAD

**Issue by YangLiu-DayDreammer** [stevenlovegrove/Pangolin#100]
Hello, today I re-installed my ubuntu 14.04.4 system and installed ROS and Elasticfusion. Everything compiles  well. But when I launch Elasticfusion connecting to Primesense, I got an Error **Pangolin X11: Indirect GLX rendering context obtained**. Guess there is something wrong with OpenGL, but no idea how to solve it. Thanks.

**Comment by olivertai** [comment]
@YangLiu-DayDreammer 
Hello, I have encountered this problem on ubuntu. Have you solve this problem before closing the issue?

**Comment by stevenlovegrove** [comment]
See #309
