### ISSUE TITLE
libc++abi.dylib error on mac 

### ISSUE THREAD

**Issue by coskunyerli** [stevenlovegrove/Pangolin#101]
I execute SimpleDisplay and get error like this 

libc++abi.dylib: terminating with uncaught exception of type pangolin::VideoException: Unable to open recorder URI

please help

**Comment by stevenlovegrove** [comment]
Which branch are you on? I would only expect that error after clicking the record button if ffmpeg isn't installed or something. Does that happen on launch of the program, or after some interaction? You should try HelloPangolin or some of the other samples. You can attach a debugger and look at the source code if you would like to go deeper. Or post a stack trace here for further help.

**Comment by coskunyerli** [comment]
I installed ffmpeg but I get different error when clicking record button. 

[mpeg4 @ 0x7f8a4c8c1600] AVFrame.format is not set
[mpeg4 @ 0x7f8a4c8c1600] Warning: AVFrame.pts=? trying to guess (78)

**Comment by stevenlovegrove** [comment]
Those warnings should not effect output. Does a recording appear in your working directory?
