### ISSUE TITLE
stacking during make

### ISSUE THREAD

**Issue by giancan** [stevenlovegrove/Pangolin#103]
Hi there,
I am trying to compile Pangolin as for the instructions.
I have all required and optional dependencies satisfied but when I run make -j the process freezes at around 80% after
building cxx src/CMakeFiles/pangolin.dir/video/drivers/uvc.cpp.o

In my previous trial it was stopping at openni.cpp.o and I though it was for the libuvc.
So I compiled that as well and now it stacks there as I said and I have no other choise than restarting the computer.

Any suggestions?
Thanks,
G.

**Comment by stevenlovegrove** [comment]
The only similar problem I've heard of has been related to limited system memory (https://github.com/stevenlovegrove/Pangolin/issues/99). Could that be possible?

**Comment by stevenlovegrove** [comment]
I'm closing this out as a probably system issue.
