### ISSUE TITLE
Pangolin SimpleVideo example

### ISSUE THREAD

**Issue by nixiehi** [stevenlovegrove/Pangolin#107]
I want to run SimpleVideo in the example of Pangolin folder.There is a uri that I should give as an argument(the path of the video) but does not matter I do ,it gives an error:
  terminate called after throwing an instance of 'pangolin::VideoException'
  what():  Unrecognised file type.
Can you give an example of the uri? Thanks in advance.

**Comment by stevenlovegrove** [comment]
There are some examples in the video.h header (https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/video/video.h). Some URI's require special support to be built in via optional dependencies (check the readme). If you can't figure out how to make it work, post back here what you're trying to open and I can try to tell you if it's supported.

**Comment by nixiehi** [comment]
This is my code,   ./SimpleVideo file:[stream=1]///home/hilal/Videos/a.avi  .How can I run a video in my user(hilal) folder then Videos then here my video(a.avi) is.    Could you write a sample code,please?

**Comment by stevenlovegrove** [comment]
It sounds like you need to make sure FFMPEG is correctly compiled into Pangolin. When you run CMake, ensure "FFMPEG Found and Enabled" is printed to the console. If it isn't, use ccmake or cmake-gui to modify your avcodec, avformat and avutil variables.

**Comment by stevenlovegrove** [comment]
I'd also recommend using VideoViewer for testing (in the tools directory), and use the following arguments to double check (though what you wrote should also be correct)

./VideoViewer "ffmpeg:///home/hilal/Videos/a.avi"
