### ISSUE TITLE
white display problem in ORB_SLAM2 on mac

### ISSUE THREAD

**Issue by coskunyerli** [stevenlovegrove/Pangolin#109]
I try to build ORB_SLAM2 and succesfully built. This library uses Pangolin

but I get some problem. when I run ORB_SLAM program Pangolin view is white. there is no image on the screen.I ran Pangolin examples and I got no error. in ORB_SLAM Pangolin view is white.However program is running.

All of them are on mac by the way. In linux there is no problem. 

Any idea for solving problem ?

**Comment by stevenlovegrove** [comment]
As a guess, ORB_SLAM might be using a texture format that is not supported by the graphics card on your mac. This has happened to me in the past. You should check in ORB_SLAM if any OpenGL errors are occurring by calling glGetError()​ in a few places throughout the display code, and in particular after uploading any video frame data to a texture.

**Comment by apatzer** [comment]
@stevenlovegrove I have this issue on both ORB_SLAM2 and LSD_SLAM (the @mp3_guy Thomas Whelan version). Can you tell us what type of textures typically cause OpenGL errors?

**Comment by stevenlovegrove** [comment]
If I remember correctly, I think it was floating point single channel textures. I just had a really quick look at ORB_SLAM2, and I can't see any texture use, though the clear colour is set to white, so a white screen is the expected starting state from what I can tell. You should double check that any feature or map draw calls are actually being made. If I were you I'd try putting some simple OpenGL calls from a Pangolin sample that you know works around this line (https://github.com/raulmur/ORB_SLAM2/blob/master/src/Viewer.cc#L126) to see what happens.

**Comment by stevenlovegrove** [comment]
@apatzer Do you still believe this to be a Pangolin bug, or should I close this issue?
