### ISSUE TITLE
pangolin_export.h is missing

### ISSUE THREAD

**Issue by kingstarcraft** [stevenlovegrove/Pangolin#113]
Hi,
I  successfully use cmake and vs2013 to bulid pangolin in windows,but when I use it to bulid orb_slam2 project , the error I get like this:
 can't open pangonlin/pangolin_export.h,no such file or directory

**Comment by stevenlovegrove** [comment]
You should check that ORB_SLAM2 includes Pangolin headers in the recommended way:

find_package(Pangolin 0.2 REQUIRED)
include_directories(${Pangolin_INCLUDE_DIRS})

${Pangolin_INCLUDE_DIRS} includes two paths, one of which appears to be missing from your ORB_SLAM build.

**Comment by stevenlovegrove** [comment]
Closing. Please re-open if you find the method above to be broken.
