### ISSUE TITLE
automated install

### ISSUE THREAD

**Issue by ahundt** [stevenlovegrove/Pangolin#120]
I've created an automated install script which should work on OS X and Linux which uses [homebrew](http://brew.sh) / [linuxbrew](http://linuxbrew.sh):

Install homebrew-robotics as described in the readme.md:
https://github.com/ahundt/homebrew-robotics

then run:

```
brew install pangolin
```

that's it! 

If desired I can create more detailed instructions for inclusion in the readme.md

**Comment by stevenlovegrove** [comment]
Great, thanks! I'm not a homebrew user myself, but I'm sure there are people who will find it handy.

**Comment by autosquid** [comment]
@ahundt  why not directly submit it to `homebrew-core`?

**Comment by ahundt** [comment]
@autosquid Pangolin is probably sufficiently popular to be accepted into https://github.com/Homebrew/homebrew-science if you'd like to do the small tweaks needed and submit the pull request.

**Comment by stevenlovegrove** [comment]
@autosquid @ahundt I would be very happy if someone wanted to take care of that. Let me know if there are any small tweaks needed for Pangolin itself.
