### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by ManyuChang** [stevenlovegrove/Pangolin#130]
when I run 'make -j',displaying following context: 

Linking CXX shared library libpangolin.so
/usr/bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/libpangolin.so] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2

**Comment by ManyuChang** [comment]
I have solved it by the modifying command" cmake -G "Unix Makefiles" -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so.1 -DCPP11_NO_BOOST=1 "..

**Comment by stevenlovegrove** [comment]
Interesting - I've not seen that before. Is this due to conflicting versions of Python on your machine, or do you think a change is required in Pangolin?

**Comment by ManyuChang** [comment]
Maybe python on my machine should be recompile , I just let it find "libpython2.7.so". And Pangolin is great!

**Comment by stevenlovegrove** [comment]
Glad to hear it.
