### ISSUE TITLE
Incompatible with ffmpeg 3.1.0?

### ISSUE THREAD

**Issue by jiapei100** [stevenlovegrove/Pangolin#133]
Looks like Pangolin is TOO old?
Current Pangolin is NOT compatible with ffmpeg-git? Say, ffmpeg 3.1.0?

Cheers
Pei

**Comment by stevenlovegrove** [comment]
FFMPEG is the bane of my existence. See https://github.com/stevenlovegrove/Pangolin/issues/27 https://github.com/stevenlovegrove/Pangolin/pull/56 https://github.com/stevenlovegrove/Pangolin/issues/131 etc. It's API removes / renames methods regularly and there are two major forks of it (ffmpeg and libav), both of which are used in different Ubuntu versions. I generally try to support ffmpeg for Ubuntu releases, but I will take patches for other versions if you have some which will not break versions from recent Ubuntu distros.

**Comment by jiapei100** [comment]
@stevenlovegrove 
Check this [https://github.com/jiapei100/Pangolin/tree/ffmpeg3](url)
It took me a whole day... 
Any test code for me to try?

**Comment by stevenlovegrove** [comment]
Thanks for those commits, though as per the README, can you apply your changes against the devel branch?
