### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sweeneychris** [stevenlovegrove/Pangolin#134]
Thanks for maintaining an awesome library! I have very limited OpenGL experience and Pangolin has really helped make things a breeze for me.

Any chance you could issue a new release? The current master branch does not compile for me on Ubuntu 14.04, but the development branch works great and clearly has many improvements to the master branch.

**Comment by stevenlovegrove** [comment]
I'm glad it's proving useful. Sure, I can do that. Give me a day or so.

**Comment by stevenlovegrove** [comment]
Okay, I just bumped to v0.4
