### ISSUE TITLE
Easy way of binding textures to uniform sampler2Ds

### ISSUE THREAD

**Issue by jstraub** [stevenlovegrove/Pangolin#144]
Is there a simple way of binding a texture to a uniform sampler2D variable that can be used in a custom shader? Something like: 

> GlSlProgram::SetUniform("textureSampler0",texture0);

One would probably also need a way of unbinding the texture.

**Comment by stevenlovegrove** [comment]
Unless there is a new way that I don't know about, you cannot set samplers as uniforms. You have to use glActiveTexture (https://www.opengl.org/sdk/docs/man/docbook4/xhtml/glActiveTexture.xml) and Texture::Bind to select which textures are bound to the texture units for your shaders. By default, sampler0 will already be bound, so you can just bind / unbind textures as per the fixed pipeline if you are only using one texture.
