### ISSUE TITLE
mingw compile failure

### ISSUE THREAD

**Issue by gohyz** [stevenlovegrove/Pangolin#150]
Hi All.
     I met a problem when I want to build the latest version in win10 with gcc5.3.0 in MinGw in CodeBlock(16.01)
And I generate the CodeBlock Project with CMake-GUI(3.6.0).
Everything is OK.
But when it process to libpng, the procedure is failed. 
Do anybody meet this problem?(When I selected to build with MSVC 2015 x64, everything is OK)
![image](https://cloud.githubusercontent.com/assets/22606313/19060256/f4bbf0b0-8a18-11e6-87d1-a2bcb2d7e22a.png)

///////////////////////////////
[ 16%] Built target __zlib
C:/MinGW/bin/mingw32-make.exe -f external\CMakeFiles__libpng.dir\build.make external/CMakeFiles/__libpng.dir/depend
mingw32-make.exe[2]: Entering directory 'E:/OrbSlam/Pangonlin_builds'
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" E:\OrbSlam\Pangolin-master E:\OrbSlam\Pangolin-master\external E:\OrbSlam\Pangonlin_builds E:\OrbSlam\Pangonlin_builds\external E:\OrbSlam\Pangonlin_builds\external\CMakeFiles__libpng.dir\DependInfo.cmake --color=
mingw32-make.exe[2]: Leaving directory 'E:/OrbSlam/Pangonlin_builds'
C:/MinGW/bin/mingw32-make.exe -f external\CMakeFiles__libpng.dir\build.make external/CMakeFiles/__libpng.dir/build
mingw32-make.exe[2]: Entering directory 'E:/OrbSlam/Pangonlin_builds'
[ 17%] Performing update step for '__libpng'
cd /d E:\OrbSlam\Pangonlin_builds\external\libpng\src__libpng && "C:\Program Files\CMake\bin\cmake.exe" -P E:/OrbSlam/Pangonlin_builds/external/libpng/tmp/__libpng-gitupdate.cmake
[ 18%] Performing configure step for '__libpng'
cd /d E:\OrbSlam\Pangonlin_builds\external\libpng\src__libpng-build && "C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_PREFIX=E:/OrbSlam/Pangonlin_builds/external/libpng -DZLIB_INCLUDE_DIR=E:/OrbSlam/Pangonlin_builds/external/zlib/include -DZLIB_LIBRARY=E:/OrbSlam/Pangonlin_builds/external/zlib/lib/zlibstatic_.lib -DCMAKE_BUILD_TYPE= "-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG" -DCMAKE_C_FLAGS_DEBUG=-g "-DCMAKE_C_FLAGS_MINSIZEREL=-Os -DNDEBUG" "-DCMAKE_C_FLAGS_RELWITHDEBINFO=-O2 -g -DNDEBUG" "-GCodeBlocks - MinGW Makefiles" E:/OrbSlam/Pangonlin_builds/external/libpng/src/__libpng
Re-run cmake no build system arguments
CMake Warning (dev) at CMakeLists.txt:301 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
  The LOCATION property should not be read from target "png16".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at CMakeLists.txt:317 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
  The LOCATION property should not be read from target "png16_static".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Configuring done
-- Generating done
-- Build files have been written to: E:/OrbSlam/Pangonlin_builds/external/libpng/src/__libpng-build
cd /d E:\OrbSlam\Pangonlin_builds\external\libpng\src__libpng-build && "C:\Program Files\CMake\bin\cmake.exe" -E touch E:/OrbSlam/Pangonlin_builds/external/libpng/src/__libpng-stamp/__libpng-configure
[ 19%] Performing build step for '__libpng'
cd /d E:\OrbSlam\Pangonlin_builds\external\libpng\src__libpng-build && C:/MinGW/bin/mingw32-make.exe
mingw32-make.exe[3]: Entering directory 'E:/OrbSlam/Pangonlin_builds/external/libpng/src/__libpng-build'
"C:\Program Files\CMake\bin\cmake.exe" -HE:\OrbSlam\Pangonlin_builds\external\libpng\src__libpng -BE:\OrbSlam\Pangonlin_builds\external\libpng\src__libpng-build --check-build-system CMakeFiles\Makefile.cmake 0
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_progress_start E:\OrbSlam\Pangonlin_builds\external\libpng\src__libpng-build\CMakeFiles E:\OrbSlam\Pangonlin_builds\external\libpng\src__libpng-build\CMakeFiles\progress.marks
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\Makefile2 all
mingw32-make.exe[4]: Entering directory 'E:/OrbSlam/Pangonlin_builds/external/libpng/src/__libpng-build'
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\png16.dir\build.make CMakeFiles/png16.dir/depend
mingw32-make.exe[5]: Entering directory 'E:/OrbSlam/Pangonlin_builds/external/libpng/src/__libpng-build'
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" E:\OrbSlam\Pangonlin_builds\external\libpng\src__libpng E:\OrbSlam\Pangonlin_builds\external\libpng\src__libpng E:\OrbSlam\Pangonlin_builds\external\libpng\src__libpng-build E:\OrbSlam\Pangonlin_builds\external\libpng\src__libpng-build E:\OrbSlam\Pangonlin_builds\external\libpng\src__libpng-build\CMakeFiles\png16.dir\DependInfo.cmake --color=
mingw32-make.exe[5]: Leaving directory 'E:/OrbSlam/Pangonlin_builds/external/libpng/src/__libpng-build'
*_C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\png16.dir\build.make CMakeFiles/png16.dir/build
**mingw32-make.exe[5]: **\* No rule to make target 'E:/OrbSlam/Pangonlin_builds/external/zlib/lib/zlibstatic_.lib', needed by 'libpng16.dll'.  Stop.
mingw32-make.exe[4]: *_\* [CMakeFiles/png16.dir/all] Error 2**
mingw32-make.exe[3]: **\* [all] Error 2
mingw32-make.exe[5]: Entering directory 'E:/OrbSlam/Pangonlin_builds/external/libpng/src/__libpng-build'
mingw32-make.exe[2]: **\* [external/libpng/src/__libpng-stamp/__libpng-build] Error 2
mingw32-make.exe[1]: **\* [external/CMakeFiles/__libpng.dir/all] Error 2
mingw32-make.exe: **\* [all] Error 2
mingw32-make.exe[5]: Leaving directory 'E:/OrbSlam/Pangonlin_builds/external/libpng/src/__libpng-build'
CMakeFiles\Makefile2:142: recipe for target 'CMakeFiles/png16.dir/all' failed**
mingw32-make.exe[4]: Leaving directory 'E:/OrbSlam/Pangonlin_builds/external/libpng/src/__libpng-build'
Makefile:137: recipe for target 'all' failed
mingw32-make.exe[3]: Leaving directory 'E:/OrbSlam/Pangonlin_builds/external/libpng/src/__libpng-build'
external\CMakeFiles__libpng.dir\build.make:110: recipe for target 'external/libpng/src/__libpng-stamp/__libpng-build' failed
mingw32-make.exe[2]: Leaving directory 'E:/OrbSlam/Pangonlin_builds'
CMakeFiles\Makefile2:196: recipe for target 'external/CMakeFiles/__libpng.dir/all' failed
mingw32-make.exe[1]: Leaving directory 'E:/OrbSlam/Pangonlin_builds'
E:/OrbSlam/Pangonlin_builds/Makefile:126: recipe for target 'all' failed
Process terminated with status 2 (0 minute(s), 37 second(s))
5 error(s), 0 warning(s) (0 minute(s), 37 second(s))

**Comment by stevenlovegrove** [comment]
See issue https://github.com/stevenlovegrove/Pangolin/issues/137 for a similar problem. Pangolin is trying to clone and build some libraries for you but you don't have git on your path for it to do so. You can either make sure cmake has access to git (and the internet), or turn off the options listed in #137

**Comment by snphnolt** [comment]
Hi,

I entcounter a similiar problem.
How do I give cmake the permission to access git?
Thanks in advance
