### ISSUE TITLE
SaveRenderNow stores empty image

### ISSUE THREAD

**Issue by christian-rauch** [stevenlovegrove/Pangolin#162]
What is the correct way to use `SaveRenderNow` to render and store the current view?

If I use `d_cam.SaveRenderNow("cube");` in the SimpleDisplay example (after rendering the cube) instead of `d_cam.SaveOnRender("cube");`, I only get an empty png file.

**Comment by stevenlovegrove** [comment]
The requirement (which I should document better) is that the View (or a child) has an overload of Render() that actually does something, or it's extern_draw_function is defined. If you are rendering using Activate() or alike in your loop, it cannot work. You could do something similar by setting up a framebuffer and rendering to that instead, then saving the buffer.

**Comment by christian-rauch** [comment]
I see, `Render()` is only pure virtual. I actually tried to use `GlFramebuffer` before, but struggled to correctly render into an image which has a higher resolution than the window (or monitor).

I could solve my problem by using two `glViewport` with different resolutions. For reference, this is the way that I render the same scene on-screen and off-screen at different resolutions:

```
  const uint w = 2048;
  const uint h = 2048;

  // off-screen buffer
  pangolin::GlTexture color(w,h);
  pangolin::GlRenderBuffer depth(w,h);
  pangolin::GlFramebuffer fbo(color, depth);

  // Default hooks for exiting (Esc) and fullscreen (tab).
  while( !pangolin::ShouldQuit() )
  {
    // clear and render into on-screen buffer
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);    

    d_cam.Activate(s_cam);
    glColor3f(1.0,1.0,1.0);
    pangolin::glDrawColouredCube();

    if( pangolin::Pushed(save_cube) ) {
        // new view at higher resolution
        glViewport(0,0,w,h);

        // activate framebuffer
        fbo.Bind();
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

        // render into frame buffer
        glColor3f(1.0,1.0,1.0);
        pangolin::glDrawColouredCube();

        glFlush();

        // write image
        pangolin::Image<unsigned char> buffer;
        pangolin::VideoPixelFormat fmt = pangolin::VideoFormatFromString("RGBA32");
        buffer.Alloc(w, h, w * fmt.bpp/8 );
        glReadBuffer(GL_BACK);
        glPixelStorei(GL_PACK_ALIGNMENT, 1); // TODO: Avoid this?
        glReadPixels(0,0,w,h, GL_RGBA, GL_UNSIGNED_BYTE, buffer.ptr );
        pangolin::SaveImage(buffer, fmt, "cube_now.png", false);
        buffer.Dealloc();

        // deactivate frame buffer
        fbo.Unbind();
    }

    // Swap frames and Process Events
    pangolin::FinishFrame();
  }
```

**Comment by stevenlovegrove** [comment]
if you enjoy lambdas, you could also use one of those for your drawing:

```
...
d_cam.extern_draw_function = [&](pangolin::View&){
  d_cam.Activate(s_cam);
  glColor3f(1.0,1.0,1.0);
  pangolin::glDrawColouredCube();
};
...
while(...)
{
  if(...) {
    d_cam.SaveRenderNow("cube.png");
  }
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
  pangolin::FinishFrame();  
}
```

This would cause d_cam to be rendered automatically within FinishFrame and enable use of SaveRenderNow(...)
