### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ASif2660** [stevenlovegrove/Pangolin#163]
Hello all,

I am trying to build and install Pangolin in my virtual machine Ubuntu 14.04. However the system turns off automatically after I enter make -j command. . Kindly help me out.

Asif.

This is the output of cmake .. in my build directory 

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
Build type not set (defaults to release)
-DCMAKE_BUILD_TYPE=Debug for debug
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Python Found and Enabled
-- Eigen Found and Enabled
-- libdc1394 Found and Enabled
-- V4L Found and Enabled
-- Performing Test HAVE_FFMPEG_MAX_ANALYZE_DURATION2
-- Performing Test HAVE_FFMPEG_MAX_ANALYZE_DURATION2 - Failed
-- Performing Test HAVE_FFMPEG_AVFORMAT_ALLOC_OUTPUT_CONTEXT2
-- Performing Test HAVE_FFMPEG_AVFORMAT_ALLOC_OUTPUT_CONTEXT2 - Failed
-- Performing Test HAVE_FFMPEG_AVPIXELFORMAT
-- Performing Test HAVE_FFMPEG_AVPIXELFORMAT - Success
-- ffmpeg Found and Enabled
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- libpng Found and Enabled
-- libjpeg Found and Enabled
-- libtiff Found and Enabled
-- libopenexr Found and Enabled
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Oculus NOT found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/canm/Pangolin-master/build

After I run make -j the building stops at this point 
Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/ffmpeg.cpp.o

**Comment by stevenlovegrove** [comment]
This sounds similar to issue https://github.com/stevenlovegrove/Pangolin/issues/99 . If your system or make is crashing, it's unlikely to be Pangolin's fault. Try increasing the memory for your VM.

**Comment by stevenlovegrove** [comment]
Closing this since it's unlikely to be related to Pangolin.
