### ISSUE TITLE
Release v0.5 do not accept patch to work without OpenGL

### ISSUE THREAD

**Issue by OtacilioNeto** [stevenlovegrove/Pangolin#165]
Pangolin release v0.3 works without OpenGL with the patch attached. Release v0.5 do not accept the patch and not works without OpenGL.
[patch-src_display_device_display__x11.txt](https://github.com/stevenlovegrove/Pangolin/files/553244/patch-src_display_device_display__x11.txt)

**Comment by stevenlovegrove** [comment]
Hi - could you explain what you mean?

**Comment by OtacilioNeto** [comment]
Hi Steve

Some times the users needs pangolin on machines that do not have OpenGL full features drivers instaled, like Linux or FreeBSD virtualbox guest machines without 3D acceleration enabled. In version v0.3 of Pangolin, the attached patch can be applied to pangolin, and this one can run in this machines with lose of performance, but run. In version v0.5 the patch can not be applied more because of so many modifications in original files. So, I reported and attached here to be registered and if someone give a try to make another version of the patch.

[]'s

**Comment by stevenlovegrove** [comment]
Ah, I see. Thank you.

**Comment by stevenlovegrove** [comment]
This is quite old now, closing. Thanks again.
