### ISSUE TITLE
/usr/bin/ld: cannot find -lPUBLIC

### ISSUE THREAD

**Issue by KevenLee** [stevenlovegrove/Pangolin#168]
Hello, when I compiler the pangolin in ubuntu12.04, I encounter those error:

[ 80%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/v4l.cpp.o
[ 82%] Building C object src/CMakeFiles/pangolin.dir/fonts.c.o
Linking CXX shared library libpangolin.so
/usr/bin/ld: cannot find -lPUBLIC
/usr/bin/ld: cannot find -lPUBLIC
/usr/bin/ld: cannot find -lPUBLIC
/usr/bin/ld: cannot find -lPUBLIC
/usr/bin/ld: cannot find -lPUBLIC
/usr/bin/ld: cannot find -lPUBLIC
/usr/bin/ld: cannot find -lPUBLIC
/usr/bin/ld: cannot find -lPUBLIC
/usr/bin/ld: cannot find -lPUBLIC
/usr/bin/ld: cannot find -lPUBLIC
/usr/bin/ld: cannot find -lPUBLIC
/usr/bin/ld: cannot find -lPUBLIC
/usr/bin/ld: cannot find -lPUBLIC
collect2: error: ld returned 1 exit status
make[2]: *** [src/libpangolin.so] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2

how should I do.

**Comment by stevenlovegrove** [comment]
I do not know how the library 'PUBLIC' is getting into the linker string - I've not seen this before. Can you share your build/src/PangolinTargets.cmake file?

**Comment by KevenLee** [comment]
Hello，I find some PUBLIC in files :
1. CMakeModules/EnsureSymbolsLoaded.cmake 
    target_link_libraries(${target} PUBLIC  "-u ${symbol}")

2. src/CMakeLists.txt 
    target_link_libraries(${LIBRARY_NAME} PUBLIC  ${LINK_LIBS})

I think 'PUBLIC' do not means library here, because when I remove those PUBLIC, all things go well.

**Comment by stevenlovegrove** [comment]
In that case, you may wish to revert to the last tagged version of
pangolin. The line you mentioned is new and relates to enabling video
drivers. If it doesn't work correctly, you may have trouble reading video.
I plan on making some more fixes to that mechanism soon.

**Comment by KevenLee** [comment]
some error happen after I removed 'PUBLIC'. 

I run ORB-SLAM2 with pangolin.

terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Unable to retrieve framebuffer options

Can you tell me how to fix it?

Thanks

**Comment by stevenlovegrove** [comment]
See my reply to your comment posted here: https://github.com/stevenlovegrove/Pangolin/issues/74

**Comment by stevenlovegrove** [comment]
Regarding your original post, I believe I should have just fixed that with commit f807ff742dbd441b9acb99a3d688ab971a385154

**Comment by KevenLee** [comment]
I update the pangolin codes now, but, if I do not remove 'PUBLIC' in the files I mentioned before, I still find something are wrong as following:

Linking CXX shared library libpangolin.so
/usr/bin/ld: cannot find -lPUBLIC
collect2: error: ld returned 1 exit status

OS: ubuntu 12.04

> Regarding your original post, I believe I should have just fixed that with commit f807ff7

**Comment by stevenlovegrove** [comment]
Oops - sorry! I found it in exactly one file which I have just corrected in 4c67c63bc69ec45d2dcd05fadc9c33192636a372

That is the one reference you're referring too, right? It was causing you trouble because your version of cmake must be quite old.
