### ISSUE TITLE
opengl error 1282

### ISSUE THREAD

**Issue by M1234Thomas** [stevenlovegrove/Pangolin#170]
Hello,

I am getting an error as follows.

OpenGL Error: XX (1282)
In: \ElasticFusion\Pangolin-master\include\pangolin/gl/gl.hpp, line 562

I have checked the graphics card and is set to use NVIDIA to use all the times. 
I can not figure out what the issue is.

**Comment by stevenlovegrove** [comment]
That error is GL_INVALID_OPERATION. Pangolin frequently checks glGetError() via the macro CheckGlDieOnError(), and if it fails it means that there has been an OpenGL error between this call and the last call of CheckGlDieOnError(), which may not have been recently. I'm afraid you will need to do some debugging to find out exactly where this error is stemming from. You can insert more CheckGlDieOnError() calls into your code to narrow it down.
