### ISSUE TITLE
Can't display text on view

### ISSUE THREAD

**Issue by alchkim** [stevenlovegrove/Pangolin#172]
Hi, I'm currently modified the HelloPangolin example file to see if I could get text to appear on the view and am having some trouble getting it to work and only seeing boxes. Below is my modified version of main.cpp in HelloPangolin.

```
#include <pangolin/pangolin.h>
#include <pangolin/compat/glutbitmap.h>

int main( int /*argc*/, char** /*argv*/ )
{  
    pangolin::CreateWindowAndBind("Main",640,480);
    glEnable(GL_DEPTH_TEST);

    // Define Projection and initial ModelView matrix
    pangolin::OpenGlRenderState s_cam(
        pangolin::ProjectionMatrix(640,480,420,420,320,240,0.2,100),
        pangolin::ModelViewLookAt(-2,2,-2, 0,0,0, pangolin::AxisY)
    );

    // Create Interactive View in window
    pangolin::Handler3D handler(s_cam);
    pangolin::View& d_cam = pangolin::CreateDisplay()
            .SetBounds(0.0, 1.0, 0.0, 1.0, -640.0f/480.0f)
            .SetHandler(&handler);

    while( !pangolin::ShouldQuit() )
    {
        // Clear screen and activate view to render into
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
        d_cam.Activate(s_cam);

        glRasterPos2f(0.0, 0.0);
        glColor3f(1,1,1);        
        std::string word = "Hello World";
        const unsigned char* bob = (const unsigned char*)word.c_str();
        glutBitmapString(0, bob);

        // Swap frames and Process Events
        pangolin::FinishFrame();
    }
    
    return 0;
}
```
I also tried to use
```
pangolin::GlFont::I().Text("Hello World").Draw()
```
but am still getting boxes. I did not see any message stating that the font was unable to be initialized. Any ideas on how I can make this work?

**Comment by stevenlovegrove** [comment]
It isn't very intuitive, but you must enable alpha blending for this to work, since Pangolin implements text rendering using an alpha texture. For an example, see this bit of code:
https://github.com/stevenlovegrove/Pangolin/blob/master/src/handler/handler_image.cpp#L138

The statefullness of OpenGL is a pain-point here - I should probably save the state, change it, and pop it within the Test(..).Draw() method.

**Comment by alchkim** [comment]
Thanks for the help. Enabling alpha blending solved the issue for me.

**Comment by wenwenqingqing** [comment]
https://github.com/stevenlovegrove/Pangolin/blob/master/src/handler/handler_image.cpp#L138
Sorry. This link is unavailable. 404

**Comment by wenwenqingqing** [comment]
@stevenlovegrove
