### ISSUE TITLE
Text rendering. Letters appearing as rectangular blocks

### ISSUE THREAD

**Issue by pianoza** [stevenlovegrove/Pangolin#173]
UPD. This is probably more like a question, not an issue

I want to show a text as a label in a 3D scene, so the text will always show up facing the camera, but move when view is changed. I am using HelloPangolin example to implement this, and the output I got so far is the following:

![example](https://cloud.githubusercontent.com/assets/3731130/20248734/0f5ee0a6-a9e2-11e6-9f32-3a212d9adc8b.png)

As you can see, the text is appearing in rectangular forms. I added the following code to the HelloPangolin example

```
std::string str = "Hello!";
pangolin::GlFont glFont("/Full/Path/To/Pangolin/src/_embed_/fonts/AnonymousPro.ttf", 64.0);
while( !pangolin::ShouldQuit() )
{
        // ....
        // code from the example + sphere
        // ....
        glColor3f(0.0, 0.0, 1.0);
        pangolin::GlText txt = glFont.Text(str.c_str());
        txt.Draw(0.5, 0.5, 0.5);
        pangolin::FinishFrame();
}
```
Could anyone help to fix this or suggest another way to show a text on a scene?

**Comment by stevenlovegrove** [comment]
Please see issue https://github.com/stevenlovegrove/Pangolin/issues/172

**Comment by pianoza** [comment]
@stevenlovegrove thank you very much, and sorry for the duplicate question, next time will look for similar issues better before posting anything.

**Comment by stevenlovegrove** [comment]
Not to worry. I will leave this open actually, because I should try to find a solution!
