### ISSUE TITLE
Getting image from window

### ISSUE THREAD

**Issue by AlejandroSilvestri** [stevenlovegrove/Pangolin#175]
Hi, I'm so new to Pangolin.
I'm looking for a way to get an image (a opencv Mat) from Pangolin render.
Im not talking about saving an image to a file, but getting its pixel matrix in memory.

Thank you

**Comment by stevenlovegrove** [comment]
If you mean that you'd like to use the pixels displayed on the screen, you can use glReadPixels to read from the back buffer:

```
    pangolin::Image<unsigned char> buffer;
    pangolin::VideoPixelFormat fmt = pangolin::VideoFormatFromString("RGBA32");
    buffer.Alloc(v.w, v.h, v.w * fmt.bpp/8 );
    glReadBuffer(GL_BACK);
    glPixelStorei(GL_PACK_ALIGNMENT, 1);
    glReadPixels(v.l, v.b, v.w, v.h, GL_RGBA, GL_UNSIGNED_BYTE, buffer.ptr );
```

Converting from a pangolin::Image to an OpenCV Mat should be simple.

**Comment by AlejandroSilvestri** [comment]
That was fast!  
I'm trying the code right now.  I'll leave this issue open if I can add some code.
Thank you very much.

**Comment by AlejandroSilvestri** [comment]
It works fine.  Converting to Mat:

        // pangolin::Viewport v is our image source
        cv::Mat img, imgBuffer = cv::Mat(v.h, v.w, CV_8UC4, buffer.ptr);
        cv::cvtColor(imgBuffer, img,  cv::COLOR_RGBA2BGR);
        cv::flip(imagen, img, 0);
        cv::imshow("some window", img);
