### ISSUE TITLE
show image

### ISSUE THREAD

**Issue by myBestLove** [stevenlovegrove/Pangolin#180]
first thanks for your work.
I want to show my image in the windows , i tried to modify the simpledisplayimage,like this

     void setImageData(unsigned char * imageArray,Mat image){

      // for(int i = 0 ; i < size;i++) {

      //   imageArray[i] = (unsigned char)(rand()/(RAND_MAX/255.0));

      // }

      int index = 0;

      for(int i=0;i<image.rows;i++)
     {

        uchar* p = image.ptr<uchar>(i);

        for(int j=0;i<image.cols*image.channels();j++){

          imageArray[index] = p[j];

          index++;

         }

      }

    }

  and function add this:

    Mat image = imread("baboon.jpg");
    ...
    const int width =  image.cols;
    const int height = image.rows;

    unsigned char* imageArray = new unsigned char[width*height*3];
    pangolin::GlTexture imageTexture(width,height,GL_RGB,false,0,GL_RGB,GL_UNSIGNED_BYTE);
    ...
    //Set some random image data and upload to GPU
    setImageData(imageArray,image);
    imageTexture.Upload(imageArray,GL_RGB,GL_UNSIGNED_BYTE);

but i got nothing , just  white ,  how to correct show the image ? thx

**Comment by stevenlovegrove** [comment]
The code looks more or less like it should work. I would try basing your code on SimpleVideo instead. You should be able to use it to display your image directly with:
`./SimpleVideo baboon.jpg`

With that working, you can try modifying it to load the image directly with
`pangolin::LoadImage("baboon.jpg")`

And finally, you can try putting back your use of OpenCV if you like.

**Comment by myBestLove** [comment]
thx for help .

i used the `LoadFromFile("baboon.jpg")` and it worked. but it was reversed

i also tried 
`Mat image = imread("baboon.jpg");
...
imageTexture.Upload(image.data,GL_BGR,GL_UNSIGNED_BYTE);
`
it also worked  but reversed ,  if i used function `setImageData()`, it didn't worked, i didn't kwon the reason.

and i readed the code about `LoadImage` , i had to new a TypedIamge, and do others work, it was to complex to me .

i am new

**Comment by yiakwy** [comment]
@myBestLove @stevenlovegrove I also have the same problem when I use python binding:

```python
img = datum.attrs.get('img')
# read from opencv
img = img.astype(np.uint8)
# Initially I want to use cv2.resize(img, (h,w)), because cv image shape is equal to ( H, W, CHANNEL)
# but it doesn't work. 
img = cv2.resize(img, (w, h))

...
texture.Upload(img, gl.GL_RGB, gl.GL_UNSIGNED_BYTE)
```

It shows the image but reverse one (180 degree rotation)

**Comment by tfy14esa** [comment]
> @myBestLove @stevenlovegrove I also have the same problem when I use python binding:
> 
> ```python
> img = datum.attrs.get('img')
> # read from opencv
> img = img.astype(np.uint8)
> # Initially I want to use cv2.resize(img, (h,w)), because cv image shape is equal to ( H, W, CHANNEL)
> # but it doesn't work. 
> img = cv2.resize(img, (w, h))
> 
> ...
> texture.Upload(img, gl.GL_RGB, gl.GL_UNSIGNED_BYTE)
> ```
> 
> It shows the image but reverse one (180 degree rotation)

Have you tried adding the line "texture.RenderToViewportFlipY()" after your texture.upload... line?
