### ISSUE TITLE
Cmake error libusb.h no such file or directory

### ISSUE THREAD

**Issue by jdcart** [stevenlovegrove/Pangolin#181]
I had this error when trying to build in Ubuntu 10.04. Had to change from "#include <libusb.h>" to "#include <libusb-1.0/libusb.h>" in the Pangolin/src/video/drivers/uvc.cpp and Pangolin/include/pangolin/video/drivers/uvc.h

**Comment by stevenlovegrove** [comment]
Thanks for reporting, but I'll close this issue as I do not attempt to support such old versions of Ubuntu.
