### ISSUE TITLE
Compilation problems with pangolin

### ISSUE THREAD

**Issue by vinod-mv** [stevenlovegrove/Pangolin#183]
This is to report a compilation error and a possible solution. When I tried to compile the sources by pulling it in using CMake's externalproject_add, I hit upon the following error

Code/Pangolin/src/video/drivers/ffmpeg.cpp:803:46: error: implicit instantiation of undefined template 'std::__1::array<std::__1::basic_string<char>, 49>'
            const std::array<std::string,49> ffmpeg_ext = {

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:116:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;

I solved this problem by adding include<array> in the file Pangolin/src/video/drivers/ffmpeg.cpp

**Comment by stevenlovegrove** [comment]
Thanks. If you raise a pull request, I can merge your change directly.
