### ISSUE TITLE
Compilation failure when BUILD_PANGOLIN_VIDEO is OFF

### ISSUE THREAD

**Issue by prclibo** [stevenlovegrove/Pangolin#186]
1. `src/image/image_io.cpp` calls `OpenVideo` and `OpenVideoOutput`. When `BUILD_PANGOLIN_VIDEO` is turned off, this file is still compiled and thus raise compilation errors.

2. In `src/CMakeLists.txt`, when turning off `BUILD_PANGOLIN_VIDEO`, `pthread` and `rt` are not added to link libraries, which causes linking errors.

**Comment by stevenlovegrove** [comment]
Looking at your diff, it appears that this is already fixed in master, so I'll close this issue. Please reopen if the problem persists.
