### ISSUE TITLE
Drawing text at absolute 3D position

### ISSUE THREAD

**Issue by mojovski** [stevenlovegrove/Pangolin#188]
Is there a way to draw some text at a 3D position in world frame?
I would like to do something like
```
drawText(x,y,z, "Hello");
```
and when I rotate the viewer towards x,y,z, the text should be visible.

Would be awesome!

Thanks alot!

**Comment by stevenlovegrove** [comment]
Yes, that's possible:
https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/gl/gltext.h#L62

You could write something like:
pangolin::GlFont()::I().Text("Hello World!").Draw(x,y,z);

You can store the GlText object for reuse to improve efficiency a bit.

**Comment by mojovski** [comment]
Perfect! Thank you very much.
btw, this worked:
```
pangolin::GlFont::I().Text("Hello World!").Draw(x,y,z);
```
(GlFont:: not GlFont():: because of the singleton static declaration).

**Comment by monage2018** [comment]
how to set fontsize
