### ISSUE TITLE
make -j problem

### ISSUE THREAD

**Issue by arifle** [stevenlovegrove/Pangolin#189]
Hello guys,
I am facing such a problem each time after 'make -j'. I have tried to usd gcc&g++ 4.7, 4.9 and 5 on Ubuntu 14.04 and the default version on my VM is 4.8 which is being used now but none of them works. The font file is also replaced with a .ttf which is only 13.x kb and is much smaller than the initial one. I used to post this question at the end of #99. What I want is simply to build it for ORBSLAM2.

[ 84%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/deinterlace.cpp.o
Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/firewire.cpp.o
Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/v4l.cpp.o
Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/openni.cpp.o
Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/ffmpeg.cpp.o
Building C object src/CMakeFiles/pangolin.dir/fonts.c.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [src/CMakeFiles/pangolin.dir/video/drivers/split.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/CMakeFiles/pangolin.dir/video/drivers/pango_video_output.cpp.o] Error 4
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2
arifle@ubuntu:~/Pangolin/build$

**Comment by stevenlovegrove** [comment]
I guess make (without j) also fails?

Unfortunately, I am not able to reproduce this, so you will have to do some exploration on your own. Others with this issue have been able to fix it by increasing their VM's memory, but I'm not sure by how much, or why it would require so much. Presumably you could also increase your page file size if you do not have enough physical memory.

**Comment by stevenlovegrove** [comment]
This issue has also only been reported inside of VM's - you could try a different VM software, or install Ubuntu natively.

**Comment by jp953310** [comment]
I am getting the same error and I have Linux4Tegra (Ubuntu 16.04) installed natively on a TX1. When I compile and watch the memory being used ( top | grep -i mem ) it looks like I am running out of RAM mid-compile which is causing the internal compiler error. Do you have any idea of how much RAM I need available to compile?

Thank you,
James

**Comment by arifle** [comment]
Hello Steven,

I gave up using make -j, and I use make instead. It works well.

**Comment by stevenlovegrove** [comment]
@jp953310 As you can imagine, fonts.c contains the binary pixmap data for the default font. Without it, Pangolin fonts may fail to load unless you load one manually. To change the default font to a file, rather than the binary data, you can adjust the code here: https://github.com/stevenlovegrove/Pangolin/blob/master/src/gl/glfont.cpp#L54
