### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by einspyon** [stevenlovegrove/Pangolin#193]
Is there any document about API ?

**Comment by mojovski** [comment]
There are great simple examples in the "examples" directory. For a production ready example see the orb slam repository. They use pangolin very well!

Good luck!

**Comment by stevenlovegrove** [comment]
@mojovski is right - Pangolin is mostly documented through its examples. This will hopefully improve with time, but realistically you shouldn't wait for it...

**Comment by fanyuzeng** [comment]
How to use it?

**Comment by fanyuzeng** [comment]
@stevenlovegrove  Will you write a simple tutorial on how to use it,please? I want use some function of Pangolin.
Best regards to you.
