### ISSUE TITLE
what():  Pangolin X11: Failed to open X display When run/debug via X11

### ISSUE THREAD

**Issue by caunion** [stevenlovegrove/Pangolin#194]
Hi @stevenlovegrove , I meet a problem when run pangolin examples on a ubuntu 14.04 server via SSH (X11) from mac. The typical error I get when directly run in terminal or debug is (i.e.  SimpleDisplay / HelloPangolin)
> terminate called after throwing an instance of 'std::runtime_error'
> what():  Pangolin X11: Failed to open X display

The X11 is fine both for mac client & ubuntu server as I tested clion/gedit with X11. Also, those examples run fine on server. And the glxgears / glmark2 run smooth on the server, but failed run via X11 on mac (not sure if this is normal?).

Do you have any ideas or suggestions? 

I noticed https://github.com/stevenlovegrove/Pangolin/issues/69 met similar problem and solved by reinstall everything. But I am afraid I can not reinstall ubuntu on the server since it shared by other lab members.
 
=====================
I attach the context variables and code (line #484) when exception occurs in "HelloPangolin", in case it helps.  (Note, the CLion IDE is run via X11, so the program is remotely debugging on Ubuntu).

![image](https://cloud.githubusercontent.com/assets/2020324/21786733/691d5b94-d693-11e6-81a7-25e2d1a5afe0.png)

**Comment by voyage19941119** [comment]
I met the same problem,I am running a programm on ubuntu 14.04 server shared with other lab member. have u solve this? or I will go back tell you if I find the resolution

**Comment by stevenlovegrove** [comment]
Forwarding OpenGL over X11 requires certain XServer and XClient extensions. Very concretely, if you can get another OpenGL program to run (such as glxgears), then Pangolin should also work. @caunion it sounds like glxgears isn't working for you either over ssh?

If you have a configuration in which glxgears can run, but the HelloPangolin example can't, then there is likely a Pangolin bug.

**Comment by UsmanMaqbool** [comment]
@caunion did you get the solution?

**Comment by caunion** [comment]
Hi. Sorry I missed the msg.

I did not solve this problem on public server. However, after trying to install everything on another 16.04 server, I do meet similar problem: (X11 not working even on sample code!).

Then I found this problem only happen on my mac client, and if I try ssh from another ubuntu machine to the 16.04 server, it works fine. I suspect that it because of mac XQuatz (2.7.11) issue, **so I removed it and installed an older version (2.7.8), and examples over X11 works fine**... 

However, my target is to run ElasticFusion, which is also built on Pangolin, but still can not make it work though.

**Comment by voyage19941119** [comment]
@caunion Hi , I'm trying to run ElasticFusion too,and also on server through ssh. But I suppose ,there's no GUI when running codes on remote server, so it's not a good idea to run it on server.Kintinuous either

**Comment by caunion** [comment]
@voyage19941119 Hi, ideally, I think if turn on X11 forwarding, there will be GUI for ElasticFusion to shown on client, since both ElasticFusion and Kintinuous are built on Pangolin. I have not test X11 forwarding for Kintunous though.

**Comment by casiahnu** [comment]
@caunion Hi , I'm trying to run ElasticFusion on server through ssh too, and I turn on X11 forwarding, But still make it work, did you make it successful?

**Comment by cuiwei9567** [comment]
@caunion 不知道你有没有成功解决这个问题，我也是打算在ssh上跑ElasticFusion，很尴尬！

**Comment by samwesley** [comment]
@caunion This worked for me - hosting on an AWS EC2 instance and working on a Mac

**Comment by michaelczh** [comment]
I tried to run under VNC, but failed due to 

> Xlib: extension "GLX" missing on display ":1.0"

**Comment by thiac** [comment]
It may be work if you run it on the sever directly, not by ssh.

**Comment by QianYC** [comment]
I try to run ElasticFusion on server through vnc too.
The server is Ubuntu16.04, and runs xvnc4.
I get the problem when running GPUTest: "Pangolin x11: unable to retrieve framebuffer options"

Did anyone else solve this problem?

**Comment by moon142857** [comment]
When I am running in Docker, report the following error and the host will be fine
./SimplePlot/SimplePlot 
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X11 Error: BadMatch (invalid parameter attributes)
X11 Error: BadValue (integer parameter out of range for operation)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Failed to create an OpenGL context
Aborted (core dumped)

**Comment by msanthosh-git** [comment]
@moon142857 : Did you resolved it.. Please help me out if u have solution.

**Comment by tjdahlke** [comment]
Likewise, same issue for me.

**Comment by feisonzl** [comment]
@moon142857 Did this problem resolved? I have the same problem with you

**Comment by kbfx1234** [comment]
Same issue for me when run in ssh

**Comment by owenwijaya177** [comment]
I find the same problem while trying to run ORB-SLAM2 through docker

**Comment by YiqiJ** [comment]
same issue when trying to run ORB-SLAM3 in ssh

**Comment by YiqiJ** [comment]
I solved this problem by disabling GUI display implemented for ORB-SLAM3. Since ssh cannot get graphical interface, I guess this is the major problem causing such Pangolin error.

**Comment by haloworld-C** [comment]
> When I am running in Docker, report the following error and the host will be fine ./SimplePlot/SimplePlot libGL error: No matching fbConfigs or visuals found libGL error: failed to load driver: swrast X11 Error: BadMatch (invalid parameter attributes) X11 Error: BadValue (integer parameter out of range for operation) terminate called after throwing an instance of 'std::runtime_error' what(): Pangolin X11: Failed to create an OpenGL context Aborted (core dumped)
----------------------------------------------------------------------------------------------------------------------------------------------------
For me I changed my docker scripts below, and it works well:
```bash
xhost + 
CURRENT_FILE_PATH=$(dirname $(dirname "$PWD")) 
docker run -it \  
-d \              
--name halo-dev \ 
--net=host \      
--hostname halo2world \   
-e DISPLAY=unix$DISPLAY \ 
-v /tmp/.X11-unix:/tmp/.X11-unix:rw \ 
--privileged \    # what I added
--gpus all\       # what I added
-v $CURRENT_FILE_PATH/..:/home/halo2world/ \ 
-e NVIDIA_DRIVER_CAPABILITIES=all \          # what I added, I think it's unnessary if you use general graphic driver
-v /etc/localtime:/etc/localtime \           
-w /home/halo2world \                        
--rm \                                       
guangaltman/halo-dev:ubuntu1804
x
```
I belive this issue related with the nividia driver you installed , and on my another computer I only installed the general nividia driver didn't have this issue.

**Comment by satyapalsinh10** [comment]
Hi colin,

I am also facing the same issue 

can you please confirm if this issue can be solved using the above steps suggested.

`sudo add-apt-repository ppa:graphics-drivers/ppa
sudo apt-get update
sudo ubuntu-drivers autoinstall
sudo reboot`

**Comment by qwert12131990** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by num-doc** [comment]
and  I was running slam on docker, but Pangolin reported an error  [Pangolin X11: Failed to open X display]

**Comment by AbdullahJirjees** [comment]
@num-doc Hi, I am having the same issue, did you found a solution for that?

**Comment by num-doc** [comment]
> @num-doc Hi, I am having the same issue, did you found a solution for that?

It has been a bit long, this problem is docker's problem, it is recommended to check the environment or build your own environment

**Comment by Gson-glitch** [comment]
Hello, I was able to fix the issue on docker while building ORB-SLAM3 by following the below steps:
### 1. Create or modify the docker-compose.yml file as follows:
```
version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: orb-slam3-python:dev
    container_name: orb-slam3-python-dev
    volumes:
      - .:/opt/ORB_SLAM3-PythonBinding
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    tty: true
```

### 2. Allow Docker to Use Host's X11 Display:
`xhost +local:root`

### 3. Build and Run the Docker Container
```
docker-compose build dev
docker-compose run --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix dev bash
```

### 4. Disabling Hierarchical Z-buffer and Separate Stencil Buffer Optimizations in Intel Graphics Drivers 
```
export hiz=false
export INTEL_HIZ=0
export INTEL_SEPARATE_STENCIL=0
```

### 5. Building ORB-SLAM3
`LIBGL_ALWAYS_SOFTWARE=1 ./Examples/Monocular/mono_tum_vi Vocabulary/ORBvoc.txt Examples/Monocular/TUM-VI.yaml dataset/dataset-room1_512_16/mav0/cam0/data Examples/Monocular/TUM_TimeStamps/dataset-room1_512.txt dataset-room1_512_mono`
