### ISSUE TITLE
CMakeLists.txt not match

### ISSUE THREAD

**Issue by NIEQiang001** [stevenlovegrove/Pangolin#197]
CMake Error: The source ".../Pangolin/CMakeLists.txt" does not match the source ".../Pangolin/src/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

**Comment by stevenlovegrove** [comment]
It sounds as though you've made a small mistake with CMake. Try removing your current build files and starting over. From the Pangolin root directory:
```
git -f clean
mkdir build
cd build
cmake ..
make
```

**Comment by NIEQiang001** [comment]
yeah, I realized that after I wrote the issue. Many thanks to your reply! I have solved that problem now. As a new in this area, I still have a lot to learn.  Thanks a lot~



qnie
 
From: Steven Lovegrove
Date: 2017-01-19 02:39
To: stevenlovegrove/Pangolin
CC: NIEQiang001; Author
Subject: Re: [stevenlovegrove/Pangolin] CMakeLists.txt not match (#197)
It sounds as though you've made a small mistake with CMake. Try removing your current build files and starting over. From the Pangolin root directory:
git -f clean
mkdir build
cd build
cmake ..
make

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
==================================================================================
This email is scanned by IRONPORT anti-spam and anti-virus server.  
Notes:
1) If you want to report this email to be "SPAM EMAIL", 
then please forward this email  to "spam@access.ironport.com".
2) If you need any asistance, please contact our dept computing team. 
==================================================================================
