### ISSUE TITLE
when I built it on windows, the GLEW cannot install automatically

### ISSUE THREAD

**Issue by NIEQiang001** [stevenlovegrove/Pangolin#198]
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find GLEW (missing: GLEW_INCLUDE_DIR GLEW_LIBRARY)

**Comment by hari0920** [comment]
I faced the same problem. Try using the source from http://glew.sourceforge.net/install.html and building them yourself separately.

**Comment by NIEQiang001** [comment]
@hari0920 Thanks. I found that it couldn't down load the GLEW automatically because of missing git software. To install git is also a solution.

**Comment by stevenlovegrove** [comment]
@NIEQiang001 - exactly. I will leave this issue open to remind me to document that in the readme.

**Comment by stevenlovegrove** [comment]
I just added this to my readme, so closing out.
