### ISSUE TITLE
How can I change the camera pose and save it as a screenshot?

### ISSUE THREAD

**Issue by mojovski** [stevenlovegrove/Pangolin#202]
I would like to set the camera pos at run time and store the view as an image on disk.
This is what I have done so far:
```
s_cam=pangolin::OpenGlRenderState(
            pangolin::ProjectionMatrix(640,480,420,420,320,240,0.1,10000),
            pangolin::ModelViewLookAt(-0,0.5,-3, 0,0,0, pangolin::AxisY));

d_cam = pangolin::CreateDisplay()
            .SetBounds(0.0, 1.0, pangolin::Attach::Pix(UI_WIDTH), 1.0, -640.0f/480.0f)
            .SetHandler(new pangolin::Handler3D(s_cam));
```

... then later in a callback function to a button of the GUI:
```
pangolin::OpenGlMatrix T_wc = s_cam.GetModelViewMatrix();
...[manipulate the model view matrix]...
s_cam.SetModelViewMatrix(T_wc);
d_cam.Render();
d_cam.SaveRenderNow(out_img_prefix);
```
What I receive is an image showing only the background. Even if I dont manipulat the T_wc matrix.

Can anyone suggest a proper way to do this?

Thanks a lot!

**Comment by stevenlovegrove** [comment]
The issue you're encountering is similar to (https://github.com/stevenlovegrove/Pangolin/issues/162)

`SaveRenderNow()` relies on a render callback attached to the View. You can instead use `d_cam.SaveOnRender("image")` do grab pixels directly from the screen, if you're happy with the image being the same resolution as your display size.

**Comment by mojovski** [comment]
thanks! :)
