### ISSUE TITLE
Can not find "unistd.h" with windows10 and vs2013

### ISSUE THREAD

**Issue by hitsjt** [stevenlovegrove/Pangolin#204]
Hi,
I tried to build Pangolin using windows10 and vs2013,but encountered this problem.
How could i fix it?

Thank you!

**Comment by stevenlovegrove** [comment]
Master is broken on windows right now. I'd recommend checking out a slightly older version:
https://github.com/stevenlovegrove/Pangolin/commit/8b8b7b96adcf58ac2755dedd3f681fc512385af0

**Comment by hitsjt** [comment]
Thanks to your reply,i will have a try.

**Comment by stevenlovegrove** [comment]
This should now be fixed on master.
