### ISSUE TITLE
GlTextureCudaArray fails on most internal formats

### ISSUE THREAD

**Issue by jjpark** [stevenlovegrove/Pangolin#207]
I have tried creating a GlTextureCudaArray with internal formats other than floats such as gl_R32UI, but most of them failed.

cudaGraphicsGLRegisterImage failed: 11

**Comment by stevenlovegrove** [comment]
I'm not sure about this one - GlTextureCudaArray is only a light wrapper providing RAII around the resources. If I were you, I would first check that creating the texture of that type works, and then try the CUDA interop.
