### ISSUE TITLE
Is it possible to add sub-panels?

### ISSUE THREAD

**Issue by jstraub** [stevenlovegrove/Pangolin#208]
Is it possible to add sub-panels? A sub-panel would appear once I click on some button? It would contain a set of variables as well? How would I tell Pangolin to add a variable to a specific sub-panel?

The number of variables is getting a bit out of hands ;)

**Comment by manujnaman** [comment]
You can show/hide panels. Say you have a 'main' panel named environment. 
    pangolin::CreatePanel("main_panel").SetBounds(  ..
This has a checkbox 
    pangolin::Var<bool>  main_show_pc1("main_panel.ShowSubPanel", true, true);

You have another (sub) panel attached to right of above main panel
    pangolin::CreatePanel("sub_panel")

Then in the main code show/hide of sub panel can be done as:

      if (pangolin::Var<bool>("main_panel.ShowSubPanel").GuiChanged()) {
          pangolin::Display("sub_panel").Show((bool)pangolin::Var<bool>("main_panel.ShowSubPanel"));
      }

You can then have many sub panels, show hide as needed. In place of check box a slider might be better with many panels.

Best,
Manuj

**Comment by jstraub** [comment]
Thank you Manuj that works =) I just had to also specify the bounds for the sub_panel.
