### ISSUE TITLE
examples shows errors

### ISSUE THREAD

**Issue by voyage19941119** [stevenlovegrove/Pangolin#211]
First,thank you for offering Pangolin!
![oz tui0mipqm htc__pactd](https://cloud.githubusercontent.com/assets/11376132/23441132/5ebff8e2-fe5b-11e6-8037-89dc6a16d9e5.png)
![nsnd31nm59141 5p5ss c8v](https://cloud.githubusercontent.com/assets/11376132/23441136/606853e2-fe5b-11e6-9e19-6e8a21335d67.png)
![uz7px_tww760qo8dk nv o](https://cloud.githubusercontent.com/assets/11376132/23441140/621b951e-fe5b-11e6-82ea-1b8e92ec5031.png)
all examples don't work,but I just installed Pangolin as directed,and I have tried two version that end with the same result . what is going on?

**Comment by stevenlovegrove** [comment]
It looks like your compiler is too old, and does not fully support the C++11 standard.

**Comment by HTLife** [comment]
@voyage19941119
You could modify the CMakeList.txt of SimpleDisplay example to 
```
cmake_minimum_required(VERSION 2.6.0)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

find_package(Pangolin 0.4 REQUIRED)
include_directories(${Pangolin_INCLUDE_DIRS})

add_executable(SimpleDisplay main.cpp)
target_link_libraries(SimpleDisplay ${Pangolin_LIBRARIES} )
```
which works for me.
