### ISSUE TITLE
OpenGL Error: XX (1280)

### ISSUE THREAD

**Issue by anatoly-spb** [stevenlovegrove/Pangolin#212]
When I run ElasticFusion build with Visual Studio 2013 on Windows 7 64bit based on Pangolin (current master)), I have problem with the draw_global_surface.vert shader:

```
Creating live capture... failed!
DeviceOpen using default: no devices found
GLSL Shader compilation failed: H:/tmp/ef/src/ElasticFusion/Core/src/Shaders/dra
w_global_surface.vert:
ERROR: 0:21: 'location' : syntax error parse error


GLSL Program link failed: Geometry shader object: no attached vertex shader obje
ct.

OpenGL Error: XX (1280)
In: H:\tmp\ef\src\Pangolin\include\pangolin/gl/gl.hpp, line 192
```
What is wrong?

**Comment by stevenlovegrove** [comment]
This is a question for @mp3guy . OpenGL error 1280 is 'GL_INVALID_ENUM'

**Comment by mp3guy** [comment]
@anatoly-spb You should contact https://github.com/fsrajer about Windows support for ElasticFusion, I did not resolve support myself.
