### ISSUE TITLE
JPEG not supported (textures)

### ISSUE THREAD

**Issue by AlexKrimi** [stevenlovegrove/Pangolin#215]
While using pangolin::GlTexture loaded from file img.jpg
an error appeared "Jpeg support not enabled please rebuild pangolin"
rebuilding doesn't help
what's wrong?

**Comment by stevenlovegrove** [comment]
You need to make sure Pangolin is able to find libjpeg. If you're on Linux, you should `sudo apt-get install libjpeg-dev`
