### ISSUE TITLE
interact with mouse

### ISSUE THREAD

**Issue by harrysocool** [stevenlovegrove/Pangolin#217]
Is it possible to interact with mouse on the point clouds. (eg. move the mouse onto one point, then it shows some information like which point clouds it belongs)

**Comment by stevenlovegrove** [comment]
I'm afraid that feature isn't offered automatically - you would have to implement it yourself.

**Comment by duyilong** [comment]
uh,,, is interacting with mouse still not functionality available? @stevenlovegrove
