### ISSUE TITLE
Could give me Pangolin.lib for windows platform

### ISSUE THREAD

**Issue by alexpeng3d** [stevenlovegrove/Pangolin#219]
I need x64 Pangolin.lib to develop my orb-slam, but my still cannot build successfully Pangolin.lib,
need help, thanks.

**Comment by stevenlovegrove** [comment]
I have recently configured Appveyor to output some binaries for x64, so you're in luck:
https://ci.appveyor.com/project/stevenlovegrove/pangolin/build/1.0.144/artifacts
