### ISSUE TITLE
how to get PangolinConfig.cmake

### ISSUE THREAD

**Issue by Chorior** [stevenlovegrove/Pangolin#220]
My CmakeLists.txt is in "... /Pangolin-master/Pangolin-master/external " . 
And I run cmake, I get the warning : 

CMake Warning (dev) at CMakeLists.txt:151 (set):
  Cannot set "ExternConfig": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.7)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

Configuring done

I add " cmake_minimum_required(VERSION 2.6) " on the top of " CmakeLists.txt ", there is only the first warning left . Here is the output:

Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:152 (set):
  Cannot set "ExternConfig": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

Configuring done

If I ignore the warning , and click Generate . Then I get a project that does not contain any *.h, *.cpp or *.hpp files. 

There must be something wrong on my process, I hope someone can give me a favor!   Thanks !

**Comment by Chorior** [comment]
Is there a guide for compiling Pangolin for windows?

**Comment by Chenhui2018** [comment]
Using Git Bash to cmake pangolin, and you will get a pangolin vs2012 win32 peoject.

search and download the Git Bash
      https://git-scm.com/downloads

1. cd "pangolin backage's path"; 
or 1.1"git clone https://github.com/stevenlovegrove/Pangolin.git"
then 1.2 cd pangolin
2. mkdir build
3. cd build
4. "the path of cmake.exe .. "  ( Note: \\ and "..")
such as: 
E:\\cmake-3.7.0-rc1-win32-x86\\bin\\cmake.exe ..
5. you get your project.
