### ISSUE TITLE
when i make it , it occurs a problem .  

### ISSUE THREAD

**Issue by lulinyuan** [stevenlovegrove/Pangolin#222]
/usr/bin/ld: /usr/local/lib/libpython3.5m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC /usr/local/lib/libpython3.5m.a: error adding symbols: Bad value collect2: error: ld returned 1 exit status src/CMakeFiles/pangolin.dir/build.make:1688: recipe for target 'src/libpangolin.so' failed make[2]: *** [src/libpangolin.so] Error 1 CMakeFiles/Makefile2:136: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2 Makefile:149: recipe for target 'all' failed make: *** [all] Error 2

**Comment by lulinyuan** [comment]
@chachi

**Comment by lulinyuan** [comment]
@stevenlovegrove

**Comment by stevenlovegrove** [comment]
I'm not sure what has caused that, but I'd recommend setting BUILD_PANGOLIN_PYTHON to false using ccmake or cmake-gui. Python support in Pangolin is not really necessary.

**Comment by lulinyuan** [comment]
Thanks you very much！@stevenlovegrove

**Comment by ngthanhtin** [comment]
Hi @stevenlovegrove I want to use pangolin in python, I built successfully if I set BUILD_PANGOLIN_PYTHON=False, but if it is True, I could not cmake --build . It raises the error that is: 
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/pangolin.dir/build.make:2874: recipe for target 'src/libpangolin.so' failed
make[2]: *** [src/libpangolin.so] Error 1
CMakeFiles/Makefile2:176: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
Could you help me please ? Thanks
