### ISSUE TITLE
Can't build shared library on Windows with MSVC14

### ISSUE THREAD

**Issue by hexonxons** [stevenlovegrove/Pangolin#223]
What I tried:

    mkdir build
    cd build
    cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release .. | Out-File E:/cmake.clear.log
    cmake --build . --config Release | Out-File E:/cmake_build.clear.log

What I got:
[cmake.clear.txt](https://github.com/stevenlovegrove/Pangolin/files/852556/cmake.clear.txt)
[cmake_build.clear.txt](https://github.com/stevenlovegrove/Pangolin/files/852557/cmake_build.clear.txt)

Everything is ok, if `BUILD_SHARED_LIBS=OFF`.  
  
Is it possible to make shared library on windows?

**Comment by stevenlovegrove** [comment]
I've probably missed a PANGOLIN_EXPORT annotation in a few places. Adding this to the erroneous classes / methods will hopefully do the trick. It has worked in the past, so hopefully it isn't too broken yet. When I get a chance I will try to add building as a shared library to the Appveyor CI build.

**Comment by hexonxons** [comment]
Yeah, there is a lot of warnings about that, I'll try tomorrow to annotate all classes with warnings and will make PR, if it fix these errors.
