### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by Thezkiller** [stevenlovegrove/Pangolin#225]
error:
/usr/bin/ld: /usr/local/lib/libavcodec.a(avpacket.o): relocation R_X86_64_32S against `av_destruct_packet' can not be used when making a shared object; recompile with -fPIC
i don't know how it comes,can you tell how to solve it.

**Comment by stevenlovegrove** [comment]
I don't know I'm afraid. If this is whilst building Pangolin, I would recommend setting BUILD_PANGOLIN_FFMPEG to false. You likely don't need ffmpeg support unless you want to read compressed video.

**Comment by belosthomas** [comment]
Same problem.
Why just not add -fPIC to the CXX_FLAGS. This would also solve the Python compatibility problem : 

 - https://github.com/stevenlovegrove/Pangolin/issues/130
 - https://github.com/stevenlovegrove/Pangolin/issues/222
