### ISSUE TITLE
opecv2.4.11 issue

### ISSUE THREAD

**Issue by 812406210** [stevenlovegrove/Pangolin#226]
/home/ywj/Downloads/opencv-2.4.11/modules/highgui/src/cap_ffmpeg_impl.hpp:2022:41: warning: ignoring return value of ‘int avformat_write_header(AVFormatContext*, AVDictionary**)’, declared with attribute warn_unused_result [-Wunused-result]
         avformat_write_header(oc_, NULL);
                                         ^
make[2]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/src/cap_ffmpeg.cpp.o] Error 1
make[1]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
make: *** [all] Error 2
**************************************************
I  had install ffmpeg3.2.4，why install opencv 2.4.11 had two error? thank you!

**Comment by stevenlovegrove** [comment]
This does not appear to be related to Pangolin. I'm afraid I don't know about your problem.

**Comment by 812406210** [comment]
Follow your step,install it appear this problem. In this  process ,my cp can't install ffmpeg,so i install ffmpeg's source.  i had installed  it moretime.,when i install Pangolin. But, it also appeared this problem .

**Comment by 812406210** [comment]
Follow your step,install it appear this problem. In this  process ,my pc can't install ffmpeg,so i install ffmpeg's source.  i had installed  it moretime.,when i install Pangolin. But, it also appeared this problem .

**Comment by stevenlovegrove** [comment]
You can disable Pangolin's ffmpeg by setting PANGOLIN_BUILD_FFMPEG to false using ccmake/cmake-gui. Then you can use whichever ffmpeg you like with OpenCV.

**Comment by 812406210** [comment]
Thanks , I try it
