### ISSUE TITLE
How to solve error: ‘picojson’ has not been declared

### ISSUE THREAD

**Issue by Kanelankai** [stevenlovegrove/Pangolin#229]
I came out with the error as follows:
when execute make -j.
/home/kane/catkin_ws/src/Pangolin/test/log/testlog.cpp: In function ‘void writeFakeFrame(const pangolin::PacketStreamSource&, size_t, pangolin::PacketStreamWriter&)’:
/home/kane/catkin_ws/src/Pangolin/test/log/testlog.cpp:20:5: error: ‘picojson’ has not been declared
     picojson::value meta;
     ^
/home/kane/catkin_ws/src/Pangolin/test/log/testlog.cpp:20:21: error: expected ‘;’ before ‘meta’
     picojson::value meta;
                     ^
/home/kane/catkin_ws/src/Pangolin/test/log/testlog.cpp:21:5: error: ‘meta’ was not declared in this scope
     meta["source"] = source.id;
     ^
make[2]: *** [test/log/CMakeFiles/Testlog.dir/testlog.cpp.o] Error 1
make[1]: *** [test/log/CMakeFiles/Testlog.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
I tried to solve this error by adding  #include <pangolin/utils/picojson.h> in testlog.cpp file but failed.
Can anyone help me to solve it?
Thanks.
@stevenlovegrove

**Comment by stevenlovegrove** [comment]
The json library was recently renamed. It seems likely that your build is picking up another, older version of Pangolin somewhere else. You should check ~/.cmake/packages/pangolin, and your install folder.

**Comment by Kanelankai** [comment]
Thank you for your reply.

Indeed, I have installed Pangolin in another place before.

I will check it.

Thank you!

在 2017/3/28 下午12:57, Steven Lovegrove 写道:

The json library was recently renamed. It seems likely that your build is picking up another, older version of Pangolin somewhere else. You should check ~/.cmake/packages/pangolin, and your install folder.
