### ISSUE TITLE
Export the obtained PointCloud

### ISSUE THREAD

**Issue by Lyokone** [stevenlovegrove/Pangolin#230]
Hello,

I've spend the last couple of days trying to figure out how to export a point cloud drawn in Pangolin to Json or PLY format with no result.

Is there a way to do this ?

Thanks in advance for your response :)

**Comment by stevenlovegrove** [comment]
Pangolin is a visualisation utility library. It does not keep track of points drawn with it. Presumably you have some pre-existing program which is using Pangolin - you will need to modify that program to export the points.

**Comment by Lyokone** [comment]
Okay thank you very much for your answer :)
