### ISSUE TITLE
No makefile found

### ISSUE THREAD

**Issue by hjjayakrishnan** [stevenlovegrove/Pangolin#232]
When running cmake.., it gave errors:

```
CMake Error at test/log/CMakeLists.txt:2 (find_package):
  By not providing "FindPangolin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Pangolin",
  but CMake did not find one.

  Could not find a package configuration file provided by "Pangolin"
  (requested version 0.4) with any of the following names:

    PangolinConfig.cmake
    pangolin-config.cmake

  Add the installation prefix of "Pangolin" to CMAKE_PREFIX_PATH or set
  "Pangolin_DIR" to a directory containing one of the above files.  If
  "Pangolin" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/odroid/Pangolin/CMakeFiles/CMakeOutput.log".
```

To bypass this I tried` cmake .. -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF` and it compiled successfully.
Next when I try `make -j` it throws up m`ake: *** No targets specified and no makefile found.  Stop.`

Any idea how to fix this issue? Thanks.

**Comment by stevenlovegrove** [comment]
if cmake executes without error, it should create a Makefile in the directory that you're in. If that file does not exist, then you will get the error that you see. You must execute make from the same directory. Beside a cmake error, I can't think of other reasons for failure. Based on your previous issue, my only other guess is that the Makefile cannot be written to disk for some reason.

**Comment by hjjayakrishnan** [comment]
Hi @stevenlovegrove I managed to fix the errors. All I had to do was to clone the repo all over again and instead of just cmake, I had to run sudo cmake to give the necessary permissions to create the /home/odroid/.cmake/packages/Pangolin/645635e5c3eb48c40f7fe9ca4be297bf file.

But when I finally ran make it started making up until about 66% when my system just crashed. And this happened multiple times.

**Comment by stevenlovegrove** [comment]
Did you try it without -j ? This can happen on Linux when the machine runs out of memory - perhaps you only have a limited amount on your system?

**Comment by hjjayakrishnan** [comment]
@stevenlovegrove Awesome. That was the problem. Now it successfully built it. Thanks a lot.

**Comment by riccitensor** [comment]
The "-j" solution does not work for me. Still the same error.

My OS is Ubuntu 16.4, I am installing ORB_SLAM2.
