### ISSUE TITLE
Build type not set error when doing "cmake .."

### ISSUE THREAD

**Issue by vannem95** [stevenlovegrove/Pangolin#233]
When i do **cmake ..**, it is giving the following error.

**Build type not set (defaults to release)**
**-DCMAKE_BUILD_TYPE=Debug for debug**
**CMake Error at CMakeModules/FindGLEW.cmake:51 (MESSAGE):**
  **Could not find GLEW**
**Call Stack (most recent call first):**
  **src/CMakeLists.txt:162 (find_package)**

**-- Configuring incomplete, errors occurred!**
**See also "/home/vivek/Pangolin/build/CMakeFiles/CMakeOutput.log".**

What do i do?

**Comment by stevenlovegrove** [comment]
"Build type not set" is not an error, but a message.

The real error is that it cannot find GLEW. To install it, follow the instructions in the readme:

(win) built automatically (assuming git is on your path and you have internet access)
(deb) sudo apt-get install libglew-dev
(mac) sudo port install glew

**Comment by Inger-Chao** [comment]
> "Build type not set" is not an error, but a message.
> 
> The real error is that it cannot find GLEW. To install it, follow the instructions in the readme:
> 
> (win) built automatically (assuming git is on your path and you have internet access)
> (deb) sudo apt-get install libglew-dev
> (mac) sudo port install glew

I used `brew install glew`, but It's still have same error. Is there any differences between `port` install and `brew install`?

**Comment by stevenlovegrove** [comment]
@Inger-Chao I'm afraid I don't know much about brew but I would expect that to work. You just need to make sure the installed location is on your search path for Pangolin.

**Comment by ylffan** [comment]
I am on Windows and I have the same issue even after following http://glew.sourceforge.net/install.html to install GLEW.
I don't see the instruction in the readme file regarding this. Could you clarify how exactly GLEW should be installed such that it will be compatible with this. Thanks

**Comment by stevenlovegrove** [comment]
> I am on Windows and I have the same issue even after following http://glew.sourceforge.net/install.html to install GLEW. I don't see the instruction in the readme file regarding this. Could you clarify how exactly GLEW should be installed such that it will be compatible with this. Thanks

On Windows I would recommend using vcpkg. The main readme does this in the following line:
`./scripts/install_prerequisites.sh recommended`

which calls out to vcpkg. You can either use your own vcpkg install, or the one from the Pangolin submodule (this is currently broken on the master branch, but someone else has had success just updating the submodule version to the latest).

**Comment by fusesujan** [comment]
If anyone facing the same problem with Ubuntu 22.04 Lts then >

`sudo apt-get install libglew-dev`

Run this,, this will fixed. 

I hope you are running the repo of 
https://github.com/stevenlovegrove/Pangolin.git
While facing the error with Cmake build.

**Comment by christian-rauch** [comment]
> If anyone facing the same problem with Ubuntu 22.04 Lts then >
> 
> `sudo apt-get install libglew-dev`
> 
> Run this,, this will fixed.

The package `libglew-dev` is part of the installation script:
https://github.com/stevenlovegrove/Pangolin/blob/9cb2e73e543f886c022a695da2b77e2c33198471/scripts/install_prerequisites.sh#L123

If you follow the instructions, this issue will not appear.
