### ISSUE TITLE
PangolinConfig.cmake not included in windows binary

### ISSUE THREAD

**Issue by zwn** [stevenlovegrove/Pangolin#235]
Could PangolinConfig.cmake be included in the appveyor build artifact?

**Comment by stevenlovegrove** [comment]
The PangolinConfig.cmake file as currently built has lots of absolute paths in, so it is not trivial to deploy. I'll leave this issue open, and hopefully someone (maybe me) will implement this at some point. Feel free to make a PR if you have a good solution.

**Comment by stevenlovegrove** [comment]
4 years later, and I think this is solved :)
