### ISSUE TITLE
Wayland support with GL ES2

### ISSUE THREAD

**Issue by gapaluec** [stevenlovegrove/Pangolin#236]
I am trying to add Wayland support for Pangolin. I started with Wayland & OpenGL and planning to move to Wayland & GL ES2 to get Pangolin working on small embedded devices which only support GL ES2.

Issue 1:
As of now I am facing issue with mouse integration. I am getting same response with middle click and left click. in SimpleDisplay example, I have tested that Handler3D::MouseMotion is getting called with correct mouse button mapping. Still response is same.

Issue 2: When compiling with GL ES2, only a blank window is appearing when I try to run SimpleDisplay.

Any pointers will be helpful. Codes are at https://github.com/gapaluec/Pangolin

**Comment by stevenlovegrove** [comment]
This is great! As you can probably tell, I've not used the gles2 engine stuff for a while, so it may have gotten quite broken without testing.

I'm afraid I'm completely unfamiliar with Wayland, or even how to use it. Is there an easy way to get it working alongside X11 on Ubuntu for testing?

**Comment by gapaluec** [comment]
With Ubuntu moving to Wayland ( https://wiki.ubuntu.com/Wayland ), we have more reason to add Wayland support to Pangolin.

**Comment by NikolausDemmel** [comment]
@christian-rauch @pagaluec, you mention Qt  here. Is it possible to combine the Pangolin viewer with additional (independent) QtWidgets / Windows?

**Comment by NikolausDemmel** [comment]
Ah ok, thanks.

Actually, what I would like to do is not having Qt widgets inside pangolin, but the other way round, i.e. using a pangolin window together with some other independent qt windows in the same application. I don't really know much about at which level the "window management", "event loops", or other aspects of both libraries might be conflicting. I guess I should just try it out.

**Comment by stevenlovegrove** [comment]
It should theoretically work fine - this is why Pangolin has a BindToContext method, so that you can use a context that you have already been given (by e.g. a Qt OpenGL widget). You will need to hook up the Qt widget input and resize signals to call the process::Mouse(...) etc events in display.h
