### ISSUE TITLE
Changing Font  Size and color

### ISSUE THREAD

**Issue by shening** [stevenlovegrove/Pangolin#238]
I am using 
pangolin::GlFont::I().Text(obj_detected).Draw(0,0,0); 
to display text on a map. Does anyone know how I can change the font size and color of the text ?

Thanks

Sebastian

**Comment by stevenlovegrove** [comment]
You can load alternative fonts using the GlFont constructor, rather than the singleton default. You can give a filename, or use the default set, though you will need to refer to the default symbol via an extern for now.

```
namespace pangolin{
extern "C" const unsigned char AnonymousPro_ttf[];
}
...
pangolin::GLFont myfont(pangolin::AnonymousPro_ttf, 15);
myfont.Text(...)
...
```
