### ISSUE TITLE
Menu bar disapears when shader is loaded

### ISSUE THREAD

**Issue by copark86** [stevenlovegrove/Pangolin#240]
Hi,
Thanks for the nice library. I am having a stupid problem with a shader loading. 

I have made a simple surfel drawing shader and it works fine except that whenever the shader is loaded the left sidebar disappears. I have been looking at ElasticFusion to see how they solve the problem but couldn't find any clue. 

The following is part of my code. 

Could you kindly advice me how to solve the problem?
Thanks!
`

    std::shared_ptr<Shader>   drawDepthProgram(loadProgramFromFile("depth.vert", "depth.frag", depth.geom"));
    GLuint vbo;
    glGenBuffers(1, &vbo);
    GLuint shaderProgram = drawDepthProgram->programId();
    glBindBuffer(GL_ARRAY_BUFFER, vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof(GLfloat)*draw_size*10, points, GL_STATIC_DRAW);

    // Create VAO
    GLuint vao;
    glGenVertexArrays(1, &vao);
    glBindVertexArray(vao);

    // Specify the layout of the vertex data
    GLint posAttrib = glGetAttribLocation(shaderProgram, "pos");
    glEnableVertexAttribArray(posAttrib);
    glVertexAttribPointer(posAttrib, 3, GL_FLOAT, GL_FALSE, 10 * sizeof(GLfloat), 0);

    GLint colAttrib = glGetAttribLocation(shaderProgram, "color");
    glEnableVertexAttribArray(colAttrib);
    glVertexAttribPointer(colAttrib, 3, GL_FLOAT, GL_FALSE, 10 * sizeof(GLfloat), (void*) (3 * sizeof(GLfloat)));

    GLint norAttrib = glGetAttribLocation(shaderProgram, "normal");
    glEnableVertexAttribArray(norAttrib);
    glVertexAttribPointer(norAttrib, 3, GL_FLOAT, GL_FALSE, 10 * sizeof(GLfloat), (void*) (6 * sizeof(GLfloat)));

    GLint sidesAttrib = glGetAttribLocation(shaderProgram, "sides");
    glEnableVertexAttribArray(sidesAttrib);
    glVertexAttribPointer(sidesAttrib, 1, GL_FLOAT, GL_FALSE, 10 * sizeof(GLfloat), (void*) (9 * sizeof(GLfloat)));

    // Default hooks for exiting (Esc) and fullscreen (tab).
    while (!pangolin::ShouldQuit()) {

        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

        d_cam.Activate(s_cam);
        //pangolin::glDrawColouredCube();

        glEnable(GL_PROGRAM_POINT_SIZE);
        glEnable(GL_POINT_SPRITE);
        glPushAttrib(GL_VIEWPORT_BIT);

        drawDepthProgram->Bind();
        pangolin::OpenGlMatrix m =s_cam.GetProjectionModelViewMatrix();
        Eigen::Matrix4f pose;
        pose.Identity();
        for(int k = 0;k<16;k++)
            pose(k)=(float)m.m[k];
        drawDepthProgram->setUniform(Uniform("projection", pose));
        drawDepthProgram->setUniform(Uniform("surfel_size", 0.01f));

        glDrawArrays(GL_POINTS, 0, draw_size);

        drawDepthProgram->Unbind();

        glDisable(GL_PROGRAM_POINT_SIZE);
        glDisable(GL_POINT_SPRITE);
        glPopAttrib();

        glFinish();

        //drawDepthProgram->
        //glBindBuffer(GL_ARRAY_BUFFER, 0);

        pangolin::FinishFrame();
    }

`

**Comment by stevenlovegrove** [comment]
You've probably solved this already, but I've just had time to take a look. I think it's likely you've forgotten to unbind something. Looking at your code, I can't see any glDisableVertexAttribArray's for instance.

**Comment by copark86** [comment]
Hi! 
Thanks for the comment. 
Although I somehow solve the problem by adding glDeleteBuffers at the end of the loop, I'm quite not sure if it is a correct way to do. I also tried glDisableVertexAttribArray but didn't work too. 

As you can see in the code, I am a newbie in opengl:) Sorry in advance if any of my stupid code upset you.


	// Default hooks for exiting (Esc) and fullscreen (tab).
	while (!pangolin::ShouldQuit()) {

		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);


		if (rgb_checkbox)
		    m_iDraw_type = 0; // otherwise
		if (time_checkbox)
		    m_iDraw_type = 1; // color by time
		if (confidence_checkbox)
		    m_iDraw_type = 2; // color by confidence
		if (normal_checkbox)
		    m_iDraw_type = 3; // normal map
		if (activeinactive_checkbox)
		    m_iDraw_type = 4; // active inactive


		d_cam.Activate(s_cam);


		glBindBuffer(GL_ARRAY_BUFFER, vbo);
		glBufferData(GL_ARRAY_BUFFER, sizeof(GLfloat)*draw_size*10, points, GL_STATIC_DRAW);

		// Create VAO
		GLuint vao;
		glGenVertexArrays(1, &vao);
		glBindVertexArray(vao);

		// Specify the layout of the vertex data
		GLint posAttrib = glGetAttribLocation(shaderProgram, "pos");
		glEnableVertexAttribArray(posAttrib);
		glVertexAttribPointer(posAttrib, 3, GL_FLOAT, GL_FALSE, 10 * sizeof(GLfloat), 0);

		GLint colAttrib = glGetAttribLocation(shaderProgram, "color");
		glEnableVertexAttribArray(colAttrib);
		glVertexAttribPointer(colAttrib, 3, GL_FLOAT, GL_FALSE, 10 * sizeof(GLfloat), (void*) (3 * sizeof(GLfloat)));

		GLint norAttrib = glGetAttribLocation(shaderProgram, "normal");
		glEnableVertexAttribArray(norAttrib);
		glVertexAttribPointer(norAttrib, 3, GL_FLOAT, GL_FALSE, 10 * sizeof(GLfloat), (void*) (6 * sizeof(GLfloat)));

		GLint sidesAttrib = glGetAttribLocation(shaderProgram, "sides");
		glEnableVertexAttribArray(sidesAttrib);
		glVertexAttribPointer(sidesAttrib, 1, GL_FLOAT, GL_FALSE, 10 * sizeof(GLfloat), (void*) (9 * sizeof(GLfloat)));


		glEnable(GL_PROGRAM_POINT_SIZE);
		glEnable(GL_POINT_SPRITE);
		glPushAttrib(GL_VIEWPORT_BIT);

		drawDepthProgram->Bind();
		pangolin::OpenGlMatrix m =s_cam.GetProjectionModelViewMatrix();
		Eigen::Matrix4f pose;
		pose.Identity();
		for(int k = 0;k<16;k++)
		    pose(k)=(float)m.m[k];
		drawDepthProgram->setUniform(Uniform("projection", pose));
		drawDepthProgram->setUniform(Uniform("surfel_size", (float)rad_val));
		drawDepthProgram->setUniform(Uniform("color_mode", m_iDraw_type));


		glDrawArrays(GL_POINTS, 0, draw_size);

		drawDepthProgram->Unbind();

		glDisable(GL_PROGRAM_POINT_SIZE);
		glDisable(GL_POINT_SPRITE);
		glPopAttrib();

		glFinish();
		glDeleteBuffers(1,&vbo);
		//glDisableVertexAttribArray(vao);

		glBindVertexArray(0);

		// button handlers
		if (pangolin::Pushed(save_window))// save whole window
		    pangolin::SaveWindowOnRender("window");
		if (pangolin::Pushed(save_view))// save the view only
		    d_cam.SaveOnRender("view");


		pangolin::FinishFrame();
	}

**Comment by copark86** [comment]
The following Opengl lecture was quite helpful to understand the problem above.
For Opengl newbies like me..

Play list 1
https://www.youtube.com/playlist?list=PLRwVmtr-pp04XomGtm-abzb-2M1xszjFx

buffer object
https://www.youtube.com/watch?v=kgp8kKWG_qU&list=PLRwVmtr-pp04XomGtm-abzb-2M1xszjFx&index=130
https://www.youtube.com/watch?v=ku-PAcZfz_E&list=PLRwVmtr-pp04XomGtm-abzb-2M1xszjFx&index=131
https://www.youtube.com/watch?v=sqlE67aADKs&list=PLRwVmtr-pp04XomGtm-abzb-2M1xszjFx&index=132
https://www.youtube.com/watch?v=xa1qxh8f63s&list=PLRwVmtr-pp04XomGtm-abzb-2M1xszjFx&index=133
https://www.youtube.com/watch?v=4_euGM0MmgM&list=PLRwVmtr-pp04XomGtm-abzb-2M1xszjFx&index=134
https://www.youtube.com/watch?v=aPtYBHvB0XU&list=PLRwVmtr-pp04XomGtm-abzb-2M1xszjFx&index=135
https://www.youtube.com/watch?v=b7jtjWLF2ZE&list=PLRwVmtr-pp04XomGtm-abzb-2M1xszjFx&index=136

Play list 2
https://www.youtube.com/playlist?list=PLRwVmtr-pp06qT6ckboaOhnm9FxmzHpbY
