### ISSUE TITLE
Pangolin make error

### ISSUE THREAD

**Issue by LittleMing233** [stevenlovegrove/Pangolin#243]
hello ,when i  finished "cmake ..", it looks good,but when i "make" in the build document,it has some mistake:
  ****/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmCloseOnce'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmMap'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmUnmap'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmOpenOnce'****
how can i solve the problem.
pls reply to my email, thX!!!

**Comment by stevenlovegrove** [comment]
That looks more like a problem with your OpenGL installation. I would try making sure you're linking to the correct libGL library and that it works with other GL programs.
