### ISSUE TITLE
How to draw multiple windows?

### ISSUE THREAD

**Issue by rakeshshrestha31** [stevenlovegrove/Pangolin#244]
I need two windows that are maintained by two separate threads. Just calling pangolin::CreateWindowAndBind in separate threads draws both thread in the same window and end result is a mess. I couldn't find any example for that. Is there any straightforward way of doing that? Sorry if the problem sounds dumb, I am quite new at this.

Thanks in advance.

**Comment by stevenlovegrove** [comment]
It is possible, but you must call pangolin::CreateWindowAndBind from within the thread (instead of calling it and then spawning a thread). This is because this call binds the new OpenGL context to the currently active thread.

**Comment by rakeshshrestha31** [comment]
Is there a way to create unique OpenGL contexts for the two threads? (Maybe by making lower level OpenGL calls). I need the two windows to be maintained by different threads.

**Comment by stevenlovegrove** [comment]
pangolin::CreateWindowAndBind will create a new context for the current thread. You can call it twice, once per thread, to get two windows.

**Comment by rakeshshrestha31** [comment]
Looks like I had some issues with X11-xserver. Calling pangolin::CreateWindowAndBind from two thread wasn't giving me two independent windows. I tried my code in a different machine and turns out it was doing the right thing all along.

Thank you for you time Steven. And great job with the Pangolin library, really love it.
