### ISSUE TITLE
Make error about "Testlog"

### ISSUE THREAD

**Issue by zxw1992** [stevenlovegrove/Pangolin#246]
Hello, I got this error when make Pangolin:

[ 72%] Built target pangolin
Scanning dependencies of target Testlog
[ 73%] Building CXX object test/log/CMakeFiles/Testlog.dir/testlog.cpp.o
[ 75%] Linking CXX executable Testlog
//usr/lib/x86_64-linux-gnu/libsoxr.so.0：对‘GOMP_parallel@GOMP_4.0’未定义的引用
collect2: error: ld returned 1 exit status
test/log/CMakeFiles/Testlog.dir/build.make:119: recipe for target 'test/log/Testlog' failed
make[2]: *** [test/log/Testlog] Error 1
CMakeFiles/Makefile2:208: recipe for target 'test/log/CMakeFiles/Testlog.dir/all' failed
make[1]: *** [test/log/CMakeFiles/Testlog.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

How to solve this problem?

**Comment by stevenlovegrove** [comment]
GOMP has to do with OpenMP. I have no idea why libsoxr is getting linked in here - did you add that? Building Testlog can be disabled in any case using the CMake BUILD_TESTS flag (with ccmake or cmake-gui)

**Comment by andrespy** [comment]
Hello,
I have the same problem, did you fix it?
thanks in advance

**Comment by andrespy** [comment]
I tried disabling BUILD_EXAMPLES flag and I did not have the problem anymore
