### ISSUE TITLE
Make error about realsense.cpp

### ISSUE THREAD

**Issue by clin14** [stevenlovegrove/Pangolin#247]
Hi,

During the make process, the error message occurred as following:

[ 68%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/realsense.cpp.o
/home/project-use/Pangolin/src/video/drivers/realsense.cpp:1:31: fatal error: librealsense/rs.hpp: No such file or directory
compilation terminated.
src/CMakeFiles/pangolin.dir/build.make:1502: recipe for target 'src/CMakeFiles/pangolin.dir/video/drivers/realsense.cpp.o' failed

How could I fix this problem? Thanks

**Comment by stevenlovegrove** [comment]
Do you want to use realsense? If not, you can disable it by using cmake-gui or ccmake to clear the appropriate realsense variables. Otherwise you will need to debug this yourself and make sure the appropriate include directories are found.

**Comment by stevenlovegrove** [comment]
https://github.com/stevenlovegrove/Pangolin/pull/190 may be applicable.

**Comment by clin14** [comment]
Thanks. It did work.
