### ISSUE TITLE
Orthographic Projection

### ISSUE THREAD

**Issue by copark86** [stevenlovegrove/Pangolin#250]
Hi,
To get an orthographic projection I used the following code instead of "d_cam.Activate(s_cam);". But it seems like not working. Anything wrong?

d_cam.ActivatePixelOrthographic();
s_cam.Apply();

Thanks!

**Comment by stevenlovegrove** [comment]
ActivatePixelOrthographic is largely for 2D drawing in pixel coordinates. You can instead give your s_cam an orthographic projection using the ProjectionMatrixOrthographic(). That way you can still manipulate the view with your mouse.

**Comment by copark86** [comment]
Thanks for the quick reply! 
It's working now.

**Comment by Tomas-Lee** [comment]
> Thanks for the quick reply!
> It's working now.
Excuse me,
Could you give me your code snippet about the ProjectionMatrixOrthographic()? 
I am a newbie and have no idea about the meaning of the function parameters. Could you explain it for me?
Thank you very very much.
