### ISSUE TITLE
conflicting return type

### ISSUE THREAD

**Issue by wangzheqie** [stevenlovegrove/Pangolin#251]
I follow the readme.md file, every thing is ok, untill run "make -l". When compile up to 73%, the problem is happen as follows:
That means confilciting the return type.
------------------------------------------------- separating line ----------------------------------------------------------

[ 73%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/openni2.cpp.o
In file included from /home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp:29:0:
/home/qie/softs/ros_slam/Pangolin/include/pangolin/video/drivers/openni2.h:103:9: error: conflicting return type specified for ‘virtual int pangolin::OpenNi2Video::GetCurrentFrameId() const’
     int GetCurrentFrameId() const;
         ^~~~~~~~~~~~~~~~~
In file included from /home/qie/softs/ros_slam/Pangolin/include/pangolin/video/video.h:120:0,
                 from /home/qie/softs/ros_slam/Pangolin/include/pangolin/pangolin.h:59,
                 from /home/qie/softs/ros_slam/Pangolin/include/pangolin/video/drivers/openni2.h:31,
                 from /home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp:29:
/home/qie/softs/ros_slam/Pangolin/include/pangolin/video/video_interface.h:161:20: error:   overriding ‘virtual size_t pangolin::VideoPlaybackInterface::GetCurrentFrameId() const’
     virtual size_t GetCurrentFrameId() const = 0;
                    ^~~~~~~~~~~~~~~~~
In file included from /home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp:29:0:
/home/qie/softs/ros_slam/Pangolin/include/pangolin/video/drivers/openni2.h:106:9: error: conflicting return type specified for ‘virtual int pangolin::OpenNi2Video::GetTotalFrames() const’
     int GetTotalFrames() const ;
         ^~~~~~~~~~~~~~
In file included from /home/qie/softs/ros_slam/Pangolin/include/pangolin/video/video.h:120:0,
                 from /home/qie/softs/ros_slam/Pangolin/include/pangolin/pangolin.h:59,
                 from /home/qie/softs/ros_slam/Pangolin/include/pangolin/video/drivers/openni2.h:31,
                 from /home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp:29:
/home/qie/softs/ros_slam/Pangolin/include/pangolin/video/video_interface.h:165:20: error:   overriding ‘virtual size_t pangolin::VideoPlaybackInterface::GetTotalFrames() const’
     virtual size_t GetTotalFrames() const = 0;
                    ^~~~~~~~~~~~~~
/home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp: In member function ‘virtual std::unique_ptr<pangolin::VideoInterface> pangolin::RegisterOpenNi2VideoFactory()::OpenNI2VideoFactory::Open(const pangolin::Uri&)’:
/home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp:656:71: error: invalid new-expression of abstract class type ‘pangolin::OpenNi2Video’
                 nivid = new OpenNi2Video(pangolin::PathExpand(uri.url));
                                                                       ^
In file included from /home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp:29:0:
/home/qie/softs/ros_slam/Pangolin/include/pangolin/video/drivers/openni2.h:43:8: note:   because the following virtual functions are pure within ‘pangolin::OpenNi2Video’:
 struct OpenNi2Video : public VideoInterface, public VideoPropertiesInterface, public VideoPlaybackInterface
        ^~~~~~~~~~~~
In file included from /home/qie/softs/ros_slam/Pangolin/include/pangolin/video/video.h:120:0,
                 from /home/qie/softs/ros_slam/Pangolin/include/pangolin/pangolin.h:59,
                 from /home/qie/softs/ros_slam/Pangolin/include/pangolin/video/drivers/openni2.h:31,
                 from /home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp:29:
/home/qie/softs/ros_slam/Pangolin/include/pangolin/video/video_interface.h:168:20: note: 	virtual size_t pangolin::VideoPlaybackInterface::Seek(size_t)
     virtual size_t Seek(size_t frameid) = 0;
                    ^~~~
/home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp:658:54: error: invalid new-expression of abstract class type ‘pangolin::OpenNi2Video’
                 nivid = new OpenNi2Video(stream_modes);
                                                      ^
/home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp:660:79: error: invalid new-expression of abstract class type ‘pangolin::OpenNi2Video’
                nivid = new OpenNi2Video(default_dim, default_roi, default_fps);
                                                                              ^
src/CMakeFiles/pangolin.dir/build.make:1622: recipe for target 'src/CMakeFiles/pangolin.dir/video/drivers/openni2.cpp.o' failed
make[2]: *** [src/CMakeFiles/pangolin.dir/video/drivers/openni2.cpp.o] Error 1
CMakeFiles/Makefile2:168: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wangzheqie** [comment]
Only after I ignore the error using "make -i" can it build successfully.

**Comment by kzampog** [comment]
Hi,

I'm also getting exactly the same build errors. Everything used to build cleanly on my Ubuntu 16.04 setups (I think I last updated Pangolin about 10 days ago), but one of the latest commits must have broken something.

**Comment by mrhebert** [comment]
Having the same issue on Ubuntu 16.04. I tried checking out an arbitrary older commit ` a7792a4` from April and it built fine, but didn't dig deeper into when exactly it starts breaking.

**Comment by stevenlovegrove** [comment]
Yeah, this is my fault. I'll push a fix shortly

**Comment by stevenlovegrove** [comment]
Should be fixed here f695ffd9274c6f2f32d6d6d3f0b563307fc988cc on master. Sorry!

**Comment by kzampog** [comment]
Thank you!

**Comment by lvxingzhe1991** [comment]
used by ubuntu14.04 
error: overriding ‘virtual std::size_t pangolin::VideoPlaybackInterface::GetTotalFrames() const’
virtual size_t GetTotalFrames() const = 0;
can you help me how to solve it?

**Comment by stevenlovegrove** [comment]
The realsense issue is here https://github.com/stevenlovegrove/Pangolin/pull/254, which has just been fixed in 5ddf761e219b1f0da3d4674b8357fef4182ed91a
