### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by lvxingzhe1991** [stevenlovegrove/Pangolin#253]
error:   overriding ‘virtual std::size_t pangolin::VideoPlaybackInterface::GetTotalFrames() const’
     virtual size_t GetTotalFrames() const = 0;
                    ^
/home/ly/orb-slam2/Pangolin/src/video/drivers/realsense.cpp:82:5: warning: unused parameter ‘frameid’ [-Wunused-parameter]
 int RealSenseVideo::Seek(int frameid) {
     ^
/home/ly/orb-slam2/Pangolin/src/video/drivers/realsense.cpp: In member function ‘virtual std::unique_ptr<pangolin::VideoInterface> pangolin::RegisterRealSenseVideoFactory()::RealSenseVideoFactory::Open(const pangolin::Uri&)’:
/home/ly/orb-slam2/Pangolin/src/video/drivers/realsense.cpp:93:80: error: cannot allocate an object of abstract type ‘pangolin::RealSenseVideo’
             return std::unique_ptr<VideoInterface>( new RealSenseVideo(dim, fps) );
                                                                                ^
In file included from /home/ly/orb-slam2/Pangolin/src/video/drivers/realsense.cpp:2:0:
/home/ly/orb-slam2/Pangolin/include/pangolin/video/drivers/realsense.h:18:8: note:   because the following virtual functions are pure within ‘pangolin::RealSenseVideo’:
 struct RealSenseVideo : public VideoInterface, public VideoPropertiesInterface, public VideoPlaybackInterface
        ^
In file included from /home/ly/orb-slam2/Pangolin/include/pangolin/video/video.h:120:0,
                 from /home/ly/orb-slam2/Pangolin/include/pangolin/pangolin.h:59,
                 from /home/ly/orb-slam2/Pangolin/include/pangolin/video/drivers/realsense.h:3,
                 from /home/ly/orb-slam2/Pangolin/src/video/drivers/realsense.cpp:2:
/home/ly/orb-slam2/Pangolin/include/pangolin/video/video_interface.h:168:20: note: 	virtual std::size_t pangolin::VideoPlaybackInterface::Seek(std::size_t)
     virtual size_t Seek(size_t frameid) = 0;
                    ^
/home/ly/orb-slam2/Pangolin/src/video/drivers/realsense.cpp:94:9: warning: control reaches end of non-void function [-Wreturn-type]
         }

**Comment by lvxingzhe1991** [comment]
how can i solve the problem,please reply to me,thanks.

**Comment by QinZiwen** [comment]
I have the same problem

**Comment by lvxingzhe1991** [comment]
did you solve it?

**Comment by QinZiwen** [comment]
sorry, I'm not

**Comment by stevenlovegrove** [comment]
Sounds like issue https://github.com/stevenlovegrove/Pangolin/pull/254, which has just been fixed in 5ddf761e219b1f0da3d4674b8357fef4182ed91a
