### ISSUE TITLE
 error:   overriding ‘virtual std::size_t pangolin::VideoPlaybackInterface::GetTotalFrames() const’

### ISSUE THREAD

**Issue by lvxingzhe1991** [stevenlovegrove/Pangolin#255]
used by ubuntu14.04 
/home/ly/orb-slam2/Pangolin/include/pangolin/video/video_interface.h:165:20: error:   overriding ‘virtual std::size_t pangolin::VideoPlaybackInterface::GetTotalFrames() const’
     virtual size_t GetTotalFrames() const = 0;
                    ^
/home/ly/orb-slam2/Pangolin/src/video/drivers/realsense.cpp:82:5: warning: unused parameter ‘frameid’ [-Wunused-parameter]
 int RealSenseVideo::Seek(int frameid) {

can you help me how to solve it?thanks in advance

**Comment by stevenlovegrove** [comment]
Sounds like issue https://github.com/stevenlovegrove/Pangolin/pull/254, which has just been fixed in 5ddf761e219b1f0da3d4674b8357fef4182ed91a
