### ISSUE TITLE
Simple mouse click overlay

### ISSUE THREAD

**Issue by sweeneychris** [stevenlovegrove/Pangolin#257]
Hi Steven,

I'm trying to build a simple app that displays an image and draws a square around where the user clicks (and stores the x,y location). Could you point me in the best direction to implement this? I imagine I'll need to implement a new Handler object, but I'm not sure how to pull data (i.e. the x,y location of the click) out of the handler. Thanks!

**Comment by sweeneychris** [comment]
As a follow-up question, if I have a window with multiple views (an image, a plotter, some buttons) is there a simple way to get the original image coordinates from the mouse click coordinates which will be in the viewport coordinates? It's not hard to do by hand, just curious if this is already built in

**Comment by sweeneychris** [comment]
Figured out the answer to both of these questions after playing around with the library a bit. Thanks!

**Comment by stevenlovegrove** [comment]
Just saw this, sorry! Glad you figured it out!
Did you use a pangolin::ImageView and set the extern_draw_function by chance? It's undocumented, but probably the best way :)
