### ISSUE TITLE
How to read matrix from configuration file?

### ISSUE THREAD

**Issue by christian-rauch** [stevenlovegrove/Pangolin#258]
In the `SimpleDisplay` example, there is the `app.cfg` configuration file which contains:
```
M =
[1, 0, 0
 0, 1, 0
 0, 0, 1];
```
How do I read this into a matrix, e.g. `double[9]` or `std::vector<double>`?
From `type_convert.h` it looks like you can only read non-primitive types if they are serialiseable through `ostringstream`/`istringstream`. E.g. I cannot read a matrix using `pangolin::Var<std::vector<double>>` or `pangolin::Var<double[9]>`.

Is the only way to load a matrix or vector from configuration files by reading them as string (`pangolin::Var<std::string>`) and do the deserialisation manually?

**Comment by stevenlovegrove** [comment]
I think I wrote that when I was using the TooN matrix library. I believe that had default serialization and deserialization stream operators. As a hack, you could maybe implement your desired stream overloads and place them in the Pangolin namespace so that the serialization works out.

Issue https://github.com/stevenlovegrove/Pangolin/issues/29 describes my intention to allow alternate serialization methods to be used.

**Comment by christian-rauch** [comment]
I am reading matrices from configuration files using this function:
```
template<typename T>
void deserialise_matrix(const std::string &mat_string, Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic> &M) {
    std::stringstream mat_ss(mat_string);
    std::string row;
    uint irow = 0;
    while(std::getline(mat_ss,row,',')) {
        M.conservativeResize(irow+1, Eigen::NoChange);
        std::stringstream row_ss(row);
        uint icol = 0;
        std::string v;
        while(std::getline(row_ss,v, ' ')) {
            if(v.size()!=0) {
                if(irow==0) {
                    M.conservativeResize(Eigen::NoChange, icol+1);
                }
                std::stringstream(v) >> M(irow,icol);
                icol++;
            }
        }
        irow++;
    }
}
```

In the configuration file, a matrix must be given in space separated columns and comma separated rows. E.g.:
```
camera_pose =
-0.87853094 +0.23144165 -0.41787336 1.154833,
0.47680032 +0.37163644 -0.79658509 0.87038,
-0.029066 -0.8990668  -0.43684557 0.75409,
0 0 0 1;
```
You need to take care to remove any spaces at the beginning of rows.

You can then read the string and deserialise it via:
```
const pangolin::Var<std::string> cpose_string("camera_pose");
Eigen::MatrixXf mx;
deserialise_matrix<float>(cpose_string, mx);
```
