### ISSUE TITLE
Pangolin Install Error (Debian 8 Jessie)

### ISSUE THREAD

**Issue by Gasethata** [stevenlovegrove/Pangolin#259]
Hi I have been struggling to install Pangolin in order to use ORB_SLAM2

I did managed to install all dependencies for it, but after the "make -j" command, this is the error I get:

/home/vip/Pangolin/src/log/packetstream.cpp: In member function ‘pangolin::pangoTagType pangolin::PacketStream::readTag(pangolin::pangoTagType)’:
/home/vip/Pangolin/src/log/packetstream.cpp:39:15: error: ‘runtime_error’ is not a member of ‘std’
         throw std::runtime_error(("Tag mismatch error: expected tag '" + tagName(r) + "' does not match found tag '" + tagName(x) + "'").c_str());
               ^
src/CMakeFiles/pangolin.dir/build.make:446: recipe for target 'src/CMakeFiles/pangolin.dir/log/packetstream.cpp.o' failed
make[2]: *** [src/CMakeFiles/pangolin.dir/log/packetstream.cpp.o] Error 1
CMakeFiles/Makefile2:168: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
vip@VIPWS1:~/Pangolin/build$ 

Please if anyone can help with this, it will be much appreciated.
Thank you.

**Comment by stevenlovegrove** [comment]
have you tried adding
`#include <stdexcept>`
to /home/vip/Pangolin/src/log/packetstream.cpp?

**Comment by Gasethata** [comment]
Thanks Steven
#include <stdexcept> 
to ../Pangolin/src/log/packetstream.cpp 
did fixed my problem.

**Comment by vtushevskiy** [comment]
I had same error on ubilinux, #include <stdexcept> helped
