### ISSUE TITLE
Draw 3D shape in Pangolin

### ISSUE THREAD

**Issue by Santi-7** [stevenlovegrove/Pangolin#264]
I've seen that Pangolin offers a specific function for drawing a basic 3D cube: `glDrawColouredCube`.

I want to draw any other 3D shape. For any I mean, for example, a Darth Vader. Does Pangolin offer any API for this? If affirmative, which is the input format of the 3D shapes?

**Comment by stevenlovegrove** [comment]
There is a branch with a PLY loader, but it is work in progress and unsupported (https://github.com/stevenlovegrove/Pangolin/tree/modelviewer2). That being said, you can use any OpenGL with Pangolin, so any third-party loader can be used in conjunction with Pangolin to navigate models.
