### ISSUE TITLE
build error in TX1

### ISSUE THREAD

**Issue by lizzzcai** [stevenlovegrove/Pangolin#265]
Dear all, i try to build Pangolin in my TX1, but fails. Here is the message.

[ 71%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/openni.cpp.o
[ 72%] Building C object src/CMakeFiles/pangolin.dir/fonts.c.o
[ 73%] Linking CXX shared library libpangolin.so
[ 73%] Built target pangolin
Scanning dependencies of target HelloPangolin
[ 73%] Building CXX object examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/main.cpp.o
[ 74%] Linking CXX executable HelloPangolin
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmCloseOnce'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmMap'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmUnmap'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmOpenOnce'
collect2: error: ld returned 1 exit status
examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/build.make:112: recipe for target 'examples/HelloPangolin/HelloPangolin' failed
make[2]: *** [examples/HelloPangolin/HelloPangolin] Error 1
CMakeFiles/Makefile2:268: recipe for target 'examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/all' failed
make[1]: *** [examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

anyone has idea? thanks.

**Comment by stevenlovegrove** [comment]
Google is your friend.

Does this help?
https://devtalk.nvidia.com/default/topic/946136/building-an-opengl-application/?offset=8
