### ISSUE TITLE
build problem openni.cpp

### ISSUE THREAD

**Issue by goxy2** [stevenlovegrove/Pangolin#266]
When i make:
#cd build
#cmake ..
#cmake --build .
i have a lot syntactic errors and at the end it is:
make[2]: *** [src/CMakeFiles/pangolin.dir/video/drivers/openni.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2
What i am do wrong?

Syntax errors are (over 7000 lines):
In file included from /usr/include/ni/XnStatus.h:25:0,
                 from /usr/include/ni/XnTypes.h:28,
                 from /usr/include/ni/XnOpenNI.h:28,
                 from /usr/include/ni/XnCppWrapper.h:28,
                 from /home/Pangolin/include/pangolin/video/drivers/openni.h:19,
                 from /home/Pangolin/src/video/drivers/openni.cpp:28:
/usr/include/ni/XnPlatform.h:74:3: error: #error OpenNI Platform Abstraction Layer - Unsupported Platform!
  #error OpenNI Platform Abstraction Layer - Unsupported Platform!
   ^
In file included from /usr/include/ni/XnTypes.h:29:0,
                 from /usr/include/ni/XnOpenNI.h:28,
                 from /usr/include/ni/XnCppWrapper.h:28,
                 from /home/Pangolin/include/pangolin/video/drivers/openni.h:19,
                 from /home/Pangolin/src/video/drivers/openni.cpp:28:
/usr/include/ni/XnOS.h:52:3: error: #error OpenNI OS Abstraction Layer - Unsupported Platform!
  #error OpenNI OS Abstraction Layer - Unsupported Platform!
   ^
In file included from /home/Pangolin/include/pangolin/video/drivers/openni.h:19:0,
                 from /home/Pangolin/src/video/drivers/openni.cpp:28:
/usr/include/ni/XnCppWrapper.h:10019:76: error: macro "XN_VALIDATE_NEW" passed 4 arguments, but takes just 2
    XN_VALIDATE_NEW(pTrans, StateChangedCallbackTranslator, handler, pCookie);
                                                                            ^
/usr/include/ni/XnCppWrapper.h:10078:75: error: macro "XN_VALIDATE_NEW" passed 4 arguments, but takes just 2
   XN_VALIDATE_NEW(pTrans, StateChangedCallbackTranslator, handler, pCookie);
                                                                           ^
In file included from /usr/include/ni/XnTypes.h:28:0,
                 from /usr/include/ni/XnOpenNI.h:28,
                 from /usr/include/ni/XnCppWrapper.h:28,
                 from /home/Pangolin/include/pangolin/video/drivers/openni.h:19,
                 from /home/Pangolin/src/video/drivers/openni.cpp:28:
/usr/include/ni/XnStatus.h:34:9: error: ‘XnUInt32’ does not name a type
 typedef XnUInt32 XnStatus;
              ^

**Comment by stevenlovegrove** [comment]
I would try using the OpenNI2 driver instead if you need it. You can disable this driver by setting BUILD_PANGOLIN_OPENNI to false using cmake-gui
