### ISSUE TITLE
ffmpeg issue?

### ISSUE THREAD

**Issue by limhyon** [stevenlovegrove/Pangolin#27]
Recently, I have my Ubuntu changed to 14.04 LTS.
The FFmpeg is not available in this version of linux. so 
$ sudo apt-get install ffmpeg
does not work. 

I can find following.
http://fcorti.com/2014/04/22/ffmpeg-ubuntu-14-04-lts/

Have you ever try to run Pangolin 14.04?

**Comment by dcanelhas** [comment]
Looks like that ppa is no longer available. 
There is another ppa at ppa:kirillshkrogalev/ffmpeg-next which *didn't work* for me. 

solution:

install yasm, needed in the configure script;
```sudo apt-get install yasm ```
then
```git clone git://source.ffmpeg.org/ffmpeg.git
cd ffmpeg/
./configure --enable-shared
make -j8
sudo make install
```
Then build pangolin as you normally would. Without the --enable-shared option above there will be issues in pangolin's build when linking the static ffmpeg libraries into a dynamic shared one.

```relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
```
I hear ffmpeg is again part of the official repos in 15.04.

**Comment by peaceful-mage** [comment]
however when I use type the command make -j8 it report the error :
LD	libswscale/libswscale.so.4
LD	libswresample/libswresample.so.2
libavutil/libavutil.so:can't be distinguished:it has been cut
and i don't know how to solve it.
In another case ,I use sudo apt-get install ffmpeg and install it successful ,however I still can't install the pangolin

**Comment by stevenlovegrove** [comment]
I don't have any advice there, except to remind you that FFMPEG is an optional dependency. Unless you need it, you can set the cmake cache lines to empty strings to disable.

**Comment by qazmichaelgw** [comment]
I was trying to compile the file.
make[2]: *** [src/CMakeFiles/pangolin.dir/video/drivers/ffmpeg.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
It seems that the ffmpeg has some problems, and it is hard to install the ffmpeg correctly. BTW, my operating system is ubuntu 14.04 lts. Thanks a lot!

**Comment by stevenlovegrove** [comment]
Hi qazmichaelgw. What Pangolin commit are you on? Could you give the detailed error message (make VERBOSE=1 should help).

As per the comment above yours, if you don't need ffmpeg (you probably don't), you can disable it by setting the CMake cache lines to the empty string (using cmake-gui, or ccmake).

**Comment by qazmichaelgw** [comment]
/home/micoarm/Pangolin/src/video/drivers/ffmpeg.cpp:49:39: error: ‘PIX_FMT_YUYV422’ was not declared in this scope
 #define TEST_PIX_FMT_RETURN(fmt) case PIX_FMT_##fmt: return #fmt;
                                       ^
/home/micoarm/Pangolin/src/video/drivers/ffmpeg.cpp:56:5: note: in expansion of macro ‘TEST_PIX_FMT_RETURN’
     TEST_PIX_FMT_RETURN(YUYV422);
     ^
/home/micoarm/Pangolin/src/video/drivers/ffmpeg.cpp:49:39: error: ‘PIX_FMT_RGB24’ was not declared in this scope
 #define TEST_PIX_FMT_RETURN(fmt) case PIX_FMT_##fmt: return #fmt;
                                       ^
/home/micoarm/Pangolin/src/video/drivers/ffmpeg.cpp:57:5: note: in expansion of macro ‘TEST_PIX_FMT_RETURN’
     TEST_PIX_FMT_RETURN(RGB24);
     ^
/home/micoarm/Pangolin/src/video/drivers/ffmpeg.cpp:49:39: error: ‘PIX_FMT_BGR24’ was not declared in this scope
 #define TEST_PIX_FMT_RETURN(fmt) case PIX_FMT_##fmt: return #fmt;
                                       ^
/home/micoarm/Pangolin/src/video/drivers/ffmpeg.cpp:58:5: note: in expansion of macro ‘TEST_PIX_FMT_RETURN’
     TEST_PIX_FMT_RETURN(BGR24);
     ^
/home/micoarm/Pangolin/src/video/drivers/ffmpeg.cpp:49:39: error: ‘PIX_FMT_YUV422P’ was not declared in this scope
 #define TEST_PIX_FMT_RETURN(fmt) case PIX_FMT_##fmt: return #fmt;
                                       ^
/home/micoarm/Pangolin/src/video/drivers/ffmpeg.cpp:59:5: note: in expansion of macro ‘TEST_PIX_FMT_RETURN’
     TEST_PIX_FMT_RETURN(YUV422P);
     ^
/home/micoarm/Pangolin/src/video/drivers/ffmpeg.cpp:49:39: error: ‘PIX_FMT_YUV444P’ was not declared in this scope
 #define TEST_PIX_FMT_RETURN(fmt) case PIX_FMT_##fmt: return #fmt;
                                       ^
/home/micoarm/Pangolin/src/video/drivers/ffmpeg.cpp:60:5: note: in expansion of macro ‘TEST_PIX_FMT_RETURN’
     TEST_PIX_FMT_RETURN(YUV444P);
     ^
/home/micoarm/Pangolin/src/video/drivers/ffmpeg.cpp:49:39: error: ‘PIX_FMT_YUV410P’ was not declared in this scope
 #define TEST_PIX_FMT_RETURN(fmt) case PIX_FMT_##fmt: return #fmt;

Hello stevenlovegrove, here are some error messages. I just clone your latest code on the devel branch. BTW, how to set the cmake cache lines to the empty string by ccmake?
Best regards

**Comment by stevenlovegrove** [comment]
Hopefully fixed with @magniffico 's patch.

**Comment by ccckblaze** [comment]
If anyone has same issus just like @qazmichaelgw 's.
Try this:
vim Pangolin/include/pangolin/video/drivers/ffmpeg.h
add "#define PixelFormat AVPixelFormat" after AVCodec includes

**Comment by stevenlovegrove** [comment]
I've just committed 2e5df57739aa57021828ca74dd3f72c2fbae4bbe to support this older version of ffmpeg.

**Comment by mervynwee** [comment]
In case anyone is interested, what helped for me was to go to CMakeLists.txt in Pangolin/src, and remove this whole part:

```
find_package(FFMPEG QUIET)
if(BUILD_PANGOLIN_VIDEO AND FFMPEG_FOUND)
  set(HAVE_FFMPEG 1)
  list(APPEND INTERNAL_INC  ${FFMPEG_INCLUDE_DIRS} )
  list(APPEND LINK_LIBS ${FFMPEG_LIBRARIES} )
  list(APPEND HEADERS ${INCDIR}/video/drivers/ffmpeg.h)
  list(APPEND SOURCES video/drivers/ffmpeg.cpp)
  list(APPEND VIDEO_FACTORY_REG RegisterFfmpegVideoFactory )
  list(APPEND VIDEO_FACTORY_REG RegisterFfmpegVideoOutputFactory )

  if(_GCC_)
    # FFMPEG is a real pain for deprecating the API.
    set_source_files_properties(video/drivers/ffmpeg.cpp    PROPERTIES COMPILE_FLAGS "-Wno-deprecated-declarations")
  endif()
  message(STATUS "ffmpeg Found and Enabled")
endif()

```

Then go back to Pangolin/build
cmake ..
make
