### ISSUE TITLE
Use Pangolin and GLEW

### ISSUE THREAD

**Issue by Santi-7** [stevenlovegrove/Pangolin#270]
I want to use Pangolin and GLEW in the same app. When trying this, I get a core dump in the first call to a GLEW function. For example, in a basic call to:

    std::vector<float> vertices = ... // Load from a file.
    glBufferData(GL_ARRAY_BUFFER, vertices.size()*sizeof(vertices[0]), &vertices[0], GL_STATIC_DRAW);

Everything works fine with basic OpenGL functions, like `glDrawArrays()`. But it seems that the previous GL entrypoints are not found. I have tried to add `glewExperimental=TRUE`, as it's explaiend [here](https://www.khronos.org/opengl/wiki/OpenGL_Loading_Library), in [line 103 of this Pangolin src](https://github.com/stevenlovegrove/Pangolin/blob/master/src/display/device/display_glut.cpp), before the call to `glewInit()`, but the issue persists.

How can I achieve to use Pangolin and GLEW in the same app?

**Comment by stevenlovegrove** [comment]
GLEW and Pangolin work fine together. Make sure Pangolin is compiled with GLEW so that the glew header is included before GL (https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/gl/glplatform.h)

**Comment by Santi-7** [comment]
Yes, the problem seems to be here. Pangolin doesn't include me the glew header. I've put the following message, and it's not shown while my app is running.

    #ifdef HAVE_GLEW
        #pragma message("Including GLEW")
        #include <GL/glew.h>
    #endif

I have glew installed. How can I compile Pangolin with this library?

**Comment by stevenlovegrove** [comment]
You should use cmake-gui or ccmake to inspect the build system variables.
Perhaps your GLEW is in a non-standard location? What os are you on?

Cmakes output should say something like GLEW found and enabled when it's
picked up, I think, but look for the GLEW section in the cmakes files to
debug.

**Comment by stevenlovegrove** [comment]
If I were you, I'd uninstall your custom built glew and install it via apt-get, as per Pangolin's Readme

`sudo apt-get install libglew-dev`
