### ISSUE TITLE
save screenshot

### ISSUE THREAD

**Issue by RayRuizhiLiao** [stevenlovegrove/Pangolin#271]
Hello!

I'm using "d_cam.SaveOnRender(file_name); " to store my window display, but I somehow get this error: "libpng error: bad parameters to zlib"

Do you have any idea where this error comes from? I Googled it but couldn't find any meaningful answer.

Thanks!

**Comment by stevenlovegrove** [comment]
This is my fault - it has been fixed with this pull request (https://github.com/stevenlovegrove/Pangolin/pull/267)
