### ISSUE TITLE
Store screenshot

### ISSUE THREAD

**Issue by RayRuizhiLiao** [stevenlovegrove/Pangolin#272]
If I have this:

pangolin::View& d_cam1 = pangolin::Display("cam1")
	.SetAspect(640.0f / 480.0f)
	.SetHandler(new pangolin::Handler3D(s_cam));

Is there any way to store the current screenshot, except for using SaveRenderNow() or SaveOnRender()?

Thanks!

**Comment by stevenlovegrove** [comment]
No, those are your best options.
