### ISSUE TITLE
Error "could not convert ‘PIX_FMT_GRAY8’ from ‘PixelFormat’ to ‘pangolin::PixelFormat’ " on command "cmake --build ."

### ISSUE THREAD

**Issue by duduRodrigues** [stevenlovegrove/Pangolin#273]
When I try to build Pangolin I keep getting this error: could not convert ‘PIX_FMT_GRAY8’ from ‘PixelFormat’ to ‘pangolin::PixelFormat’

First, when I run "cmake .." I notice these log lines on terminal: 
![have_ffmpeg_avpixelformat](https://user-images.githubusercontent.com/10099698/28484082-eacbb97e-6e46-11e7-8293-b8fc9009f32e.png)

They show that some tests have failed. But I already have installed the ffmpeg lib, so I do not know why I keep getting this errors.

But anyway the command "cmake .." is concluded with ''success''.
When I try to run the command "cmake --build ." I get these errors:

![error](https://user-images.githubusercontent.com/10099698/28484178-516817ea-6e47-11e7-9d5d-3729eb55db62.png)

What can I do to fix it? I already have installed all dependencies and tried everything. Please, help! 

Thank you!

**Comment by stevenlovegrove** [comment]
I don't know - it looks like you have an unusual version or combination of ffmpeg. Unless you actually need to use ffmpeg (i.e. read avi files or something), the easiest thing for you is probably to simply not compile Pangolin with ffmpeg. E.e. set BUILD_PANGOLIN_FFMPEG to OFF using ccmake or cmake-guil

**Comment by stevenlovegrove** [comment]
Pangolin has had a few ffmpeg fixes since this date. Please re-open if you still have this problem and need ffmpeg.
