### ISSUE TITLE
SimpleDisplay Example Does Not Work After Pull

### ISSUE THREAD

**Issue by RayRuizhiLiao** [stevenlovegrove/Pangolin#274]
The image (screenshot) cannot be properly saved after clicking the "save_cube" button. The png file cannot be opened. 

Can you please check that? Thanks!

**Comment by stevenlovegrove** [comment]
I think this issue should have been fixed very recently when the following commit was merged: https://github.com/stevenlovegrove/Pangolin/commit/2e15d76b8f64ecd2e720e746490d90ee59c1a204

Does your build include that commit?

**Comment by RayRuizhiLiao** [comment]
Yes I had included that commit, and it didn't work. A png file can be saved, but it cannot be opened. 

Any idea why?

**Comment by stevenlovegrove** [comment]
I just checked on my machine, and the png is saved and can be viewed both with the system image viewer, and with Pangolin's VideoViewer, so I'm not sure what is wrong on your machine. What are the exact steps to reproduce? What system are you on? What version of libpng? What viewer are you using? Have you tried using VideoViewer in tools/VideoViewer?

**Comment by RayRuizhiLiao** [comment]
Thanks Steven.
