### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by gaobingshu** [stevenlovegrove/Pangolin#279]
make[2]: *** [src/CMakeFiles/pangolin.dir/image/image_io_jpg.cpp.o] 错误 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] 错误 2
make: *** [all] 错误 2

I meet this error and can someone help me?
Thank you!

**Comment by gaobingshu** [comment]
/home/gaobingshu/Pangolin/src/image/image_io_jpg.cpp: 在函数‘pangolin::TypedImage pangolin::LoadJpg(std::istream&)’中:
/home/gaobingshu/Pangolin/src/image/image_io_jpg.cpp:168:15: 错误： ‘runtime_error’不是‘std’的成员
/home/gaobingshu/Pangolin/src/image/image_io_jpg.cpp:170:15: 错误： ‘runtime_error’不是‘std’的成员
/home/gaobingshu/Pangolin/src/image/image_io_jpg.cpp: 在函数‘void pangolin::SaveJpg(const pangolin::Image<unsigned char>&, const pangolin::PixelFormat&, std::ostream&, float)’中:
/home/gaobingshu/Pangolin/src/image/image_io_jpg.cpp:210:15: 错误： ‘runtime_error’不是‘std’的成员
/home/gaobingshu/Pangolin/src/image/image_io_jpg.cpp:213:15: 错误： ‘runtime_error’不是‘std’的成员
make[2]: *** [src/CMakeFiles/pangolin.dir/image/image_io_jpg.cpp.o] 错误 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by stevenlovegrove** [comment]
I can't tell what the problem is. What is your platform and compiler?

**Comment by jerrykingnice** [comment]
I met the same problem.
[ 20%] Building CXX object src/CMakeFiles/pangolin.dir/log/packetstream.cpp.o
/opt/dso/Pangolin/src/log/packetstream.cpp: In member function 'pangolin::pangoTagType pangolin::PacketStream::readTag(pangolin::pangoTagType)':
/opt/dso/Pangolin/src/log/packetstream.cpp:39:15: error: 'runtime_error' is not a member of 'std'

root@localhost:/opt/dso/Pangolin/build# g++ --version
g++ (Ubuntu/Linaro 4.9.4-2ubuntu1~12.04) 4.9.4

**Comment by LostXine** [comment]
I add 
`#include<stdexcept>`
to .../src/log/packetstream.cpp and it works.
Hope it helps.

**Comment by stevenlovegrove** [comment]
@LostXine c25fd41e37c227c4188e45d915857d8c6ad12d8e - thanks.

**Comment by heroamd** [comment]
i have the same problem and #include<stdexcept> don't work.
