### ISSUE TITLE
Compilation error of examples

### ISSUE THREAD

**Issue by sunstarsun** [stevenlovegrove/Pangolin#282]
i am getting the following error

 error: ‘class pangolin::VarValue<CustomType>’ has no member named ‘str’
             this->str = str_ptr;
make[2]: *** [CMakeFiles/SimpleDisplay.dir/main.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/SimpleDisplay.dir/all' failed
make[1]: *** [CMakeFiles/SimpleDisplay.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stevenlovegrove** [comment]
What platform is this? Are you on master? What is the full build output?
