### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by plyte** [stevenlovegrove/Pangolin#283]
~/env/Pangolin/build$ cmake --build .
[  1%] Linking CXX shared library libpangolin.so
/usr/bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/pangolin.dir/build.make:2037: recipe for target 'src/libpangolin.so' failed
make[2]: *** [src/libpangolin.so] Error 1
CMakeFiles/Makefile2:135: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stevenlovegrove** [comment]
This looks like a python linking issue. You can disable python support if you don't need it, or you could try adding fPIC to the cmake build flags.

**Comment by plyte** [comment]
Thanks! I'll check it out.

**Comment by naonaomxy** [comment]
Do you solve it? I get the same errors.

**Comment by fenfeibani** [comment]
@stevenlovegrove 
how to disable python support and add fPIC to the cmake build flags. Thank you！

**Comment by stevenlovegrove** [comment]
You can disable python by setting BUILD_PANGOLIN_PYTHON to false (with cmake-gui or ccmake for instance).
https://github.com/stevenlovegrove/Pangolin/blob/master/src/CMakeLists.txt#L247

for adding fPIC, you could put it here:
https://github.com/stevenlovegrove/Pangolin/blob/master/CMakeLists.txt#L50
