### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by CarbontTitan** [stevenlovegrove/Pangolin#284]
Hi, I am getting the following error and I am not sure why.
I have the DepthSense SDK installed.
Any help would be greatly appreciated.

~/Pangolin/Pangolin/build$ cmake --build .
Scanning dependencies of target pangolin
[  0%] Building CXX object src/CMakeFiles/pangolin.dir/video/video.cpp.o
[  1%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/depthsense.cpp.o
In file included from /home/indoortrack/Pangolin/Pangolin/src/video/drivers/depthsense.cpp:28:0:
/home/indoortrack/Pangolin/Pangolin/include/pangolin/video/drivers/depthsense.h:38:26: fatal error: DepthSense.hxx: No such file or directory
compilation terminated.
src/CMakeFiles/pangolin.dir/build.make:1838: recipe for target 'src/CMakeFiles/pangolin.dir/video/drivers/depthsense.cpp.o' failed
make[2]: *** [src/CMakeFiles/pangolin.dir/video/drivers/depthsense.cpp.o] Error 1
CMakeFiles/Makefile2:136: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stevenlovegrove** [comment]
Maybe the DepthSense API has changed or you have your include path setup incorrectly for DepthSense. You should look into the SDK to see what the header files look like and if DepthSense.hxx exists anywhere. If you don't plan to use DepthSense with Pangolin, you can disable it in Pangolin's cmake vars to proceed with compilation (probably something like -DBUILD_DEPTHSENSE=0)

**Comment by CarbontTitan** [comment]
Many thanks for your reply. Apologies if this is a stupid question, but how would I check if the include path is correct?
I just installed the DepthSense as per the instructions on their site.

**Comment by stevenlovegrove** [comment]
Sorry I never noticed your follow up. Please re-open if you have this problem on the master branch.
