### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by JingruiYu** [stevenlovegrove/Pangolin#286]
Hi, I am not sure why, but here is a warning and an error:

CMake Warning at src/CMakeLists.txt:652 (export):
  Cannot create package registry file:

    /home/yujr/.cmake/packages/Pangolin/be7d1796df240480052067a613bde09e

  No such file or directory

CMake Error at test/log/CMakeLists.txt:2 (find_package):
  By not providing "FindPangolin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Pangolin",
  but CMake did not find one.

  Could not find a package configuration file provided by "Pangolin"
  (requested version 0.4) with any of the following names:

    PangolinConfig.cmake
    pangolin-config.cmake

  Add the installation prefix of "Pangolin" to CMAKE_PREFIX_PATH or set
  "Pangolin_DIR" to a directory containing one of the above files.  If
  "Pangolin" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

could you help me?

**Comment by sajjadt** [comment]
A workaround that worked for me is to disable tests and examples. 
```
cmake -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF ..
```

**Comment by NikolausDemmel** [comment]
See also #326.

As commented in https://github.com/stevenlovegrove/Pangolin/issues/326#issuecomment-392140263, I think it would be best if tests and examples would not rely on the package registry to ensure they always find the correct version of pangolin when you have multiple builds from different projects on the same system.
