### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by shiva2000** [stevenlovegrove/Pangolin#287]
I get this following error while compiling the source. Can you please suggest what I could be doing wrong?

Thanks
Shiva

In file included from /usr/local/include/TooN/TooN.h:39:0,
                 from /home/shiva/work/Pangolin/include/pangolin/display/opengl_render_state.h:45,
                 from /home/shiva/work/Pangolin/include/pangolin/gl/glsl.h:40,
                 from /home/shiva/work/Pangolin/src/gl/gltext.cpp:29:
/usr/local/include/TooN/internal/operators.hh:52:83: error: expected identifier before ‘(’ token
  template<class L, class R, int F = Field<L,R>::is> struct AddType      { typedef TOON_TYPEOF(gettype<L>()+gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:52:83: error: expected unqualified-id before ‘(’ token
  template<class L, class R, int F = Field<L,R>::is> struct AddType      { typedef TOON_TYPEOF(gettype<L>()+gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:52:83: error: expected ‘)’ before ‘(’ token
/usr/local/include/TooN/internal/operators.hh:52:83: error: expected ‘)’ before ‘(’ token
/usr/local/include/TooN/internal/operators.hh:52:83: error: ‘typeof’ declared as function returning a function
  template<class L, class R, int F = Field<L,R>::is> struct AddType      { typedef TOON_TYPEOF(gettype<L>()+gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:52:83: error: expected ‘;’ at end of member declaration
/usr/local/include/TooN/internal/operators.hh:52:83: error: expected unqualified-id before ‘+’ token
  template<class L, class R, int F = Field<L,R>::is> struct AddType      { typedef TOON_TYPEOF(gettype<L>()+gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:53:83: error: expected identifier before ‘(’ token
  template<class L, class R, int F = Field<L,R>::is> struct SubtractType { typedef TOON_TYPEOF(gettype<L>()-gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:53:83: error: expected unqualified-id before ‘(’ token
  template<class L, class R, int F = Field<L,R>::is> struct SubtractType { typedef TOON_TYPEOF(gettype<L>()-gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:53:83: error: expected ‘)’ before ‘(’ token
/usr/local/include/TooN/internal/operators.hh:53:83: error: expected ‘)’ before ‘(’ token
/usr/local/include/TooN/internal/operators.hh:53:83: error: ‘typeof’ declared as function returning a function
  template<class L, class R, int F = Field<L,R>::is> struct SubtractType { typedef TOON_TYPEOF(gettype<L>()-gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:53:83: error: expected ‘;’ at end of member declaration
/usr/local/include/TooN/internal/operators.hh:53:83: error: expected unqualified-id before ‘-’ token
  template<class L, class R, int F = Field<L,R>::is> struct SubtractType { typedef TOON_TYPEOF(gettype<L>()-gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:54:83: error: expected identifier before ‘(’ token
  template<class L, class R, int F = Field<L,R>::is> struct MultiplyType { typedef TOON_TYPEOF(gettype<L>()*gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:54:83: error: expected unqualified-id before ‘(’ token
  template<class L, class R, int F = Field<L,R>::is> struct MultiplyType { typedef TOON_TYPEOF(gettype<L>()*gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:54:83: error: expected ‘)’ before ‘(’ token
/usr/local/include/TooN/internal/operators.hh:54:83: error: expected ‘)’ before ‘(’ token
/usr/local/include/TooN/internal/operators.hh:54:83: error: ‘typeof’ declared as function returning a function
  template<class L, class R, int F = Field<L,R>::is> struct MultiplyType { typedef TOON_TYPEOF(gettype<L>()*gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:54:83: error: expected ‘;’ at end of member declaration
/usr/local/include/TooN/internal/operators.hh:54:83: error: template-id ‘gettype<R>’ in declaration of primary template
  template<class L, class R, int F = Field<L,R>::is> struct MultiplyType { typedef TOON_TYPEOF(gettype<L>()*gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:54:83: error: expected ‘;’ at end of member declaration
/usr/local/include/TooN/internal/operators.hh:54:83: error: expected unqualified-id before ‘)’ token
  template<class L, class R, int F = Field<L,R>::is> struct MultiplyType { typedef TOON_TYPEOF(gettype<L>()*gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:55:83: error: expected identifier before ‘(’ token
  template<class L, class R, int F = Field<L,R>::is> struct DivideType   { typedef TOON_TYPEOF(gettype<L>()/gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:55:83: error: expected unqualified-id before ‘(’ token
  template<class L, class R, int F = Field<L,R>::is> struct DivideType   { typedef TOON_TYPEOF(gettype<L>()/gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:55:83: error: expected ‘)’ before ‘(’ token
/usr/local/include/TooN/internal/operators.hh:55:83: error: expected ‘)’ before ‘(’ token
/usr/local/include/TooN/internal/operators.hh:55:83: error: ‘typeof’ declared as function returning a function
  template<class L, class R, int F = Field<L,R>::is> struct DivideType   { typedef TOON_TYPEOF(gettype<L>()/gettype<R>()) type;};
                                                                                   ^
/usr/local/include/TooN/internal/operators.hh:55:83: error: expected ‘;’ at end of member declaration
/usr/local/include/TooN/internal/operators.hh:55:83: error: expected unqualified-id before ‘/’ token
  template<class L, class R, int F = Field<L,R>::is> struct DivideType   { typedef TOON_TYPEOF(gettype<L>()/gettype<R>()) type;};
                                                                                   ^
In file included from /usr/local/include/TooN/se3.h:33:0,
                 from /home/shiva/work/Pangolin/include/pangolin/display/opengl_render_state.h:46,
                 from /home/shiva/work/Pangolin/include/pangolin/gl/glsl.h:40,
                 from /home/shiva/work/Pangolin/src/gl/gltext.cpp:29:
/usr/local/include/TooN/so3.h: In instantiation of ‘void TooN::SO3<Precision>::coerce() [with Precision = double]’:
/usr/local/include/TooN/so3.h:96:10:   required from ‘TooN::SO3<Precision>& TooN::SO3<Precision>::operator=(const TooN::Matrix<Rows2, Cols2, Precision2, Base2>&) [with int R = 3; int C = 3; P = double; A = TooN::Internal::Slice<4, 1>; Precision = double]’
/usr/local/include/TooN/so3.h:65:42:   required from ‘TooN::SO3<Precision>::SO3(const TooN::Matrix<Rows2, Cols2, Precision2, Base2>&) [with int R = 3; int C = 3; P = double; A = TooN::Internal::Slice<4, 1>; Precision = double]’
/home/shiva/work/Pangolin/include/pangolin/display/opengl_render_state.h:342:43:   required from here
/usr/local/include/TooN/so3.h:103:47: error: ambiguous overload for ‘operator*’ (operand types are ‘TooN::Internal::GenericMBase<3, 3, double, 3, 1, TooN::Internal::MatrixAlloc<3, 3, double, true> >::Vec {aka TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >}’ and ‘TooN::Internal::GenericMBase<3, 3, double, 3, 1, TooN::Internal::MatrixAlloc<3, 3, double, true> >::Vec {aka TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >}’)
   my_matrix[1] -= my_matrix[0] * (my_matrix[0]*my_matrix[1]);
                                               ^
/usr/local/include/TooN/so3.h:103:47: note: candidates are:
In file included from /usr/local/include/TooN/TooN.h:98:0,
                 from /home/shiva/work/Pangolin/include/pangolin/display/opengl_render_state.h:45,
                 from /home/shiva/work/Pangolin/include/pangolin/gl/glsl.h:40,
                 from /home/shiva/work/Pangolin/src/gl/gltext.cpp:29:
/usr/local/include/TooN/internal/operators.hh:494:64: note: TooN::Vector<Size, typename TooN::Internal::Multiply::Return<P1, P2>::Type> TooN::operator*(const TooN::Vector<Size2, Precision2, Base2>&, const P2&) [with int Size = 3; P1 = double; B1 = TooN::Internal::SliceVBase<1>; P2 = TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >; typename TooN::Internal::Multiply::Return<P1, P2>::Type = void]
 Vector<Size, typename Internal::Multiply::Return<P1,P2>::Type> operator*(const Vector<Size, P1, B1>& v, const P2& s){
                                                                ^
/usr/local/include/TooN/internal/operators.hh:521:64: note: TooN::Vector<Size, typename TooN::Internal::Multiply::Return<P2, P1>::Type> TooN::operator*(const P2&, const TooN::Vector<Size2, Precision2, Base2>&) [with int Size = 3; P1 = double; B1 = TooN::Internal::SliceVBase<1>; P2 = TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >; typename TooN::Internal::Multiply::Return<P2, P1>::Type = void]
 Vector<Size, typename Internal::Multiply::Return<P2,P1>::Type> operator*(const P2& s, const Vector<Size, P1, B1>& v){
                                                                ^
In file included from /usr/local/include/TooN/se3.h:33:0,
                 from /home/shiva/work/Pangolin/include/pangolin/display/opengl_render_state.h:46,
                 from /home/shiva/work/Pangolin/include/pangolin/gl/glsl.h:40,
                 from /home/shiva/work/Pangolin/src/gl/gltext.cpp:29:
/usr/local/include/TooN/so3.h:105:47: error: ambiguous overload for ‘operator*’ (operand types are ‘TooN::Internal::GenericMBase<3, 3, double, 3, 1, TooN::Internal::MatrixAlloc<3, 3, double, true> >::Vec {aka TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >}’ and ‘TooN::Internal::GenericMBase<3, 3, double, 3, 1, TooN::Internal::MatrixAlloc<3, 3, double, true> >::Vec {aka TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >}’)
   my_matrix[2] -= my_matrix[0] * (my_matrix[0]*my_matrix[2]);
                                               ^
/usr/local/include/TooN/so3.h:105:47: note: candidates are:
In file included from /usr/local/include/TooN/TooN.h:98:0,
                 from /home/shiva/work/Pangolin/include/pangolin/display/opengl_render_state.h:45,
                 from /home/shiva/work/Pangolin/include/pangolin/gl/glsl.h:40,
                 from /home/shiva/work/Pangolin/src/gl/gltext.cpp:29:
/usr/local/include/TooN/internal/operators.hh:494:64: note: TooN::Vector<Size, typename TooN::Internal::Multiply::Return<P1, P2>::Type> TooN::operator*(const TooN::Vector<Size2, Precision2, Base2>&, const P2&) [with int Size = 3; P1 = double; B1 = TooN::Internal::SliceVBase<1>; P2 = TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >; typename TooN::Internal::Multiply::Return<P1, P2>::Type = void]
 Vector<Size, typename Internal::Multiply::Return<P1,P2>::Type> operator*(const Vector<Size, P1, B1>& v, const P2& s){
                                                                ^
/usr/local/include/TooN/internal/operators.hh:521:64: note: TooN::Vector<Size, typename TooN::Internal::Multiply::Return<P2, P1>::Type> TooN::operator*(const P2&, const TooN::Vector<Size2, Precision2, Base2>&) [with int Size = 3; P1 = double; B1 = TooN::Internal::SliceVBase<1>; P2 = TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >; typename TooN::Internal::Multiply::Return<P2, P1>::Type = void]
 Vector<Size, typename Internal::Multiply::Return<P2,P1>::Type> operator*(const P2& s, const Vector<Size, P1, B1>& v){
                                                                ^
In file included from /usr/local/include/TooN/se3.h:33:0,
                 from /home/shiva/work/Pangolin/include/pangolin/display/opengl_render_state.h:46,
                 from /home/shiva/work/Pangolin/include/pangolin/gl/glsl.h:40,
                 from /home/shiva/work/Pangolin/src/gl/gltext.cpp:29:
/usr/local/include/TooN/so3.h:106:47: error: ambiguous overload for ‘operator*’ (operand types are ‘TooN::Internal::GenericMBase<3, 3, double, 3, 1, TooN::Internal::MatrixAlloc<3, 3, double, true> >::Vec {aka TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >}’ and ‘TooN::Internal::GenericMBase<3, 3, double, 3, 1, TooN::Internal::MatrixAlloc<3, 3, double, true> >::Vec {aka TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >}’)
   my_matrix[2] -= my_matrix[1] * (my_matrix[1]*my_matrix[2]);
                                               ^
/usr/local/include/TooN/so3.h:106:47: note: candidates are:
In file included from /usr/local/include/TooN/TooN.h:98:0,
                 from /home/shiva/work/Pangolin/include/pangolin/display/opengl_render_state.h:45,
                 from /home/shiva/work/Pangolin/include/pangolin/gl/glsl.h:40,
                 from /home/shiva/work/Pangolin/src/gl/gltext.cpp:29:
/usr/local/include/TooN/internal/operators.hh:494:64: note: TooN::Vector<Size, typename TooN::Internal::Multiply::Return<P1, P2>::Type> TooN::operator*(const TooN::Vector<Size2, Precision2, Base2>&, const P2&) [with int Size = 3; P1 = double; B1 = TooN::Internal::SliceVBase<1>; P2 = TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >; typename TooN::Internal::Multiply::Return<P1, P2>::Type = void]
 Vector<Size, typename Internal::Multiply::Return<P1,P2>::Type> operator*(const Vector<Size, P1, B1>& v, const P2& s){
                                                                ^
/usr/local/include/TooN/internal/operators.hh:521:64: note: TooN::Vector<Size, typename TooN::Internal::Multiply::Return<P2, P1>::Type> TooN::operator*(const P2&, const TooN::Vector<Size2, Precision2, Base2>&) [with int Size = 3; P1 = double; B1 = TooN::Internal::SliceVBase<1>; P2 = TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >; typename TooN::Internal::Multiply::Return<P2, P1>::Type = void]
 Vector<Size, typename Internal::Multiply::Return<P2,P1>::Type> operator*(const P2& s, const Vector<Size, P1, B1>& v){
                                                                ^
In file included from /usr/local/include/TooN/so3.h:34:0,
                 from /usr/local/include/TooN/se3.h:33,
                 from /home/shiva/work/Pangolin/include/pangolin/display/opengl_render_state.h:46,
                 from /home/shiva/work/Pangolin/include/pangolin/gl/glsl.h:40,
                 from /home/shiva/work/Pangolin/src/gl/gltext.cpp:29:
/usr/local/include/TooN/helpers.h: In instantiation of ‘TooN::Vector<S, P> TooN::unit(const TooN::Vector<Size2, Precision2, Base2>&) [with int Size = 3; Precision = double; Base = TooN::Internal::SliceVBase<1>]’:
/usr/local/include/TooN/so3.h:102:35:   required from ‘void TooN::SO3<Precision>::coerce() [with Precision = double]’
/usr/local/include/TooN/so3.h:96:10:   required from ‘TooN::SO3<Precision>& TooN::SO3<Precision>::operator=(const TooN::Matrix<Rows2, Cols2, Precision2, Base2>&) [with int R = 3; int C = 3; P = double; A = TooN::Internal::Slice<4, 1>; Precision = double]’
/usr/local/include/TooN/so3.h:65:42:   required from ‘TooN::SO3<Precision>::SO3(const TooN::Matrix<Rows2, Cols2, Precision2, Base2>&) [with int R = 3; int C = 3; P = double; A = TooN::Internal::Slice<4, 1>; Precision = double]’
/home/shiva/work/Pangolin/include/pangolin/display/opengl_render_state.h:342:43:   required from here
/usr/local/include/TooN/helpers.h:73:23: error: ambiguous overload for ‘operator*’ (operand types are ‘const TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >’ and ‘const TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >’)
   return v * (1/sqrt(v*v));
                       ^
/usr/local/include/TooN/helpers.h:73:23: note: candidates are:
In file included from /usr/local/include/TooN/TooN.h:98:0,
                 from /home/shiva/work/Pangolin/include/pangolin/display/opengl_render_state.h:45,
                 from /home/shiva/work/Pangolin/include/pangolin/gl/glsl.h:40,
                 from /home/shiva/work/Pangolin/src/gl/gltext.cpp:29:
/usr/local/include/TooN/internal/operators.hh:494:64: note: TooN::Vector<Size, typename TooN::Internal::Multiply::Return<P1, P2>::Type> TooN::operator*(const TooN::Vector<Size2, Precision2, Base2>&, const P2&) [with int Size = 3; P1 = double; B1 = TooN::Internal::SliceVBase<1>; P2 = TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >; typename TooN::Internal::Multiply::Return<P1, P2>::Type = void]
 Vector<Size, typename Internal::Multiply::Return<P1,P2>::Type> operator*(const Vector<Size, P1, B1>& v, const P2& s){
                                                                ^
/usr/local/include/TooN/internal/operators.hh:521:64: note: TooN::Vector<Size, typename TooN::Internal::Multiply::Return<P2, P1>::Type> TooN::operator*(const P2&, const TooN::Vector<Size2, Precision2, Base2>&) [with int Size = 3; P1 = double; B1 = TooN::Internal::SliceVBase<1>; P2 = TooN::Vector<3, double, TooN::Internal::SliceVBase<1> >; typename TooN::Internal::Multiply::Return<P2, P1>::Type = void]
 Vector<Size, typename Internal::Multiply::Return<P2,P1>::Type> operator*(const P2& s, const Vector<Size, P1, B1>& v){
                                                                ^
make[2]: *** [src/CMakeFiles/pangolin.dir/gl/gltext.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2

**Comment by stevenlovegrove** [comment]
TooN is not required for Pangolin. If you don't intend to use TooN with pangolin, you can disable TooN support using cmake which should fix your issue. I've not used TooN for some time, so it's possible my wrapper functions are outdated.

**Comment by stevenlovegrove** [comment]
If anyone is still using TooN in Pangolin, please reopen (and ideally submit a PR for fixes :D )
