### ISSUE TITLE
Check Box unable to work as a private member of a class

### ISSUE THREAD

**Issue by Akira87** [stevenlovegrove/Pangolin#288]
Hi,
I am trying to create two check boxes as a private members in a class. But I noticed that in the main loop function that calls the draw functions, does not seem to update the check boxes in the main loop. However, if I declare the two check boxes as a static variables in the main loop function, it works perfectly well. May I know what may be the cause that does not allow the declaration of the check boxes as private members?

Thanks.

**Comment by stevenlovegrove** [comment]
Sorry for never responding. I would need to see some minimal code to really say what is going on. Since this is so old I'll close but please reopen if anyone hits this problem.
