### ISSUE TITLE
Vars: Custom serialization

### ISSUE THREAD

**Issue by stevenlovegrove** [stevenlovegrove/Pangolin#29]
Add ability to over-ride serialization methods for Pangolin Variables, or set default numerical precision, etc.

**Comment by aicioara** [comment]
@stevenlovegrove  I can add that because I need it. Which file should I look into?

**Comment by aicioara** [comment]
Just to double check, I want variables like this to be less truncated, I guess this is what the feature is asking.

![screenshot267](https://cloud.githubusercontent.com/assets/3248682/15315060/60a7ecfe-1c0d-11e6-930d-2b3a0e2381c1.png)

(Ideally it should say 16266, not 1.627e+4)

**Comment by stevenlovegrove** [comment]
The precision and formatting is set here:
https://github.com/stevenlovegrove/Pangolin/blob/devel/src/display/widgets/widgets.cpp#L477

My original intention was to more generally allow an arbitrary stream serialisation within Vars for Sliders and also custom types. This can also be helpful when writing json settings files (via pangolin.save() from the dropdown console)

**Comment by aicioara** [comment]
I'll give it a thought and submit a PR once I have something. No promises.
