### ISSUE TITLE
Record from multiple firewire 1394b cameras

### ISSUE THREAD

**Issue by rohanchabra** [stevenlovegrove/Pangolin#292]
In the documentation of videoviewer I cannot easily find how to actually use two or more sync firewire cameras. It will be great to know about that.  
For example:- how can I use both url//0 and url//1
I tried join:- 
I am using PointGrey Cameras
I tried the following command but it seems to freeze the VideoViewer. Single camera works fine even with join operation.
join://{dc1394:[fmt=GRAY8,size=800x600,fps=15]//0}{dc1394:[fmt=GRAY8,size=800x600,fps=15]//1}

**Comment by stevenlovegrove** [comment]
Sorry to be so slow to reply - that command line looks good (make sure you quote it for your terminal). Does it work if you launch two instances of VideoViewer, or does it still freeze?
