### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by haidela** [stevenlovegrove/Pangolin#295]
Hello everyone, last week I was installing Pangolin no problem, after my operating system had problem and installed a new OS, virtual machine,  and Pangolin in ROS indigo + Ubuntu 14.04.5 Desktop am64 under VMware workstation 14 Pro, when I run cmake --build . : ERROR:

haidara@haidara-virtual-machine:~/catkin_ws/src/Pangolin/build$ cmake --build .
Scanning dependencies of target pangolin
[  1%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_exr.cpp.o
/home/haidara/catkin_ws/src/Pangolin/src/image/image_io_exr.cpp:34:31: error: invalid use of incomplete type ‘class Imf::IStream’
 class StdIStream: public Imf::IStream
                               ^
In file included from /usr/include/OpenEXR/ImfInputFile.h:46:0,
                 from /home/haidara/catkin_ws/src/Pangolin/src/image/image_io_exr.cpp:8:
/usr/include/OpenEXR/ImfHeader.h:62:7: error: forward declaration of ‘class Imf::IStream’
 class IStream;
       ^
/home/haidara/catkin_ws/src/Pangolin/src/image/image_io_exr.cpp: In constructor ‘pangolin::StdIStream::StdIStream(std::istream&)’:
/home/haidara/catkin_ws/src/Pangolin/src/image/image_io_exr.cpp:38:14: error: type ‘Imf::IStream’ is not a direct base of ‘pangolin::StdIStream’
         Imf::IStream ("stream"),
              ^
/home/haidara/catkin_ws/src/Pangolin/src/image/image_io_exr.cpp: In function ‘pangolin::TypedImage pangolin::LoadExr(std::istream&)’:
/home/haidara/catkin_ws/src/Pangolin/src/image/image_io_exr.cpp:82:32: error: no matching function for call to ‘Imf::InputFile::InputFile(pangolin::StdIStream&)’
     Imf::InputFile file(istream);
                                ^
/home/haidara/catkin_ws/src/Pangolin/src/image/image_io_exr.cpp:82:32: note: candidates are:
In file included from /home/haidara/catkin_ws/src/Pangolin/src/image/image_io_exr.cpp:8:0:
/usr/include/OpenEXR/ImfInputFile.h:195:5: note: Imf::InputFile::InputFile(const Imf::InputFile&)
     InputFile (const InputFile &);   // not implemented
     ^
/usr/include/OpenEXR/ImfInputFile.h:195:5: note:   no known conversion for argument 1 from ‘pangolin::StdIStream’ to ‘const Imf::InputFile&’
/usr/include/OpenEXR/ImfInputFile.h:83:5: note: Imf::InputFile::InputFile(Imf::IStream&, int)
     InputFile (IStream &is, int numThreads = globalThreadCount());
     ^
/usr/include/OpenEXR/ImfInputFile.h:83:5: note:   no known conversion for argument 1 from ‘pangolin::StdIStream’ to ‘Imf::IStream&’
/usr/include/OpenEXR/ImfInputFile.h:71:5: note: Imf::InputFile::InputFile(const char*, int)
     InputFile (const char fileName[], int numThreads = globalThreadCount());
     ^
/usr/include/OpenEXR/ImfInputFile.h:71:5: note:   no known conversion for argument 1 from ‘pangolin::StdIStream’ to ‘const char*’
make[2]: *** [src/CMakeFiles/pangolin.dir/image/image_io_exr.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2
haidara@haidara-virtual-machine:~/catkin_ws/src/Pangolin/build$ 

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES

auto-starting new master
process[master]: started with pid [31542]
ROS_MASTER_URI=http://haidara-virtual-machine:11311/

setting /run_id to 338686d8-b1a1-11e7-a91b-000c295aa32e
process[rosout-1]: started with pid [31555]
started core service [/rosout]

I am trying all issues about make error with no success. Anyone who has ideas about this would be appreciated.

**Comment by chunshun** [comment]
have you solved ?

**Comment by haidela** [comment]
@chunshun not yet

**Comment by bmende** [comment]
I am getting almost the exact same build error. I think that it may have to do with a recent pull request to support OpenEXR because if you look at the current ci tests, it is failing. I just went back one commit and it seems to be working now. Hopefully this will get fixed soon!

**Comment by codefordead** [comment]
got same question!!!!

**Comment by codefordead** [comment]
@haidela  I randomly downloaded the commit at Sep 16 2017 and it worked.

**Comment by haidela** [comment]
@bmende & @codefordead Thank you for reply, I am downloading  one released  commit and installed it, it works well. Thank you

**Comment by WantBeBitter** [comment]
@haidela @codefordead @bmende Hi,i have met the same problem,and i dont know where and how to download the so-called 'commit',thank u for help!

**Comment by haidela** [comment]
@WantBeBitterHello, if you open the link https://github.com/stevenlovegrove/Pangolin, on the left there is the icon Branch and scroll to choose one released commit and download it.

**Comment by WantBeBitter** [comment]
@haidela I have already download this commit "OpenEXR Load support (thanks Simon)",but it doesnt work.Is there Anything more I can do ?

**Comment by codefordead** [comment]
@WantBeBitter  I will email you my download and just follow the instruction. It will work.

**Comment by codefordead** [comment]
@WantBeBitter  https://www.dropbox.com/s/k0636xos4hpbn6d/Pangolin-8b6a6b706d50d4172eeb6d5827f40b2207483cf0.zip?dl=0

**Comment by WantBeBitter** [comment]
@codefordead thx!

**Comment by stevenlovegrove** [comment]
Yeah, the latest commit is failing, sorry. Temporarily, you should:

`git checkout e03bc2702d41cde78f43f4284646f2f0607f88ee `

**Comment by hanyang1986** [comment]
@codefordead  thx
