### ISSUE TITLE
.dll for windows

### ISSUE THREAD

**Issue by arifle** [stevenlovegrove/Pangolin#297]
Is the CI server able to generate a Windows binary package with .dll library in it.

**Comment by stevenlovegrove** [comment]
Yes - there is a link in the readme (https://ci.appveyor.com/project/stevenlovegrove/pangolin/build/artifacts)

**Comment by vicdxxx** [comment]
> Yes - there is a link in the readme (https://ci.appveyor.com/project/stevenlovegrove/pangolin/build/artifacts)

this article is deleted
