### ISSUE TITLE
Cannot build Pangolin on macOS High Sierra 10.13

### ISSUE THREAD

**Issue by dimitris64bit** [stevenlovegrove/Pangolin#298]
It stops at 73% with the following error:

[ 73%] Linking CXX shared library libpangolin.dylib
Undefined symbols for architecture x86_64:
  "_jpeg_CreateCompress", referenced from:
      pangolin::SaveJpg(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, float) in image_io_jpg.cpp.o
  "_jpeg_CreateDecompress", referenced from:
      pangolin::LoadJpg(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_jpg.cpp.o
  "_jpeg_destroy_compress", referenced from:
      pangolin::SaveJpg(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, float) in image_io_jpg.cpp.o
  "_jpeg_destroy_decompress", referenced from:
      pangolin::LoadJpg(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_jpg.cpp.o
  "_jpeg_finish_compress", referenced from:
      pangolin::SaveJpg(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, float) in image_io_jpg.cpp.o
  "_jpeg_finish_decompress", referenced from:
      pangolin::LoadJpg(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_jpg.cpp.o
  "_jpeg_read_header", referenced from:
      pangolin::LoadJpg(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_jpg.cpp.o
  "_jpeg_read_scanlines", referenced from:
      pangolin::LoadJpg(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_jpg.cpp.o
  "_jpeg_resync_to_restart", referenced from:
      pangolin::LoadJpg(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_jpg.cpp.o
  "_jpeg_set_defaults", referenced from:
      pangolin::SaveJpg(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, float) in image_io_jpg.cpp.o
  "_jpeg_set_quality", referenced from:
      pangolin::SaveJpg(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, float) in image_io_jpg.cpp.o
  "_jpeg_start_compress", referenced from:
      pangolin::SaveJpg(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, float) in image_io_jpg.cpp.o
  "_jpeg_start_decompress", referenced from:
      pangolin::LoadJpg(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_jpg.cpp.o
  "_jpeg_std_error", referenced from:
      pangolin::LoadJpg(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_jpg.cpp.o
      pangolin::SaveJpg(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, float) in image_io_jpg.cpp.o
  "_jpeg_write_scanlines", referenced from:
      pangolin::SaveJpg(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, float) in image_io_jpg.cpp.o
  "_png_create_info_struct", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
      pangolin::SavePng(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, int) in image_io_png.cpp.o
  "_png_create_read_struct", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_create_write_struct", referenced from:
      pangolin::SavePng(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, int) in image_io_png.cpp.o
  "_png_destroy_read_struct", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_destroy_write_struct", referenced from:
      pangolin::SavePng(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, int) in image_io_png.cpp.o
  "_png_free_data", referenced from:
      pangolin::SavePng(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, int) in image_io_png.cpp.o
  "_png_get_bit_depth", referenced from:
      pangolin::PngFormat(png_struct_def*, png_info_def*) in image_io_png.cpp.o
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_get_color_type", referenced from:
      pangolin::PngFormat(png_struct_def*, png_info_def*) in image_io_png.cpp.o
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_get_image_height", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_get_image_width", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_get_interlace_type", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_get_io_ptr", referenced from:
      pangolin::pango_png_stream_read(png_struct_def*, unsigned char*, unsigned long) in image_io_png.cpp.o
      pangolin::pango_png_stream_write(png_struct_def*, unsigned char*, unsigned long) in image_io_png.cpp.o
      pangolin::pango_png_stream_write_flush(png_struct_def*) in image_io_png.cpp.o
  "_png_get_rowbytes", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_get_rows", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_read_png", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_set_IHDR", referenced from:
      pangolin::SavePng(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, int) in image_io_png.cpp.o
  "_png_set_compression_level", referenced from:
      pangolin::SavePng(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, int) in image_io_png.cpp.o
  "_png_set_expand_gray_1_2_4_to_8", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_set_longjmp_fn", referenced from:
      pangolin::SavePng(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, int) in image_io_png.cpp.o
  "_png_set_packing", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_set_palette_to_rgb", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_set_read_fn", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_set_rows", referenced from:
      pangolin::SavePng(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, int) in image_io_png.cpp.o
  "_png_set_sig_bytes", referenced from:
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_set_write_fn", referenced from:
      pangolin::SavePng(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, int) in image_io_png.cpp.o
  "_png_sig_cmp", referenced from:
      pangolin::pango_png_validate(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
      pangolin::LoadPng(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image_io_png.cpp.o
  "_png_write_png", referenced from:
      pangolin::SavePng(pangolin::Image<unsigned char> const&, pangolin::PixelFormat const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, int) in image_io_png.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libpangolin.dylib] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2

Any help?

**Comment by BofeiCHEN** [comment]
@dimitris64bit The same problem for me. Have you solved it?

**Comment by mateng0915** [comment]
I  also facing the same problem @dimitris64bit @BofeiCHEN are you guys solve this problem, my system is OSX 10.13

**Comment by BofeiCHEN** [comment]
@mateng0915 sorry, I didn't find a solution in Mac.

**Comment by stevenlovegrove** [comment]
I build Pangolin on OSX (High Sierra) regularly and so does the build server, so this is likely going to be a configuration issue. I would check that the jpeg/png header includes and library point to the same version of the library. Also it would help to comment what compiler and library versions you're using for those two dependencies. I tend to install libjpeg and libpng via macports, but maybe you're getting them from elsewhere?

**Comment by mateng0915** [comment]
i instal libjpeg and libpng through brew

**Comment by mateng0915** [comment]
error: static_assert failed
      "Allocator::value_type must be same type as value_type"
    static_assert((is_same<typename allocator_type::value_type, value_type>::value),
this is the error message

**Comment by Swetko** [comment]
Hi Steve! I am trying to let students in the Computer Vision class use Pangolin and lots of the use Macs. We see the same issue compiling on Mac. Do you know if the issue is with brew/macports ?

**Comment by NikolausDemmel** [comment]
I use Pangolin on macos Sierra, some of my students on Mojave and it seems to work fine. We use the dependencies from homebrew.

I've had issue with libpng / libjpeg / libtiff and cmake before when Mono was installed and cmake picked up those headers instead of the homebrew-installed versions. See https://github.com/openMVG/openMVG/issues/1349#issuecomment-401492811 for a workaround.

Where is cmake finding those libraries in your case?

**Comment by stevenlovegrove** [comment]
Hey Svet - again, I think it is likely that Pangolin is finding headers and libraries from two different install locations (check with cmake-gui).

**Comment by kir486680** [comment]
I have same issue with Big Sur
