### ISSUE TITLE
Hi, how can i compiling Pangolin on arm platform with tina linux?

### ISSUE THREAD

**Issue by xinliangyu** [stevenlovegrove/Pangolin#299]
my tina linux only have libEGL.so libGLESv1_CM.so libGLESv2.so and libMali.so,
but don't have glut 、glew and x11library.
so i don't know how to change pangolin cmakelist file.
can anyone give me some suggestion?
thanks very much!

**Comment by stevenlovegrove** [comment]
You will likely have to make code changes to support this. You need to find a way of opening a GL context and sending input events through (probably using EGL I guess). There are specific paths for Android and iOS, but not other embedded systems.

Good luck!

**Comment by eraserpencil** [comment]
@stevenlovegrove 
Is your advice to all arm architectures or specific to tina linux?

**Comment by stevenlovegrove** [comment]
@eraserpencil the issue is the windowing and GL implementation, not the host processor, per se. Pangolin only supports X11 (Linux), Wayland (Linux), Cocoa (mac), maybe Android. If your device has OpenGL and an XServer (like an Nvidia Jetson running Ubuntu for example), it should work as-is.
