### ISSUE TITLE
Pangolin make error about image-io-exr.cpp

### ISSUE THREAD

**Issue by zxff** [stevenlovegrove/Pangolin#300]
/home/jetlag/my_slam/Pangolin/src/image/image_io_exr.cpp:34:31: error: invalid use of incomplete type ‘class Imf::IStream’
 class StdIStream: public Imf::IStream
                               ^
In file included from /usr/include/OpenEXR/ImfInputFile.h:46:0,
                 from /home/jetlag/my_slam/Pangolin/src/image/image_io_exr.cpp:8:
/usr/include/OpenEXR/ImfHeader.h:62:7: error: forward declaration of ‘class Imf::IStream’
 class IStream;
       ^
/home/jetlag/my_slam/Pangolin/src/image/image_io_exr.cpp: In constructor ‘pangolin::StdIStream::StdIStream(std::istream&)’:
/home/jetlag/my_slam/Pangolin/src/image/image_io_exr.cpp:38:14: error: type ‘Imf::IStream’ is not a direct base of ‘pangolin::StdIStream’
         Imf::IStream ("stream"),
              ^
/home/jetlag/my_slam/Pangolin/src/image/image_io_exr.cpp: In function ‘pangolin::TypedImage pangolin::LoadExr(std::istream&)’:
/home/jetlag/my_slam/Pangolin/src/image/image_io_exr.cpp:82:32: error: no matching function for call to ‘Imf::InputFile::InputFile(pangolin::StdIStream&)’
     Imf::InputFile file(istream);
                                ^
/home/jetlag/my_slam/Pangolin/src/image/image_io_exr.cpp:82:32: note: candidates are:
In file included from /home/jetlag/my_slam/Pangolin/src/image/image_io_exr.cpp:8:0:
/usr/include/OpenEXR/ImfInputFile.h:195:5: note: Imf::InputFile::InputFile(const Imf::InputFile&)
     InputFile (const InputFile &);   // not implemented
     ^
/usr/include/OpenEXR/ImfInputFile.h:195:5: note:   no known conversion for argument 1 from ‘pangolin::StdIStream’ to ‘const Imf::InputFile&’
/usr/include/OpenEXR/ImfInputFile.h:83:5: note: Imf::InputFile::InputFile(Imf::IStream&, int)
     InputFile (IStream &is, int numThreads = globalThreadCount());
     ^
/usr/include/OpenEXR/ImfInputFile.h:83:5: note:   no known conversion for argument 1 from ‘pangolin::StdIStream’ to ‘Imf::IStream&’
/usr/include/OpenEXR/ImfInputFile.h:71:5: note: Imf::InputFile::InputFile(const char*, int)
     InputFile (const char fileName[], int numThreads = globalThreadCount());
     ^
/usr/include/OpenEXR/ImfInputFile.h:71:5: note:   no known conversion for argument 1 from ‘pangolin::StdIStream’ to ‘const char*’
make[2]: *** [src/CMakeFiles/pangolin.dir/image/image_io_exr.cpp.o] 错误 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] 错误 2
make: *** [all] 错误 2

please give me some advices if you occur this issue,thanks!

**Comment by Archerrrr** [comment]
Exactly the same problem that I met, using a virtual machine of Ubuntu 14.
Needing help...

**Comment by khashwung** [comment]
also the same problem using virtual machine of Ubuntu 14..

**Comment by ShawnChan924** [comment]
also the same problem in VM of Ubuntu 14.04

**Comment by Archerrrr** [comment]
I reset the project to a older version using git command, and it run correctly.

**Comment by khashwung** [comment]
Yes... an order version works. Thank Archerrr.

**Comment by GITSHOHOKU** [comment]
I am a new programmer,how to get an order version

**Comment by stevenlovegrove** [comment]
This should now be fixed on the most recent version

**Comment by stevenlovegrove** [comment]
Closing. Please reopen if you hit this again.
