### ISSUE TITLE
example with python command prompt

### ISSUE THREAD

**Issue by phil0stine** [stevenlovegrove/Pangolin#303]
I stumbled upon the "Pangolin Python Command Prompt" feature and am interested in its use/application, but cannot find any examples. Anything you can point me to would be appreciated.

**Comment by stevenlovegrove** [comment]
If you press the ` character (back-tick) whilst in a Pangolin program a python console will drop down (Quake style). You can execute any python code there, and you can also access and manipulate pangolin::Vars. Tab complete should also (hopefully) work.

In the near future, there should be more python bindings which will allow you to manipulate Pangolin interactively, or have hybrid C++ / Pangolin programs.

**Comment by phil0stine** [comment]
Very cool, I look forward to playing with it some more, especially manipulating Vars dynamically.
