### ISSUE TITLE
Build failure in examples with clang-40

### ISSUE THREAD

**Issue by yurivict** [stevenlovegrove/Pangolin#307]
```
examples/SimpleDisplay/CMakeFiles/SimpleDisplay.dir/main.cpp.o: In function `main':
examples/SimpleDisplay/main.cpp:(.text+0x225): undefined reference to `pangolin::CreateWindowAndBind(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, pangolin::Params const&)'
```

I have no way to know how to use your library if your own examples fail.

**Comment by stevenlovegrove** [comment]
Pangolin builds just fine on Clang (https://travis-ci.org/stevenlovegrove/Pangolin/builds/320323444)

And you should be prepared to debug open-source software that you have not payed for.

**Comment by NikolausDemmel** [comment]
Maybe #356 is somehow related, but it looks like Pangolin should build examples and main library both with libc++.

Just for the record, Pangolin compiles fine for me with clang both on Linux and macOS, so yeah as @stevenlovegrove mentioned, you'd have to do some digging or at least provide more information about your setup. Some gratitude also often goes a long way.
