### ISSUE TITLE
OpenEXR is deprecated. Please replace it with some other dependency.

### ISSUE THREAD

**Issue by yurivict** [stevenlovegrove/Pangolin#308]
```
Extracting OpenEXR-2.2.0_8: 100%
Message from OpenEXR-2.2.0_8:

===>   NOTICE:

This port is deprecated; you may wish to reconsider installing it:
It is scheduled to be removed on or after 2017-12-31.
```

**Comment by yurivict** [comment]
I can't create the FreeBSD port because it depends on the vulnerable library.
Please make this it. dependency optional, or replace it.

**Comment by stevenlovegrove** [comment]
It is already optional. The README lists it in the "Optional Dependencies for video input" section, and here is the optional configuration line:

https://github.com/stevenlovegrove/Pangolin/blob/master/src/CMakeLists.txt#L524

Please do a little research before raising an issue. Thanks.
