### ISSUE TITLE
Pangolin X11: Indirect GLX rendering context obtained

### ISSUE THREAD

**Issue by olivertai** [stevenlovegrove/Pangolin#309]
I downloaded the lastest version of Pangolin and built successfully. But when I tried to run the example `HelloPangolin` I got a problem:
`Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.Pangolin X11: Indirect GLX rendering context obtained`
But this doesn't stop the visualization.
When I tried to use functions of Pangolin in my code I got the same problem.
Could you help me with this problem? Thanks.

**Comment by stevenlovegrove** [comment]
This warning tends to happen when running in a virtual machine, over a network, or when your display drivers are incorrectly installed. It means that Pangolin couldn't provide a framebuffer that meets the default requirements (such as double buffering and bit depth). This is generally machine configuration dependent. You can safely ignore the warning if you are happy with your performance and environment.
