### ISSUE TITLE
Mouse scrolliong in a pangolin::Panel area

### ISSUE THREAD

**Issue by bergercookie** [stevenlovegrove/Pangolin#310]
Suppose I build and launch one of the examples (e.g., SimpleDisplay). If I navigate with the mouse on top of the panel buttons and scroll, then the buttons shift with the direction of scrolling, which is generally not the way you want them to behave.

Is there any way to suppress that?

**Before scrolling**

![1](https://user-images.githubusercontent.com/5816719/33429572-4a55449c-d5c5-11e7-89a3-37dec639d251.png)

**After scrolling**

![2](https://user-images.githubusercontent.com/5816719/33429581-5272df4a-d5c5-11e7-92a6-7e24abb95579.png)

Cheers,

**Comment by stevenlovegrove** [comment]
This would require some extra logic on the scroll handler for the panel to check if the widgets overflow. It should be possible to implement but is not on my todo list. I'd accept a patch if this annoys you a lot :)
