### ISSUE TITLE
Keyboard Input : Trying to write IsShiftPressed()

### ISSUE THREAD

**Issue by JmanVtrus** [stevenlovegrove/Pangolin#312]
I see that the mouse state has a mask for whether control, shift, alt, is being pressed but I am not sure whether there is a way to tell without a mouse message? I could query the X11 functions myself but I am I don't see a way to get the X11's Display*. I was hoping on some advice on how best to hook into pangolin to implement this or expose the related X11 references to make the X11 calls.

Appreciate the info

**Comment by JmanVtrus** [comment]
Ah, so the WindowInterface returned by pangolin::CreateWindowAndBind is of type X11Window and can be cast directly thus allowing for:

    pangolin::X11Window* win = (pangolin::X11Window*)WindowInterface;
    ::Display* display = win->display->display;
    ::XQueryKeymap(win->display->display, keys);

**Comment by mateosss** [comment]
Is there any cross-platform way of doing this?
Any reason `key_modifiers` is not sent down the stack [here](https://github.com/stevenlovegrove/Pangolin/blob/e80f97436fb1ff813189c54f18667d0d7b22711d/components/pango_display/src/process.cpp#L48)?
