### ISSUE TITLE
Compilation Error, Video_Output, prototype can not be found

### ISSUE THREAD

**Issue by qiaoting159753** [stevenlovegrove/Pangolin#313]
Hello, 
I encountered an error during compilation. The error message in below: 

[ 44%] Building CXX object src/CMakeFiles/pangolin.dir/video/video_output.cpp.o
/home/p/Documents/Pangolin/src/video/video_output.cpp:93:6: error: prototype for ‘void pangolin::VideoOutput::AddStream(const AVPixelFormat&, size_t, size_t, size_t)’ does not match any in class ‘pangolin::VideoOutput’
 void VideoOutput::AddStream(const PixelFormat& pf, size_t w, size_t h, size_t pitch)
      ^
In file included from /home/p/Documents/Pangolin/src/video/video_output.cpp:29:0:
/home/p/Documents/Pangolin/include/pangolin/video/video_output.h:75:10: error: candidates are: void pangolin::VideoOutput::AddStream(const pangolin::PixelFormat&, size_t, size_t)
     void AddStream(const PixelFormat& pf, size_t w,size_t h);
          ^
/home/p/Documents/Pangolin/include/pangolin/video/video_output.h:73:10: error:                 void pangolin::VideoOutput::AddStream(const pangolin::PixelFormat&, size_t, size_t, size_t)
     void AddStream(const PixelFormat& pf, size_t w,size_t h,size_t pitch);
          ^
/home/p/Documents/Pangolin/src/video/video_output.cpp:98:6: error: prototype for ‘void pangolin::VideoOutput::AddStream(const AVPixelFormat&, size_t, size_t)’ does not match any in class ‘pangolin::VideoOutput’
 void VideoOutput::AddStream(const PixelFormat& pf, size_t w, size_t h)
      ^
In file included from /home/p/Documents/Pangolin/src/video/video_output.cpp:29:0:
/home/p/Documents/Pangolin/include/pangolin/video/video_output.h:75:10: error: candidates are: void pangolin::VideoOutput::AddStream(const pangolin::PixelFormat&, size_t, size_t)
     void AddStream(const PixelFormat& pf, size_t w,size_t h);
          ^
/home/p/Documents/Pangolin/include/pangolin/video/video_output.h:73:10: error:                 void pangolin::VideoOutput::AddStream(const pangolin::PixelFormat&, size_t, size_t, size_t)
     void AddStream(const PixelFormat& pf, size_t w,size_t h,size_t pitch);
          ^
src/CMakeFiles/pangolin.dir/build.make:1046: recipe for target 'src/CMakeFiles/pangolin.dir/video/video_output.cpp.o' failed
make[2]: *** [src/CMakeFiles/pangolin.dir/video/video_output.cpp.o] Error 1
CMakeFiles/Makefile2:135: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

The Cmake command goes smooth. Like: 

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Build type not set (defaults to release)
-DCMAKE_BUILD_TYPE=Debug for debug
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Python Found and Enabled
-- Eigen Found and Enabled
-- libdc1394 Found and Enabled
-- V4L Found and Enabled
-- Performing Test HAVE_FFMPEG_MAX_ANALYZE_DURATION2
-- Performing Test HAVE_FFMPEG_MAX_ANALYZE_DURATION2 - Success
-- Performing Test HAVE_FFMPEG_AVFORMAT_ALLOC_OUTPUT_CONTEXT2
-- Performing Test HAVE_FFMPEG_AVFORMAT_ALLOC_OUTPUT_CONTEXT2 - Success
-- Performing Test HAVE_FFMPEG_AVPIXELFORMAT
-- Performing Test HAVE_FFMPEG_AVPIXELFORMAT - Success
-- ffmpeg Found and Enabled
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- libpng Found and Enabled
-- libjpeg Found and Enabled
-- libtiff Found and Enabled
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/p/Documents/Pangolin/build

So, please any idea about how should I get it work? Thanks a lot for your help. I really appreciate your help. Thanks. 

Best Regards, 
T

**Comment by stevenlovegrove** [comment]
There is somehow some kind of a variable name conflict from FFmpeg (AVPixelFormat). That is meant to be pangolin::PixelFormat. I can't work out why that would happen, but dissabling ffmpeg in Pangolin is probably one workaround. If you find another solution, please post back!

**Comment by Andreluizfc** [comment]
How to disable `ffmpeg` inside Pangolin? I have Pretty much the same Error.

**Comment by stevenlovegrove** [comment]
@Andreluizfc Missed this, sorry!

cmake -DBUILD_PANGOLIN_FFMPEG=OFF ..
