### ISSUE TITLE
fatal error: librealsense/rs.hpp: No such file or directory

### ISSUE THREAD

**Issue by suijingfeng** [stevenlovegrove/Pangolin#319]
the log printed:
------------------------------------------------
/home/suijingfeng/catkin_ws/Pangolin/src/video/drivers/realsense.cpp:1:31: fatal error: librealsense/rs.hpp: No such file or directory
compilation terminated.
src/CMakeFiles/pangolin.dir/build.make:1814: recipe for target 'src/CMakeFiles/pangolin.dir/video/drivers/realsense.cpp.o' failed
make[2]: *** [src/CMakeFiles/pangolin.dir/video/drivers/realsense.cpp.o] Error 1
CMakeFiles/Makefile2:136: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
---------------------------------------------

**Comment by stevenlovegrove** [comment]
This was probably just fixed here https://github.com/stevenlovegrove/Pangolin/commit/30c971e46aa22dfa44fbe50439dfa62cc151b63e
