### ISSUE TITLE
Pangolin failed to work on EclipseCDT on win10(64bits)

### ISSUE THREAD

**Issue by genghe1991** [stevenlovegrove/Pangolin#320]
I am trying to using pangolin on EclipseCDT on windows environment. But there always be some errors from building and installation to trying to run some example code in eclipseCDT. 
So I am providing as many information as I could to see if anyone could help me sort things out.

My system is 64bits and I am using cmake and mingw64_x86_64-7.2.0-posix-sjlj-rt_v5-rev1 to build the source files. 
The C compiler identification is GNU 7.2.0
The CXX compiler identification is GNU 7.2.0
Glew has been installed separately and I believed it was recognized successfully during cmake configuration.
The source file I use is downloaded directly from the master branch in github.

The first error I encountered when making pangolin is as below:

> mingw32-make[5]: 
> *** No rule to make target 'D:/BuildFiles/Pangolin0110/external/zlib/lib/zlibstatic*.lib', needed by 'libpng16.dll'.  Stop.
> mingw32-make[4]: *** [CMakeFiles\Makefile2:67: CMakeFiles/png16.dir/all] Error 2
> mingw32-make[3]: *** [Makefile:140: all] Error 2
> mingw32-make[2]: *** [external\CMakeFiles\__libpng.dir\build.make:111: external/libpng/src/__libpng-stamp/__libpng-build] Error 2
> mingw32-make[1]: *** [CMakeFiles\Makefile2:158: external/CMakeFiles/__libpng.dir/all] Error 2
> mingw32-make: *** [Makefile:151: all] Error 2
> 

As it seems to be a part of extern libs so I just deselected the BUILD_EXTERN_LIBJPEG and BUILD_EXTERN_LIBPNG to avoid this problem. Still I do not know what causes this error.

The next error came up is related to 
M_PI 

> In “Pangolin-master/include/pangolin/gl/gldraw.h”.
> Errors say 'M_PI' was not declared in this scope. And also it showed that “suggested alternative: 'CMAPI'” ( it won’t work)

I had defined it manually by add 
#ifndef M_PI
    #define M_PI 3.14159265358979323846
#endif
Into the file.

There was another this kind of error and I dealt with them the same way,
including: 
 WM_MOUSEHWHEEL:
In “Pangolin-master\src\display\device\display_win.cpp:357:10”
(I used #define WM_MOUSEHWHEEL                  0x020E)

After that the building part works just fine and Pangolin could be installed.

In Eclipse, below is my settings:
In GCC C++ Complier include part:
"D:\InstallFiles\Glew\include"
"D:\InstallFiles\Pangolin_0110\include"

In Mingw C++ linker libraries part:

Libraries(-I)：
glew32
opengl32
pangolin

Library search path(-L)：
"D:\InstallFiles\Pangolin_0110\lib"
"D:\InstallFiles\Glew\lib"

And then I try to run the the helloPangolin example code

There shows a lot of undefined reference errors:

> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display.cpp.obj):display.cpp:(.text+0x1e70): undefined reference to `glReadBuffer'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display.cpp.obj):display.cpp:(.text+0x1e7f): undefined reference to `glPixelStorei'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display.cpp.obj):display.cpp:(.text+0x1edd): undefined reference to `glReadPixels'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display.cpp.obj):display.cpp:(.text+0x2bd0): undefined reference to `glTexCoordPointer'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display.cpp.obj):display.cpp:(.text+0x2c0d): undefined reference to `glDisable'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x8d6): undefined reference to `glMatrixMode'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x8fd): undefined reference to `glMatrixMode'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0xbf0): undefined reference to `glMatrixMode'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0xc1a): undefined reference to `glMatrixMode'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x129a): undefined reference to `glMatrixMode'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x129f): undefined reference to `glLoadIdentity'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x12a9): undefined reference to `glMatrixMode'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x12ae): undefined reference to `glLoadIdentity'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x1b76): undefined reference to `glTexGendv'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x1b90): undefined reference to `glTexGendv'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x1baa): undefined reference to `glTexGendv'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x1bc4): undefined reference to `glTexGendv'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x1bd9): undefined reference to `glTexGeni'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x1bee): undefined reference to `glTexGeni'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x1c03): undefined reference to `glTexGeni'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x1c18): undefined reference to `glTexGeni'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x1c38): undefined reference to `glDisable'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x1c42): undefined reference to `glDisable'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x1c4c): undefined reference to `glDisable'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text+0x1c56): undefined reference to `glDisable'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text$_ZN8pangolin12glLoadMatrixEPKd[_ZN8pangolin12glLoadMatrixEPKd]+0x11): undefined reference to `glLoadMatrixd'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(opengl_render_state.cpp.obj):opengl_render_state.cpp:(.text$_ZN8pangolin12glMultMatrixEPKd[_ZN8pangolin12glMultMatrixEPKd]+0x11): undefined reference to `glMultMatrixd'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text+0x259): undefined reference to `glGetFloatv'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text+0x26b): undefined reference to `glLineWidth'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text+0x27c): undefined reference to `glGetFloatv'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text+0x28e): undefined reference to `glPointSize'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text+0x35d): undefined reference to `glFlush'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text+0x392): undefined reference to `glLineWidth'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text+0x39e): undefined reference to `glPointSize'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text+0x1652): undefined reference to `glReadBuffer'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text+0x1688): undefined reference to `glReadPixels'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin14GlRenderBuffer12ReinitialiseEiii[_ZN8pangolin14GlRenderBuffer12ReinitialiseEiii]+0x24): undefined reference to `__imp___glewDeleteRenderbuffersEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin14GlRenderBuffer12ReinitialiseEiii[_ZN8pangolin14GlRenderBuffer12ReinitialiseEiii]+0x50): undefined reference to `__imp___glewGenRenderbuffersEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin14GlRenderBuffer12ReinitialiseEiii[_ZN8pangolin14GlRenderBuffer12ReinitialiseEiii]+0x69): undefined reference to `__imp___glewBindRenderbufferEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin14GlRenderBuffer12ReinitialiseEiii[_ZN8pangolin14GlRenderBuffer12ReinitialiseEiii]+0x81): undefined reference to `__imp___glewRenderbufferStorageEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin14GlRenderBuffer12ReinitialiseEiii[_ZN8pangolin14GlRenderBuffer12ReinitialiseEiii]+0xa2): undefined reference to `__imp___glewBindRenderbufferEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin14GlRenderBufferD1Ev[_ZN8pangolin14GlRenderBufferD1Ev]+0x61): undefined reference to `__imp___glewDeleteRenderbuffersEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin13GlFramebufferD1Ev[_ZN8pangolin13GlFramebufferD1Ev]+0x3e): undefined reference to `__imp___glewDeleteFramebuffersEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin13GlFramebufferC1ERNS_9GlTextureERNS_14GlRenderBufferE[_ZN8pangolin13GlFramebufferC1ERNS_9GlTextureERNS_14GlRenderBufferE]+0x22): undefined reference to `__imp___glewGenFramebuffersEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZNK8pangolin13GlFramebuffer4BindEv[_ZNK8pangolin13GlFramebuffer4BindEv]+0xf): undefined reference to `__imp___glewBindFramebufferEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZNK8pangolin13GlFramebuffer4BindEv[_ZNK8pangolin13GlFramebuffer4BindEv]+0x26): undefined reference to `__imp___glewDrawBuffers'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin13GlFramebuffer12ReinitialiseEv[_ZN8pangolin13GlFramebuffer12ReinitialiseEv]+0x19): undefined reference to `__imp___glewDeleteFramebuffersEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin13GlFramebuffer12ReinitialiseEv[_ZN8pangolin13GlFramebuffer12ReinitialiseEv]+0x2e): undefined reference to `__imp___glewGenFramebuffersEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZNK8pangolin13GlFramebuffer6UnbindEv[_ZNK8pangolin13GlFramebuffer6UnbindEv]+0xf): undefined reference to `__imp___glewDrawBuffers'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZNK8pangolin13GlFramebuffer6UnbindEv[_ZNK8pangolin13GlFramebuffer6UnbindEv]+0x27): undefined reference to `__imp___glewBindFramebufferEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin13GlFramebuffer12AttachColourERNS_9GlTextureE[_ZN8pangolin13GlFramebuffer12AttachColourERNS_9GlTextureE]+0x35): undefined reference to `__imp___glewBindFramebufferEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin13GlFramebuffer12AttachColourERNS_9GlTextureE[_ZN8pangolin13GlFramebuffer12AttachColourERNS_9GlTextureE]+0x4c): undefined reference to `__imp___glewFramebufferTexture2DEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin13GlFramebuffer12AttachColourERNS_9GlTextureE[_ZN8pangolin13GlFramebuffer12AttachColourERNS_9GlTextureE]+0x78): undefined reference to `__imp___glewBindFramebufferEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin13GlFramebuffer11AttachDepthERNS_14GlRenderBufferE[_ZN8pangolin13GlFramebuffer11AttachDepthERNS_14GlRenderBufferE]+0x26): undefined reference to `__imp___glewBindFramebufferEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin13GlFramebuffer11AttachDepthERNS_14GlRenderBufferE[_ZN8pangolin13GlFramebuffer11AttachDepthERNS_14GlRenderBufferE]+0x3d): undefined reference to `__imp___glewFramebufferRenderbufferEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(view.cpp.obj):view.cpp:(.text$_ZN8pangolin13GlFramebuffer11AttachDepthERNS_14GlRenderBufferE[_ZN8pangolin13GlFramebuffer11AttachDepthERNS_14GlRenderBufferE]+0x63): undefined reference to `__imp___glewBindFramebufferEXT'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0x31): undefined reference to `glViewport'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0x77): undefined reference to `glScissor'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0xb3): undefined reference to `glViewport'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0xe6): undefined reference to `glScissor'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0x100): undefined reference to `glDisable'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0x185): undefined reference to `glMatrixMode'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0x18a): undefined reference to `glLoadIdentity'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0x1fd): undefined reference to `glOrtho'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0x207): undefined reference to `glMatrixMode'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0x20c): undefined reference to `glLoadIdentity'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0x233): undefined reference to `glMatrixMode'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0x238): undefined reference to `glLoadIdentity'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0x242): undefined reference to `glMatrixMode'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(viewport.cpp.obj):viewport.cpp:(.text+0x247): undefined reference to `glLoadIdentity'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(handler.cpp.obj):handler.cpp:(.text+0xa1a): undefined reference to `glReadBuffer'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(handler.cpp.obj):handler.cpp:(.text+0xa59): undefined reference to `glReadPixels'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0x338): undefined reference to `__imp_ChoosePixelFormat'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0x395): undefined reference to `__imp_SetPixelFormat'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0x400): undefined reference to `__imp_GetPixelFormat'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0x423): undefined reference to `__imp_DescribePixelFormat'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0x58a): undefined reference to `__imp_CreatePalette'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0x5d5): undefined reference to `__imp_SelectPalette'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0x5e5): undefined reference to `__imp_RealizePalette'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0xa20): undefined reference to `__imp_GetStockObject'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0xc94): undefined reference to `__imp_wglCreateContext'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0xcc4): undefined reference to `__imp_wglMakeCurrent'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0xcf1): undefined reference to `__imp_wglMakeCurrent'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0xd08): undefined reference to `__imp_wglDeleteContext'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0xd2f): undefined reference to `__imp_DeleteObject'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0xdfb): undefined reference to `__imp_UnrealizeObject'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0xe23): undefined reference to `__imp_SelectPalette'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0xe3a): undefined reference to `__imp_RealizePalette'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0xe7e): undefined reference to `__imp_UnrealizeObject'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0xea6): undefined reference to `__imp_SelectPalette'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0xebd): undefined reference to `__imp_RealizePalette'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0x152c): undefined reference to `__imp_wglMakeCurrent'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0x15b1): undefined reference to `__imp_SwapBuffers'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(display_win.cpp.obj):display_win.cpp:(.text+0x1828): undefined reference to `__imp_glewInit'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(gldraw.cpp.obj):gldraw.cpp:(.text+0x33): undefined reference to `glPushAttrib'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(gldraw.cpp.obj):gldraw.cpp:(.text+0x3d): undefined reference to `glDisable'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(gldraw.cpp.obj):gldraw.cpp:(.text+0x47): undefined reference to `glDisable'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(gldraw.cpp.obj):gldraw.cpp:(.text+0x5c): undefined reference to `glColor3ub'
> D:\InstallFiles\Pangolin_0110\lib/libpangolin.a(gldraw.cpp.obj):gldraw.cpp:(.text+0x7b): undefined reference to `glPopAttrib'
> collect2.exe: error: ld returned 1 exit status

Another error I encountered but I think is not that important is as below: after I added #include<Gl/glew.h> to the code.

> 
> D:\InstallFiles\Pangolin_0110\include/pangolin/utils/picojson.h:498:40: error: expected ')' before 'PRId64'
>          SNPRINTF(buf, sizeof(buf), "%" PRId64, u_.int64_);
>                                         ^~~~~~
> D:\InstallFiles\Pangolin_0110\include/pangolin/utils/picojson.h:498:57: warning: spurious trailing '%' in format [-Wformat=]
>          SNPRINTF(buf, sizeof(buf), "%" PRId64, u_.int64_);

                                                         ^
D:\InstallFiles\Pangolin_0110\include/pangolin/utils/picojson.h:498:57: warning: too many arguments for format [-Wformat-extra-args]

After I comment out this part. Again it shows the whole bunch of the undefined referenced errors.

I also installed freeglut in my computer and it works well in eclipse. Therefore I believe the openGL is fine on my computer. But I am not sure if freeglut is needed for pangolin. 
And after I add #include <GL/freeglut.h> other errors show and part of them is as below.

> 
> typedef void (GLAPIENTRY * PFNGLDRAWCOMMANDSSTATESADDRESSNVPROC) (const GLuint64* indirects, const GLsizei* sizes, const GLuint* states, const GLuint* fbos, GLuint count);
>                                                                          ^~~~~~~~
>                                                                          GLuint
> D:\InstallFiles\Glew\include/Gl/glew.h:14636:53: error: typedef 'PFNGLDRAWVKIMAGENVPROC' is initialized (use decltype instead)
>  typedef void (GLAPIENTRY * PFNGLDRAWVKIMAGENVPROC) (GLuint64 vkImage, GLuint sampler, GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z, GLfloat s0, GLfloat t0, GLfloat s1, GLfloat t1);
>                                                      ^~~~~~~~
> D:\InstallFiles\Glew\include/Gl/glew.h:14636:53: error: 'GLuint64' was not declared in this scope
> D:\InstallFiles\Glew\include/Gl/glew.h:14636:53: note: suggested alternative: 'GLuint'
>  typedef void (GLAPIENTRY * PFNGLDRAWVKIMAGENVPROC) (GLuint64 vkImage, GLuint sampler, GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z, GLfloat s0, GLfloat t0, GLfloat s1, GLfloat t1);
>                                                      ^~~~~~~~
>                                                      GLuint
> D:\InstallFiles\Glew\include/Gl/glew.h:14636:78: error: expected primary-expression before 'sampler'
>  typedef void (GLAPIENTRY * PFNGLDRAWVKIMAGENVPROC) (GLuint64 vkImage, GLuint sampler, GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z, GLfloat s0, GLfloat t0, GLfloat s1, GLfloat t1);
>                                                                               ^~~~~~~
> D:\InstallFiles\Glew\include/Gl/glew.h:14636:95: error: expected primary-expression before 'x0'
>  typedef void (GLAPIENTRY * PFNGLDRAWVKIMAGENVPROC) (GLuint64 vkImage, GLuint sampler, GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z, GLfloat s0, GLfloat t0, GLfloat s1, GLfloat t1);
>                                                                                                ^~
> D:\InstallFiles\Glew\include/Gl/glew.h:14636:107: error: expected primary-expression before 'y0'
>  typedef void (GLAPIENTRY * PFNGLDRAWVKIMAGENVPROC) (GLuint64 vkImage, GLuint sampler, GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z, GLfloat s0, GLfloat t0, GLfloat s1, GLfloat t1);
>                                                                                                            ^~
> D:\InstallFiles\Glew\include/Gl/glew.h:14636:119: error: expected primary-expression before 'x1'
>  typedef void (GLAPIENTRY * PFNGLDRAWVKIMAGENVPROC) (GLuint64 vkImage, GLuint sampler, GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z, GLfloat s0, GLfloat t0, GLfloat s1, GLfloat t1);
>                                                                                                                        ^~
> D:\InstallFiles\Glew\include/Gl/glew.h:14636:131: error: expected primary-expression before 'y1'
>  typedef void (GLAPIENTRY * PFNGLDRAWVKIMAGENVPROC) (GLuint64 vkImage, GLuint sampler, GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z, GLfloat s0, GLfloat t0, GLfloat s1, GLfloat t1);
>                                                                                                                                    ^~
> D:\InstallFiles\Glew\include/Gl/glew.h:14636:143: error: expected primary-expression before 'z'
>  typedef void (GLAPIENTRY * PFNGLDRAWVKIMAGENVPROC) (GLuint64 vkImage, GLuint sampler, GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z, GLfloat s0, GLfloat t0, GLfloat s1, GLfloat t1);
>                                                                                                                                                ^
> D:\InstallFiles\Glew\include/Gl/glew.h:14636:154: error: expected primary-expression before 's0'
>  typedef void (GLAPIENTRY * PFNGLDRAWVKIMAGENVPROC) (GLuint64 vkImage, GLuint sampler, GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z, GLfloat s0, GLfloat t0, GLfloat s1, GLfloat t1);
>                                                                                                                                                           ^~
> D:\InstallFiles\Glew\include/Gl/glew.h:14636:166: error: expected primary-expression before 't0'
>  typedef void (GLAPIENTRY * PFNGLDRAWVKIMAGENVPROC) (GLuint64 vkImage, GLuint sampler, GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z, GLfloat s0, GLfloat t0, GLfloat s1, GLfloat t1);
>                                                                                                                                                                       ^~
> D:\InstallFiles\Glew\include/Gl/glew.h:14636:178: error: expected primary-expression before 's1'
>  typedef void (GLAPIENTRY * PFNGLDRAWVKIMAGENVPROC) (GLuint64 vkImage, GLuint sampler, GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z, GLfloat s0, GLfloat t0, GLfloat s1, GLfloat t1);
>                                                                                                                                                                                   ^~
> D:\InstallFiles\Glew\include/Gl/glew.h:14636:190: error: expected primary-expression before 't1'
>  typedef void (GLAPIENTRY * PFNGLDRAWVKIMAGENVPROC) (GLuint64 vkImage, GLuint sampler, GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z, GLfloat s0, GLfloat t0, GLfloat s1, GLfloat t1);
>                                                                                                                                                                                               ^~
> D:\InstallFiles\Glew\include/Gl/glew.h:14637:71: error: 'GLchar' does not name a type; did you mean 'char'?
>  typedef GLVULKANPROCNV (GLAPIENTRY * PFNGLGETVKPROCADDRNVPROC) (const GLchar* name);
>                                                                        ^~~~~~
>                                                                        char

I also download the Binaries are available for Windows x64 the hellowpangolin.exe works fine. Hope this information will help to exclude some possible reasons of all these trouble. 

I am really new to this, I could not really identify where the true problem is. 
I am not sure if there is any conflict between pangolin and freeglut. Should I use some other openGL utility tool?
Please let me know which part I did wrong or did I miss something in the Eclipse Configuration par.

Sorry for the long article, I have been working on these stuff for several days but still could not figure them out. I am just trying to providing as detailed information as I could to help solve the problem. 
Thank you for anyone could help.

**Comment by stevenlovegrove** [comment]
We can ignore eclipse, because that is just an IDE.

The problem is that Pangolin is not well tested with mingw64. I suspect a number of the windows / MSVC macros are a little conflated - many of the _WIN_ guards should probably really be _MSVC_ guards. Unfortunately I do not know of a free CI server that will build with mingw on Windows, and that isn't a platform that I use. I will accept patches for mingw if you make progress. 

On Windows, my preferred development environment is to install the free MSVC compiler and git bash (which includes msys for unix command line tools), but use QtCreator / Eclipse as an IDE. That way you can build and link native Windows static and dynamic dll's with your project.
