### ISSUE TITLE
Add GUI elements to multiple windows from different threads

### ISSUE THREAD

**Issue by d-vo** [stevenlovegrove/Pangolin#321]
I have two windows that are maintained by two separate threads. Drawing poses no issue, but adding a panel raises some problems, if the menu elements are added from two parallel threads.

Code: 
pangolin::CreatePanel("menu").SetBounds(0.0,1.0,0.0,pangolin::Attach::Pix(100));
pangolin::Var<bool> menuTest("menu.Test",true,true);

Nevertheless: Great library :)

**Comment by stevenlovegrove** [comment]
What happens exactly? One thread creates a variable which is shown in a window belonging to another thread?

If so, a workaround is to pre-instantiate the variables before creating the windows. The creation is not thread safe, but access is.
