### ISSUE TITLE
pangolin::VideoInput::Grab( wait = false ) hangs on camera disconnect

### ISSUE THREAD

**Issue by JmanVtrus** [stevenlovegrove/Pangolin#322]
Greetings All,

I am trying to allow for someone to hotplug an rgbd/depth camera at runtime, and every part is good, and my code can detect when it is unplugged, but not as fast as the Update loop is grabbing video frames from a VideoInput context. As such, this code:

```
void LocalCameraStream::Update(const vtrus::ui::AppTime &time)
{
    super::Update(time);
    std::vector<pangolin::Image<unsigned char>> imgs;
    if (VideoInput->Grab(VideoBuffer, imgs, false, false)) { }
}
```

Hangs in the call to Grab when the camera gets unplugged. I was hoping to get some advice or some better knowledge of how grab was made to handle this case or some other alternatives

The call stack shows:

> pangolin::VideoInput::Grab
> pangolin::VideoInput::GrabNext
> pangolin::OpenNi2Video::GrabNet
> oni::implemention::Context::readFrame
> oni::implementation::Context::waitForStreams
> XnLinuxPosixEvent::Wait
> pthread_cond_wait

**Comment by stevenlovegrove** [comment]
You will probably need to look at the OpenNi2Video implementation and insert some logic in there.
