### ISSUE TITLE
How can I use other 3D models by pangolin

### ISSUE THREAD

**Issue by ymd1012** [stevenlovegrove/Pangolin#325]
Just like using the code pangolin::glDrawColouredCube to draw a cube,can I use some codes to draw the model I want?
Or should I make a model in OpenGL at first?

**Comment by stevenlovegrove** [comment]
Pangolin has utilities for drawing a few things (in gldraw.h) but in general you will need to use the OpenGL API explicitly, or some other utility library.

**Comment by flyaudio** [comment]
How about 3d model used in ROS ?  like :  *.urdf/ *.xacro/ *.dae

**Comment by stevenlovegrove** [comment]
Unlike when this question was first asked, Pangolin does now have the ability to load .obj and .ply files (see https://github.com/stevenlovegrove/Pangolin/blob/master/tools/ModelViewer/main.cpp) but not Collada (dae) unfortunately. If you wanted to add it, you'd have to implement a loader for dae (see https://github.com/stevenlovegrove/Pangolin/blob/master/src/geometry/geometry_ply.cpp as a reference)
