### ISSUE TITLE
CMake Error at test/log/CMakeLists.txt:2

### ISSUE THREAD

**Issue by geoffviola** [stevenlovegrove/Pangolin#326]
I got the following error while following the instructions on a new computer

```
CMake Error at test/log/CMakeLists.txt:2 (find_package):
  By not providing "FindPangolin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Pangolin",
  but CMake did not find one.

  Could not find a package configuration file provided by "Pangolin"
  (requested version 0.4) with any of the following names:

    PangolinConfig.cmake
    pangolin-config.cmake

  Add the installation prefix of "Pangolin" to CMAKE_PREFIX_PATH or set
  "Pangolin_DIR" to a directory containing one of the above files.  If
  "Pangolin" provides a separate development package or SDK, be sure it has
  been installed.
```

It looks like when doing a fresh build and running cmake without parameters, the tests try to run `find_package(Pangolin` without the module being added to the path. A workaround would be to pass `-DBUILD_TESTS=false` to cmake.

**Comment by ahmadyan** [comment]
I have the same issue installing Pangolin on a new mac as well. 
I confirm the work-around.

**Comment by stevenlovegrove** [comment]
The Pangolin package should be exported automatically via the CMake package registry. The CMake exports can be found in ~/.cmake/packages/Pangolin/ on Linux / OSX.

I've had people comment on this problem previously when running without permission to write to that folder (from within Docker or something, for instance). Could this be the case here?

**Comment by geoffviola** [comment]
I don't think it's a permissions issue. I think I could reproduce it in a virtual environment, but that would take some effort. You won't see the issue, unless it's on a machine without Pangolin installed.

**Comment by geoffviola** [comment]
The file looks good. I didn't realize that file got generated on CMake. I wasn't able to reproduce the problem. The problem might be on my install.

Here are the steps that I tried. 
```
docker run -it ubuntu
# In container
cd /home
mkdir temp
cd temp
apt-get update
apt-get install -y git cmake build-essential mesa-common-dev libpng-dev libjpeg-dev libxxf86vm1 libxxf86vm-dev libxi-dev libxrandr-dev freeglut3-dev libglapi-mesa freeglut3-dev
git clone https://github.com/stevenlovegrove/Pangolin.git
cd Pangolin
mkdir build
cd build
cmake ..
# no errors...
```

Since those tests are never compiled, it might be prudent to delete those CMakeLists.txt.

**Comment by NikolausDemmel** [comment]
You also get this error if you do 
```
cmake .. -DEXPORT_Pangolin=Off
```

You have to explicitly 
```
cmake .. -DEXPORT_Pangolin=Off -DBUILD_TESTS=Off
```

Maybe it would be good if cmake would check `EXPORT_Pangolin` before trying to compile tests, or even better if the tests would not rely on the global config. That seems error prone if you have multiple copies of pangolin in different projects compiled at the same time, since it might pick up the wrong one.
