### ISSUE TITLE
mac os error "use of undeclared identifier 'NSWindowStyleMaskClosable'"

### ISSUE THREAD

**Issue by guiyuliu** [stevenlovegrove/Pangolin#327]
when I build it on mac os ,error occurred 
```
error: 
      use of undeclared identifier 'NSWindowStyleMaskClosable'
  ...NSClosableWindowMask backing:NSBackingStoreBuffered defer:YES];
     ^
/Users/lgy/Documents/workspace/Pangolin/src/display/device/display_osx.mm:41:39: note: 
      expanded from macro 'NSClosableWindowMask'
#  define NSClosableWindowMask        NSWindowStyleMaskClosable
                                      ^
5 errors generated.
make[2]: *** [src/CMakeFiles/pangolin.dir/display/device/display_osx.mm.o] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by stevenlovegrove** [comment]
This is probably related to this commit: https://github.com/stevenlovegrove/Pangolin/commit/7a24ac185ea4d4f808df13fe0b45e8bc1b710e43 You may want to look at that and propose modifications to work with your platform.

**Comment by lood339** [comment]
Do you solve this problem? I have a similar problem in Mac 10.10.
PangolinNSApplication.mm:57:39: error: use of undeclared identifier 'NSEventMaskAny'
                nextEventMatchingMask:NSAnyEventMask
I guess "PangolinNSApplication.mm" require some head files but I am not familiar with Mac.

**Comment by bringert** [comment]
I'm seeing the same issue building on OS X 10.11. I commented out all the #defines added in https://github.com/stevenlovegrove/Pangolin/commit/7a24ac185ea4d4f808df13fe0b45e8bc1b710e43 which got me past this problem.

I'm not sure what the right preprocessor conditions are to get around this. Looking at other projects, they seem to do the defines the other way around. See e.g. https://github.com/macvim-dev/macvim/blob/master/src/MacVim/MacVim.h#L43

**Comment by NikolausDemmel** [comment]
I just ran into this build failure on macos 10.11. See #490 for a proper fix (AFAICT).
