### ISSUE TITLE
Linker Problem (visualStudio, Win10)

### ISSUE THREAD

**Issue by gaeae** [stevenlovegrove/Pangolin#331]
Visual Studio 15 2017 (v141)
Windows 10
x64
Release and Debug

I proceeded as described in the manual. (Without any problems!)

Now added:
- include directories (/include ; /build/src/include/ and build/external/glew/include)
- library derectories (/build/src/Release/ ; build/external/glew/lib/)
- additional dependencies (pangolin.lib ; glew.lib ; glew_shared.lib)
- copied pangolin.dll and glew.dll in the solution directory

When including pangolin.h (in my Viewer.cpp file) the following error occurs: 

> 1>Viewer.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl pangolin::Handler::Keyboard(struct pangolin::View &,unsigned char,int,int,bool)" (?Keyboard@Handler@pangolin@@UEAAXAEAUView@2@EHH_N@Z)
> 1>Viewer.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl pangolin::Handler::Mouse(struct pangolin::View &,enum pangolin::MouseButton,int,int,bool,int)" (?Mouse@Handler@pangolin@@UEAAXAEAUView@2@W4MouseButton@2@HH_NH@Z)
> 1>Viewer.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl pangolin::Handler::MouseMotion(struct pangolin::View &,int,int,int)" (?MouseMotion@Handler@pangolin@@UEAAXAEAUView@2@HHH@Z)
> 1>Viewer.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl pangolin::Handler::PassiveMouseMotion(struct pangolin::View &,int,int,int)" (?PassiveMouseMotion@Handler@pangolin@@UEAAXAEAUView@2@HHH@Z)
> 1>Viewer.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl pangolin::Handler::Special(struct pangolin::View &,enum pangolin::InputSpecial,float,float,float,float,float,float,int)" (?Special@Handler@pangolin@@UEAAXAEAUView@2@W4InputSpecial@2@MMMMMMH@Z)
> 1>Viewer.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl pangolin::HandlerScroll::Mouse(struct pangolin::View &,enum pangolin::MouseButton,int,int,bool,int)" (?Mouse@HandlerScroll@pangolin@@UEAAXAEAUView@2@W4MouseButton@2@HH_NH@Z)
> 1>Viewer.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl pangolin::HandlerScroll::Special(struct pangolin::View &,enum pangolin::InputSpecial,float,float,float,float,float,float,int)" (?Special@HandlerScroll@pangolin@@UEAAXAEAUView@2@W4InputSpecial@2@MMMMMMH@Z)
> 1>\x64\Debug\test.exe : fatal error LNK1120: 7 unresolved externals

**Comment by stevenlovegrove** [comment]
Hmm, I'm not sure about that one, sorry!

**Comment by JeffyOLOLO** [comment]
Hi!
I think that you didn't connect someone library (apparently related to processing keyboard and mouse).

**Comment by Work-jk-l** [comment]
The same error in my project.

**Comment by Kamoski** [comment]
Same issue with my installation, literally same unresolved symbols. Proceeded with building steps, without any problems to that moment, and i can't do anything about it. Any suggestions?

**Comment by stevenlovegrove** [comment]
Since this is old, closing for now. Please reopen if anyone sees this on the current master branch.
