### ISSUE TITLE
How to use pangolin on android project ?

### ISSUE THREAD

**Issue by yuri4029** [stevenlovegrove/Pangolin#333]
Hi everyone, I'm on a project which must use pangolin on a project android. Now, I cannot figure out how to compile pangolin on android project  and I have some questions, please help me.
1. Where is Pangolin library on an android project - that means what is the structure of an android project with Pangolin ?
2. How to package Pangolin on an android project ? At this point, my purpose is very easy, it is only put pangolin on an empty project android and build it .
Thanks for any suggests or tutorials.

**Comment by stevenlovegrove** [comment]
Firstly, you can expect that Pangolin is probably broken on Android right now, so you probably need to make some modifications. You will need to be familiar with the Android NDK.

1) The structure of an Android Pangolin program is identical to that of a desktop Pangolin program. All of Pangolin's examples should work without modification. The only difference is that you must specify an android-make toolchain file (something like https://github.com/taka-no-me/android-cmake). You use the toolchain file to invoke CMake. 

2) After that, you can simply 'make' to cross-compile. Pangolin includes some AndroidUtils.cmake helpers which add special targets for packaging APK's and uploading to the device with ADB (make XXX-apk, make XXX-push, make XXX-run).

**Comment by tranminh1831996** [comment]
Very thank you explain. I installed Cmake, and NDK and clone pangolin, then when  I am try https://github.com/taka-no-me/android-cmake , it took this .
![taka](https://user-images.githubusercontent.com/23437453/36531549-e05e3f94-17f0-11e8-9bb6-cbfcfea0d95b.png)

**Comment by stevenlovegrove** [comment]
The message output seems to suggest you don't have the toolchain file around....

You should be prepared that getting this to work right now is probably not for the faint of heart. You may need some more persistence.

**Comment by vyi** [comment]
Hi Steve, 
Has there been any improvements (with regard to Pangolin on Android) since then?

**Comment by stevenlovegrove** [comment]
I'm afraid not - it will still require some work.

**Comment by siriusA-6597** [comment]
Hi @stevenlovegrove 

I am working on integrating pangolin with android for a project. I have followed all the instructions mentioned in this issue thread as well as mentioned [here](https://github.com/stevenlovegrove/Pangolin/issues/95). @tranminh1831996, If you were successful in using pangolin with android, can you please help me with this ?

**Details:**
cmake version: 3.18.4
OS: CentOS 7

**This is the command I am using for building the pangolin project:** 
cmake -DCMAKE_TOOLCHAIN_FILE=/home/X/Android/Sdk/ndk/21.0.6113669/build/cmake/android.toolchain.cmake -DANDROID_NDK=/home/X/Android/Sdk/ndk/21.0.6113669/ -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI="armeabi-v7a" <path to pangolin top-level dir>

**Command output:**
CMake Error at CMakeModules/AndroidUtils.cmake:216 (get_target_property):
  get_target_property() called with non-existent target "PUBLIC".
Call Stack (most recent call first):
  CMakeModules/AndroidUtils.cmake:249 (add_to_depend_libs)
  src/CMakeLists.txt:639 (target_link_libraries)

CMake Error at CMakeModules/AndroidUtils.cmake:216 (get_target_property):
  get_target_property() called with non-existent target "-lEGL".
Call Stack (most recent call first):
  CMakeModules/AndroidUtils.cmake:249 (add_to_depend_libs)
  src/CMakeLists.txt:639 (target_link_libraries)

CMake Error at CMakeModules/AndroidUtils.cmake:216 (get_target_property):
  get_target_property() called with non-existent target "-lGLESv2".
Call Stack (most recent call first):
  CMakeModules/AndroidUtils.cmake:249 (add_to_depend_libs)
  src/CMakeLists.txt:639 (target_link_libraries)

CMake Error at CMakeModules/AndroidUtils.cmake:216 (get_target_property):
  get_target_property() called with non-existent target
  "/home/X/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/16/libEGL.so".
Call Stack (most recent call first):
  CMakeModules/AndroidUtils.cmake:249 (add_to_depend_libs)
  src/CMakeLists.txt:639 (target_link_libraries)

CMake Error at CMakeModules/AndroidUtils.cmake:216 (get_target_property):
  get_target_property() called with non-existent target "android".
Call Stack (most recent call first):
  CMakeModules/AndroidUtils.cmake:249 (add_to_depend_libs)
  src/CMakeLists.txt:639 (target_link_libraries)

CMake Error at CMakeModules/AndroidUtils.cmake:216 (get_target_property):
  get_target_property() called with non-existent target "log".
Call Stack (most recent call first):
  CMakeModules/AndroidUtils.cmake:249 (add_to_depend_libs)
  src/CMakeLists.txt:639 (target_link_libraries)

CMake Error at CMakeModules/AndroidUtils.cmake:244 (_target_link_libraries):
  IMPORTED library can only be used with the INTERFACE keyword of
  target_link_libraries
Call Stack (most recent call first):
  CMakeModules/AndroidUtils.cmake:147 (target_link_libraries)
  /usr/local/share/cmake-3.18/Modules/FindDoxygen.cmake:452 (add_executable)
  /usr/local/share/cmake-3.18/Modules/FindDoxygen.cmake:610 (_Doxygen_find_doxygen)
  src/CMakeLists.txt:702 (find_package)

Can you please help me with this error log and lead me to some direction as I am unable to figure out how to resolve this issue ?? Thank you very much.

**Comment by stevenlovegrove** [comment]
Getting Pangolin to work with Android will require someone to put in some effort. Ideally we can fix it up and then get it integrated into the CI system so that it can stay maintained. Closing this now.
