### ISSUE TITLE
Static initialization inside Pangolin

### ISSUE THREAD

**Issue by HumamHelfawi** [stevenlovegrove/Pangolin#335]
Thanks for the great work!
I have a library which uses Pangolin for visualization. The library has an option to build with visualization(which mean it will link against Pangolin) or without visualization (It won't even include or link to Pangolin).

When I built it with visualization and call some functions from it even without calling anything that is related to visualization (which means nothing related to Pangolin) I got an error (malloc.c:2394: sysmalloc: Assertion). If I call the same function but without linking the library to Pangolin, nothing wrong happens!

I know this is not related exactly to Pangolin but I really get tired of debugging it without knowing the real the issues. I thought that maybe Pangolin has some static constructors somewhere that makes the heap corrupted  (may be due to wrong using of Pangolin not a problem in Pangolin it self)

So my question, does Pangolin has any static initialization of any kind?

Thank you very much for taking the time to read the long issue

P.S. I am using the last version from master branch

**Comment by stevenlovegrove** [comment]
Um, possibly. I wouldn't be surprised if I static initialize a few things in Pangolin, though they don't come to mind.

Have you tried using valgrind yet if you suspect heap corruption?

**Comment by stevenlovegrove** [comment]
Closing this issue - please reopen if you discover anything funny.
