### ISSUE TITLE
Support with GLES2

### ISSUE THREAD

**Issue by bpwiselybabu** [stevenlovegrove/Pangolin#336]
I am having trouble using GLES2 and pangolin. The glVertexPointer() gives me compilation errors. Is the project tested to work with GLES2? The function glVertexPointer() is not available in GLES2.

**Comment by stevenlovegrove** [comment]
I'm afraid that code is not well tested. GLES support was originally written for Android several years ago and may be out of date.

**Comment by bpwiselybabu** [comment]
Thank you for the reply. I do have compatibility problems. Do you have any plan to support it in the future? Or do you know anyone who is working on a fork with that plan in mind?

**Comment by stevenlovegrove** [comment]
I do not, sorry.

**Comment by bpwiselybabu** [comment]
Thank you @stevenlovegrove. This project has been very useful!
