### ISSUE TITLE
Problem compiling with Mingw

### ISSUE THREAD

**Issue by bemberst** [stevenlovegrove/Pangolin#341]
Hi

I'm trying to compile pangolin with mingw32.
I have add git to my path, and i use cmake as you recommand in issue #137 and #150 
For glew, zlib and libjpeg there is no problem.
But for libpng, i have :
[ 20%] Creating directories for '__libpng'
[ 21%] Performing download step (git clone) for '__libpng'
Cloning into '__libpng'...
Note: checking out 'v1.6.18'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at e6172809b... [libpng16] Imported from libpng-1.6.18.tar
[ 22%] No patch step for '__libpng'
[ 22%] Performing update step for '__libpng'
[ 23%] Performing configure step for '__libpng'
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found ZLIB: C:/Users/benoi/Desktop/xvisio/pangolin-git/build/external/zlib/lib/zlibstatic*.lib (found version "1.2.8")
CMake Warning (dev) at CMakeLists.txt:301 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "png16".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:317 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "png16_static".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/benoi/Desktop/xvisio/pangolin-git/build/external/libpng/src/__libpng-build
[ 24%] Performing build step for '__libpng'
Scanning dependencies of target png16
[  2%] Building C object CMakeFiles/png16.dir/png.obj
[  4%] Building C object CMakeFiles/png16.dir/pngerror.obj
[  7%] Building C object CMakeFiles/png16.dir/pngget.obj
[  9%] Building C object CMakeFiles/png16.dir/pngmem.obj
[ 11%] Building C object CMakeFiles/png16.dir/pngpread.obj
[ 14%] Building C object CMakeFiles/png16.dir/pngread.obj
[ 16%] Building C object CMakeFiles/png16.dir/pngrio.obj
[ 19%] Building C object CMakeFiles/png16.dir/pngrtran.obj
[ 21%] Building C object CMakeFiles/png16.dir/pngrutil.obj
[ 23%] Building C object CMakeFiles/png16.dir/pngset.obj
[ 26%] Building C object CMakeFiles/png16.dir/pngtrans.obj
[ 28%] Building C object CMakeFiles/png16.dir/pngwio.obj
[ 30%] Building C object CMakeFiles/png16.dir/pngwrite.obj
[ 33%] Building C object CMakeFiles/png16.dir/pngwtran.obj
[ 35%] Building C object CMakeFiles/png16.dir/pngwutil.obj
mingw32-make[5]: *** No rule to make target 'C:/Users/benoi/Desktop/xvisio/pangolin-git/build/external/zlib/lib/zlibstatic*.lib', needed by 'libpng16.dll'.  Stop.
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/png16.dir/all' failed
mingw32-make[4]: *** [CMakeFiles/png16.dir/all] Error 2
Makefile:139: recipe for target 'all' failed
mingw32-make[3]: *** [all] Error 2
external\CMakeFiles\__libpng.dir\build.make:110: recipe for target 'external/libpng/src/__libpng-stamp/__libpng-build' failed
mingw32-make[2]: *** [external/libpng/src/__libpng-stamp/__libpng-build] Error 2
CMakeFiles\Makefile2:233: recipe for target 'external/CMakeFiles/__libpng.dir/all' failed
mingw32-make[1]: *** [external/CMakeFiles/__libpng.dir/all] Error 2
Makefile:150: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

Perhaps i have bad configured the project. Any idea?

**Comment by bemberst** [comment]
Hi

I have correct the problem by changing in Pangolin\external\CMakelists.txt 
Line 84 :   
               -DZLIB_LIBRARY=${zlib_PREFIX}/lib/zlibstatic*.lib
by
               -DZLIB_LIBRARY=${zlib_PREFIX}/lib/libzlibstatic.a

**Comment by stevenlovegrove** [comment]
I'm not sure how to change this in a platform independent way. If anyone has a good idea, please let me know.

**Comment by stevenlovegrove** [comment]
We've just switched to vcpkg instead of the external_project mechanism, so this should be fixed now. Thanks!
