### ISSUE TITLE
where can I find pypangolin.so?

### ISSUE THREAD

**Issue by ElliotHYLee** [stevenlovegrove/Pangolin#343]
After the given instruction for python, pip list does not show pypangolin. How can I add it? where can I find the .so file?

**Comment by stevenlovegrove** [comment]
There should be pypangolin.so in the build folder. You have to add this to your python path. I'm not familiar with how to install it globally, but I would be happy to take a pull request to do that.

**Comment by ElliotHYLee** [comment]
Thanks for the reply. I found that the python binding works only for python3. Unfortunately, I'm not familiar with the build & installation process as well.

**Comment by stevenlovegrove** [comment]
The bindings will also work with Python 2.X, but you must ensure that the version that Pangolin finds matches the version you intend to use.
