### ISSUE TITLE
Captured mouse event

### ISSUE THREAD

**Issue by qiuyuanWang** [stevenlovegrove/Pangolin#345]
Hi,
  In my code, I tried to capture mouse event, such as left-click, right-click, but I did not find any code or document about it. I found I can use pangolin::RegisterkeyPressCallBack function to cope with keyboard press event. Is pangolin supported to cope with mouse events?

**Comment by duyilong** [comment]
@qiuyuanWang Hello, did u find any new clues?

**Comment by qiuyuanWang** [comment]
No, it is still a problem

**Comment by stevenlovegrove** [comment]
Take a look at pangolin::Handler and Handler3D (handler/handler.h). You can derive your own subclasses of Handler and use them for custom manipulation.

**Comment by qiuyuanWang** [comment]
@stevenlovegrove thanks!!!It really works!!
I derive my own subclasses and overwrite the function. Here is my code:

namespace pangolin {
struct MyHandler3D : Handler3D {
  MyHandler3D(OpenGlRenderState &cam_state,
              AxisDirection enforce_up = AxisNone,
              float trans_scale = 0.01f,
              float zoom_fraction = PANGO_DFLT_HANDLER3D_ZF)
      : Handler3D(cam_state, enforce_up, trans_scale, zoom_fraction) {};
  void Mouse(View &display,
             MouseButton button,
             int x,
             int y,
             bool pressed,
             int button_state) {

      ...... here implement the function captured mouse event.

  }
};
}

**Comment by turinglife** [comment]
My runnable implementation:

struct CustomHandler3D : public pangolin::Handler3D {
    CustomHandler3D(pangolin::OpenGlRenderState& cam_state, pangolin::AxisDirection enforce_up=pangolin::AxisNone, float trans_scale=0.01f, float zoom_fraction=PANGO_DFLT_HANDLER3D_ZF) : 
        pangolin::Handler3D(cam_state, enforce_up, trans_scale, zoom_fraction){};
    void Mouse(pangolin::View& view, pangolin::MouseButton button, int x, int y, bool pressed, int button_state) {
        if( (view.views[0]->show) && (view.views[0])->vp.Contains(x, y) && button == pangolin::MouseButton::MouseButtonLeft) {
            std::cout<<"mouse left click once"<<std::endl;
            std::cout<<"button_state = "<<button_state<<std::endl;
        }
    };
};
