### ISSUE TITLE
max/min macros and functions conflict when compile on Win 10, VS 17

### ISSUE THREAD

**Issue by JeffyOLOLO** [stevenlovegrove/Pangolin#352]
When i tried compile project was conflict beetwen macro `std::max(a,b)`/`std::min(a,b)` and functions `std::numeric_limits<T>::max()`/`std::numeric_limits<T>::min()`.
To get rid of the error you must add code below in **include/pangolin/image/image.h** after all include:

    #ifdef max
    #undef max
    #endif

    #ifdef min
    #undef min
    #endif

Don't know how lib will be work with images after that, but examples HelloPangolin, SimpleDisplayImage and SimplePlot run normal.

**Comment by stevenlovegrove** [comment]
std::max/min are not macros - they are namespaced functions that do not conflict with numeric_limits.

This is not a Pangolin problem, but a problem with the win api windef.h pollution with global macro names. You should be careful whenever including windef.h (via windows.h for example).

The Windows API offers a workaround for this particular issue - you can #define NOMINMAX before including windows.h (or similar) to exclude the definition of these nuisance macros.
