### ISSUE TITLE
extra brace in external/CMakeLists.txt

### ISSUE THREAD

**Issue by joebedard** [stevenlovegrove/Pangolin#353]
It's on line 23:
```
IMPORTED_LOCATION_DEBUG   ${CMAKE_INSTALL_PREFIX}}/lib/glewd.lib
```
Do you see it? ;-)

It's causing some build errors, so you might want to fix it.

**Comment by weizhsgg** [comment]
@joebedard  Thank you for your help and nice answer. I encountered this error too.

**Comment by stevenlovegrove** [comment]
Thanks!
