### ISSUE TITLE
 No known video handler for URI 'convert'

### ISSUE THREAD

**Issue by SowmyaN9** [stevenlovegrove/Pangolin#354]
Hi Steven,
I get the below message when I execute the example code simple Record :
terminate called after throwing an instance of 'pangolin::VideoExceptionNoKnownHandler'
  what():  No known video handler for URI 'convert'
Aborted (core dumped)
I'm currently on ubuntu 14.04,using the webcam logitech c170.
./SimpleRecord convert:[fmt=RGB24]//v4l:///dev/video0  /home/output/out.avi ;  is the cmd I used
Executing the cmd v4l2-ctl --list-devices gives  : 
   Webcam C170 (usb-0000:00:1a.0-1.2):
	  /dev/video0
Can you please provide some insight to resolve this error?

**Comment by stevenlovegrove** [comment]
The convert:// filter requires the optional ffmpeg libraries to be installed (see the readme)

**Comment by SowmyaN9** [comment]
@Steven: Thank you for your reply. Installation of  libavdevice-dev and libavfilter-dev packages are required which are not mentioned in the readme I suppose.
when I execute the same again : ./SimpleRecord convert:[fmt=RGB24]//v4l:///dev/video0 file:///home/output/out.avi  I get an exception what(): No known video handler for URI 'file'
Aborted (core dumped)
Is this again a ffmpeg dependency issue?

**Comment by stevenlovegrove** [comment]
Try 
./VideoViewer convert:[fmt=RGB24]//v4l:///dev/video0 

without any other arguments first to see if that works.

**Comment by SowmyaN9** [comment]
Yes, this works!! even just ./SimpleRecord works and I can play recorded video as well. But this cmd ./SimpleRecord convert:[fmt=RGB24]//v4l:///dev/video0 file:///home/output throws an exception

**Comment by SowmyaN9** [comment]
Thank you Steven!
