### ISSUE TITLE
Using Pangolin in cmake project with custom Eigen version

### ISSUE THREAD

**Issue by NikolausDemmel** [stevenlovegrove/Pangolin#355]
I would like to use Pangolin in another cmake project, including its source tree as a git submodule. However, I am no cmake expert, and thus I'm asking for advice, experience, best-practices.

One simple way would be to just compile Pangolin beforehand, letting cmake's package registry in `~/.cmake/packages/...` ensure that a subsequent `find_package(Pangolin)` call in my projects cmake source finds the location. But as hinted in https://github.com/stevenlovegrove/Pangolin/issues/326#issuecomment-392140263, I've had trouble before with this approach, where cmake would pick up the "wrong" pangolin build tree, for example if I have multiple projects coming with Pangolin, or when I have different builds for debug / release / etc.

I think ideally I would want to include Pangolins sources directly in my project with `add_subdirectory` to directly depend on it's targets and get best build-parallelization. I guess this would also be best if sometimes I need to tweak and change Pangolin's source. However, it seems this would require a lot of fiddling with Pangolin's cmake. As it is, if I do this, Pangolin's top-level cmake creates conflicting targets like `uninstall` or `doc`. I guess it is simply not designed to be used that way. Is anyone successfully using Pangolin with `add_subdirectory`?

An alternative that is probably a bit more robust to the specifics of Pangolins cmake might be cmake's `ExternalProject`. One would need to ensure that all the needed parameters are passed to the cmake sub-process, also making sure pangolin does not export itself to the package registry. When using pangolin the parent project's cmake, one could either do `find_package`, specifying the exact location where it should search for the external-project to ensure it does not find another Pangolin build / install tree. It seems like pangolin itself uses external projects slightly differently in https://github.com/stevenlovegrove/Pangolin/blob/master/external/CMakeLists.txt (although that seems to be specific to windows in that instance). But I guess a similar thing could be done, creating custom targets and setting `Pangolin_INCLUDE_DIRS` and `Pangolin_LIBRARIES` appropriately. Does anyone have an example of using Pangolin in that way?

I'd appreciate thoughts on what is the best approach and/or pointers to examples.

**Comment by stevenlovegrove** [comment]
Pangolin is designed to support this use case, though I haven't tried it recently. You can see an example in this project: https://github.com/arpg/CoreDev

If there are issues (like duplicate target names), I'm happy to help you resolve them - i.e. by renaming docs to pangodocs or similar

**Comment by stevenlovegrove** [comment]
Notice the line:
set(Pangolin_DIR ${Pangolin_BINARY_DIR}/src)

**Comment by NikolausDemmel** [comment]
Thanks for the pointers, I'll have to give it a try.

**Comment by NikolausDemmel** [comment]
I finally got around to trying this. Thanks @stevenlovegrove  for pointing me the the usage in `CoreDev`. I needed a few tweaks in Pangolin to make it work, but now it works nicely.

Here is how I include Pangolin (it's in a `thirdparty` subfolder, hence the `PARENT_SCOPE`). Later, where needed, I simply do `find_package(Pangolin)`. I haven't checked what happens when installing and if that requires any additional changes.

```cmake
# Pangolin
# TODO: check first if we should use external pangolin
# TODO: check what happens on install...
message(STATUS "Configuring Pangolin...")
set(EXPORT_Pangolin OFF CACHE BOOL "")
set(BUILD_EXAMPLES OFF CACHE BOOL "")
set(BUILD_TESTS OFF CACHE BOOL "")
set(BUILD_PYPANGOLIN_MODULE OFF CACHE BOOL "")
mark_as_advanced(EXPORT_Pangolin)
mark_as_advanced(BUILD_EXAMPLES)
mark_as_advanced(BUILD_TESTS)
mark_as_advanced(BUILD_PYPANGOLIN_MODULE)
add_subdirectory(Pangolin)
set(Pangolin_DIR ${Pangolin_BINARY_DIR}/src PARENT_SCOPE)
message(STATUS "Pangolin_BINARY_DIR: ${Pangolin_BINARY_DIR}")
message(STATUS "... Pangolin configuration done.")
```

The following diff shows the changes I needed in Pangolin. Notice the two renamed targets `uninstall` and `doc` which are present in the parent repository. Otherwise I get errors like:

```
CMake Error at CMakeLists.txt:667 (add_custom_target):
  add_custom_target cannot create target "uninstall" because another target
  with the same name already exists.  The existing target is a custom target
  created in source directory
  "/Users/demmeln/work/slam/dba/openMVG/src/third_party/Pangolin".  See
  documentation for policy CMP0002 for more details.
```

For the C++11 flags I'm not 100% if that change is strictly needed, but that is what the parent project uses and it seems to work. Finally, there is a workaround needed since the parent project has an internal version of `Eigen`. It is picked up correctly, but later I get errors like:

```
CMake Error in third_party/Pangolin/src/CMakeLists.txt:
  Target "pangolin" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/Users/demmeln/work/slam/dba/openMVG/src/third_party/eigen"

  which is prefixed in the source directory.
```

Probably the cmake logic could be refined such that it does not depend on the parent project's variable. Maybe it should check if the found Eigen version is in the source directory or not.

Let me know if there are any changes you'd like to include upstream, then I can make a PR. Otherwise, IMHO we can close this issue.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 32a2d78..6004687 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -48,7 +48,14 @@ else()
 endif()
 
 if(NOT MSVC)
-    set( CMAKE_CXX_FLAGS "-std=c++0x -Wall -Wextra ${CMAKE_CXX_FLAGS}" )
+    set( CMAKE_CXX_FLAGS "-Wall -Wextra ${CMAKE_CXX_FLAGS}" )
+    if(${CMAKE_VERSION} VERSION_LESS "3.2.0")
+        set( CMAKE_CXX_FLAGS "-std=c++11 ${CMAKE_CXX_FLAGS}" )
+    else()
+        set(CMAKE_CXX_STANDARD 11)
+        set(CMAKE_CXX_STANDARD_REQUIRED ON)
+        set(CMAKE_CXX_EXTENSIONS OFF)
+    endif()
 endif()
 
 if(ANDROID)
@@ -84,7 +91,7 @@ configure_file(
   	IMMEDIATE @ONLY
 )
 
-add_custom_target(uninstall
+add_custom_target(uninstall_pangolin
   "${CMAKE_COMMAND}" -P "${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake")
 
 add_subdirectory("external")
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 1c38632..3b54e24 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -286,7 +286,8 @@ if(BUILD_PANGOLIN_EIGEN)
   find_package(Eigen QUIET)
   if(EIGEN_FOUND)
     set(HAVE_EIGEN 1)
-    list(APPEND USER_INC  ${EIGEN_INCLUDE_DIR} )
+    # FIXME: conflicts with internal pangolin from parent project
+    #list(APPEND USER_INC  ${EIGEN_INCLUDE_DIR} )
     if(_CLANG_)
       # Eigen causes many of these errors. Suppress.
       set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated-register")
@@ -575,6 +576,18 @@ target_include_directories(${LIBRARY_NAME} PUBLIC $<BUILD_INTERFACE:${PROJECT_SO
                                                   $<INSTALL_INTERFACE:${INSTALL_INCLUDE_DIR}>)
 target_link_libraries(${LIBRARY_NAME} PUBLIC ${LINK_LIBS})
 
+# Hack for openMVG internal eigen
+if (DEFINED OpenMVG_USE_INTERNAL_EIGEN)
+  target_include_directories(${LIBRARY_NAME} PUBLIC
+    $<BUILD_INTERFACE:${EIGEN_INCLUDE_DIRS}>
+    $<INSTALL_INTERFACE:${CMAKE_INSTALL_PREFIX}/include/openMVG/third_party/eigen/>)
+else()
+  target_include_directories(${LIBRARY_NAME} SYSTEM PUBLIC
+    $<BUILD_INTERFACE:${EIGEN_INCLUDE_DIRS}>
+    $<INSTALL_INTERFACE:${EIGEN_INCLUDE_DIRS}>)
+endif()
+
+
 ## Generate symbol export helper header on MSVC
 IF(MSVC)
     string(TOUPPER ${LIBRARY_NAME} LIBRARY_NAME_CAPS)
@@ -635,12 +648,12 @@ if(BUILD_PYPANGOLIN_MODULE AND HAVE_PYTHON )
 endif()
 
 #######################################################
-## Generate Doxygen documentation target (make doc)
+## Generate Doxygen documentation target (make doc_pangolin)
 find_package(Doxygen)
 if(DOXYGEN_FOUND)
     configure_file(${CMAKE_CURRENT_SOURCE_DIR}/Doxyfile.in ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile @ONLY)
     file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/../doc )
-    add_custom_target(doc
+    add_custom_target(doc_pangolin
         ${DOXYGEN_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile
         WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/../doc
         COMMENT "Generating API documentation with Doxygen" VERBATIM
```

**Comment by stevenlovegrove** [comment]
Cool - if you're able to get rid of the OpenMVG hack and Eigen issue, I'm happy to upstream this.

**Comment by powderluv** [comment]
PR is here https://github.com/stevenlovegrove/Pangolin/pull/419 with just the necessary changes

**Comment by stevenlovegrove** [comment]
It looks like I can close this now, probably? Please reopen if this is still an issue.
