### ISSUE TITLE
Compiling with clang on Linux, libc++ vs libstdc++

### ISSUE THREAD

**Issue by NikolausDemmel** [stevenlovegrove/Pangolin#356]
When I compile Pangolin on Linux with clang, it compiles with `libc++`: https://github.com/stevenlovegrove/Pangolin/blob/4335035057dc26f98b1a498b9b4843015fc9e5c5/CMakeLists.txt#L53

This causes issue when later using it in another project which is compiled with the default `libstdc++`. You get errors like:

```
undefined reference to `pangolin::CreateWindowAndBind(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, pangolin::Params const&)'
```

If that particular line in the `CMakeLists.txt` is removed, clang defaults to `libstdc++` on Linux and everything works fine.

Do you remember why that line is there? It looks like it has been for 5 or more years. Maybe back then things were different, but I believe that clang defaults to the native STL implementation on each platform, i.e. to `libstdc++` on Linux and `libc++` on macOS. So maybe that line can be removed?

**Comment by stevenlovegrove** [comment]
Seems to be unnecessary for me on OSX now. I've removed it in 99fa6fb740f41476764be37bc11da4de478078aa and a user can always override it if necessary.

**Comment by stevenlovegrove** [comment]
I might have to revert that change - I'm having some issue getting clang on Linux to work on my CI server (https://travis-ci.org/stevenlovegrove/Pangolin/jobs/386984827)
