### ISSUE TITLE
Pangolin Make error.....ubuntu 16.04

### ISSUE THREAD

**Issue by sharwanram** [stevenlovegrove/Pangolin#359]
/ORB_SLAM2/Pangolin/build$ make
Scanning dependencies of target pangolin
[  1%] Building CXX object src/CMakeFiles/pangolin.dir/utils/file_extension.cpp.o
[  2%] Building CXX object src/CMakeFiles/pangolin.dir/utils/timer.cpp.o
[  3%] Building CXX object src/CMakeFiles/pangolin.dir/utils/sigstate.cpp.o
[  4%] Building CXX object src/CMakeFiles/pangolin.dir/utils/file_utils.cpp.o
[  5%] Building CXX object src/CMakeFiles/pangolin.dir/utils/threadedfilebuf.cpp.o
[  6%] Building CXX object src/CMakeFiles/pangolin.dir/utils/uri.cpp.o
[  7%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_zstd.cpp.o
[  8%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_raw.cpp.o
[  9%] Building CXX object src/CMakeFiles/pangolin.dir/image/pixel_format.cpp.o
[ 10%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_pango.cpp.o
[ 11%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_exr.cpp.o
[ 12%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_png.cpp.o
[ 13%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_jpg.cpp.o
[ 14%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_tga.cpp.o
[ 15%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_ppm.cpp.o
[ 16%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io.cpp.o
[ 17%] Building CXX object src/CMakeFiles/pangolin.dir/log/packet.cpp.o
[ 18%] Building CXX object src/CMakeFiles/pangolin.dir/log/packetstream_reader.cpp.o
[ 19%] Building CXX object src/CMakeFiles/pangolin.dir/log/packetstream.cpp.o
[ 20%] Building CXX object src/CMakeFiles/pangolin.dir/log/playback_session.cpp.o
[ 21%] Building CXX object src/CMakeFiles/pangolin.dir/log/packetstream_writer.cpp.o
[ 22%] Building CXX object src/CMakeFiles/pangolin.dir/gl/gltexturecache.cpp.o
In file included from /home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.h:248:0,
                 from /home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gltexturecache.h:30,
                 from /home/gpslab/ORB_SLAM2/Pangolin/src/gl/gltexturecache.cpp:28:
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In member function 'void pangolin::GlTexture::CopyFrom(const pangolin::GlTexture&)':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:298:40: error: 'glCopyImageSubData' was not declared in this scope
                        width, height, 1);
                                        ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In member function 'void pangolin::GlRenderBuffer::Reinitialise(GLint, GLint, GLint)':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:464:42: error: 'glDeleteRenderbuffersEXT' was not declared in this scope
         glDeleteRenderbuffersEXT(1, &rbid);
                                          ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:469:35: error: 'glGenRenderbuffersEXT' was not declared in this scope
     glGenRenderbuffersEXT(1, &rbid);
                                   ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:470:52: error: 'glBindRenderbufferEXT' was not declared in this scope
     glBindRenderbufferEXT(GL_RENDERBUFFER_EXT, rbid);
                                                    ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:471:81: error: 'glRenderbufferStorageEXT' was not declared in this scope
  glRenderbufferStorageEXT(GL_RENDERBUFFER_EXT, internal_format, width, height);
                                                                              ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In destructor 'pangolin::GlRenderBuffer::~GlRenderBuffer()':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:479:42: error: 'glDeleteRenderbuffersEXT' was not declared in this scope
         glDeleteRenderbuffersEXT(1, &rbid);
                                          ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In destructor 'pangolin::GlFramebuffer::~GlFramebuffer()':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:528:41: error: 'glDeleteFramebuffersEXT' was not declared in this scope
         glDeleteFramebuffersEXT(1, &fbid);
                                         ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In constructor 'pangolin::GlFramebuffer::GlFramebuffer(pangolin::GlTexture&, pangolin::GlRenderBuffer&)':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:535:34: error: 'glGenFramebuffersEXT' was not declared in this scope
     glGenFramebuffersEXT(1, &fbid);
                                  ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In constructor 'pangolin::GlFramebuffer::GlFramebuffer(pangolin::GlTexture&, pangolin::GlTexture&, pangolin::GlRenderBuffer&)':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:544:34: error: 'glGenFramebuffersEXT' was not declared in this scope
     glGenFramebuffersEXT(1, &fbid);
                                  ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In member function 'void pangolin::GlFramebuffer::Bind() const':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:553:50: error: 'glBindFramebufferEXT' was not declared in this scope
     glBindFramebufferEXT(GL_FRAMEBUFFER_EXT, fbid);
                                                  ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:555:52: error: 'glDrawBuffers' was not declared in this scope
     glDrawBuffers( attachments, attachment_buffers );
                                                    ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In member function 'void pangolin::GlFramebuffer::Reinitialise()':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:562:41: error: 'glDeleteFramebuffersEXT' was not declared in this scope
         glDeleteFramebuffersEXT(1, &fbid);
                                         ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:564:34: error: 'glGenFramebuffersEXT' was not declared in this scope
     glGenFramebuffersEXT(1, &fbid);
                                  ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In member function 'void pangolin::GlFramebuffer::Unbind() const':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:570:42: error: 'glDrawBuffers' was not declared in this scope
     glDrawBuffers( 1, attachment_buffers );
                                          ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:572:47: error: 'glBindFramebufferEXT' was not declared in this scope
     glBindFramebufferEXT(GL_FRAMEBUFFER_EXT, 0);
                                               ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In member function 'GLenum pangolin::GlFramebuffer::AttachColour(pangolin::GlTexture&)':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:580:50: error: 'glBindFramebufferEXT' was not declared in this scope
     glBindFramebufferEXT(GL_FRAMEBUFFER_EXT, fbid);
                                                  ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:581:94: error: 'glFramebufferTexture2DEXT' was not declared in this scope
 rTexture2DEXT(GL_FRAMEBUFFER_EXT, color_attachment, GL_TEXTURE_2D, tex.tid, 0);
                                                                              ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In member function 'void pangolin::GlFramebuffer::AttachDepth(pangolin::GlRenderBuffer&)':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:592:50: error: 'glBindFramebufferEXT' was not declared in this scope
     glBindFramebufferEXT(GL_FRAMEBUFFER_EXT, fbid);
                                                  ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:594:107: error: 'glFramebufferRenderbufferEXT' was not declared in this scope
 EXT(GL_FRAMEBUFFER_EXT, GL_DEPTH_ATTACHMENT_EXT, GL_RENDERBUFFER_EXT, rb.rbid);
                                                                              ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In member function 'void pangolin::GlBuffer::Reinitialise(pangolin::GlBufferType, GLuint, GLenum, GLuint, GLenum)':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:652:28: error: 'glGenBuffers' was not declared in this scope
         glGenBuffers(1, &bo);
                            ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:656:97: error: 'glBufferData' was not declared in this scope
 ffer_type, num_elements*GlDataTypeBytes(datatype)*count_per_element, 0, gluse);
                                                                              ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In member function 'void pangolin::GlBuffer::Resize(GLuint)':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:674:69: error: 'glGetBufferSubData' was not declared in this scope
         glGetBufferSubData(buffer_type, 0, backup_size_bytes, backup);
                                                                     ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:675:105: error: 'glBufferData' was not declared in this scope
 _type, new_num_elements*GlDataTypeBytes(datatype)*count_per_element, 0, gluse);
                                                                              ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:676:66: error: 'glBufferSubData' was not declared in this scope
         glBufferSubData(buffer_type, 0, backup_size_bytes, backup);
                                                                  ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In destructor 'pangolin::GlBuffer::~GlBuffer()':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:691:31: error: 'glDeleteBuffers' was not declared in this scope
         glDeleteBuffers(1, &bo);
                               ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In member function 'void pangolin::GlBuffer::Bind() const':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:697:33: error: 'glBindBuffer' was not declared in this scope
     glBindBuffer(buffer_type, bo);
                                 ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In member function 'void pangolin::GlBuffer::Unbind() const':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:702:32: error: 'glBindBuffer' was not declared in this scope
     glBindBuffer(buffer_type, 0);
                                ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In member function 'void pangolin::GlBuffer::Upload(const GLvoid*, GLsizeiptr, GLintptr)':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:708:56: error: 'glBufferSubData' was not declared in this scope
     glBufferSubData(buffer_type,offset,size_bytes, data);
                                                        ^
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp: In member function 'void pangolin::GlBuffer::Download(GLvoid*, GLsizeiptr, GLintptr) const':
/home/gpslab/ORB_SLAM2/Pangolin/include/pangolin/gl/gl.hpp:715:61: error: 'glGetBufferSubData' was not declared in this scope
     glGetBufferSubData(buffer_type, offset, size_bytes, data);
                                                             ^
src/CMakeFiles/pangolin.dir/build.make:566: recipe for target 'src/CMakeFiles/pangolin.dir/gl/gltexturecache.cpp.o' failed
make[2]: *** [src/CMakeFiles/pangolin.dir/gl/gltexturecache.cpp.o] Error 1
CMakeFiles/Makefile2:135: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by NikolausDemmel** [comment]
Just posting an error message w/o further comment is probably not very useful. You should include more information, like: What OS and version is this? Does latest Pangolin master compile?

Also, best wrap the pasted output in tripple quotes ` ``` ` to format as code block.

**Comment by sharwanram** [comment]
I am using ubuntu 16.04.....i dont have idea it is latest or not .....
i used 
git clone https://github.com/stevenlovegrove/Pangolin.git

**Comment by NikolausDemmel** [comment]
Have you installed glew?

**Comment by NikolausDemmel** [comment]
I can reproduce this when OpenGL but not glew is installed, at least on Ubuntu 16.04.

Solution: Install glew like it says in the Readme: `sudo apt-get install libglew-dev`.

@stevenlovegrove: It would probably be good if cmake would check for this. So maybe either https://github.com/stevenlovegrove/Pangolin/blob/4335035057dc26f98b1a498b9b4843015fc9e5c5/src/CMakeLists.txt#L160 would need to not be quiet, or `HAVE_GLEW=0` needs to be handled properly.

**Comment by sharwanram** [comment]
thanks Sir It works now ....but i got some warnings

**Comment by sharwanram** [comment]
Scanning dependencies of target pangolin
[  1%] Building CXX object src/CMakeFiles/pangolin.dir/utils/file_extension.cpp.o
[  2%] Building CXX object src/CMakeFiles/pangolin.dir/utils/timer.cpp.o
[  3%] Building CXX object src/CMakeFiles/pangolin.dir/utils/sigstate.cpp.o
[  4%] Building CXX object src/CMakeFiles/pangolin.dir/utils/file_utils.cpp.o
[  5%] Building CXX object src/CMakeFiles/pangolin.dir/utils/threadedfilebuf.cpp.o
[  6%] Building CXX object src/CMakeFiles/pangolin.dir/utils/uri.cpp.o
[  7%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_zstd.cpp.o
[  8%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_raw.cpp.o
[  9%] Building CXX object src/CMakeFiles/pangolin.dir/image/pixel_format.cpp.o
[ 10%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_pango.cpp.o
[ 11%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_exr.cpp.o
[ 12%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_png.cpp.o
[ 13%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_jpg.cpp.o
[ 14%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_tga.cpp.o
[ 15%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_ppm.cpp.o
[ 16%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io.cpp.o
[ 17%] Building CXX object src/CMakeFiles/pangolin.dir/log/packet.cpp.o
[ 18%] Building CXX object src/CMakeFiles/pangolin.dir/log/packetstream_reader.cpp.o
[ 19%] Building CXX object src/CMakeFiles/pangolin.dir/log/packetstream.cpp.o
[ 20%] Building CXX object src/CMakeFiles/pangolin.dir/log/playback_session.cpp.o
[ 21%] Building CXX object src/CMakeFiles/pangolin.dir/log/packetstream_writer.cpp.o
[ 22%] Building CXX object src/CMakeFiles/pangolin.dir/gl/gltexturecache.cpp.o
[ 23%] Building CXX object src/CMakeFiles/pangolin.dir/gl/gldraw.cpp.o
[ 23%] Building CXX object src/CMakeFiles/pangolin.dir/gl/glpangoglu.cpp.o
[ 24%] Building CXX object src/CMakeFiles/pangolin.dir/gl/glchar.cpp.o
[ 25%] Building CXX object src/CMakeFiles/pangolin.dir/gl/glfont.cpp.o
In file included from /home/gpslab/ORB_SLAM2/Pangolin/src/gl/glfont.cpp:30:0:
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:2495:15: warning: 'int stbtt_BakeFontBitmap(const unsigned char*, int, float, unsigned char*, int, int, int, int, stbtt_bakedchar*)' defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_BakeFontBitmap(const unsigned char *data, int offset,  // f
               ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:2540:16: warning: 'void stbtt_GetBakedQuad(stbtt_bakedchar*, int, int, int, float*, float*, stbtt_aligned_quad*, int)' defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_GetBakedQuad(stbtt_bakedchar *chardata, int pw, int ph, in
                ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:2643:15: warning: 'int stbtt_PackBegin(stbtt_pack_context*, unsigned char*, int, int, int, int, void*)' defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_PackBegin(stbtt_pack_context *spc, unsigned char *pixels, i
               ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:2674:16: warning: 'void stbtt_PackEnd(stbtt_pack_context*)' defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_PackEnd  (stbtt_pack_context *spc)
                ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:2978:15: warning: 'int stbtt_PackFontRange(stbtt_pack_context*, unsigned char*, int, float, int, int, stbtt_packedchar*)' defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_PackFontRange(stbtt_pack_context *spc, unsigned char *fontd
               ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:2680:16: warning: 'void stbtt_PackSetOversampling(stbtt_pack_context*, unsigned int, unsigned int)' defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_PackSetOversampling(stbtt_pack_context *spc, unsigned int 
                ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:2990:16: warning: 'void stbtt_GetPackedQuad(stbtt_packedchar*, int, int, int, float*, float*, stbtt_aligned_quad*, int)' defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_GetPackedQuad(stbtt_packedchar *chardata, int pw, int ph, 
                ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:1510:16: warning: 'void stbtt_GetFontVMetrics(const stbtt_fontinfo*, int*, int*, int*)' defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_GetFontVMetrics(const stbtt_fontinfo *info, int *ascent, i
                ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:1517:16: warning: 'void stbtt_GetFontBoundingBox(const stbtt_fontinfo*, int*, int*, int*, int*)' defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_GetFontBoundingBox(const stbtt_fontinfo *info, int *x0, in
                ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:1505:16: warning: 'void stbtt_GetCodepointHMetrics(const stbtt_fontinfo*, int, int*, int*)' defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_GetCodepointHMetrics(const stbtt_fontinfo *info, int codep
                ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:1200:15: warning: 'int stbtt_GetCodepointBox(const stbtt_fontinfo*, int, int*, int*, int*, int*)' defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_GetCodepointBox(const stbtt_fontinfo *info, int codepoint, 
               ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:1205:15: warning: 'int stbtt_IsGlyphEmpty(const stbtt_fontinfo*, int)' defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_IsGlyphEmpty(const stbtt_fontinfo *info, int glyph_index)
               ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:1156:15: warning: 'int stbtt_GetCodepointShape(const stbtt_fontinfo*, int, stbtt_vertex**)' defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_GetCodepointShape(const stbtt_fontinfo *info, int unicode_c
               ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:1537:16: warning: 'void stbtt_FreeShape(const stbtt_fontinfo*, stbtt_vertex*)' defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_FreeShape(const stbtt_fontinfo *info, stbtt_vertex *v)
                ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:2398:16: warning: 'void stbtt_FreeBitmap(unsigned char*, void*)' defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_FreeBitmap(unsigned char *bitmap, void *userdata)
                ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:2479:26: warning: 'unsigned char* stbtt_GetCodepointBitmap(const stbtt_fontinfo*, float, float, int, int*, int*, int*, int*)' defined but not used [-Wunused-function]
 STBTT_DEF unsigned char *stbtt_GetCodepointBitmap(const stbtt_fontinfo *info, f
                          ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:2484:16: warning: 'void stbtt_MakeCodepointBitmap(const stbtt_fontinfo*, unsigned char*, int, int, int, float, float, int)' defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_MakeCodepointBitmap(const stbtt_fontinfo *info, unsigned c
                ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:1575:16: warning: 'void stbtt_GetCodepointBitmapBox(const stbtt_fontinfo*, int, float, float, int*, int*, int*, int*)' defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_GetCodepointBitmapBox(const stbtt_fontinfo *font, int code
                ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:2440:26: warning: 'unsigned char* stbtt_GetGlyphBitmap(const stbtt_fontinfo*, float, float, int, int*, int*, int*, int*)' defined but not used [-Wunused-function]
 STBTT_DEF unsigned char *stbtt_GetGlyphBitmap(const stbtt_fontinfo *info, float
                          ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:3167:15: warning: 'int stbtt_FindMatchingFont(const unsigned char*, const char*, stbtt_int32)' defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_FindMatchingFont(const unsigned char *font_collection, cons
               ^
/home/gpslab/ORB_SLAM2/Pangolin/src/gl/stb_truetype.h:3070:23: warning: 'const char* stbtt_GetFontNameString(const stbtt_fontinfo*, int*, int, int, int, int)' defined but not used [-Wunused-function]
 STBTT_DEF const char *stbtt_GetFontNameString(const stbtt_fontinfo *font, int *
                       ^
[ 26%] Building CXX object src/CMakeFiles/pangolin.dir/gl/gltext.cpp.o
[ 27%] Building CXX object src/CMakeFiles/pangolin.dir/display/viewport.cpp.o
[ 28%] Building CXX object src/CMakeFiles/pangolin.dir/display/window_factory.cpp.o
[ 29%] Building CXX object src/CMakeFiles/pangolin.dir/display/display.cpp.o
[ 30%] Building CXX object src/CMakeFiles/pangolin.dir/display/opengl_render_state.cpp.o
[ 31%] Building CXX object src/CMakeFiles/pangolin.dir/display/image_view.cpp.o
[ 32%] Building CXX object src/CMakeFiles/pangolin.dir/display/view.cpp.o
[ 33%] Building CXX object src/CMakeFiles/pangolin.dir/handler/handler.cpp.o
[ 34%] Building CXX object src/CMakeFiles/pangolin.dir/handler/handler_image.cpp.o
[ 35%] Building CXX object src/CMakeFiles/pangolin.dir/handler/handler_glbuffer.cpp.o
[ 36%] Building CXX object src/CMakeFiles/pangolin.dir/plot/datalog.cpp.o
[ 37%] Building CXX object src/CMakeFiles/pangolin.dir/plot/plotter.cpp.o
[ 38%] Building CXX object src/CMakeFiles/pangolin.dir/var/input_record_repeat.cpp.o
[ 39%] Building CXX object src/CMakeFiles/pangolin.dir/var/vars.cpp.o
[ 40%] Building CXX object src/CMakeFiles/pangolin.dir/display/widgets/widgets.cpp.o
[ 41%] Building CXX object src/CMakeFiles/pangolin.dir/video/video_input.cpp.o
[ 42%] Building CXX object src/CMakeFiles/pangolin.dir/video/video.cpp.o
[ 43%] Building CXX object src/CMakeFiles/pangolin.dir/video/stream_encoder_factory.cpp.o
[ 44%] Building CXX object src/CMakeFiles/pangolin.dir/video/video_interface_factory.cpp.o
[ 45%] Building CXX object src/CMakeFiles/pangolin.dir/video/video_output_interface_factory.cpp.o
[ 46%] Building CXX object src/CMakeFiles/pangolin.dir/video/video_output.cpp.o
[ 47%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/test.cpp.o
[ 48%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/images.cpp.o
[ 49%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/images_out.cpp.o
[ 50%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/split.cpp.o
[ 51%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/pvn.cpp.o
[ 52%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/pango.cpp.o
[ 53%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/pango_video_output.cpp.o
[ 54%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/debayer.cpp.o
[ 55%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/shift.cpp.o
[ 56%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/mirror.cpp.o
[ 57%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/unpack.cpp.o
[ 58%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/join.cpp.o
[ 59%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/merge.cpp.o
[ 60%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/json.cpp.o
[ 61%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/thread.cpp.o
[ 62%] Building CXX object src/CMakeFiles/pangolin.dir/tools/video_viewer.cpp.o
[ 63%] Building CXX object src/CMakeFiles/pangolin.dir/display/device/display_wayland.cpp.o
[ 64%] Building CXX object src/CMakeFiles/pangolin.dir/display/device/display_x11.cpp.o
[ 65%] Building CXX object src/CMakeFiles/pangolin.dir/utils/posix/semaphore.cpp.o
[ 66%] Building CXX object src/CMakeFiles/pangolin.dir/utils/posix/shared_memory_buffer.cpp.o
[ 67%] Building CXX object src/CMakeFiles/pangolin.dir/utils/posix/condition_variable.cpp.o
[ 68%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/firewire.cpp.o
[ 69%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/deinterlace.cpp.o
[ 70%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/v4l.cpp.o
[ 71%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/openni.cpp.o
[ 72%] Building CXX object src/CMakeFiles/pangolin.dir/fonts.cpp.o
[ 73%] Linking CXX shared library libpangolin.so
[ 73%] Built target pangolin
Scanning dependencies of target HelloPangolin
[ 73%] Building CXX object examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/main.cpp.o
[ 74%] Linking CXX executable HelloPangolin
[ 74%] Built target HelloPangolin
Scanning dependencies of target SimpleMultiDisplay
[ 75%] Building CXX object examples/SimpleMultiDisplay/CMakeFiles/SimpleMultiDisplay.dir/main.cpp.o
[ 76%] Linking CXX executable SimpleMultiDisplay
[ 76%] Built target SimpleMultiDisplay
Scanning dependencies of target SimpleDisplayImage
[ 77%] Building CXX object examples/SimpleDisplayImage/CMakeFiles/SimpleDisplayImage.dir/main.cpp.o
[ 78%] Linking CXX executable SimpleDisplayImage
[ 78%] Built target SimpleDisplayImage
Scanning dependencies of target SimpleScene
[ 79%] Building CXX object examples/SimpleScene/CMakeFiles/SimpleScene.dir/main.cpp.o
[ 80%] Linking CXX executable SimpleScene
[ 80%] Built target SimpleScene
Scanning dependencies of target SimplePlot
[ 81%] Building CXX object examples/SimplePlot/CMakeFiles/SimplePlot.dir/main.cpp.o
[ 82%] Linking CXX executable SimplePlot
[ 82%] Built target SimplePlot
Scanning dependencies of target SimpleDisplay
[ 83%] Building CXX object examples/SimpleDisplay/CMakeFiles/SimpleDisplay.dir/main.cpp.o
[ 84%] Linking CXX executable SimpleDisplay
[ 84%] Built target SimpleDisplay
Scanning dependencies of target SimpleVideo
[ 85%] Building CXX object examples/SimpleVideo/CMakeFiles/SimpleVideo.dir/main.cpp.o
[ 86%] Linking CXX executable SimpleVideo
[ 86%] Built target SimpleVideo
Scanning dependencies of target SimpleRecord
[ 87%] Building CXX object examples/SimpleRecord/CMakeFiles/SimpleRecord.dir/main.cpp.o
[ 88%] Linking CXX executable SimpleRecord
[ 88%] Built target SimpleRecord
Scanning dependencies of target SharedMemoryCamera
[ 89%] Building CXX object examples/SharedMemoryCamera/CMakeFiles/SharedMemoryCamera.dir/main.cpp.o
[ 90%] Linking CXX executable SharedMemoryCamera
[ 90%] Built target SharedMemoryCamera
Scanning dependencies of target VideoViewer
[ 91%] Building CXX object tools/VideoViewer/CMakeFiles/VideoViewer.dir/main.cpp.o
[ 92%] Linking CXX executable VideoViewer
[ 92%] Built target VideoViewer
Scanning dependencies of target VideoConvert
[ 93%] Building CXX object tools/VideoConvert/CMakeFiles/VideoConvert.dir/main.cpp.o
[ 94%] Linking CXX executable VideoConvert
[ 94%] Built target VideoConvert
Scanning dependencies of target VideoJsonTransform
[ 95%] Building CXX object tools/VideoJson/CMakeFiles/VideoJsonTransform.dir/main-transform.cpp.o
[ 96%] Linking CXX executable VideoJsonTransform
[ 96%] Built target VideoJsonTransform
Scanning dependencies of target VideoJsonPrint
[ 97%] Building CXX object tools/VideoJson/CMakeFiles/VideoJsonPrint.dir/main-print.cpp.o
[ 98%] Linking CXX executable VideoJsonPrint
[ 98%] Built target VideoJsonPrint
Scanning dependencies of target Plotter
[ 99%] Building CXX object tools/Plotter/CMakeFiles/Plotter.dir/main.cpp.o
[100%] Linking CXX executable Plotter
[100%] Built target Plotter

**Comment by NikolausDemmel** [comment]
I think you can ignore those.

@stevenlovegrove, is warning-free build an objective with Pangolin?

**Comment by sharwanram** [comment]
ok sir

**Comment by stevenlovegrove** [comment]
My bad - I recently made GLEW optional when merging some wayland stuff but I've made it required again here b133e3ad86825b9dd6dae50ad603517d76c9cda2 (And yes, warning free is an aim - the static STB thing is a recent lapse that I'm about to look at).
