### ISSUE TITLE
comment out pointers

### ISSUE THREAD

**Issue by rpfly3** [stevenlovegrove/Pangolin#363]
@stevenlovegrove Thanks for the excellent code. Here is a issue I found for the latest code.
`
//static void pointer_handle_frame(void */*data*/, struct wl_pointer */*wl_pointer*/) { }

//static void pointer_handle_axis_source(void */*data*/, struct wl_pointer */*wl_pointer*/, uint32_t /*axis_source*/) { }

//static void pointer_handle_axis_stop(void */*data*/, struct wl_pointer */*wl_pointer*/, uint32_t /*time*/, uint32_t /*axis*/) { }

//static void pointer_handle_axis_discrete(void */*data*/, struct wl_pointer */*wl_pointer*/, uint32_t /*axis*/, int32_t /*discrete*/) { }

static const struct wl_pointer_listener pointer_listener = {
    pointer_handle_enter,
    pointer_handle_leave,
    pointer_handle_motion,
    pointer_handle_button,
    pointer_handle_axis,
#if WAYLAND_VERSION_GE(1,12)
    pointer_handle_frame,
    pointer_handle_axis_source,
    pointer_handle_axis_stop,
    pointer_handle_axis_discrete,
#endif
};
`

Why leave pointers like handle_frame etc there? There are some compile problems.

**Comment by kzampog** [comment]
This is the same as https://github.com/stevenlovegrove/Pangolin/issues/364.
