### ISSUE TITLE
Problem when making on ubuntu 16.04

### ISSUE THREAD

**Issue by Cheren15** [stevenlovegrove/Pangolin#364]
I have came across the problem when I making as follow:

src/CMakeFiles/pangolin.dir/build.make:1574: recipe for target 'src/CMakeFiles/pangolin.dir/display/device/display_wayland.cpp.o' failed
make[2]: *** [src/CMakeFiles/pangolin.dir/display/device/display_wayland.cpp.o] Error 1
CMakeFiles/Makefile2:136: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

And I have installed the Glew and tried altered the PYTHON thing in ccmake, it would not work for me. 
So I directly turn off the pangolin GUI in ccmake and bypass this module to build, I was wondered if this will affect future using and is there any better way to solve the problem??

**Comment by kzampog** [comment]
I am also unable to build `display_wayland.cpp` on Mint 18.3:

```
/home/kzampog/Coding/Libraries/Pangolin/src/display/device/display_wayland.cpp:600:5: error: ‘pointer_handle_frame’ was not declared in this scope
     pointer_handle_frame,
     ^
/home/kzampog/Coding/Libraries/Pangolin/src/display/device/display_wayland.cpp:601:5: error: ‘pointer_handle_axis_source’ was not declared in this scope
     pointer_handle_axis_source,
     ^
/home/kzampog/Coding/Libraries/Pangolin/src/display/device/display_wayland.cpp:602:5: error: ‘pointer_handle_axis_stop’ was not declared in this scope
     pointer_handle_axis_stop,
     ^
/home/kzampog/Coding/Libraries/Pangolin/src/display/device/display_wayland.cpp:603:5: error: ‘pointer_handle_axis_discrete’ was not declared in this scope
     pointer_handle_axis_discrete,
     ^
```

**Comment by zxp771** [comment]
Hi @kzampog
I got the same problem.
I also  modified the display_wayland.cpp as d7b6942 
but it still not work.
Do you have any other method?

**Comment by kzampog** [comment]
I just uncommented lines  585-591 of `display_wayland.cpp` and it compiled fine on my Mint 18.3!

**Comment by PeterQFR** [comment]
you can use commit f499c390b282 on master branch works. Seems some recent changes broke it.

**Comment by zxp771** [comment]
Hi @kzampog 
I uncommented those lines like this:
![2018-06-05 13-49-49](https://user-images.githubusercontent.com/35118859/40993448-ac3a4366-68c7-11e8-978c-898ef9841093.png)

but there still have the same problem.
[ 58%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/merge.cpp.o
[ 59%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/json.cpp.o
[ 60%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/thread.cpp.o
[ 61%] Building CXX object src/CMakeFiles/pangolin.dir/tools/video_viewer.cpp.o
[ 62%] Building CXX object src/CMakeFiles/pangolin.dir/display/device/display_wayland.cpp.o
/home/aero/Pangolin/src/display/device/display_wayland.cpp:600:5: error: ‘pointer_handle_frame’ was not declared in this scope
     pointer_handle_frame,
     ^
/home/aero/Pangolin/src/display/device/display_wayland.cpp:601:5: error: ‘pointer_handle_axis_source’ was not declared in this scope
     pointer_handle_axis_source,
     ^
/home/aero/Pangolin/src/display/device/display_wayland.cpp:602:5: error: ‘pointer_handle_axis_stop’ was not declared in this scope
     pointer_handle_axis_stop,
     ^
/home/aero/Pangolin/src/display/device/display_wayland.cpp:603:5: error: ‘pointer_handle_axis_discrete’ was not declared in this scope
     pointer_handle_axis_discrete,
     ^
src/CMakeFiles/pangolin.dir/build.make:1574: recipe for target 'src/CMakeFiles/pangolin.dir/display/device/display_wayland.cpp.o' failed
make[2]: *** [src/CMakeFiles/pangolin.dir/display/device/display_wayland.cpp.o] Error 1
CMakeFiles/Makefile2:136: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zxp771** [comment]
Hi @PeterQFR 
Thanks for your help.
I saw those code but it may not meet with my problem.
anyway thanks for your share.

**Comment by zxp771** [comment]
Hi@kzampog 
I uncommended the
//#if WAYLAND_VERSION_GE(1,12)
//    pointer_handle_frame,
//    pointer_handle_axis_source,
//    pointer_handle_axis_stop,
//    pointer_handle_axis_discrete,
//#endif
it'll occur some warning like this:
/home/aero/Pangolin/src/display/device/display_wayland.cpp:605:1: warning: missing initializer for member ‘wl_pointer_listener::frame’ [-Wmissing-field-initializers]
 };
 ^
/home/aero/Pangolin/src/display/device/display_wayland.cpp:605:1: warning: missing initializer for member ‘wl_pointer_listener::axis_source’ [-Wmissing-field-initializers]
/home/aero/Pangolin/src/display/device/display_wayland.cpp:605:1: warning: missing initializer for member ‘wl_pointer_listener::axis_stop’ [-Wmissing-field-initializers]
/home/aero/Pangolin/src/display/device/display_wayland.cpp:605:1: warning: missing initializer for member ‘wl_pointer_listener::axis_discrete’ [-Wmissing-field-initializers]

but it compiled fine finally.
Do those warnings impact the usability of Pangolin?

**Comment by kzampog** [comment]
@zxp771 I just _removed_ the comments from lines 585-591 in the latest commit, so they now look like:
```
static void pointer_handle_frame(void */*data*/, struct wl_pointer */*wl_pointer*/) { }

static void pointer_handle_axis_source(void */*data*/, struct wl_pointer */*wl_pointer*/, uint32_t /*axis_source*/) { }

static void pointer_handle_axis_stop(void */*data*/, struct wl_pointer */*wl_pointer*/, uint32_t /*time*/, uint32_t /*axis*/) { }

static void pointer_handle_axis_discrete(void */*data*/, struct wl_pointer */*wl_pointer*/, uint32_t /*axis*/, int32_t /*discrete*/) { }
```
I did not have to make any other changes (I'm running Linux Mint 18.3). I am getting warnings, but it builds successfully. You could temporarily either use this fix or just revert to the previous commit @PeterQFR suggested.

Interestingly, there are no errors in the first place on the travis setup for one of my projects that uses Pangolin (I guess due to older wayland version in their 14.04 image). In any case, I believe this will be fixed soon! :)

**Comment by zxp771** [comment]
Hi@kzampog 
Thanks for your help.
For now the Pangolin works.

**Comment by christian-rauch** [comment]
Removing the function definitions (or commenting them) is clearly an error since they are used by the `pointer_listener`. PR https://github.com/stevenlovegrove/Pangolin/pull/366 reverts this and only defines the functions if they are supported and used.

**Comment by stevenlovegrove** [comment]
I've merged Christian's fix. Sorry all!
