### ISSUE TITLE
libavdevice-dev required for FFMPEG but not listed

### ISSUE THREAD

**Issue by jhthompson** [stevenlovegrove/Pangolin#365]
Regarding the changes to the find FFMPEG CMake file in https://github.com/stevenlovegrove/Pangolin/commit/4335035057dc26f98b1a498b9b4843015fc9e5c5 

The libavdevice-dev package is required for FFMPEG but not listed on the README.md

Listed:

    (deb) sudo apt-get install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libswscale-dev

Should be:

    (deb) sudo apt-get install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libswscale-dev libavdevice-dev

**Comment by stevenlovegrove** [comment]
Thanks!
