### ISSUE TITLE
Last commit b656418f70f9c8882ca7bc7ab507ca817f8475cb breaks build

### ISSUE THREAD

**Issue by Karafare** [stevenlovegrove/Pangolin#371]
The changes in src/video/drivers/pango_video_output.cpp and include/pangolin/utils/memstreambuf.h seem to break the build due to issues with the initialization of encoded_stream_data in line 207 of pango_video_output.cpp. Reverting the last commit allows building the project.

System:
- Ubuntu 14.04 (3.13.0-151-generic x86_64)
- gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu8~14.04.2) 
- built with C++11

Error message: [builderror.txt](https://github.com/stevenlovegrove/Pangolin/files/2118399/builderror.txt)

**Comment by Karafare** [comment]
Thank you for the hint to the solution. I somehow stupidly didn't associate this error with the other one.
@NikolausDemmel As a newer compiler fixes this issue I wouldn't support the older one indefinitely but gracefully phase out the support announcing a fixed date for the incompatibility and updating the readme accordingly.

**Comment by NikolausDemmel** [comment]
Trusty goes EOL April 2019, so that would be the latest I guess...

**Comment by stevenlovegrove** [comment]
Should be fixed in https://github.com/stevenlovegrove/Pangolin/commit/cdeb97c03824cdefeaa617800c033c0c03ee5902
