### ISSUE TITLE
window-less offscreen rendering

### ISSUE THREAD

**Issue by christian-rauch** [stevenlovegrove/Pangolin#374]
Is it possible to use Pangolin without a window, i.e. for pure offscreen rendering?

I am doing  off-screen rendering using `pangolin::GlFramebuffer` and a `glViewport` to render an image that might be larger than the screen size. I can than access the pixel values via `glReadPixels`. To setup pangolin, you need to call `CreateWindowAndBind` even if you do not draw into this window.

I guess that since the X11 window is using GLX, there is no way around rendering without a window. I have seen that via EGL, it's possible to render without an X-server at all: https://devblogs.nvidia.com/egl-eye-opengl-visualization-without-x-server/. Would using EGL for X11 help in this situation? Could EGL also be used in place of WGL (Windows) and CGL (Mac OS X)?

**Comment by stevenlovegrove** [comment]
Pangolin does not currently support that, but yes, implementing an EGL context is probably the best way to go. With the new Window factory, I think it would be good to offer it as a window URI, too.

**Comment by christian-rauch** [comment]
This is now implemented in https://github.com/stevenlovegrove/Pangolin/commit/a69487917cca852cd90c883cb94795f92316bc7a.
