### ISSUE TITLE
Reading 3D coordinates in camera frame via GetCamCoordinates

### ISSUE THREAD

**Issue by christian-rauch** [stevenlovegrove/Pangolin#375]
I am trying to read the 3D coordinates of pixels using `GetCamCoordinates`:
```C++
// configure camera
pangolin::OpenGlRenderState robot_cam;
robot_cam.SetProjectionMatrix(pangolin::ProjectionMatrixRDF_TopLeft(
            w, h, fu, fv, cx, cy, z_near, z_far));

// configure display
pangolin::View &robot_display = pangolin::Display("robot view")
    .SetHandler(new pangolin::Handler3D(robot_cam));
robot_display.SetAspect(w/double(h));

// read depth in OpenGL units
cv::Mat_<float> depth_gl(h, w);
glReadPixels(0, 0, w, h, GL_DEPTH_COMPONENT, GL_FLOAT, depth_gl.data);

// obtain coordinates in world units
cv::Mat_<cv::Vec3d> points(h, w);
// for x,y
robot_display.GetCamCoordinates(robot_cam, x, y, depth_gl(y,x), points(y,x)[0], points(y,x)[1], points(y,x)[2]);
```

The z values appear correct (`points(y,x)[2]`, 3rd channel of `points`) but the x and y coordinates appear skewed as if a wrong focal length is used.

However, I am getting the correct x and y coordinates using the depth from `points(y,x)[2]` and manually computing:
```C++
// for x,y
points(y,x)[0] = (x - cx) * points(y,x)[2] / fu;
points(y,x)[0] = (y - cy) * points(y,x)[2] / fv;
```

How do I have to use `GetCamCoordinates` to get the correct coordinates?

**Comment by stevenlovegrove** [comment]
It depends a little on how you've set things up, but robot_display isn't guaranteed to be w*h real pixels - it will be drawn scaled to fit the window. Perhaps you have a different window size and you're seeing a focal length difference since GetCamCoordinates is using the actual size of the viewport, not w*h?

If that isn't your issue, then you might like to compare to Handler3D::GetPosNormal() (which I can say with confidence works :)

**Comment by christian-rauch** [comment]
You are right, `GetCamCoordinates()` is using the viewport of `robot_display` and not the one that I defined with `glViewport(0,0,w,h);` (forgot to mention this in the code listing).

Using `glUnProject` directly:
```C++
static const double Identity4d[] = {1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1};
const GLint viewport[4] = {0,0,w,h};
pangolin::glUnProject(x, y, double(depth_gl(y,x)),
    Identity4d, robot_cam.GetProjectionMatrix().m, viewport,
    &points(y,x)[0], &points(y,x)[1], &points(y,x)[2]);
```
gives me the correct point cloud.
