### ISSUE TITLE
How to change the text inside a button

### ISSUE THREAD

**Issue by jb892** [stevenlovegrove/Pangolin#377]
Hi there, I was wondering how to change the text of a button. 
For example:
```
// init a button.
pangolin::Var<bool> a_button("ui.Start", false, false);
...
while(!pangolin::ShouldQuit())
{
...
    if (pangolin::Pushed(a_button))
        a_button.Meta().full_name = "ui.Stop"; // Change text here
...
}
...
```
However, this piece of code doesn't work. Could anybody help me to make this work? Many thanks!

**Comment by stevenlovegrove** [comment]
This had been fixed for buttons for a while, but remained for checkboxes which I've also now just fixed. Thanks for reporting.
