### ISSUE TITLE
How to add a text overlay on a sub-Display. 

### ISSUE THREAD

**Issue by jb892** [stevenlovegrove/Pangolin#378]
Hi there, anybody know how to add a text overlay on a sub-display?
For example:
![screenshot from 2018-06-25 11-33-11](https://user-images.githubusercontent.com/5748897/41829343-c11b91cc-786c-11e8-9ebe-cb5a3af648b8.png)

**Comment by stevenlovegrove** [comment]
You can do something like the following untested code (you may need to play around a little):

```
pangolin::View& view = ...
pangolin::GlFont::I().Text("Hello").DrawWindow(view.v.x, view.v.y)
```

where `view` is the sub-display you want to add the text to.
