### ISSUE TITLE
 Pangolin not working on the new macOS Mojave?

### ISSUE THREAD

**Issue by ymao1993** [stevenlovegrove/Pangolin#379]

**Comment by stevenlovegrove** [comment]
I've not tried it - how does it fail? Can you give the full build output?

**Comment by powderluv** [comment]
I noticed the issue on an earlier tag on Pangolin (before the Windows regression) where you hit a Sig11. I tried top of master and all the samples work fine.

**Comment by powderluv** [comment]
also now that OpenGL is deprecated in 10.14 what do we do going forward on OSX ? Pangolin on Metal ?

**Comment by stevenlovegrove** [comment]
Good question - I'm open to suggestions. Anyone know of any opensource, OpenGL on Metal wrappers?

**Comment by powderluv** [comment]
Probably port to Vulcan and use  https://github.com/KhronosGroup/MoltenVK ? MoltenGL however is not opensource.
