### ISSUE TITLE
ZSTD error

### ISSUE THREAD

**Issue by AlexWan1027** [stevenlovegrove/Pangolin#385]
Building the project, the error "ZSTD_decompressStream’ was not declared in this scope" occur, why? How to solve this problem?

**Comment by AlexWan1027** [comment]
Oh I see.

**Comment by stevenlovegrove** [comment]
Did you discover your problem?

**Comment by heiwang1997** [comment]
I had the same problem and fixed it in Ubuntu 16.04 with:
`sudo apt install libzstd1-dev`
