### ISSUE TITLE
Pangolin X11: Unable to retrieve framebuffer options

### ISSUE THREAD

**Issue by christian-rauch** [stevenlovegrove/Pangolin#388]
I am also getting the `Pangolin X11: Unable to retrieve framebuffer options` when calling `pangolin::CreateWindowAndBind("lala", 10, 10);`. In contrast to https://github.com/stevenlovegrove/Pangolin/issues/242 and https://github.com/stevenlovegrove/Pangolin/issues/260, I am running natively under Linux X11.

However, this error only occurs when creating the window inside a class (let's say class A) method. It does not appear when creating the window in the class A constructor but I get errors when calling pangolin methods in class A methods.

Are there limitations how pangolin can be used in different threads?

The documentation of [glXChooseFBConfig](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glXChooseFBConfig.xml) mentiones:
`NULL is returned if an undefined GLX attribute is encountered in attrib_list, if screen is invalid, or if dpy does not support the GLX extension.`

Is there a way to test which attributes in `attrib_list` are unsupported and which GLX extension is unsupported? Any ideas why these settings might change in between the two cases mentioned earlier?

**Comment by christian-rauch** [comment]
I started to replace GLX by EGL for the X11 window: https://github.com/stevenlovegrove/Pangolin/pull/389 (https://github.com/christian-rauch/Pangolin/tree/x11_egl). This circumvents the problem with GLX frame buffers.

**Comment by christian-rauch** [comment]
The error I get when calling pangolin functions from the class A method seem to be related to the `context`.

When looking at the pointers of the window and context via:
```C++
std::cout << "win: " << pangolin::GetBoundWindow() << std::endl;
std::cout << "ctx: " << pangolin::GetCurrentContext() << std::endl;
std::cout << "find ctx: " << pangolin::FindContext(window_name) << std::endl;
```
I get the same addresses when called in the class A constructor after `CreateWindowAndBind()`:
```
win: 0x7fae37996070
ctx: 0x7fae37996070
find ctx: 0x7fae37996070
```
But when called in the class A method, I get:
```
win: 0
ctx: 0
find ctx: 0x7fae37996070
```
which suggests that I need to set the current context to the stored context. Is this because of the original context going out of scope after the constructor?

Setting the current context in the class A method via:
```C++
pangolin::BindToContext(window_name);
```
blocks, and doing it via:
```C++
pangolin::FindContext(window_name)->MakeCurrent();
```
gives me `EGL_BAD_ACCESS (0x3002)` at `eglMakeCurrent` (generated if context is current to some other thread).

How do I properly switch the context in the class A method?
Since I only create a single window why is this actually needed?

**Comment by stevenlovegrove** [comment]
Three years late to this, sorry! I'm not sure I understand the issue - this looks more like a threading issue than which method the call originates, is that right? Perhaps this is a precursor issue to when you added the threading example?

**Comment by christian-rauch** [comment]
Uhh, this is too long ago :-) I have no idea if this could have been caused by threading. This issue probably disappeared with the threading / context sharing implementation in #398.

In any case, I have not encountered this issue since then. So I am just going to close this for now.
