### ISSUE TITLE
Pangolin:: WindowExceptionNoKnownHandler

### ISSUE THREAD

**Issue by chaiein** [stevenlovegrove/Pangolin#390]
When I execute the ORB_SLAM2 that uses Pangolin, program breaks with the following results

terminate called after throwing an instance of 'pangolin::WindowExceptionNoKnownHandler'
  what():  No known window handler for URI 'linux'
Aborted (core dumped)

How to solve this issue. The same ORB_SLAM2 is working with Pangolin previous builds. Please update the build to the old version or solve the problem in the current build or how can I solve the above issue?

**Comment by stevenlovegrove** [comment]
Recent Pangolin builds support multiple windowing API's (Wayland and X11 on Linux). For some reason, your build does not appear to have either. To debug this, you should check this bit of code (https://github.com/stevenlovegrove/Pangolin/blob/master/src/CMakeLists.txt#L223) to see which api is getting detected and configure time, and this bit of code (https://github.com/stevenlovegrove/Pangolin/blob/master/src/display/device/display_x11.cpp#L521) to see why X11 isn't getting registered before your program starts.

**Comment by kuangjies** [comment]
Same problem. Have you solved it already?

**Comment by chaiein** [comment]
No, I haven't solved yet.



Thanking you

Chaitra G.N
Ph.D. student
VR LAB
Kyungpook National University
Daegu, South Korea
Mob: +82-10-2417-7577
website: vr.knu.ac.kr

**Comment by kuangjies** [comment]
Hi, I solved it today by putting Pangolin folder under Home directory. It was previously put in catkin_ws/src folder. I don't know why but the problem is solved. 

> No, I haven't solved yet.
> 
> 
> 
> Thanking you
