### ISSUE TITLE
Check if attached variable changed

### ISSUE THREAD

**Issue by NikolausDemmel** [stevenlovegrove/Pangolin#397]
I'm creating a checkbox with

```
pangolin::Var<bool>::Attach("ui.foo", bar, true);
```

Is there a simple way to check if the value changed since the last iteration of the event loop? For now I'm resorting to having two separate values and comparing... Works but is a bit tedious compared to the usual ease-of-use of Pangolin.

**Comment by NikolausDemmel** [comment]
Ah, I wasn't aware that you can create Var objects for existing variables to access them. 

I'm not sure why `Attach` does return the variable reference rather than the `Var` object, but I guess the API has to remain as is and you can easily do this in two lines as well.

```
pangolin::Var<bool>::Attach("ui.foo", bar, true);
pangolin::Var<bool> barGui("ui.foo");
```

That should work for me, thanks for the quick help!

**Comment by NikolausDemmel** [comment]
Just wanted to confirm that this works well. Thanks.

**Comment by ahundt** [comment]
This seems to have changed, where now an exception is thrown if the variable already exists? https://github.com/stevenlovegrove/Pangolin/issues/537
