### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by arturpol94** [stevenlovegrove/Pangolin#399]
Hi,

After I try to build the package I get this error:

/usr/bin/ld: warning: libopencv_core.so.2.4, needed by //usr/lib/x86_64-linux-gnu/libavfilter-ffmpeg.so.5, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_imgproc.so.2.4, needed by //usr/lib/x86_64-linux-gnu/libavfilter-ffmpeg.so.5, not found (try using -rpath or -rpath-link)
//usr/lib/x86_64-linux-gnu/libavfilter-ffmpeg.so.5: undefined reference to `cvSmooth'
//usr/lib/x86_64-linux-gnu/libavfilter-ffmpeg.so.5: undefined reference to `cvErode'
//usr/lib/x86_64-linux-gnu/libavfilter-ffmpeg.so.5: undefined reference to `cvReleaseStructuringElement'
//usr/lib/x86_64-linux-gnu/libavfilter-ffmpeg.so.5: undefined reference to `cvCreateStructuringElementEx'
//usr/lib/x86_64-linux-gnu/libavfilter-ffmpeg.so.5: undefined reference to `cvCreateImageHeader'
//usr/lib/x86_64-linux-gnu/libavfilter-ffmpeg.so.5: undefined reference to `cvDilate'
collect2: error: ld returned 1 exit status
examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/build.make:113: recipe for target 'examples/HelloPangolin/HelloPangolin' failed
make[2]: *** [examples/HelloPangolin/HelloPangolin] Error 1
CMakeFiles/Makefile2:268: recipe for target 'examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/all' failed
make[1]: *** [examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

I have opencv 3.2.0 but I think it should work as ORB_SLAM was tested on opencv 3.2 so I assume Pangoling too.

Does anyone know the solution for that?

Cheers

Artur

**Comment by stevenlovegrove** [comment]
Pangolin does not link OpenCV, so I do not know why you would encounter these errors. It looks as though you have a strange version of libav which needs OpenCV? Unless you require that Pangolin can read video through ffmpeg, the easiest solution may be to disable ffmpeg support in pangolin by setting the lib directories to empty using cmake-gui.

**Comment by LongruiDong** [comment]
i have met the same problem,do you know how to fix that problem now?

**Comment by JorgeQuintero** [comment]
Hello all, 

For me it was a problem related to ffmpeg5, so I reinstalled the library.

**sudo apt-get remove libavfilter-ffmpeg5
sudo apt-get install libavfilter-ffmpeg5
sudo ldconfig**

**Comment by zhangliyun9120** [comment]
@arturpol94 hello! Have you solved this problem? if you know the solution plz tell me ,ths!
