### ISSUE TITLE
Disabling / read-only widget

### ISSUE THREAD

**Issue by NikolausDemmel** [stevenlovegrove/Pangolin#400]
Is there a way to (temporarily) disable widgets from being edited / clicked ?

**Comment by stevenlovegrove** [comment]
Not currently, sorry.

**Comment by NikolausDemmel** [comment]
Ok, no worries.

Something like this in the GUI loop works for me as a workaround (of course you need to store the appropriate `previousFoo` at some point):

```
if (fooDisabled && foo.GuiChanged())
{
    foo = previousFoo;
}
```
