### ISSUE TITLE
make error in display_osx.mm on mac

### ISSUE THREAD

**Issue by Junxen** [stevenlovegrove/Pangolin#403]
In file included from /Users/slam/dso/thirdparty/Pangolin/src/display/device/display_osx.mm:33:
In file included from /Users/slam/dso/thirdparty/Pangolin/include/pangolin/display/device/OsxWindow.h:33:
In file included from /Users/slam/dso/thirdparty/Pangolin/include/pangolin/display/device/PangolinNSApplication.h:30:
In file included from /System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:29:
In file included from /System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/HIToolbox.h:240:
In file included from /System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/IMKInputSession.h:23:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:5:
/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:43:12: error: unknown property attribute 'class'
@property (class, readonly) BOOL supportsSecureCoding;

**Comment by stevenlovegrove** [comment]
Hmm, I'm not sure about that...

**Comment by stevenlovegrove** [comment]
Closing since this is pretty old now. Please reopen if anyone reexperiences this.
