### ISSUE TITLE
Download of old version 

### ISSUE THREAD

**Issue by Zoltan3057** [stevenlovegrove/Pangolin#405]
Hi.
Currently I am working on an old project, which needs Pangolin 0.1. Do anyone konw where can I download this?

**Comment by Zoltan3057** [comment]
Hi:
More specifically, when I run GlTexture::upload as in  line 127 of [https://github.com/jserv/lsd_slam/blob/master/lsd_slam_core/src/GUI.cpp](url)

`    depthImg->Upload(depthImgBuffer.getReference(), GL_RGB, GL_UNSIGNED_BYTE);
`

I got some errors like 

`In: /usr/local/include/pangolin/gl/gl.hpp, line 184
OpenGL Error: XX (1280)
In: /usr/local/include/pangolin/gl/gl.hpp, line 184
OpenGL Error: XX (1280)
In: /usr/local/include/pangolin/gl/gl.hpp, line 184
OpenGL Error: XX (1280)
In: /usr/local/include/pangolin/gl/gl.hpp, line 184
OpenGL Error: XX (1280)
In: /usr/local/include/pangolin/gl/gl.hpp, line 184
OpenGL Error: XX (1280)
In: /usr/local/include/pangolin/gl/gl.hpp, line 184
OpenGL Error: XX (1280)
In: /usr/local/include/pangolin/g`

When I look into it, I think the error is from gl.hpp

`inline void GlTexture::Upload(
    const void* data,
    GLenum data_format, GLenum data_type
) {
    Bind();
    glTexSubImage2D(GL_TEXTURE_2D,0,0,0,width,height,data_format,data_type,data);
    //glTexImage2D(GL_TEXTURE_2D, 0, internal_format, width, height, 0, data_format, data_type, data);
    CheckGlDieOnError();
}
`

But I cannot get the underline mechanism of CheckGlDieOnError(). The program is still working, but it always gives me OpenGL Errors.

**Comment by stevenlovegrove** [comment]
Error 1280 is GL_INVALID_ENUM.

Looking at your code snippet, I'm not sure why you would get that error from that line. Have you tried calling CheckGlDieOnError() before this point to make sure that the error wasn't set previously?

**Comment by GentlemanCheng** [comment]
> Hi.
> Currently I am working on an old project, which needs Pangolin 0.1. Do anyone konw where can I download this?

hi @Zoltan3057 , do you know where to download an old version now ?

**Comment by stevenlovegrove** [comment]
@Liming-Cheng all old versions are in this git repo but you'll likely hit problems with 3rd party library versions as well. There are tags for versions 0.3 and higher (https://github.com/stevenlovegrove/Pangolin/releases).

Pangolin has remained mostly backwards compatible, so it is normally not too hard to get an old program to work with the latest version with quite minimal changes.
