### ISSUE TITLE
  what():  No known video handler for URI 'shmem'

### ISSUE THREAD

**Issue by Zoltan3057** [stevenlovegrove/Pangolin#406]
Hi:
When I tried to run the SharedMemoryCamera example with SimpleVideo for visulization, I got:
`terminate called after throwing an instance of 'pangolin::VideoExceptionNoKnownHandler'
  what():  No known video handler for URI 'shmem'
Aborted (core dumped)`
Can anyone help?

**Comment by stevenlovegrove** [comment]
What platform is this on? shmem is only implemented on Linux.
