### ISSUE TITLE
How do I shut down pangolin window?

### ISSUE THREAD

**Issue by nonlinear1** [stevenlovegrove/Pangolin#409]
In my ORB_SLAM2, after I send shut down command let slam stop run. I cann't shut down pangolin window. Could someone know how I can write some codes to shut down pangloin window? the pangolin
window is as follow:
![screenshot from 2018-09-28 11-14-30](https://user-images.githubusercontent.com/19766939/46186187-cca39b00-c30f-11e8-866c-72cf8ad09454.png)

**Comment by yiakwy** [comment]
@stevenlovegrove I use jupyter (python) to code a PCViewer (backend using Pangolin). PCVIewer will start a process to run pangolin infinity rendering loop.

However, whenver I use "pangolin.DestroyWindow("PCViewer")" to close the window, jupyter will throw an error and the kernel will restart

```txt
[I 20:10:15.204 NotebookApp] Saving file at /semantic_tracker.ipynb
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
      after 57 requests (57 known processed) with 0 events remaining.
[I 20:33:59.701 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
```

How can I solve the problem?

**Comment by stevenlovegrove** [comment]
This code has been refactored a bit and I hope it is a bit more reliable for destruction.

In order to debug this, we'd really need some stack trace when the kernel crashes if that is possible? I'll close for now but please reopen if you still have this trouble on the master branch.
