### ISSUE TITLE
uri with openni2: not working for pangolin/video

### ISSUE THREAD

**Issue by dcanelhas** [stevenlovegrove/Pangolin#41]
```examples/SimpleVideo$ ./SimpleVideo openni2:[img1=rgb]//0```
displays random data as a texture.

a small test:
```
std::string uri = "openni2:[img1=depth]//0";
video = new pangolin::VideoInput(uri);
std::cout << video->SizeBytes() << std::endl;
```
expected 622080 (640 * 480 * 2)
result was 7259868570163961862

Using SizeBytes() for memory allocation causes a crash -- maybe it's time to get more RAM ;).

(devel branch)

**Comment by stevenlovegrove** [comment]
Is this definitely against the devel branch? I think this should be fixed there.

**Comment by dcanelhas** [comment]
Ah no you're right. I was on master. sorry about that. 
Both the example/SimpleVideo and the SizeBytes issue appear to be fixed in Devel

**Comment by stevenlovegrove** [comment]
Great.
