### ISSUE TITLE
Cmake error on windows 10

### ISSUE THREAD

**Issue by BrunoXL** [stevenlovegrove/Pangolin#414]
I got the error below on building `Pangolin` on windows 10. 

     -- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.17134.
     CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/ExternalProject.cmake:1654 (file):
     file problem creating directory: C:/Program Files (x86)/Pangolin
     Call Stack (most recent call first):
     C:/Program Files/CMake/share/cmake-3.11/Modules/ExternalProject.cmake:3052 (_ep_set_directories)
     external/CMakeLists.txt:10 (ExternalProject_Add)

**Comment by Work-jk-l** [comment]
The same error in my project on window10(vs2015,update3)，Compile the pangolin.sln is successful,but many errors in compile my own project using the genetrated *.lib.。So I am wondering whether pangolin can not be use on windows?

**Comment by powderluv** [comment]
You can try to pass CMAKE_INSTALL_PREFIX to work around that issue. It can't handle spaces in the file path.

**Comment by powderluv** [comment]
try https://github.com/stevenlovegrove/Pangolin/pull/420

**Comment by Gatunox** [comment]
BrunoXL

You need to be administrator, so please excute the cmd or VS2017 as an administrator an it will work, also check the **build on windows** issue, i've provided a detailed explanation to compile on windows.

regards

**Comment by navalsheth** [comment]
Ture 

> For any people encountering weird build error on Windows 10,
> 
> please make sure you run CMake-GUI and Visual Studio in Administrator mode !
> 
> Within administrator mode, the installation should be easy.

TRUE, I got stuck for one week with same error as mentioned above and then I Opened CMAKE as Administrator, Then things worked well

**Comment by lz2004xxw** [comment]
i wonder why it worked in Administrator mode ?

**Comment by valeriob** [comment]
Probably because it's trying to install into C:\Program Files (x86)\ 
i just changed that parameter in cmake and it worked without admin privileges
