### ISSUE TITLE
building gives python 3.5 bindings

### ISSUE THREAD

**Issue by kemfic1** [stevenlovegrove/Pangolin#416]
Pangolin builds successfully along with its python bindings, but it seems that pypangolin only works with python 3.5 for some reason. The python examples run fine with python 3.5, but I get the following error when running them with python 2.7:

ImportError: no module named pypangolin

How can I get pypangolin for python 2.7?

**Comment by clmno** [comment]
Did you compile pypangolin with the python 2.7 path? And add the shared library into the python version's path? (sys.path.append("/path/to/.so/file"))

**Comment by kemfic1** [comment]
@clmno How do you compile with the python 2.7 path? I've already tried appending the shared library into my path, but that only works when I run a script with python 3.5.

**Comment by kemfic1** [comment]
When I ran `/usr/bin/env python --version` I get `Python 2.7.12`

**Comment by kemfic1** [comment]
Ok, so this seems to be an issue with pybind11, not Pangolin itself. The solution's been referenced [here.](https://github.com/pybind/pybind11/issues/587#issuecomment-270429901) It works fine now.

Thanks for the help!
