### ISSUE TITLE
Make error with Jetson Xavier  Ubuntu 18.04 

### ISSUE THREAD

**Issue by anakin0620** [stevenlovegrove/Pangolin#417]
[ 72%] Building CXX object examples/HelloPangolinThreads/CMakeFiles/HelloPangolinThreads.dir/main.cpp.o
[ 73%] Building CXX object examples/SimpleDisplay/CMakeFiles/SimpleDisplay.dir/main.cpp.o
[ 74%] Building CXX object examples/SimplePlot/CMakeFiles/SimplePlot.dir/main.cpp.o
[ 75%] Building CXX object examples/SimpleVideo/CMakeFiles/SimpleVideo.dir/main.cpp.o
[ 76%] Building CXX object examples/SimpleScene/CMakeFiles/SimpleScene.dir/main.cpp.o
[ 76%] Building CXX object examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/main.cpp.o
[ 77%] Building CXX object examples/SimpleMultiDisplay/CMakeFiles/SimpleMultiDisplay.dir/main.cpp.o
[ 78%] Building CXX object examples/SimpleDisplayImage/CMakeFiles/SimpleDisplayImage.dir/main.cpp.o
[ 79%] Linking CXX executable HelloPangolin
[ 80%] Linking CXX executable SimplePlot
[ 81%] Linking CXX executable SimpleVideo
[ 82%] Linking CXX executable HelloPangolinThreads
[ 83%] Linking CXX executable SimpleDisplayImage
[ 84%] Linking CXX executable SimpleMultiDisplay
**/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeGetFB'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeFreeFB'
collect2: error: ld returned 1 exit status**
examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/build.make:113: recipe for target 'examples/HelloPangolin/HelloPangolin' failed
make[2]: *** [examples/HelloPangolin/HelloPangolin] Error 1
CMakeFiles/Makefile2:271: recipe for target 'examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/all' failed
make[1]: *** [examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeGetFB'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeFreeFB'
collect2: error: ld returned 1 exit status
examples/SimplePlot/CMakeFiles/SimplePlot.dir/build.make:113: recipe for target 'examples/SimplePlot/SimplePlot' failed
make[2]: *** [examples/SimplePlot/SimplePlot] Error 1
CMakeFiles/Makefile2:546: recipe for target 'examples/SimplePlot/CMakeFiles/SimplePlot.dir/all' failed
make[1]: *** [examples/SimplePlot/CMakeFiles/SimplePlot.dir/all] Error 2
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeGetFB'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeFreeFB'
collect2: error: ld returned 1 exit status
examples/SimpleVideo/CMakeFiles/SimpleVideo.dir/build.make:113: recipe for target 'examples/SimpleVideo/SimpleVideo' failed
make[2]: *** [examples/SimpleVideo/SimpleVideo] Error 1
CMakeFiles/Makefile2:656: recipe for target 'examples/SimpleVideo/CMakeFiles/SimpleVideo.dir/all' failed
make[1]: *** [examples/SimpleVideo/CMakeFiles/SimpleVideo.dir/all] Error 2
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeGetFB'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeFreeFB'
collect2: error: ld returned 1 exit status
examples/HelloPangolinThreads/CMakeFiles/HelloPangolinThreads.dir/build.make:113: recipe for target 'examples/HelloPangolinThreads/HelloPangolinThreads' failed
make[2]: *** [examples/HelloPangolinThreads/HelloPangolinThreads] Error 1
CMakeFiles/Makefile2:326: recipe for target 'examples/HelloPangolinThreads/CMakeFiles/HelloPangolinThreads.dir/all' failed
make[1]: *** [examples/HelloPangolinThreads/CMakeFiles/HelloPangolinThreads.dir/all] Error 2
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeGetFB'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeFreeFB'
collect2: error: ld returned 1 exit status
examples/SimpleDisplayImage/CMakeFiles/SimpleDisplayImage.dir/build.make:113: recipe for target 'examples/SimpleDisplayImage/SimpleDisplayImage' failed
make[2]: *** [examples/SimpleDisplayImage/SimpleDisplayImage] Error 1
CMakeFiles/Makefile2:436: recipe for target 'examples/SimpleDisplayImage/CMakeFiles/SimpleDisplayImage.dir/all' failed
make[1]: *** [examples/SimpleDisplayImage/CMakeFiles/SimpleDisplayImage.dir/all] Error 2
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeGetFB'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeFreeFB'
collect2: error: ld returned 1 exit status
examples/SimpleMultiDisplay/CMakeFiles/SimpleMultiDisplay.dir/build.make:113: recipe for target 'examples/SimpleMultiDisplay/SimpleMultiDisplay' failed
make[2]: *** [examples/SimpleMultiDisplay/SimpleMultiDisplay] Error 1
CMakeFiles/Makefile2:381: recipe for target 'examples/SimpleMultiDisplay/CMakeFiles/SimpleMultiDisplay.dir/all' failed
make[1]: *** [examples/SimpleMultiDisplay/CMakeFiles/SimpleMultiDisplay.dir/all] Error 2
[ 85%] Linking CXX executable SimpleScene
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeGetFB'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeFreeFB'
collect2: error: ld returned 1 exit status
examples/SimpleScene/CMakeFiles/SimpleScene.dir/build.make:113: recipe for target 'examples/SimpleScene/SimpleScene' failed
make[2]: *** [examples/SimpleScene/SimpleScene] Error 1
CMakeFiles/Makefile2:491: recipe for target 'examples/SimpleScene/CMakeFiles/SimpleScene.dir/all' failed
make[1]: *** [examples/SimpleScene/CMakeFiles/SimpleScene.dir/all] Error 2
[ 86%] Linking CXX executable SimpleDisplay
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeGetFB'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libavdevice.so: undefined reference to `drmModeFreeFB'
collect2: error: ld returned 1 exit status
examples/SimpleDisplay/CMakeFiles/SimpleDisplay.dir/build.make:113: recipe for target 'examples/SimpleDisplay/SimpleDisplay' failed
make[2]: *** [examples/SimpleDisplay/SimpleDisplay] Error 1
CMakeFiles/Makefile2:601: recipe for target 'examples/SimpleDisplay/CMakeFiles/SimpleDisplay.dir/all' failed
make[1]: *** [examples/SimpleDisplay/CMakeFiles/SimpleDisplay.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by anakin0620** [comment]
Does anyone have an idea about solving this? Appreciate!

**Comment by stevenlovegrove** [comment]
If you don't need it, you can try disabling ffmpeg by clearing cmake variables related to libavdevice etc.

Alternatively, you could try following the info here (https://devtalk.nvidia.com/default/topic/1041988/ffmpeg-problem-quot-undefined-symbol-drmmodefreefb-quot-/). Basically, on this platform is looks like there is a third-party dependency not captured, namely libdrm.so. You could try modifying CMakeModules/FindFFMPEG.cmake to include this library and any others.

**Comment by anakin0620** [comment]
Thank you for your reply. I need Pangolin since I am going to try ORB_SLAM on this new Jetson Xavier kit, I am not sure if I need FFmpeg or not. I tried to follow your instruction but I failed. I believe there are more people doing the same work on the Jetson Xavier so probably I will wait.

**Comment by anakin0620** [comment]
Finally, I disabled/removed the FindFFMPEG.cmake. Everything goes well now. Thank you  @stevenlovegrove.

**Comment by kvnptl** [comment]
Check this https://forums.developer.nvidia.com/t/problem-with-gazebo/65769/16

It works for me on Jetson AGX Xavier Jetpack 4

**Comment by anakin0620** [comment]
@kvnptl Thank you for let us know it's working flawless with the lastest Jetpack! I will try it.
