### ISSUE TITLE
VideoConverter split generates wrong file size

### ISSUE THREAD

**Issue by martinruenz** [stevenlovegrove/Pangolin#418]
I noticed that the video converter wastes space when extracting streams with index  > 0. It seems like each frame uses as much space as if all streams up to the defined index were present.

This reproduces the behavior:
```
cd /tmp
# Generate 3 random images
mx=320;my=256;head -c "$((3*mx*my))" /dev/urandom | convert -depth 8 -size "${mx}x${my}" RGB:- random1.png
mx=320;my=256;head -c "$((3*mx*my))" /dev/urandom | convert -depth 8 -size "${mx}x${my}" RGB:- random2.png
mx=320;my=256;head -c "$((3*mx*my))" /dev/urandom | convert -depth 8 -size "${mx}x${my}" RGB:- random3.png
# Join them to a pango file
vc 'join://{random1.png}{random2.png}{random3.png}' 3.pango
# Extract streams
vc 'split:[stream1=1]//3.pango' 1a.pango 
vc 'split:[stream1=2]//3.pango' 1b.pango
vc 'split:[stream1=3]//3.pango' 1c.pango
# Compare files, this worked when using 1. stream but wastes space otherwise
du 3.pango
du 1a.pango
du 1b.pango
du 1c.pango
# Even though 1c and 3 have the same size, content differs:
cmp 1c.pango 3.pango
````

**Comment by tfy14esa** [comment]
Dear Martin,
Could you let me know how you create the .pango file extension from the .png files? To me, this is not  clear.

Thanks a lot.

**Comment by stevenlovegrove** [comment]
A bit late on this, but yes - the split driver is kinda a 'view' on the original data and doesn't modify the underlying buffer. Any driver that causes a copy will 'repack' the data to remove the wasted space. For instance, you could use debayer://split:[...]//... - there the debayer doesn't actually do anything because no debayer options are being provided. I thought I added a repack:// alias but I don't seem to have one yet.

**Comment by stevenlovegrove** [comment]
@tfy14esa vc is Martin's alias for ./tools/VideoConvert/VideoConvert, so you can create the pango video file containing a single frame of 3 streams using:

```./tools/VideoConvert/VideoConvert "join://{random1.png}{random2.png}{random3.png}" test.pango```

You can alternatively use the 'images' driver to load sequences, either for use directly in a program or for conversion using the tool above:

```
./tools/VideoViewer/VideoViewer "images://~/folder/[seta,setb]/images.jpg" 
./tools/VideoViewer/VideoViewer "images://~/dataset/[stream1_*.jpg,stream1_*.jpg]"
```
