### ISSUE TITLE
Cannot open include file: 'pangolin/pangolin_export.h': No such File or Directory

### ISSUE THREAD

**Issue by kemfic1** [stevenlovegrove/Pangolin#421]
I'm compiling this on windows with Visual Studio 15. When I build the solution BUILD_ALL, I get the following error:

``` Cannot open include file: 'pangolin/pangolin_export.h': No such file or directory ```

I can't find the header file its looking for, the closest thing to it I've found is ```_pangolin_export.h``` . How can I fix this?

**Comment by kemfic1** [comment]
Looking back at the console output, I noticed I was getting this warning:
``` Command line warning D9002: ignoring unknown option '-fPIC ```

**Comment by stevenlovegrove** [comment]
This is meant to be generated during the cmake step. Specifically, this line:
https://github.com/stevenlovegrove/Pangolin/blob/892c5e29270374a684424005142db38b25d95410/src/CMakeLists.txt#L437

You should try re-cmaking.

**Comment by twistxj** [comment]
I’d like to reopen this because I am having the same issue. What am I supposed to change? I tried remaking with cmake and same error.

**Comment by stevenlovegrove** [comment]
@twistxj are you facing this issue during build of Pangolin, or in your own program? I'm guessing it is in your own program and you are including Pangolin manually (instead of via CMake). In that case, you will need to locate this file in the build directory and include it as well.
