### ISSUE TITLE
How can pangolin get camera position and its direction?

### ISSUE THREAD

**Issue by pisuto** [stevenlovegrove/Pangolin#422]
Hello,
I have a question about camera position and its direction.
Now, I get modelviewMatrix from OpenGlRenderState and I can calculate its camera position like the formula in ModelViewLookAtRUB I found in opengl_render_state.cpp.
But if I  press my right mouse button and move, then the camera position is wrong.
So what happens?
And does this mean I need to get camera position from T_cw I found in the header file or is there a easy way to get the camera position and  direction?

**Comment by stevenlovegrove** [comment]
The model_view matrix is a transform such that P_camera = ModelViewMat * P_object (using homogeneous coords). Note that if you have not pushed any transforms to the modelview stack then object coordinates and world coordinates will be the same, which is what I will assume here.

That implies that ModelViewMat is a transform T_camera_world. The right hand side of this matrix is therefore the location of the world frame center with respect to the camera coordinate system. What you want is the other way around, so you should invert this matrix and then take the top-right of it.

```
const auto T_world_camera = s_cam.GetModelViewMatrix().inverse();
const double x = T_world_camera(0,3);
const double y = T_world_camera(1,3);
const double z = T_world_camera(2,3);
```

**Comment by pisuto** [comment]
Hello,
Now I can get the camera position and I try to get the forward vector. Before I change the rotation of the camera, -Twc*(0,0,1,0) works well. But after I rotate camera, the formula can't work.

So how can I get correct forward vector of the camera after I press the right mouse button and move the camera?

**Comment by pisuto** [comment]
Hello,
Now I can get the camera position and I try to get the forward vector of the camera. 
Before I change the rotation of the camera, -Twc*(0,0,1,0) works well. But after I rotate camera, the formula can't work.

So how can I get the forward vector of the camera after I press the right mouse button and rotate the camera?

**Comment by stevenlovegrove** [comment]
The default OpenGL coordinate system, if you are using that, has z point back, so your forward vector in camera frame is (0,0,-1). You should therefore use fwd_w = Twc*(0,0,-1,0)

**Comment by pisuto** [comment]
thx!
I will try.
