### ISSUE TITLE
GlFormatChannel not defined for BGR

### ISSUE THREAD

**Issue by caselitz** [stevenlovegrove/Pangolin#433]
Hi,

I just tried to convert an OpenCV image to a `Pangolin::Image` ([related issue](https://github.com/stevenlovegrove/Pangolin/issues/293)) and display it with the `ImageView` class:

```
pangolin::ImageView test;

pangolin::Image<unsigned char> img(cv_img.ptr<unsigned char>(), cv_img.cols, cv_img.rows, cv_img.cols * 3);

pangolin::PixelFormat fmt = pangolin::PixelFormatFromString("BGR24");
pangolin::GlPixFormat glfmt(fmt);

pangolin::Display("Image Viewer").AddDisplay(test.SetImage(img, glfmt));
```

This causes an [assertion](https://github.com/stevenlovegrove/Pangolin/blob/master/src/display/image_view.cpp#L139), as the function `pangolin::GlFormatChannels()` (used [here](https://github.com/stevenlovegrove/Pangolin/blob/master/src/display/image_view.cpp#L117)) accesses the [format_channels array](https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/gl/gl.hpp#L77) where `GL_BGR` is not defined.

I feel the situation is unfortunate since the `GlPixFormat` explicitly handles `GL_BGR` and produces objects that are invalid (at least if `pangolin::GlFormatChannels()` is used with it, like in the `SetImage()` function of `ImageView`).

It seems easy to resolve this issue by adding (from my `glew.h`)
```
1231   #define GL_BGR 0x80E0
1232   #define GL_BGRA 0x80E1
```
to the Pangolin format_channels array. I'm just not sure how to do this properly. Is it necessary to account for that those are only defined with `GL_VERSION_1_2`? Also, I guess the way the function `GlFormatChannels()` accesses the array would need to be changed as the hex codes are not consecutive, e.g.,

```
inline size_t GlFormatChannels(GLenum data_layout)
{
  if (data_layout == GL_BGR) return 3;
  if (data_layout == GL_BGRA) return 4;
  return format_channels[data_layout - GL_RED];
}
```
If you tell me how you would like to have this, I could send a PR.

Best regards,
Tim

**Comment by stevenlovegrove** [comment]
Sorry for the delayed response - the last few weeks have been super busy.

Good question - we should probably just replace that with a switch statement. I'm not sure why I decided such an unsafe method was wise in the first place...
