### ISSUE TITLE
Pangolin uninstall

### ISSUE THREAD

**Issue by haleqiu** [stevenlovegrove/Pangolin#438]
I am using Ubantu and install Pangolin with cmake
When I am trying to uninstall using make uninstall 

`make uninstall
make: *** No rule to make target 'uninstall'.  Stop.` 

How can I uninstall pangolin?

**Comment by NikolausDemmel** [comment]
There is an uninstall target, but it was recently renamed to `pangolin_uninstall`, see https://github.com/stevenlovegrove/Pangolin/pull/419/files

**Comment by haleqiu** [comment]
$ make pangolin_uninstall 
make: *** No rule to make target 'pangolin_uninstall'.  Stop.

Well, It still not working

**Comment by NikolausDemmel** [comment]
Aha, tbh I have never used it, I don't know.

**Comment by haleqiu** [comment]
@stevenlovegrove anyone know this questions?

**Comment by stevenlovegrove** [comment]
There's been quite a lot of refactoring since this issue. I've just readded an uninstall target named just 'uninstall' which should work as expected (4f1302188bd1ee0e7f780b61706f14ab9e4778a7)

**Comment by LeonardoRez** [comment]
mine doesn't work. It says:

> CMake Error at cmake_uninstall.cmake:2 (message):
>   Cannot find install manifest:
>   /home/poirot/installing_pangolin/Pangolin/build/install_manifest.txt

I need to uninstall it to install another version, but I don't know exactly how

thanks for your attention

**Comment by alexs7** [comment]
same here I can't uninstall it. any advice ?

**Comment by john-liu2039** [comment]
Enter your `build` directory, then 
`
sudo make uninstall
`
This will uninstall pangolin.

**Comment by dkobayas-cyber** [comment]
I folllowed @GoWest279 's advice, but I get an error message...
```
dkobayas@Ubuntu22:~/Documents/Pangolin/build$ ls
CMakeCache.txt         libpango_glgeometry.so    libpango_windowing.so
CMakeFiles             libpango_image.so         libtinyobj.so
cmake_install.cmake    libpango_opengl.so        Makefile
cmake_uninstall.cmake  libpango_packetstream.so  PangolinConfig.cmake
examples               libpango_plot.so          PangolinConfigVersion.cmake
fonts.cpp              libpango_python.so        PangolinTargets.cmake
include                libpango_scene.so         shaders.cpp
libpango_core.so       libpango_tools.so         tools
libpango_display.so    libpango_vars.so          xdg-shell-client-protocol.h
libpango_geometry.so   libpango_video.so         xdg-shell-protocol.c
dkobayas@Ubuntu22:~/Documents/Pangolin/build$ sudo make uninstall
[sudo] password for dkobayas: 
CMake Error at cmake_uninstall.cmake:2 (message):
  Cannot find install manifest:
  /home/dkobayas/Documents/Pangolin/build/install_manifest.txt


make[3]: *** [CMakeFiles/uninstall.dir/build.make:70: CMakeFiles/uninstall] Error 1
make[2]: *** [CMakeFiles/Makefile2:866: CMakeFiles/uninstall.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:873: CMakeFiles/uninstall.dir/rule] Error 2
make: *** [Makefile:364: uninstall] Error 2

```

**Comment by angelhappyboy** [comment]
sudo make pangolin_uninstall

**Comment by christian-rauch** [comment]
> sudo make pangolin_uninstall

I don't think the `pangolin_uninstall` works:
```
cmake -B build_make -D CMAKE_INSTALL_PREFIX=/tmp/pangolin
cd build_make/
make install
# ...
-- Installing: /tmp/pangolin/[...]
# ...
make pangolin_uninstall
make: *** No rule to make target 'pangolin_uninstall'.  Stop.
```

However, target `uninstall` works:
```
make uninstall
-- Uninstalling /tmp/pangolin/[...]
Built target uninstall
```
