### ISSUE TITLE
No member named ‘GetAutoExposureCap’

### ISSUE THREAD

**Issue by hoangcuongbk80** [stevenlovegrove/Pangolin#446]
Hi there,

I got the following error when run  cmake --build .

In member function ‘void pangolin::OpenNiVideo::SetAutoExposure(bool)’:
openni.h:53:23: error: ‘class xn::ImageGenerator’ has no member named ‘GetAutoExposureCap’
             imageNode.GetAutoExposureCap().Set(enabled ? 1 : 0);

Any help would be greatly appreciated.

**Comment by stevenlovegrove** [comment]
If you would like to use OpenNI from Pangolin then you could try to fix the error (presumably OpenNI API has been updated), or if you don't care about it you can disable use of OpenNI through cmake or cmake-gui

**Comment by hoangcuongbk80** [comment]
Oh right! Thank you very much!
