### ISSUE TITLE
VideoException for improper OpenNI VideoMode when reading from oni file

### ISSUE THREAD

**Issue by dcanelhas** [stevenlovegrove/Pangolin#45]
When setting up an openni device for live capture using an openni2: uri string this is not a problem, but i find that using the provided interface in pangolin/video/drivers/openni2.h for reading from files i.e.
```
   // Open openni file
    OpenNiVideo2(const std::string& filename);
```
isn't working as it should

The following code: 
```
pangolin::OpenNiVideo2 * video;
std::string file = "/home/danielcanelhas/Video/RGBD/Captured.oni";
video = new pangolin::OpenNiVideo2(file);  
```
causes the following

terminate called after throwing an instance of 'pangolin::VideoException'
  what():  Couldn't set OpenNI VideoMode
		Stream setProperty(3) failed

This can be "fixed" by removing the check in openni2.cpp : 331

        if(rc != openni::STATUS_OK)
            throw VideoException("Couldn't set OpenNI VideoMode", openni::OpenNI::getExtendedError());

(this time I'm extra confident that I am actually on the devel branch)

I feel like I am doing it wrong though I couldn't find a parser for file: uri strings that handles oni extensions anywhere.  That would probably be the most logical way of handling it.

**Comment by qazmichaelgw** [comment]
Hello dcanelhas, Can you send me the example to set up an openni device for live capture using an openni2? I am going to use the XBOX 360 to capture the data!
Best regards

**Comment by stevenlovegrove** [comment]
You should have been able to use "openni2:///home/danielcanelhas/Video/RGBD/Captured.oni" as your URI string (as used by VideoViewer for example). Opening oni files should work. If this is still an issue for anyone, please re-open this issue and perhaps capture a small oni sequence for me to test on.

**Comment by Algomorph** [comment]
It's still an issue.

```
./VideoViewer "openni2:///media/algomorph/Data/4dmseg/TestCapture.oni"
Couldn't set OpenNI VideoMode
		Stream setProperty(3) failed
```

**Comment by Algomorph** [comment]
Test .oni file: [link](http://algomorph.com/storage/TestCapture.oni)

**Comment by Algomorph** [comment]
The problem is that for some reason you cannot set the video mode on an OpenNI stream from an .oni file. The simple work-around is to replace line 330 in ```src/video/drivers/openni2.cpp``` with
```std::cout << "Warning: Couldn't set OpenNI VideoMode" << openni::OpenNI::getExtendedError();```

Minimum example to reproduce:
```C++
#include <iostream>
#include <openni2/OpenNI.h>

int main(int argc, const char* argv[]) {
	openni::Device device;
	openni::VideoStream depth_stream;
	openni::VideoStream color_stream;
	openni::Status rc;
	openni::VideoFrameRef depth_frame_ref;
	openni::VideoFrameRef color_frame_ref;

	openni::OpenNI::initialize();

	const char* cstr = argv[1];

	device.open(cstr);

	depth_stream.create (device, openni::SENSOR_DEPTH);
	openni::VideoMode depth_video_mode;
	depth_video_mode.setFps(30);
	depth_video_mode.setPixelFormat(openni::PIXEL_FORMAT_DEPTH_1_MM);
	depth_video_mode.setResolution(320,240);
	rc = depth_stream.setVideoMode(depth_video_mode);
	if(rc == openni::STATUS_ERROR){
		std::cout << "Could not set video mode." << std::endl;
	}

	color_stream.create (device, openni::SENSOR_COLOR);
	//device.setImageRegistrationMode (openni::IMAGE_REGISTRATION_DEPTH_TO_COLOR);
	depth_stream.start ();
	color_stream.start ();


	depth_stream.readFrame (&depth_frame_ref);
	color_stream.readFrame (&color_frame_ref);

	std::cout << depth_frame_ref.getWidth() << std::endl;
	std::cout << depth_frame_ref.getHeight() << std::endl;

	depth_stream.stop();
	color_stream.stop();

	device.close();
	openni::OpenNI::shutdown();

	return 0;
}
```

**Comment by stevenlovegrove** [comment]
Instead, can we just avoid the call when loading a file? I'm happy to merge a tested PR if someone wants to offer one.

**Comment by Algomorph** [comment]
I will make the PR.

**Comment by Algomorph** [comment]
PR #263
