### ISSUE TITLE
MAKE ERROR

### ISSUE THREAD

**Issue by ImageProcessingAndPythonLearner** [stevenlovegrove/Pangolin#451]
[  1%] Building CXX object src/CMakeFiles/pangolin.dir/utils/sigstate.cpp.o
In file included from /home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h:31:0,
                 from /home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/platform.h:80,
                 from /home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/sigstate.h:32,
                 from /home/yanghai/software/Pangolin/Pangolin-master/src/utils/sigstate.cpp:28:
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:40:5: warning: identifier ‘decltype’ is a keyword in C++11 [-Wc++0x-compat]
     static auto test(int) -> decltype( (std::declval<std::stringstream&>() << std::declval<TT>(), std::true_type()) );
     ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:58:5: warning: identifier ‘static_assert’ is a keyword in C++11 [-Wc++0x-compat]
     static_assert(IsStreamable<T>::value,
     ^
In file included from /home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h:31:0,
                 from /home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/platform.h:80,
                 from /home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/sigstate.h:32,
                 from /home/yanghai/software/Pangolin/Pangolin-master/src/utils/sigstate.cpp:28:
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:40:12: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
     static auto test(int) -> decltype( (std::declval<std::stringstream&>() << std::declval<TT>(), std::true_type()) );
            ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:40:30: error: expected type-specifier before ‘decltype’
     static auto test(int) -> decltype( (std::declval<std::stringstream&>() << std::declval<TT>(), std::true_type()) );
                              ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:40:30: error: expected initializer before ‘decltype’
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:43:12: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
     static auto test(...) -> std::false_type;
            ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:43:30: error: expected type-specifier
     static auto test(...) -> std::false_type;
                              ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:43:30: error: expected initializer
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:46:40: error: ‘test’ was not declared in this scope
     static const bool value = decltype(test<T>(0))::value;
                                        ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:46:46: error: expected primary-expression before ‘>’ token
     static const bool value = decltype(test<T>(0))::value;
                                              ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:46:50: error: a function call cannot appear in a constant-expression
     static const bool value = decltype(test<T>(0))::value;
                                                  ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:46:50: error: expected ‘;’ at end of member declaration
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:46:53: error: using-declaration for non-member at class scope
     static const bool value = decltype(test<T>(0))::value;
                                                     ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:55:31: warning: variadic templates only available with -std=c++11 or -std=gnu++11 [enabled by default]
 template <typename T, typename... Args>
                               ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:56:79: warning: variadic templates only available with -std=c++11 or -std=gnu++11 [enabled by default]
 void FormatStream(std::stringstream& stream, const char* text, T arg, Args... args)
                                                                               ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h: In function ‘void pangolin::details::FormatStream(std::stringstream&, const char*, T, Args ...)’:
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:68:55: warning: variadic templates only available with -std=c++11 or -std=gnu++11 [enabled by default]
     stream << "\nFormat-Warning: There are " << sizeof...(Args) + 1
                                                       ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h: At global scope:
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:74:19: warning: variadic templates only available with -std=c++11 or -std=gnu++11 [enabled by default]
 template <typename... Args>
                   ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/format_string.h:75:52: warning: variadic templates only available with -std=c++11 or -std=gnu++11 [enabled by default]
 std::string FormatString(const char* text, Args... args)
                                                    ^
In file included from /home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/platform.h:80:0,
                 from /home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/sigstate.h:32,
                 from /home/yanghai/software/Pangolin/Pangolin-master/src/utils/sigstate.cpp:28:
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h:44:19: warning: variadic templates only available with -std=c++11 or -std=gnu++11 [enabled by default]
 template <typename... Args> PANGO_HOST_DEVICE
                   ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h:45:66: error: expected ‘,’ or ‘...’ before ‘&&’ token
 void abort(const char* function, const char* file, int line, Args&&... args)
                                                                  ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h:45:76: error: parameter packs not expanded with ‘...’:
 void abort(const char* function, const char* file, int line, Args&&... args)
                                                                            ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h:45:76: note:         ‘Args’
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h: In function ‘void pangolin::abort(const char*, const char*, int, <type error>)’:
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h:47:3: error: ‘printf’ is not a member of ‘std’
   std::printf("pangolin::abort() in function '%s', file '%s', line %d.\n", function, file, line);
   ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h:49:29: error: ‘forward’ is not a member of ‘std’
   std::cout << FormatString(std::forward<Args>(args)...) << std::endl;
                             ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h:49:46: error: expected primary-expression before ‘>’ token
   std::cout << FormatString(std::forward<Args>(args)...) << std::endl;
                                              ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h:49:48: error: ‘args’ was not declared in this scope
   std::cout << FormatString(std::forward<Args>(args)...) << std::endl;
                                                ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h:50:3: error: ‘abort’ is not a member of ‘std’
   std::abort();
   ^
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h:50:3: note: suggested alternative:
/home/yanghai/software/Pangolin/Pangolin-master/include/pangolin/utils/assert.h:45:6: note:   ‘pangolin::abort’
 void abort(const char* function, const char* file, int line, Args&&... args)
      ^
make[2]: *** [src/CMakeFiles/pangolin.dir/utils/sigstate.cpp.o] 错误 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] 错误 2
make: *** [all] 错误 2

-----------------------------------------------------------------------------------------------------------------
I don't know how to fix it.......

**Comment by stevenlovegrove** [comment]
What compiler are you using? It looks like C++11 hasn't been correctly enabled in your build.

**Comment by Shunying** [comment]
Hi Steven I am using cmake 2.8.12 on ubuntu 14.04. I have also tried to add extra cxx flags indicating that c++11 should be used but it unfortunately still fails with other errors. In order to get quick results I just switch to an older version.

**Comment by stevenlovegrove** [comment]
Pangolin has since upgraded to C++17 and I would expect this problem is too old to be relevant so I will close. Please reopen if anyone encounters it again.
