### ISSUE TITLE
points overlapping

### ISSUE THREAD

**Issue by kemfic1** [stevenlovegrove/Pangolin#452]
I'm getting this issue where points further away are overlapping/covering the closer points. Any idea on how I can fix this?

[Here's the code I'm using.](https://github.com/kemfic1/fake-stereo/blob/master/pair_vis.py)

![screenshot from 2018-11-29 12-33-25](https://user-images.githubusercontent.com/16313623/49240583-86cc8700-f3d3-11e8-83fb-434c8db5d957.png)

**Comment by stevenlovegrove** [comment]
You probably want to enable depth testing:
gl.glEnable(GL_DEPTH_TEST)

**Comment by kemfic1** [comment]
thanks, that fixed it
