### ISSUE TITLE
error: call to deleted constructor of 'pangolin::TypedImage'

### ISSUE THREAD

**Issue by ihpdep** [stevenlovegrove/Pangolin#458]
Hi, I met a problem with pangolin::TypedImage. Basically, I want to pass it through the functions, like this:
`
void fool(const pangolin::TypedImage& input){

    std::vector<pangolin::TypedImage> inBuffers;

    inBuffers.push_back(input);

}
`
and I got the following errors

> 
In file included from /Users/liyang/Desktop/Fusion/fusion.cpp:5:
In file included from /Users/liyang/Desktop/Fusion/fusion.h:10:
In file included from /Users/liyang/Desktop/Fusion/Utilities/../utilities.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:266:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__bit_reference:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:643:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1805:31: error: call to deleted constructor of 'pangolin::TypedImage'
            ::new((void*)__p) _Up(_VSTD::forward<_Args>(__args)...);
                              ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1715:18: note: in instantiation of function template specialization 'std::__1::allocator<pangolin::TypedImage>::construct<pangolin::TypedImage, const pangolin::TypedImage &>' requested here
            {__a.construct(__p, _VSTD::forward<_Args>(__args)...);}
                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1561:14: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<pangolin::TypedImage> >::__construct<pangolin::TypedImage, const pangolin::TypedImage &>' requested here
            {__construct(__has_construct<allocator_type, _Tp*, _Args...>(),
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:1593:25: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<pangolin::TypedImage> >::construct<pangolin::TypedImage, const pangolin::TypedImage &>' requested here
        __alloc_traits::construct(this->__alloc(),
                        ^
/Users/liyang/Desktop/Fusion/fusion.cpp:37:15: note: in instantiation of member function 'std::__1::vector<pangolin::TypedImage, std::__1::allocator<pangolin::TypedImage> >::push_back' requested here
    inBuffers.push_back(input);
              ^
/usr/local/lib/cmake/Pangolin/../../../include/pangolin/image/typed_image.h:70:5: note: 'TypedImage' has been explicitly marked deleted here
    TypedImage( const TypedImage& other ) = delete;
    ^
1 error generated.

I am quite new to the c++11, is there any specific method I should use to pass the image? Thanks.

**Comment by ihpdep** [comment]
Also, can't do this:
`
    pangolin::TypedImage input = pangolin::LoadImage(filename);
    //cImage filtered_depth(depth.getW(),depth.getH());
    std::vector<pangolin::TypedImage> inBuffers;
    //inBuffers.push_back(pangolin::LoadImage(filename));
    inBuffers.push_back(input);
`

Same error comes up as the previous one.

**Comment by stevenlovegrove** [comment]
TypedImage isn't copy-constructable but you can move it into your container if you like. Something along the lines of:

    std::vector<pangolin::TypedImage> inBuffers;
    inBuffers.emplace_back(pangolin::LoadImage(filename));

or

    pangolin::TypedImage input = pangolin::LoadImage(filename);
    std::vector<pangolin::TypedImage> inBuffers;
    inBuffers.push_back(std::move(input));

Note that after the second example, `input` will be invalid. It works this way to make it more difficult to accidentally copy image data which is an expensive operation.

**Comment by nmerrill67** [comment]
I don't see why this is necessary. In fact, TypedImage just stores a pointer, so there is no way to copy the underlying image data unless memcpy or similar is called. I think it would be a lot more convenient for this to act like OpenCV or NumPy, where the TypedImage reference could be copied but the two references point to the same image data.

**Comment by NikolausDemmel** [comment]
`TypedImage` owns the data. If you want a reference, you can use the `Image` class.
