### ISSUE TITLE
Add textInput

### ISSUE THREAD

**Issue by PierBJX** [stevenlovegrove/Pangolin#459]
Hi,

I would like to use [textInput](http://docs.ros.org/fuerte/api/pangolin_wrapper/html/structpangolin_1_1TextInput.html) and I don't really know how to do.
Indeed, I am using what is in ORB SLAM2 and I am trying to add a text input in the panel.
```
    pangolin::CreatePanel("menu").SetBounds(0.0, 1.0, 0.0, pangolin::Attach::Pix(175));
    pangolin::Var<bool> menuFollowCamera("menu.Follow Camera", true, true);
    pangolin::Var<bool> menuShowPoints("menu.Show Points", true, true);
    pangolin::Var<bool> menuShowKeyFrames("menu.Show KeyFrames", true, true);
    pangolin::Var<bool> menuShowGraph("menu.Show Graph", true, true);
    pangolin::Var<bool> menuLocalizationMode("menu.Localization Mode", mbReuseMap, true);
    pangolin::Var<bool> menuReset("menu.Reset", false, false);
```

So what I tried is just to add this line next to it:
`    pangolin::TextInput test("test");`

Looking at the doc, I have to add a variable in the constructor __Var & | tv_ . I don't know how to do it...

Thanks

**Comment by stevenlovegrove** [comment]
pangolin::Var<std::string> test("menu.Test", "Hello World");

Pangolin's text input is not very mature so there is no carat, but if you click inside the box and type it will show up.
