### ISSUE TITLE
Uvc.cpp failing

### ISSUE THREAD

**Issue by mihaibujanca** [stevenlovegrove/Pangolin#46]
I have installed FFMpeg (shared libraries), DC1394, the latest libuvc, libjpeg, libpng. Also CMake, OpenGL, Glut and boost.

When trying to execute make install, I am getting the following error:

<code>/home/cor/Pangolin/src/video/uvc.cpp: In member function ‘virtual bool pangolin::UvcVideo::GrabNext(unsigned char*, bool)’:
/home/cor/Pangolin/src/video/uvc.cpp:120:53: error: ‘uvc_get_frame’ was not declared in this scope
     uvc_error_t err = uvc_get_frame(devh_, &frame, 0);
                                                     ^
make[2]: *** [src/CMakeFiles/pangolin.dir/video/uvc.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2
</code>

I've been digging around for a while, but can't get what the problem is, I reinstalled libuvc from the source given in the README, but the issue still appears.

**Comment by stevenlovegrove** [comment]
It's possible that the API to libuvc has changed. You could try checking out an older version. Otherwise, unless you need to use a UVC camera, you can safely tell Pangolin not to use the library by blanking the libuvc library and include entries in cmake-gui / ccmake.

**Comment by stevenlovegrove** [comment]
This was actually fixed in commit 7062ec1b76b0c257cba973a32e8c01922a2cb524. I'm sorry that I missed recommending you try the devel branch.
