### ISSUE TITLE
Make error 

### ISSUE THREAD

**Issue by liushuangliuliu** [stevenlovegrove/Pangolin#462]
make[2]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libGL.so', needed by `src/libpangolin.so'.  Stop.
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2
how can i solve the problem,please reply to me,thanks.

**Comment by stevenlovegrove** [comment]
Perhaps you've installed a new graphics driver or something since running cmake? You should try deleting the build directory and re-configuring.

**Comment by 473867143** [comment]
px4@eason:~/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/build$ make
Scanning dependencies of target pangolin
[  0%] Building CXX object src/CMakeFiles/pangolin.dir/utils/file_extension.cpp.o
[  1%] Building CXX object src/CMakeFiles/pangolin.dir/utils/sigstate.cpp.o
[  2%] Building CXX object src/CMakeFiles/pangolin.dir/utils/file_utils.cpp.o
[  3%] Building CXX object src/CMakeFiles/pangolin.dir/utils/timer.cpp.o
[  4%] Building CXX object src/CMakeFiles/pangolin.dir/utils/threadedfilebuf.cpp.o
[  5%] Building CXX object src/CMakeFiles/pangolin.dir/utils/uri.cpp.o
[  6%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io.cpp.o
[  6%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_raw.cpp.o
[  7%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_packed12bit.cpp.o
[  8%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_tga.cpp.o
[  9%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_lz4.cpp.o
[ 10%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_pango.cpp.o
[ 11%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_jpg.cpp.o
[ 12%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_png.cpp.o
[ 12%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_zstd.cpp.o
[ 13%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_exr.cpp.o
[ 14%] Building CXX object src/CMakeFiles/pangolin.dir/image/pixel_format.cpp.o
[ 15%] Building CXX object src/CMakeFiles/pangolin.dir/image/image_io_ppm.cpp.o
[ 16%] Building CXX object src/CMakeFiles/pangolin.dir/log/packetstream_reader.cpp.o
[ 17%] Building CXX object src/CMakeFiles/pangolin.dir/log/packetstream.cpp.o
[ 18%] Building CXX object src/CMakeFiles/pangolin.dir/log/packet.cpp.o
[ 18%] Building CXX object src/CMakeFiles/pangolin.dir/log/playback_session.cpp.o
[ 19%] Building CXX object src/CMakeFiles/pangolin.dir/log/packetstream_writer.cpp.o
[ 20%] Building CXX object src/CMakeFiles/pangolin.dir/geometry/geometry.cpp.o
[ 21%] Building CXX object src/CMakeFiles/pangolin.dir/geometry/glgeometry.cpp.o
[ 22%] Building CXX object src/CMakeFiles/pangolin.dir/geometry/geometry_ply.cpp.o
[ 23%] Building CXX object src/CMakeFiles/pangolin.dir/geometry/tinyobj.cpp.o
[ 23%] Building CXX object src/CMakeFiles/pangolin.dir/geometry/geometry_obj.cpp.o
[ 24%] Building CXX object src/CMakeFiles/pangolin.dir/gl/glchar.cpp.o
[ 25%] Building CXX object src/CMakeFiles/pangolin.dir/gl/gltexturecache.cpp.o
[ 26%] Building CXX object src/CMakeFiles/pangolin.dir/gl/glpangoglu.cpp.o
[ 27%] Building CXX object src/CMakeFiles/pangolin.dir/gl/gltext.cpp.o
[ 28%] Building CXX object src/CMakeFiles/pangolin.dir/gl/gldraw.cpp.o
[ 29%] Building CXX object src/CMakeFiles/pangolin.dir/gl/glfont.cpp.o
In file included from /home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/glfont.cpp:44:0:
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:4719:15: warning: ‘int stbtt_BakeFontBitmap(const unsigned char*, int, float, unsigned char*, int, int, int, int, stbtt_bakedchar*)’ defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_BakeFontBitmap(const unsigned char *data, int offset,
               ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:3674:16: warning: ‘void stbtt_GetBakedQuad(const stbtt_bakedchar*, int, int, int, float*, float*, stbtt_aligned_quad*, int)’ defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_GetBakedQuad(const stbtt_bakedchar *chardata, int pw, int ph, int char_index,
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:3772:15: warning: ‘int stbtt_PackBegin(stbtt_pack_context*, unsigned char*, int, int, int, int, void*)’ defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_PackBegin(stbtt_pack_context *spc, unsigned char *pixels, int pw, int ph, int 
               ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:3803:16: warning: ‘void stbtt_PackEnd(stbtt_pack_context*)’ defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_PackEnd  (stbtt_pack_context *spc)
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:4133:15: warning: ‘int stbtt_PackFontRange(stbtt_pack_context*, const unsigned char*, int, float, int, int, stbtt_packedchar*)’ defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_PackFontRange(stbtt_pack_context *spc, const unsigned char *fontdata, int font
               ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:3809:16: warning: ‘void stbtt_PackSetOversampling(stbtt_pack_context*, unsigned int, unsigned int)’ defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_PackSetOversampling(stbtt_pack_context *spc, unsigned int h_oversample, unsig
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:4145:16: warning: ‘void stbtt_GetPackedQuad(const stbtt_packedchar*, int, int, int, float*, float*, stbtt_aligned_quad*, int)’ defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_GetPackedQuad(const stbtt_packedchar *chardata, int pw, int ph, int char_inde
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:4731:15: warning: ‘int stbtt_GetNumberOfFonts(const unsigned char*)’ defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_GetNumberOfFonts(const unsigned char *data)
               ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:2564:16: warning: ‘void stbtt_GetFontVMetrics(const stbtt_fontinfo*, int*, int*, int*)’ defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_GetFontVMetrics(const stbtt_fontinfo *info, int *ascent, int *descent, int *l
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:2571:16: warning: ‘int stbtt_GetFontVMetricsOS2(const stbtt_fontinfo*, int*, int*, int*)’ defined but not used [-Wunused-function]
 STBTT_DEF int  stbtt_GetFontVMetricsOS2(const stbtt_fontinfo *info, int *typoAscent, int *typoDesc
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:2582:16: warning: ‘void stbtt_GetFontBoundingBox(const stbtt_fontinfo*, int*, int*, int*, int*)’ defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_GetFontBoundingBox(const stbtt_fontinfo *info, int *x0, int *y0, int *x1, int
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:2559:16: warning: ‘void stbtt_GetCodepointHMetrics(const stbtt_fontinfo*, int, int*, int*)’ defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_GetCodepointHMetrics(const stbtt_fontinfo *info, int codepoint, int *advanceW
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:1590:15: warning: ‘int stbtt_GetCodepointBox(const stbtt_fontinfo*, int, int*, int*, int*, int*)’ defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_GetCodepointBox(const stbtt_fontinfo *info, int codepoint, int *x0, int *y0, i
               ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:1595:15: warning: ‘int stbtt_IsGlyphEmpty(const stbtt_fontinfo*, int)’ defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_IsGlyphEmpty(const stbtt_fontinfo *info, int glyph_index)
               ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:1538:15: warning: ‘int stbtt_GetCodepointShape(const stbtt_fontinfo*, int, stbtt_vertex**)’ defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_GetCodepointShape(const stbtt_fontinfo *info, int unicode_codepoint, stbtt_ver
               ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:2602:16: warning: ‘void stbtt_FreeShape(const stbtt_fontinfo*, stbtt_vertex*)’ defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_FreeShape(const stbtt_fontinfo *info, stbtt_vertex *v)
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:3523:16: warning: ‘void stbtt_FreeBitmap(unsigned char*, void*)’ defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_FreeBitmap(unsigned char *bitmap, void *userdata)
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:3612:26: warning: ‘unsigned char* stbtt_GetCodepointBitmap(const stbtt_fontinfo*, float, float, int, int*, int*, int*, int*)’ defined but not used [-Wunused-function]
 STBTT_DEF unsigned char *stbtt_GetCodepointBitmap(const stbtt_fontinfo *info, float scale_x, float
                          ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:3617:16: warning: ‘void stbtt_MakeCodepointBitmap(const stbtt_fontinfo*, unsigned char*, int, int, int, float, float, int)’ defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_MakeCodepointBitmap(const stbtt_fontinfo *info, unsigned char *output, int ou
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:3602:16: warning: ‘void stbtt_MakeCodepointBitmapSubpixelPrefilter(const stbtt_fontinfo*, unsigned char*, int, int, int, float, float, float, float, int, int, float*, float*, int)’ defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_MakeCodepointBitmapSubpixelPrefilter(const stbtt_fontinfo *info, unsigned cha
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:2640:16: warning: ‘void stbtt_GetCodepointBitmapBox(const stbtt_fontinfo*, int, float, float, int*, int*, int*, int*)’ defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_GetCodepointBitmapBox(const stbtt_fontinfo *font, int codepoint, float scale_
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:3568:26: warning: ‘unsigned char* stbtt_GetGlyphBitmap(const stbtt_fontinfo*, float, float, int, int*, int*, int*, int*)’ defined but not used [-Wunused-function]
 STBTT_DEF unsigned char *stbtt_GetGlyphBitmap(const stbtt_fontinfo *info, float scale_x, float sca
                          ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:4549:16: warning: ‘void stbtt_FreeSDF(unsigned char*, void*)’ defined but not used [-Wunused-function]
 STBTT_DEF void stbtt_FreeSDF(unsigned char *bitmap, void *userdata)
                ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:4544:27: warning: ‘unsigned char* stbtt_GetCodepointSDF(const stbtt_fontinfo*, float, int, int, unsigned char, float, int*, int*, int*, int*)’ defined but not used [-Wunused-function]
 STBTT_DEF unsigned char * stbtt_GetCodepointSDF(const stbtt_fontinfo *info, float scale, int codep
                           ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:4741:15: warning: ‘int stbtt_FindMatchingFont(const unsigned char*, const char*, int)’ defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_FindMatchingFont(const unsigned char *fontdata, const char *name, int flags)
               ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:4746:15: warning: ‘int stbtt_CompareUTF8toUTF16_bigendian(const char*, int, const char*, int)’ defined but not used [-Wunused-function]
 STBTT_DEF int stbtt_CompareUTF8toUTF16_bigendian(const char *s1, int len1, const char *s2, int len
               ^
/home/px4/Desktop/Eason-mavros-gazebo/SLAM/Pangolin/Pangolin/src/gl/stb_truetype.h:4606:23: warning: ‘const char* stbtt_GetFontNameString(const stbtt_fontinfo*, int*, int, int, int, int)’ defined but not used [-Wunused-function]
 STBTT_DEF const char *stbtt_GetFontNameString(const stbtt_fontinfo *font, int *length, int platfor
                       ^
[ 29%] Building CXX object src/CMakeFiles/pangolin.dir/display/display.cpp.o
[ 30%] Building CXX object src/CMakeFiles/pangolin.dir/display/window_factory.cpp.o
[ 31%] Building CXX object src/CMakeFiles/pangolin.dir/display/view.cpp.o
[ 32%] Building CXX object src/CMakeFiles/pangolin.dir/display/viewport.cpp.o
[ 33%] Building CXX object src/CMakeFiles/pangolin.dir/display/opengl_render_state.cpp.o
[ 34%] Building CXX object src/CMakeFiles/pangolin.dir/display/image_view.cpp.o
[ 35%] Building CXX object src/CMakeFiles/pangolin.dir/handler/handler_glbuffer.cpp.o
[ 35%] Building CXX object src/CMakeFiles/pangolin.dir/handler/handler_image.cpp.o
[ 36%] Building CXX object src/CMakeFiles/pangolin.dir/handler/handler.cpp.o
[ 37%] Building CXX object src/CMakeFiles/pangolin.dir/plot/datalog.cpp.o
[ 38%] Building CXX object src/CMakeFiles/pangolin.dir/plot/plotter.cpp.o
[ 39%] Building CXX object src/CMakeFiles/pangolin.dir/var/vars.cpp.o
[ 40%] Building CXX object src/CMakeFiles/pangolin.dir/var/input_record_repeat.cpp.o
[ 41%] Building CXX object src/CMakeFiles/pangolin.dir/display/widgets/widgets.cpp.o
[ 41%] Building CXX object src/CMakeFiles/pangolin.dir/video/video_output.cpp.o
[ 42%] Building CXX object src/CMakeFiles/pangolin.dir/video/video.cpp.o
[ 43%] Building CXX object src/CMakeFiles/pangolin.dir/video/stream_encoder_factory.cpp.o
[ 44%] Building CXX object src/CMakeFiles/pangolin.dir/video/video_output_interface_factory.cpp.o
[ 45%] Building CXX object src/CMakeFiles/pangolin.dir/video/video_interface_factory.cpp.o
[ 46%] Building CXX object src/CMakeFiles/pangolin.dir/video/video_input.cpp.o
[ 47%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/test.cpp.o
[ 47%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/images.cpp.o
[ 48%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/images_out.cpp.o
[ 49%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/split.cpp.o
[ 50%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/truncate.cpp.o
[ 51%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/pvn.cpp.o
[ 52%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/pango.cpp.o
[ 53%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/pango_video_output.cpp.o
[ 53%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/debayer.cpp.o
[ 54%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/shift.cpp.o
[ 55%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/mirror.cpp.o
[ 56%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/unpack.cpp.o
[ 57%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/pack.cpp.o
[ 58%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/join.cpp.o
[ 59%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/merge.cpp.o
[ 59%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/json.cpp.o
[ 60%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/thread.cpp.o
[ 61%] Building CXX object src/CMakeFiles/pangolin.dir/tools/video_viewer.cpp.o
[ 62%] Building CXX object src/CMakeFiles/pangolin.dir/display/device/display_wayland.cpp.o
[ 63%] Building CXX object src/CMakeFiles/pangolin.dir/display/device/display_x11.cpp.o
[ 64%] Building CXX object src/CMakeFiles/pangolin.dir/utils/posix/shared_memory_buffer.cpp.o
[ 65%] Building CXX object src/CMakeFiles/pangolin.dir/utils/posix/condition_variable.cpp.o
[ 65%] Building CXX object src/CMakeFiles/pangolin.dir/utils/posix/semaphore.cpp.o
[ 66%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/firewire.cpp.o
[ 67%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/deinterlace.cpp.o
[ 68%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/v4l.cpp.o
[ 69%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/openni.cpp.o
[ 70%] Building CXX object src/CMakeFiles/pangolin.dir/fonts.cpp.o
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by 'src/libpangolin.so'.  Stop.
CMakeFiles/Makefile2:135: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

I have the same question?how can i solve?thank u.
@stevenlovegrove @liushuangliuliu

**Comment by Ace-rui** [comment]
I have the same question. Have you solved it? Please help me. Thank you.
@stevenlovegrove  @473867143

**Comment by ahundt** [comment]
I'm able to reproduce this problem as well.

**Comment by ahundt** [comment]
This worked for me as a manual workaround since an update to ubuntu or nvidia drivers appears to have updated my libGL but left a dead simlink:

```
sudo rm /usr/lib/x86_64-linux-gnu/libGL.so
sudo ln -s libGL.so.1 /usr/lib/x86_64-linux-gnu/libGL.so
```

These instructions are helpful:
https://github.com/RobotLocomotion/drake/issues/2087#issue-148166827


```
       
costar@ubuntu|~/src/costar_visual_stacking on combined_model_weights!?                                                          
± ls /usr/lib/x86_64-linux-gnu/libGL.so                                                                     
/usr/lib/x86_64-linux-gnu/libGL.so                                                                   
costar@ubuntu|~/src/costar_visual_stacking on combined_model_weights!?                              
± ls /usr/lib/x86_64-linux-gnu/libGL.so -alh                                                                         
lrwxrwxrwx 1 root root 14 May 10 08:17 /usr/lib/x86_64-linux-gnu/libGL.so -> libGL.so.1.0.0    
```

**Comment by ngthanhtin** [comment]
I still have not fixed the problem even I have tried @ahundt 's approach
