### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by la735681253** [stevenlovegrove/Pangolin#466]
[ 77%] Linking CXX executable VideoJsonTransform
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libEGL.so：对‘mir_presentation_chain_is_valid@MIR_CLIENT_0.26.1’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libGL.so：对‘drmGetDevices2’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libEGL.so：对‘gbm_bo_create_with_modifiers’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libEGL.so：对‘mir_render_surface_get_presentation_chain@MIR_CLIENT_DETAIL_private_buffer_semantics’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libEGL.so：对‘mir_buffer_get_height@MIR_CLIENT_0.26.1’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libEGL.so：对‘gbm_bo_get_bpp’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libEGL.so：对‘mir_connection_request_extension@MIR_CLIENT_0.26’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libEGL.so：对‘mir_buffer_get_width@MIR_CLIENT_0.26.1’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libEGL.so：对‘mir_render_surface_get_size@MIR_CLIENT_DETAIL_private_buffer_semantics’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libEGL.so：对‘mir_presentation_chain_set_mode@MIR_CLIENT_DETAIL_private_buffer_semantics’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libEGL.so：对‘mir_presentation_chain_submit_buffer@MIR_CLIENT_0.26.1’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libGL.so：对‘drmGetDeviceNameFromFd2’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libEGL.so：对‘mir_render_surface_is_valid@MIR_CLIENT_DETAIL_private_buffer_semantics’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libGL.so：对‘drmGetDevice2’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libEGL.so：对‘mir_buffer_release@MIR_CLIENT_0.26.1’未定义的引用
collect2: error: ld returned 1 exit status
tools/VideoJson/CMakeFiles/VideoJsonTransform.dir/build.make:117: recipe for target 'tools/VideoJson/VideoJsonTransform' failed
make[2]: *** [tools/VideoJson/VideoJsonTransform] Error 1
CMakeFiles/Makefile2:434: recipe for target 'tools/VideoJson/CMakeFiles/VideoJsonTransform.dir/all' failed
make[1]: *** [tools/VideoJson/CMakeFiles/VideoJsonTransform.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by la735681253** [comment]
please help me

**Comment by stevenlovegrove** [comment]
I'm sorry, I can't tell what's happening here.

**Comment by gaoxiang12** [comment]
seems you are missing libglew, try sudo apt-get install libglew-dev freeglut3-dev.

**Comment by LZMHIT** [comment]
I have another with compling.
   when I run Cmake .. it is ok, but when I run make, I get this error:
file:///home/isap/Pictures/Screenshot%202019-01-26%2020:17:00.png
I don't know why, can anyone give me a favor?
