### ISSUE TITLE
Remove / detach variable

### ISSUE THREAD

**Issue by NikolausDemmel** [stevenlovegrove/Pangolin#472]
For `pangolin::Var` objects and in particular "attached" variables (`pangolin::Var<...>::Attach( ... )`), is there a way to remove / detach them?

One use case is to remove elements from the GUI, which is important in particular if the object the was "attached" to goes out of scope while the GUI is still running.

**Comment by stevenlovegrove** [comment]
Unfortunately there is not a current way to do so. There is this old PR (https://github.com/stevenlovegrove/Pangolin/pull/123) but it is now outdated and may require a little effort to merge.

**Comment by NikolausDemmel** [comment]
Thanks, I'll have a look.

I'll leave this issue open until #123 or similar is merged (or else feel free to close it at will).

**Comment by XunshanMan** [comment]
I thinks it's a very useful function too.
I'd like to keep watching this...

**Comment by stevenlovegrove** [comment]
84569fa5ec75b74b9b79b24012dda2a70ca4ac26 landed which now supports this. There are currently no examples but they are included in the new Var test suite. Essentially usage is

```
// Create or attach a Var as usual (new attach syntax prevents you having to enter the type)
int x;
pangolin::AttachVar("ui.x", x);

// And remove by a reference to the attached Var, or by its name
pangolin::RemoveVar(x);
or
pangolin::DetachVarByName("ui.x");
```

Lifetime is interesting - I used the wording `Detach` to emphasize that the variable isn't being deleted but just removed from the global Var index. This means existing references to the Var will continue to refer to the same underlying memory, but any newly instanced variables with the same name will create and share a new underlying variable. GUI elements etc respect the removal by registering for the removal event with `pangolin::VarState::I().RegisterForVarEvents(...)`
