### ISSUE TITLE
Stack around the variable 'T_wc' was corrupted

### ISSUE THREAD

**Issue by bakelew** [stevenlovegrove/Pangolin#480]
I get an exception saying "Run-Time Check Failure #2 - Stack around the variable 'T_wc' was corrupted." and programs breaks at line 185 of handler.cpp

Error happens when clicking into the pangolin window (triggering the handler).

Found using the vcpkg version of pangolin VS 2017 x64 Debug.

Possibly caused by the call to LieApplySO3 which seems to be expecting a 3x3 array, but being passed a 3x4 array?

This error does not occur in release mode.

**Comment by stevenlovegrove** [comment]
Thanks for the info. That 3x4 matrix is column major and the first 3x3 elements are the rotation matrix, so that should be okay. Not sure of the cause...

**Comment by stevenlovegrove** [comment]
If you can reproduce this on the master branch, please reopen ideally with a minimal test case. I can't reproduce on my own Windows build.
