### ISSUE TITLE
What is the meaning of this TODO task: "glPixelStorei(GL_PACK_ALIGNMENT, 1); // TODO: Avoid this?"

### ISSUE THREAD

**Issue by fulkast** [stevenlovegrove/Pangolin#481]
As seen here: https://github.com/stevenlovegrove/Pangolin/blob/0d676304fa8fb8f83d3b4224d550e6da7e3c9e52/src/display/display.cpp#L410

**Comment by stevenlovegrove** [comment]
:) It's frowned upon to change OpenGL state in a function call and this function has side-effects.

In reality, very few people would care (unless you're dealing with padded images), which is why this hasn't been removed yet. Ideally the state would be restored before the function exits.
