### ISSUE TITLE
Draw a selected rectangle on the Handler3D

### ISSUE THREAD

**Issue by qiuyuanWang** [stevenlovegrove/Pangolin#485]
Hi, all,
   I want to draw a selected rectangle on the view, Handler3D. I knew that blend technology can do this. I can draw a 3D view first, and then draw an ImageView view. The image has 4 channels and the last channel control the transparency. So, we draw a frame of a rectangle on the image to complete this feature.
  I have tried before, but currently, I don't know how to implement this. The main code is shown below:
Main{

  pangolin::View& d_cam = pangolin::Display("cam")
      .SetBounds(0,1.0f,0,1.0f,-640/480.0)
      .SetHandler(new pangolin::Handler3D(s_cam));
 pangolin::View& d_image = pangolin::Display("image")
      .SetBounds(0, 1.0f, 0, 1.0f, -640 / 480.0);

  glEnable(GL_BLEND);
  glBlendFunc(GL_ZERO, GL_ONE);

  while(true){
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    d_cam.Activate(s_cam);

    glColor3f(1.0,1.0,1.0);
    pangolin::glDrawColouredCube();

    //Set some random image data and upload to GPU
    DrawRect(imageArray);
    imageTexture.Upload(imageArray,GL_RGB,GL_UNSIGNED_BYTE);

    //display the image
    d_image.Activate();
    glColor4f(1.0,1.0,1.0,1.0);
    imageTexture.RenderToViewport();

    pangolin::FinishFrame();
   }
}

Can anyone give me a clue? thanks.

**Comment by stevenlovegrove** [comment]
Are you trying to allow a user to select a region over an image? If so, you could use the ImageView:
https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/display/image_view.h
