### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by Ericgeese** [stevenlovegrove/Pangolin#486]
Settings:
Ubuntu 18.04 && Nvidia graphic drivers 390
Error Messages:
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
src/CMakeFiles/pangolin.dir/build.make:2242: recipe for target 'src/libpangolin.so' failed
make[2]: *** [src/libpangolin.so] Error 1
CMakeFiles/Makefile2:168: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

I have to build a softlink between /usr/lib/x86_64-linux-gnu/libEGL.so and /usr/lib/x86_64-linux-gnu/libEGL.so.1 to solve it.
But why?

**Comment by stevenlovegrove** [comment]
Hmm, I'm not sure.

**Comment by christian-rauch** [comment]
@Ericgeese EGL should only be needed when building with Wayland support or when trying to build the `x11_egl` branch. The issue also appears after CMake ran, i.e. cmake found EGL but the linker cannot find the corresponding libs.

Do you have all or any of the packages `libwayland-dev`, `libxkbcommon-dev`, `libegl1-mesa-dev` installed?

**Comment by Ericgeese** [comment]
thanks, I found libegl1-mesa-dev missed.

**Comment by match08** [comment]
cannot find -lEGL
