### ISSUE TITLE
Can't build Pangolin on OSX Mojave

### ISSUE THREAD

**Issue by osjacky430** [stevenlovegrove/Pangolin#496]
Hi, I follow the instruction on Pangolin readme.md, 

`git clone https://github.com/stevenlovegrove/Pangolin.git`
`cd Pangolin`
`mkdir build`
`cd build`
`cmake ..`
`cmake --build .`

But get the following errors

`Desktop/Pangolin/src/utils/file_utils.cpp:194:19: error: 'PATH_MAX' was not declared in this scope
     char abs_path[PATH_MAX];
                   ^~~~~~~~
Desktop/Pangolin/src/utils/file_utils.cpp:194:19: note: suggested alternative: 'INT8_MAX'
     char abs_path[PATH_MAX];
                   ^~~~~~~~
                   INT8_MAX
Desktop/Pangolin/src/utils/file_utils.cpp:195:32: error: 'abs_path' was not declared in this scope
     if (realpath(path.c_str(), abs_path)) {
                                ^~~~~~~~
Desktop/Pangolin/src/utils/file_utils.cpp:195:32: note: suggested alternative: 'path'
     if (realpath(path.c_str(), abs_path)) {
                                ^~~~~~~~
                                path`

PATH_MAX seems to be Linux system constant, what should I do?

**Comment by stevenlovegrove** [comment]
PATH_MAX is guarded by ifdef _UNIX_ on master. Thanks for reporting. If you still have problems you would need to figure out why _UNIX_ is defined (perhaps mingw or something?). Reopen if needed. Thanks!

**Comment by stevenlovegrove** [comment]
Edit: sorry - I miss-read and thought this was a problem you were having on Windows. I build on MacOS as my main system and haven't seen this. Let me know if you still experience this on master.
