### ISSUE TITLE
How to use  Pangolin to save  pointcloud map  ?

### ISSUE THREAD

**Issue by GentlemanCheng** [stevenlovegrove/Pangolin#497]
Hello, many work have used this great  library , when I run an  opensource slam, I don't  know  how to save the pointcloud map which was created by Pangolin. It only draw the map real-time, and not to save automatically. 
Can you remind  me how to process this problem ?
Looking forward your reply, Thank you very much !

**Comment by stevenlovegrove** [comment]
Pangolin doesn't have a built in feature for this, I'm afraid.
