### ISSUE TITLE
/usr/bin/ld: cannot find -lpython3.5m

### ISSUE THREAD

**Issue by ZhangXinNan** [stevenlovegrove/Pangolin#500]
```bash
[ 66%] Linking CXX shared library libpangolin.so
/usr/bin/ld: cannot find -lpython3.5m
collect2: error: ld returned 1 exit status
src/CMakeFiles/pangolin.dir/build.make:2761: recipe for target 'src/libpangolin.so' failed
make[2]: *** [src/libpangolin.so] Error 1
CMakeFiles/Makefile2:139: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by fulkast** [comment]
Looks like CMake has found python version 3.5 and knows to link against it, but it is not able to find the library at link time...

**Comment by afrancir** [comment]
I also have this issue, any solution?

[ 65%] Building CXX object src/CMakeFiles/pangolin.dir/fonts.cpp.o
[ 65%] Linking CXX shared library libpangolin.so
/usr/bin/ld: cannot find -lpython3.5m
collect2: error: ld returned 1 exit status
src/CMakeFiles/pangolin.dir/build.make:2794: recipe for target 'src/libpangolin.so' failed
make[2]: *** [src/libpangolin.so] Error 1
CMakeFiles/Makefile2:177: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fulkast** [comment]
May you post the output of running the following command in your terminal?

`pkg-config --libs python3`

**Comment by jianguda** [comment]
any progress?

**Comment by liabeaumont** [comment]
> May you post the output of running the following command in your terminal?
> 
> `pkg-config --libs python3`

Hi, I also got the same issue.
[ 65%] Linking CXX shared library libpangolin.so
/usr/bin/ld: cannot find -lpython3.5m
/usr/bin/ld: cannot find -lpython3.5m
collect2: error: ld returned 1 exit status
src/CMakeFiles/pangolin.dir/build.make:2828: recipe for target 'src/libpangolin.so' failed
make[2]: *** [src/libpangolin.so] Error 1
CMakeFiles/Makefile2:209: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

Add, after I run "pkg-config --libs python3", I got:

Package python3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `python3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'python3' found

**Comment by fulkast** [comment]
> Add, after I run "pkg-config --libs python3", I got:
> 
> Package python3 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `python3.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'python3' found

Looks like you don't have `python3`. Try installing it first.

**Comment by zParquet** [comment]
> > May you post the output of running the following command in your terminal?
> > `pkg-config --libs python3`
> 
> Hi, I also got the same issue.
> [ 65%] Linking CXX shared library libpangolin.so
> /usr/bin/ld: cannot find -lpython3.5m
> /usr/bin/ld: cannot find -lpython3.5m
> collect2: error: ld returned 1 exit status
> src/CMakeFiles/pangolin.dir/build.make:2828: recipe for target 'src/libpangolin.so' failed
> make[2]: *** [src/libpangolin.so] Error 1
> CMakeFiles/Makefile2:209: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
> make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
> Makefile:151: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> Add, after I run "pkg-config --libs python3", I got:
> 
> Package python3 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `python3.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'python3' found

Maybe python3 is in your environment, but -lpython3.5m has not installed yet.
Try this command(If python3.5 is already in your environment):
sudo apt install python3.5-dev
Then -lpython3.5m will be installed correctly.

**Comment by lukasschueler** [comment]
> > > May you post the output of running the following command in your terminal?
> > > `pkg-config --libs python3`
> > 
> > 
> > Hi, I also got the same issue.
> > [ 65%] Linking CXX shared library libpangolin.so
> > /usr/bin/ld: cannot find -lpython3.5m
> > /usr/bin/ld: cannot find -lpython3.5m
> > collect2: error: ld returned 1 exit status
> > src/CMakeFiles/pangolin.dir/build.make:2828: recipe for target 'src/libpangolin.so' failed
> > make[2]: *** [src/libpangolin.so] Error 1
> > CMakeFiles/Makefile2:209: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
> > make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
> > Makefile:151: recipe for target 'all' failed
> > make: *** [all] Error 2
> > Add, after I run "pkg-config --libs python3", I got:
> > Package python3 was not found in the pkg-config search path.
> > Perhaps you should add the directory containing `python3.pc'
> > to the PKG_CONFIG_PATH environment variable
> > No package 'python3' found
> 
> Maybe python3 is in your environment, but -lpython3.5m has not installed yet.
> Try this command(If python3.5 is already in your environment):
> sudo apt install python3.5-dev
> Then -lpython3.5m will be installed correctly.

This was really helpful, thank you!
