### ISSUE TITLE
undefined reference to PyUnicodeUCS4_AsUTF8String

### ISSUE THREAD

**Issue by ZhangXinNan** [stevenlovegrove/Pangolin#501]
```bash
[ 80%] Linking CXX executable VideoViewer
../../src/libpangolin.so: undefined reference to `PyUnicodeUCS4_AsUTF8String'
../../src/libpangolin.so: undefined reference to `PyUnicodeUCS4_DecodeUTF8'
../../src/libpangolin.so: undefined reference to `PyString_FromString'
../../src/libpangolin.so: undefined reference to `PyUnicodeUCS4_FromString'
../../src/libpangolin.so: undefined reference to `PyString_AsStringAndSize'
../../src/libpangolin.so: undefined reference to `PyString_Size'
../../src/libpangolin.so: undefined reference to `PyCObject_AsVoidPtr'
../../src/libpangolin.so: undefined reference to `Py_InitModule4_64'
../../src/libpangolin.so: undefined reference to `_Py_ZeroStruct'
../../src/libpangolin.so: undefined reference to `PyUnicodeUCS4_FromStringAndSize'
../../src/libpangolin.so: undefined reference to `PyUnicodeUCS4_AsEncodedString'
../../src/libpangolin.so: undefined reference to `PyInt_AsLong'
../../src/libpangolin.so: undefined reference to `PyInt_FromSize_t'
../../src/libpangolin.so: undefined reference to `PyString_AsString'
../../src/libpangolin.so: undefined reference to `PyInt_FromSsize_t'
../../src/libpangolin.so: undefined reference to `PyUnicodeUCS4_FromEncodedObject'
collect2: error: ld returned 1 exit status
tools/VideoViewer/CMakeFiles/VideoViewer.dir/build.make:102: recipe for target 'tools/VideoViewer/VideoViewer' failed
make[2]: *** [tools/VideoViewer/VideoViewer] Error 1
CMakeFiles/Makefile2:348: recipe for target 'tools/VideoViewer/CMakeFiles/VideoViewer.dir/all' failed
make[1]: *** [tools/VideoViewer/CMakeFiles/VideoViewer.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by fulkast** [comment]
This smells similar to this issue here:
https://github.com/pytorch/pytorch/issues/591

Hope this helps a bit

**Comment by zParquet** [comment]
I installed a Python2.7.14 and use this to replace the system's default python. Then I remove the 'build' directory and cmake, make, install again, and this bug never appears again. I guess this bug is because that the system's default python2 has some bugs, and has been fixed in the newest python version.

**Comment by saprrow** [comment]
> ```shell
> [ 80%] Linking CXX executable VideoViewer
> ../../src/libpangolin.so: undefined reference to `PyUnicodeUCS4_AsUTF8String'
> ../../src/libpangolin.so: undefined reference to `PyUnicodeUCS4_DecodeUTF8'
> ../../src/libpangolin.so: undefined reference to `PyString_FromString'
> ../../src/libpangolin.so: undefined reference to `PyUnicodeUCS4_FromString'
> ../../src/libpangolin.so: undefined reference to `PyString_AsStringAndSize'
> ../../src/libpangolin.so: undefined reference to `PyString_Size'
> ../../src/libpangolin.so: undefined reference to `PyCObject_AsVoidPtr'
> ../../src/libpangolin.so: undefined reference to `Py_InitModule4_64'
> ../../src/libpangolin.so: undefined reference to `_Py_ZeroStruct'
> ../../src/libpangolin.so: undefined reference to `PyUnicodeUCS4_FromStringAndSize'
> ../../src/libpangolin.so: undefined reference to `PyUnicodeUCS4_AsEncodedString'
> ../../src/libpangolin.so: undefined reference to `PyInt_AsLong'
> ../../src/libpangolin.so: undefined reference to `PyInt_FromSize_t'
> ../../src/libpangolin.so: undefined reference to `PyString_AsString'
> ../../src/libpangolin.so: undefined reference to `PyInt_FromSsize_t'
> ../../src/libpangolin.so: undefined reference to `PyUnicodeUCS4_FromEncodedObject'
> collect2: error: ld returned 1 exit status
> tools/VideoViewer/CMakeFiles/VideoViewer.dir/build.make:102: recipe for target 'tools/VideoViewer/VideoViewer' failed
> make[2]: *** [tools/VideoViewer/VideoViewer] Error 1
> CMakeFiles/Makefile2:348: recipe for target 'tools/VideoViewer/CMakeFiles/VideoViewer.dir/all' failed
> make[1]: *** [tools/VideoViewer/CMakeFiles/VideoViewer.dir/all] Error 2
> Makefile:149: recipe for target 'all' failed
> make: *** [all] Error 2
> ```

Change `include_directories("/usr/include/python2.7")` to to python3 lib like `include_directories("/usr/include/python3.6")`
It may help

**Comment by xlx552414534** [comment]
try this: delete build, then $conda deactivate, do the cmake commands again.
