### ISSUE TITLE
How to make Pangolin focus on camera ??

### ISSUE THREAD

**Issue by ParikaGoel** [stevenlovegrove/Pangolin#503]
I am working on a SLAM project. I want to make the viewer focus on the current position of the camera i.e. current camera and the reconstruction in its neighborhood should always be visible on the screen like as shown in this video https://youtu.be/j2ZNuBCr4SA?t=7.

I saw the ORB SLAM code for reference. They use the Follow() api to do that. I used the same thing but somehow my reconstruction goes out of the screen after some time. It seems like the viewer is focusing at some other point than the current position of the camera.

I am suspecting that maybe I am not computing the matrix Twc to be given as parameter to Follow() api correctly. (s_cam.Follow(Twc)).

Can you please help me to understand what exactly is the functionality of this matrix Twc and how should I calculate provided I have the current pose of the camera (SE3d matrix)

**Comment by ParikaGoel** [comment]
My problem is fixed. For anyone else facing the same problem, I just had to pass the current pose of the camera as Twc to the follow() api

**Comment by aserbremen** [comment]
@ParikaGoel I have the same problem as you. I would like to implement something like your youtube video. I am also looking at ORB SLAM 2 but cant wrap my head around the visualization yet. 

Can you give a minimal code example of how to achieve that? Or how you achieved to follow a moving coordinate frame in 3d space?

**Comment by Gautham-JS** [comment]
@aserbremen perhaps an year too late but if anyone else stumbles upon this, you need to convert your current Rotation matrix and translation vector that you have as a 4X4 pose transform as [R | t] with last row as [0 0 0 1]. If its a `cv::Mat` or `Eigen::Matrix<double,4,4>` , convert it to `pangolin::OpenGlMatrix` type and then pass it to `s_cam.Follow( );`.

**Comment by mascomen4** [comment]
@ParikaGoel hello! Does Twc stands for Transformation matrix from camera coordinates to world coordinates?  I'm sorry, may it's not an appropriate thread to ask. 

Thanks!

**Comment by stevenlovegrove** [comment]
@mascomen4 

> @ParikaGoel hello! Does Twc stands for Transformation matrix from camera coordinates to world coordinates? I'm sorry, may it's not an appropriate thread to ask.

Yes, you can read it as 'Transformation world from camera'
