### ISSUE TITLE
How to make sure Pangolin does not draw out of the screen ??

### ISSUE THREAD

**Issue by ParikaGoel** [stevenlovegrove/Pangolin#505]
How do I make sure that all my reconstruction is displayed inside the screen.

I am using pangolin::CreateWindowAndBind("Main", 1280, 720);

With this, as the camera progresses, it goes out of the screen. But I want to make sure that if the camera is about to go out of screen, pangolin resizes the window to fit the entire reconstruction within the window.

How do I achieve that ??

**Comment by ParikaGoel** [comment]
I tried changing the ModelViewMatrix to make this happen. 
Initially, my ModelViewMatrix is defined like below

cam = pangolin::OpenGlRenderState(
	    pangolin::ProjectionMatrix(w, h, 400, 400, w / 2.0, h / 2.0, 0.1,
	                               10000),
	    pangolin::ModelViewLookAt(15, 5, 10, 0, 0, 0, pangolin::AxisY));

I made an option in the pangolin gui -> birdEyeView . When this option is on, I change the ModelViewMatrix to below 

cam.SetModelViewMatrix(
                        pangolin::ModelViewLookAt(60, 20, 40, 0, 0, 0, pangolin::AxisY));

But the problem is ,when I select this option, gui zoomes out to fit everything on screen but then the gui is not interactive anymore. I can not rotate or zoom in or out of the reconstruction

**Comment by stevenlovegrove** [comment]
The GUI manipulates those matrices, so if you set them every frame in code, they will override whatever the GUI is trying to set. I don't quite understand your original problem - you may have to include a screenshot or something.
