### ISSUE TITLE
Fail to save a png image from GlTexture

### ISSUE THREAD

**Issue by hoangcuongbk80** [stevenlovegrove/Pangolin#508]
Hi,

Thanks for your work! I am struggling with the problem of saving a png image from GlTexture, the error is as following:

> libpng warning: Invalid bit depth in IHDR
> libpng error: Invalid IHDR data
> terminate called after throwing an instance of 'std::runtime_error'
> what():  PNG Error: Error during png creation.
> Aborted (core dumped)

**Comment by stevenlovegrove** [comment]
As the message says, perhaps you're trying to save a a texture whose format is not supported by PNG? You could try saving to a different type, like .exr or .pango
