### ISSUE TITLE
VideoViewer linking error

### ISSUE THREAD

**Issue by chaiein** [stevenlovegrove/Pangolin#509]
Scanning dependencies of target pangolin
[  1%] Building CXX object src/CMakeFiles/pangolin.dir/display/display.cpp.o
[  1%] Building CXX object src/CMakeFiles/pangolin.dir/video/video.cpp.o
[  2%] Building CXX object src/CMakeFiles/pangolin.dir/fonts.cpp.o
[  3%] Linking CXX shared library libpangolin.so
[ 72%] Built target pangolin
[ 73%] Linking CXX executable VideoViewer

/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libSM.so: undefined reference to `uuid_generate@UUID_1.0'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libSM.so: undefined reference to `uuid_unparse_lower@UUID_1.0'
collect2: error: ld returned 1 exit status
tools/VideoViewer/CMakeFiles/VideoViewer.dir/build.make:104: recipe for target 'tools/VideoViewer/VideoViewer' failed
make[2]: *** [tools/VideoViewer/VideoViewer] Error 1
CMakeFiles/Makefile2:291: recipe for target 'tools/VideoViewer/CMakeFiles/VideoViewer.dir/all' failed
make[1]: *** [tools/VideoViewer/CMakeFiles/VideoViewer.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

how to solve this issue?

**Comment by stevenlovegrove** [comment]
I've not seen that before - I have no idea where that would be coming from, I'm afraid.

**Comment by afrancir** [comment]
@chaiein were you able to solve it?

**Comment by rmvanarse** [comment]
@chaiein @afrancir Were you able to solve this issue?

**Comment by bitterengsci** [comment]
Same issue... Any idea??? QAQ

**Comment by bitterengsci** [comment]
By deleting "sudo rm /usr/local/nvidia/lib64/libGLdispatch.so.0", 

(maybe yours is not under /usr/local/nvidia/lib64/, find it yourself.)
some magic worked!!!!

~ credited to my genius colleague!

**Comment by jennyziyi-xu** [comment]
I am having the same issue. 
![Screen Shot 2021-05-22 at 4 24 16 PM](https://user-images.githubusercontent.com/56279639/119239879-2937d200-bb1a-11eb-8935-62ca3cec86aa.png) 


 @bitterengsci  I can't find any file named "libGLdispatch.so". Do you happen to know how to fix the problem another way? I am on Ubuntu 20.04.

**Comment by stevenlovegrove** [comment]
@jennyziyi-xu I think your issue is different and related to OpenEXR. Maybe https://github.com/stevenlovegrove/Pangolin/issues/649, but could be different. In any case, you can disable OpenEXR in cmake to avoid.

@afrancir Your issue is different again. Try disabling the depthsense driver. 

Closing out since this is quite old.

**Comment by stevenlovegrove** [comment]
@afrancir #227 is your issue
