### ISSUE TITLE
rendering a GlTexture over part of a View

### ISSUE THREAD

**Issue by tschmidt23** [stevenlovegrove/Pangolin#51]
There is already a GlTexture::RenderToViewport function allowing the caller to specify the texture coordinates such that one can render a subset of a texture over the entire active View (i.e. setting sq_tex), but there is no function allowing the caller to specify the vertex coordinates such that one can render an entire texture over a subset of the active View (i.e. setting sq_vert). 

I've needed this a few times and just written some external code to do it, but it might be useful to others to roll it into the library.

**Comment by stevenlovegrove** [comment]
The way I normally do it is to call
Viewport(x,y,w,h).Activate();
tex.RenderToViewport(...)
but it isn't super tidy. I think you're right that it would be convenient to have a method that allowed you to use your own coordinate system directly. I'll take a look sometime soon hopefully.
