### ISSUE TITLE
Whether Pangolin could be build in QNX?

### ISSUE THREAD

**Issue by lishuiyeqq** [stevenlovegrove/Pangolin#514]
I want to compile the Pangolin in QNX,whether  pangolin could be build in QNX?
Thanks a lot!

**Comment by stevenlovegrove** [comment]
I'm not familiar with QNX - I expect you would at a minimum require some CMake changes, but if it is a Unix flavor and has OpenGL, then you could probably get it to work. If it uses Wayland or X11, then it should be quite straight-forward.

**Comment by huyutao3550346** [comment]
@stevenlovegrove hi. In my qnx system, opengles_v2 and openesl is existing. By the way the graph frame in the qnx is called "screen". Is I should implement the display device interface with screen when we use Pangolin's GUI?
