### ISSUE TITLE
3D text orientation

### ISSUE THREAD

**Issue by phil0stine** [stevenlovegrove/Pangolin#515]
Can we control the orientation of a GLFont object? When rendering in 3D, it uses the model-view matrix to assert the orientation, but this could lead to the text being upside down.

**Comment by stevenlovegrove** [comment]
The following utility function takes care of this for you - (x,y,z)' specifies the top-left location in object coordinates. The text will be oriented and sized in screen space.

https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/gl/gltext.h#L62
