### ISSUE TITLE
LNK2001 and LNK2019 errors when ORB SLAM 2 compiling Visual Studio 2017 (Pangolin.lib))

### ISSUE THREAD

**Issue by OguzhanCiftci** [stevenlovegrove/Pangolin#529]
When building ORB SLAM 2 on Visual Studio 2017 Enterprise, 

pangolin.lib (my pangolin lib from a prebuilt repository)

I get like these errors;

- "LNK2001 unresolved external symbol __imp_glDisableClientState" on file "pangolin.lib(display.obj)"

- "LNK2001 unresolved external symbol __imp_glDisable" on file "pangolin.lib(gltext.obj)"

- "LNK2001 unresolved external symbol __imp_glDisable" on file "pangolin.lib(viewport.obj)"

**Comment by rlczddl** [comment]
have you sovle it?
