### ISSUE TITLE
make Error 

### ISSUE THREAD

**Issue by LIUMeng0823** [stevenlovegrove/Pangolin#532]
/home/meng/catkin_ws/ORB-SLAM2/Pangolin/src/video/drivers/uvc.cpp: In member function ‘virtual void pangolin::UvcVideo::Start()’:
/home/meng/catkin_ws/ORB-SLAM2/Pangolin/src/video/drivers/uvc.cpp:208:71: error: too few arguments to function ‘uvc_error_t uvc_stream_start(uvc_stream_handle_t*, void (*)(uvc_frame*, void*), void*, float, uint8_t)’
         uvc_error_t stream_err = uvc_stream_start(strm_, NULL, this, 0);
                                                                                                           ^
In file included from /home/meng/catkin_ws/ORB-SLAM2/Pangolin/include/pangolin/video/drivers/uvc.h:42:0,
                 from /home/meng/catkin_ws/ORB-SLAM2/Pangolin/src/video/drivers/uvc.cpp:29:
/usr/local/include/libuvc/libuvc.h:572:13: note: declared here
 uvc_error_t uvc_stream_start(uvc_stream_handle_t *strmh,
                   ^
src/CMakeFiles/pangolin.dir/build.make:2006: recipe for target 'src/CMakeFiles/pangolin.dir/video/drivers/uvc.cpp.o' failed
make[2]: *** [src/CMakeFiles/pangolin.dir/video/drivers/uvc.cpp.o] Error 1
CMakeFiles/Makefile2:136: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

I don't know what the error means, is there someone help me?

**Comment by limit79** [comment]
Change the version of Pangolin.Just try this older version: https://github.com/zzx2GH/Pangolin.
