### ISSUE TITLE
EGL init failed when running HelloPangolinOffscreen example

### ISSUE THREAD

**Issue by xuelin-chen** [stevenlovegrove/Pangolin#533]
I compiled and install Pangolin with EGL support (the cmake did find the EGL).

But when I tried to excute HelloPangolinOffscreen, this is the output:
EGL init failed
Cannot create EGL surface
Segmentation fault (core dumped)

Does anyone have a clue of how to fix that? I have been working for a long time to get it to work in a headless ubuntu server... Thanks!

**Comment by christian-rauch** [comment]
What OS and driver are you using?

**Comment by ChenXuelinCXL** [comment]
Ubuntu 18.04 with nvidia driver 418.56.

**Comment by christian-rauch** [comment]
I am not sure about running OpenGL inside a Docker container. Maybe you need to configure the container to forward OpenGL calls to your host GPU or something like this.

I am using Ubuntu 18.04 with Nvidia driver 430. Can you update the driver to version 430 (`sudo apt install nvidia-driver-430`)?
What is your host OS? Can you run the example there?

**Comment by ChenXuelinCXL** [comment]
Thanks for your quick reply:)

I just checked that the docker I am using supports OpenGL.
And unfortunately, I do not have the root permission to update the driver...

My host OS is ubuntu 16.04, maybe I should try it in my host OS to see if it works out.

Thanks!

**Comment by edoRemelli** [comment]
I am having the same issue @xuelin-chen, were you able to make HelloPangolinOffscreen work?

**Comment by xuelin-chen** [comment]
@edoRemelli sorry, no, I gave it up at the end...

**Comment by kacperkan** [comment]
I face the same issue and running `docker run --gpus all ...` worked (this specifies Nvidia runtime to be used and requires [nvidia-docker](https://github.com/NVIDIA/nvidia-docker))

**Comment by christian-rauch** [comment]
> I face the same issue and running `docker run --gpus all ...` worked (this specifies Nvidia runtime to be used and requires [nvidia-docker](https://github.com/NVIDIA/nvidia-docker))

Does it work natively outside of Docker?

Does the minimal example https://github.com/svenpilz/egl_offscreen_opengl work?

**Comment by kacperkan** [comment]
> Does it work natively outside of Docker?
I don't understand. Do you ask about Pangolin or about the example that you attached below? In both cases, these programs were created to work natively outside Docker.

> Does the minimal example https://github.com/svenpilz/egl_offscreen_opengl work?
No, I receive two errors:
- `make test` causes ` what():  EGL error 0x3005 at eglCreateContext`
- `make test_without_x11` causes `what():  EGL error 0x3001 at eglInitialize`
no matter whether I use `--gpus all` or not. However, these errors are different than those that I met while running Pangolin.

If you have any idea to fix it, I uploaded the used Dockerfile [here](https://github.com/kacperkan/egl_offscreen_opengl) so you can play with it.

In another project, I used Dockerfile that mimics access to the display [here](https://github.com/kacperkan/light-field-distance/blob/master/Dockerfile)

**Comment by christian-rauch** [comment]
> I don't understand. Do you ask about Pangolin or about the example that you attached below?

Both. I would like to know if you can run these two programs natively without Docker, i.e. on real hardware, so that we can infer if the program itself or the Docker environment is causing this issue.

I am not sure what you mean with:
>  In both cases, these programs were created to work natively outside Docker.

How is a program special to work outside Docker? Isn't Docker supposed to run any Linux program?

> No, I receive two errors:

Is this within Docker or natively on hardware? If with Docker, please run them natively.

Btw, you have to keep an empty line between quotes (`>`) and your responses.

**Comment by kacperkan** [comment]
> Btw, you have to keep an empty line between quotes (>) and your responses. 

Thanks, I haven't noticed that.

> How is a program special to work outside Docker? Isn't Docker supposed to run any Linux program?

You are right, I thought we assumed that the program works on a host machine perfectly fine but it doesn't on Docker.

> Both. I would like to know if you can run these two programs natively without Docker, i.e. on real hardware, so that we can infer if the program itself or the Docker environment is causing this issue.

In such a case, I am limited as @xuelin-chen, since I work on a remote server with no permission to install external dependencies (docker was preinstalled, and each user is automatically added to the `docker` group).

**Comment by christian-rauch** [comment]
> In such a case, I am limited as @xuelin-chen, since I work on a remote server with no permission to install external dependencies (docker was preinstalled, and each user is automatically added to the `docker` group).

You do not have to (and also probably should not) run it natively on the server. You can run it on any PC or VM to verify if it's an issue with the code or the Docker environment.
