### ISSUE TITLE
Is it time for a version bump yet? 

### ISSUE THREAD

**Issue by norlesh** [stevenlovegrove/Pangolin#538]
The Microsoft vcpkg build manager is limited to only installing specific versions and as a result Pangolin is trapped four years back at v0.5 and subsequently anything using the current repo is prevented from being added to vcpkg due to changes in the API.

**Comment by stevenlovegrove** [comment]
Sorry for the slow reply! I have bumped the version a few times since your comment, thanks! Feel free to prod me again if you need it in the future as well.
