### ISSUE TITLE
libpangolin.so:undefined reference to 'Imf_2_3::'

### ISSUE THREAD

**Issue by jsYangCode** [stevenlovegrove/Pangolin#540]
when i run cmake --build .  some error occur! as is shown bellow! can anyone help me, give me some advice? thank you very much!
![Screenshot from 2019-08-20 10-29-52](https://user-images.githubusercontent.com/34529308/63313321-9a8b9500-c336-11e9-9b7d-b6b87e9066f7.png)

**Comment by klintan** [comment]
Have you installed OpenEXR ?

Caveat right now: Pangolin seems to still rely on OpenEXR 2.3 and the latest version on Brew (Mac) is 2.4

**Comment by stevenlovegrove** [comment]
Unless you actually need OpenEXR for opening .exr files, you can disable this in CMake as a workaround (set the lib path to the empty string)

**Comment by potoo0** [comment]
Best way is remove `CMakeModules/FindOpenEXR.cmake`, if you don't need OpenEXR.

**Comment by stevenlovegrove** [comment]
Closing for now. Please reopen if still experiencing issues on master branch.
