### ISSUE TITLE
Doxygen target incorrect name

### ISSUE THREAD

**Issue by PushyamiKaveti** [stevenlovegrove/Pangolin#541]
I was trying to install documentation for Pangolin using "cmake --build . --target  doc". This was doing nothing. Later, realized that the custom target in CMakeLists.txt is actually named pangolin_doc. Please update either the cmakelists or Readme  for successful installation.

**Comment by stevenlovegrove** [comment]
Thanks for reporting and sorry for the slow reply! Since this issue I've removed the doxygen stuff all-together since it was not very useful and rarely used. You're better off using an IDE which can show the doxygen comments such as QtCreator or VSCode etc.  I'll close this out.
