### ISSUE TITLE
How to get CMake's ExternalProject_Add to work in Visual Studio (git-submodule problem) to build the required GLEW?

### ISSUE THREAD

**Issue by Algomorph** [stevenlovegrove/Pangolin#546]
Sorry to post an issue with a link, but the description of the issue here is both very good, specific, and lengthy: https://stackoverflow.com/questions/57998968/how-to-get-cmakes-externalproject-add-to-work-in-visual-studio-git-submodule-p

If anyone can provide any insight on how to resolve this, I would highly appreciate it.

**Comment by stevenlovegrove** [comment]
Are you running cmake from the git-bash shell?

**Comment by Algomorph** [comment]
No, on Windows I typically run cmake-gui via the executable launched the standard way. I'll go ahead and try running from git-bash right now.

**Comment by Algomorph** [comment]
Tried this on my home machine, failed to replicate. This must be some kind of machine-specific issue, unless it has to do with the specific versions of CMake or git being used. I shouldn't trouble you or anyone else again until (and unless) I can consistently replicate this issue on multiple machines.
