### ISSUE TITLE
Having installation error

### ISSUE THREAD

**Issue by ishanivyas** [stevenlovegrove/Pangolin#548]
4 warnings and 2 errors generated.
make[2]: *** [src/CMakeFiles/pangolin.dir/display/device/PangolinNSGLView.mm.o] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2

**Comment by ishanivyas** [comment]
My error got fixed by fixing PangolinNSGLView.mm file @ line #85 where used self.window instead of _window

**Comment by Inger-Chao** [comment]
> My error got fixed by fixing PangolinNSGLView.mm file @ line #85 where used self.window instead of _window

It works for me at mac os catalina! Thanks!
