### ISSUE TITLE
Framebuffer with requested attributes not available

### ISSUE THREAD

**Issue by wallace-lai** [stevenlovegrove/Pangolin#549]
Hi all
I'm new to OpenGL. I Got a error message "Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts." when I was running the Pangolin examples. By the way,  I was using the Ubuntu 16.04 LTS running as a virtual Machine in VirtualBox.  What's the reason for that error occurs ? anybody knows that ?

Any suggestions will be greatly appreciated !

Thanks.

**Comment by Zhenghong-Lai** [comment]
no framebuffer driver ?

**Comment by stevenlovegrove** [comment]
A late response, sorry, but this is more a warning than an error. It caused by the video driver (or lack thereof) of your VM. There are a few similar issues people have raised if you search.
