### ISSUE TITLE
[cmake error] /usr/bin/ld: cannot find -lEGL

### ISSUE THREAD

**Issue by JunsukLee** [stevenlovegrove/Pangolin#561]
hello.
Help me please.

I use Ubuntu 16.04(x64), nvidia-deriver 430.50, cuda 10.1

I run command follow:
git clone https://github.com/stevenlovegrove/Pangolin.git
cd Pangolin
mkdir build
cd build
cmake ..
cmake --build .

my error follow:

/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
src/CMakeFiles/pangolin.dir/build.make:2166: recipe for target 'src/libpangolin.so' failed
make[2]: *** [src/libpangolin.so] Error 1
CMakeFiles/Makefile2:135: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

I run again a command "sudo apt install libegl1-mesa-dev libwayland-dev libxkbcommon-dev wayland-protocols". But I failed.

I don't know this problem... help me please....

**Comment by sunpeng981712364** [comment]
meet the same issue, and how do you solve the problem?
