### ISSUE TITLE
Help loading image and 3d point cloud using python

### ISSUE THREAD

**Issue by ThisisRavi** [stevenlovegrove/Pangolin#567]
Hi,

I'm a beginner level programmer. I apologize if it is very naive question. 

I'm trying to open image and 3d point cloud (from Lidar in .txt format). I want to display both on the screen. Please help.

Thank you very much

**Comment by christian-rauch** [comment]
Maybe you are better of using a dedicated visualisation library like [VTK](https://vtk.org) or [matplotlib](https://matplotlib.org). With Pangolin, you would still need to write your own visualisation methods in OpenGL.
