### ISSUE TITLE
What is the .pango file format?

### ISSUE THREAD

**Issue by tfy14esa** [stevenlovegrove/Pangolin#573]
It seems like the python-script "SimpleVideo.py" requires as input "--pango somefile.pango". It is very unclear how one would go about creating this file format. This issue [https://github.com/stevenlovegrove/Pangolin/issues/418](url) provides some hints that one can create it from a collection of .png files, but not how it is actually done.

**Comment by YangJae96** [comment]
I faced the same problem. Did you solve it??

**Comment by stevenlovegrove** [comment]
That is a bug in the sample - it can actually accept any pangolin video URI (a not very helpful wiki is here https://github.com/stevenlovegrove/Pangolin/wiki/Video-URI's and some more samples are in the main readme with the C++ VideoViewer program).

A simple example would be:

`python SimpleVideo.py --pango test://`

If you're on linux, you could also use uvc:// if you have a webcam plugged in, or openni:// if you have a kinect with openni sdk installed, etc.

**Comment by stevenlovegrove** [comment]
btw, if you want to use images as input, you can use "images://./path/to/images/*.jpg" or similar.

The quotes are important to stop your shell expanding them. The C++ program VideoViewer, and also the python sample both have options to also output video. The .pango format is the default output option, though others are available.
