### ISSUE TITLE
cmake..  build error

### ISSUE THREAD

**Issue by YangJae96** [stevenlovegrove/Pangolin#575]
Hi, I was trying to download the Pangolin into my Ubuntu 18.04 and i faced this error message.
 
OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.

![cmake error](https://user-images.githubusercontent.com/57695621/72217986-d3900480-3578-11ea-9d13-fbd401a67c23.png)

Is there a way to solve this problem??
Thanks in advance

**Comment by stotko** [comment]
This is actually just a warning. CMake completed the configuration pass without any errors, so you should be able to build Pangolin. However, the warning is still annoying. I have proposed a fix a while ago, see #566. The warning should disappear once it gets merged.

**Comment by YangJae96** [comment]
Thank you. I have done the build like the image.
![builddone](https://user-images.githubusercontent.com/57695621/72229877-214a5280-35f5-11ea-8d96-1bf4af8613e2.png)

Is there a tutorial that I can follow??
I want to visualize the image or video into 3D. 
I am new to this tool so could you please help me?? Thanks in advance again

**Comment by YangJae96** [comment]
For example if i try to build an example cpp file there is a error.
![example](https://user-images.githubusercontent.com/57695621/72230242-7a1aea80-35f7-11ea-99f7-0d5fdc9dc056.png)

In the image, it saids that there is no pangolin header files..
I don't know why because I built the cmake.
Is there Any Solution please??

**Comment by stotko** [comment]
As shown in the second image you have posted, the Pangolin library as well as the examples have been successfully built. No need to try to build a single example using g++. That's what CMake takes care of.

To run an example, just call the respective executable. For instance, use `./examples/HelloPangolin/HelloPangolin` inside the `build` directory to run the HelloPangolin example.
