### ISSUE TITLE
How to load .ply file for visualization?

### ISSUE THREAD

**Issue by zhanghua7099** [stevenlovegrove/Pangolin#577]
I want to read the .ply file for visualization in Pangolin. Does Pangolin support the 3D point cloud data for visualization directly?

**Comment by tfy14esa** [comment]
I also have this question.

**Comment by JunFang-NWPU** [comment]
Have someone solve this problem?

**Comment by stevenlovegrove** [comment]
It can open binary ply files (https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_geometry/src/geometry_ply.cpp). You can try loading your model using the ModelViewer tool to see if it will work.
