### ISSUE TITLE
how to install pangolin with anaconda environment (window)

### ISSUE THREAD

**Issue by kimtaehyeong** [stevenlovegrove/Pangolin#580]
Hello.
I need to install pangolin to do pyslam.
I installed git and cmake via conda install in anaconda environment. In addition, we proceeded sequentially as described in the building. However, the installation hangs due to an error in cmake .. How can I solve it?
The error details are as follows.
'dir' C: / Program Files (x86) / Pangolin 'does not exist after
   file (MAKE_DIRECTORY) '
Configuring incomplete, errors occurred!

Thank you.

**Comment by samjsmart** [comment]
`C:\Program Files (x86)` is a privileged directory. If you run CMake as an Administrator this will work, or change the directory.

**Comment by stevenlovegrove** [comment]
Sorry this is very late, but I think this is related to https://github.com/stevenlovegrove/Pangolin/pull/420. Build system has since changed and I don't think this is relevant anymore. Thanks for reporting.
