### ISSUE TITLE
Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts

### ISSUE THREAD

**Issue by dysenustc** [stevenlovegrove/Pangolin#581]
@stevenlovegrove Hi, [basolt](https://gitlab.com/VladyslavUsenko/basalt) is a vio project using gangolin as gui, but when i run it on ubuntu 16.04 docker system, i got this error, and connot watch all the gui results. and i am sure my docker run glxgears ok.  So, how can i solve this problem? thanks.
![error](https://user-images.githubusercontent.com/17872888/76145392-08758f00-60c4-11ea-92bf-1e6a46edce87.png)
![res](https://user-images.githubusercontent.com/17872888/76145395-0e6b7000-60c4-11ea-9dbc-f48fc83123bb.png)

**Comment by NikolausDemmel** [comment]
Downstream issue [resolved](https://gitlab.com/VladyslavUsenko/basalt/-/issues/27#note_301320561). This can be closed.
