### ISSUE TITLE
CMake Error at CMakeLists.txt:2 (project):   No CMAKE_CXX_COMPILER could be found.

### ISSUE THREAD

**Issue by DominicccLUO** [stevenlovegrove/Pangolin#584]
At first i tried to use Pangolin at my WSL subsystem, but i was told that the subsystem is not as powerful as a virtual machine. Then i tried to use it on my VMware, but when i cmake, i had this error : 
CMake Error at CMakeLists.txt:2 (project):   No CMAKE_CXX_COMPILER could be found.
![image](https://user-images.githubusercontent.com/61530137/77230656-bb6bdf80-6bd0-11ea-87b4-1a85512a64a4.png)
How should I solve it ? Thx a lot !!!

**Comment by tsunghan-mama** [comment]
It seems that you haven't install `g++`.
You can try `apt install g++` and then build Pangolin again.
