### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [stevenlovegrove/Pangolin#585]
Would you like to [wrap any pointer data members](https://github.com/stevenlovegrove/Pangolin/blob/b0e6f5995f59e4bf1f8ad93b0519de9a09f44ea8/src/video/drivers/realsense2.cpp#L7 "Update candidate: RealSense2Video class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by stevenlovegrove** [comment]
I try to normally, though there are some legacy (pre C++11) uses here and there. I'm always open to PR's if there is code that you're using and able to test. Thanks!
