### ISSUE TITLE
ModuleNotError found

### ISSUE THREAD

**Issue by Zumbalamambo** [stevenlovegrove/Pangolin#587]
I'm getting this error even after installing

```

>   File "SimpleDisplay.py", line 4, in <module>
>     import pypangolin as pango
> ModuleNotFoundError: No module named 'pypangolin'

```

**Comment by stevenlovegrove** [comment]
I have done quite a bit of work in the last few commits to make python use much simpler (e.g. 1b372f672884287dd7313882bf674ce2020bf50a).

You can now build the pypangolin_pip_install target to install python and avoid the many versioning gotchas. It will also print very explicitly the version of python that it has been built and installed for and the README now describes how to change the version during the cmake step. Hopefully this all adds up to a better user experience. I'll close this now. Please reopen if you experience this again on the master branch.
