### ISSUE TITLE
Can't run HelloPangolinOffscreen on Windows

### ISSUE THREAD

**Issue by sudodata** [stevenlovegrove/Pangolin#588]
I Can't run HelloPangolinOffscreen on Windows 10, but it works well on Ubuntu 18.04, and who can help?

**Comment by sudodata** [comment]
The problem was found in line8: pangolin::CreateWindowAndBind("",w,h,pangolin::Params({{"scheme", "headless"}}));

**Comment by christian-rauch** [comment]
I haven't tested this on Windows. What errors do you get?

Can you run a simple example like https://github.com/svenpilz/egl_offscreen_opengl?

**Comment by stevenlovegrove** [comment]
It's likely:
```
find_package(OpenGL QUIET COMPONENTS EGL)
if(OpenGL_EGL_FOUND)
```
is failing. It fails on MacOs too. If you don't care about EGL and just want a Framebuffer example, you can safely change the "headless" text to "default" or remove that Param arg.
