### ISSUE TITLE
images sequence displayed wrong

### ISSUE THREAD

**Issue by ckLibra** [stevenlovegrove/Pangolin#590]
I use opencv to load the RGB images sequence and convert them to uchar array.Finally I use GlTexture to render them,but the image displayer is distorted and gray like the following images.
original:  
![279](https://user-images.githubusercontent.com/30599093/79035239-223c5180-7bef-11ea-8635-187995d3d440.jpg)

displayed: 
![5 GG1SXE~KZ10P0LY6J5_F5](https://user-images.githubusercontent.com/30599093/79035269-60d20c00-7bef-11ea-8c9e-c952659f6c0c.png)

Here is my code about opencv and display.

    for (int i = 0; i < filesAbsolutePath.size(); i++) {
        cv::Mat m = cv::imread(filesAbsolutePath[i], cv::IMREAD_COLOR);

        if (m.rows * m.cols == 0)
        {
            printf("cv::imread could not read image ! \n");
            return;
        }
        if (m.type() != CV_8UC3)
        {
            printf("cv::imread did something strange! this may segfault. \n");
            return;
        }
   
        unsigned char* buffer = new unsigned char[3 * m.rows * m.cols];

        int index = 0;
        for (int i = m.rows - 1; i >= 0; i--) {
            for (int j = 0; j < m.cols; j++){
                auto color = m.at<cv::Vec3b>(i, j);
                //int color[3] = { 0, 255, 0 };
                for (int c = 0; c < 3; c++) {
                    buffer[index] = color[c];
                    index++;
                }
            }
        }
        image_collection.push_back(buffer);
    }
--------------------------------------------------------------------------------------------------------------
    pangolin::CreateWindowAndBind("Main", w, h);

    // Create viewport for video with fixed aspect
    pangolin::View& vVideo = pangolin::Display("Video").SetAspect((float)w / h);

    // OpenGl Texture for video frame.
    pangolin::GlTexture texVideo(w, h, glformat, false, 0, glformat, gltype);

    for (int frame = 0; !pangolin::ShouldQuit() && frame < image_collection.size(); ++frame)
    {
        glClear(GL_DEPTH_BUFFER_BIT | GL_COLOR_BUFFER_BIT);

        texVideo.Upload(image_collection[frame], glformat, gltype);

        // Activate video viewport and render texture
        vVideo.Activate();
        texVideo.RenderToViewportFlipY();

        cv::waitKey(1000);
        // Swap back buffer with front and process window events
        pangolin::FinishFrame();
    }

**Comment by jzhzhang** [comment]
@ckLibra Hi, I meet the same problem. Have you found the solution?

**Comment by ckLibra** [comment]
> @ckLibra Hi, I meet the same problem. Have you found the solution?

I am sorry that I haven't found.I just display the gray image instead.

**Comment by t-lou** [comment]
I just read this thread and found a solution, I guess it is already late.

Either in Pangolin or gltexture, there is an alignment. The simple rendering is only correct when `m.cols%4==0`. Maybe it is also needed for rows, didn't check.

So just add `m = m.rowRange(0, m.rows / 4 * 4).colRange(0, m.cols / 4 * 4);` after cv::imread.

![Screenshot_20200809_225957](https://user-images.githubusercontent.com/16481337/89741792-94854b80-da94-11ea-8630-92e6d1dc244e.png)

**Comment by ckLibra** [comment]
Thanks for your help! @t-lou
