### ISSUE TITLE
ADD more examples to Pangolin

### ISSUE THREAD

**Issue by BillZHOU110** [stevenlovegrove/Pangolin#592]
Hello, I am brand new for Pangolin and I see that There is almost no tutorials or examples to learn how to use this library. And I think the examples in the file in not enough. Ainsi, I hope you can add some simple examples for the transformation matrix and some examples for drawing a trajectory by datas.

**Comment by christian-rauch** [comment]
There are quite a few examples in https://github.com/stevenlovegrove/Pangolin/tree/master/examples. What is missing?

**Comment by stevenlovegrove** [comment]
This is a common request and I agree. Always on the todo list :)
