### ISSUE TITLE
offscreen - scheme:headless doesn't work?

### ISSUE THREAD

**Issue by archershot** [stevenlovegrove/Pangolin#602]
I run offscreen example on my ubuntu 16.04 and it doesn;t work. While it work sucessfully on window 10.
The warning message as below:
terminate called after throwing an instance of 'pangolin::WindowExceptionNoKnownHandler'
  what():  No known window handler for URI 'headless'

**Comment by a333klm** [comment]
same here.

**Comment by a333klm** [comment]
Tried to get git clone https://github.com/svenpilz/egl_offscreen_opengl.git working. Did not work either.
Added message("EGL available? " ${OpenGL_EGL_FOUND}) as suggested in #443. 
cd Pangolin/build
cmake ../ 
said that xkbcommon was missing.
sudo apt install ibxkbcommon-dev
make
sudo make install
HelloPangolinSimpleOffscreen worked. It generated two cubes.
egl_offscreen_opengl did not work.

**Comment by stevenlovegrove** [comment]
@a333klm It sounds like you managed to get this to work, but I'm not sure I understand what you did? I'll close this issue for now since it's so old, but please reopen if you experience it again. Thanks!
