### ISSUE TITLE
error: XDG_RUNTIME_DIR not set in the environment?

### ISSUE THREAD

**Issue by ML-BOSS** [stevenlovegrove/Pangolin#603]
I installed Pangolin in ubuntu 16.04 as a dependency for other project. 
My project is running (maybe some features are missing) .

However, during running it gives the following error message. I think this is related to pangolin.
```
START PANGOLIN!
error: XDG_RUNTIME_DIR not set in the environment.
INITIALIZE FROM INITIALIZER (2036 pts)!

```

Is there any suggestion please?

**Comment by stevenlovegrove** [comment]
Sorry for the slow reply. I don't believe this is related. As a test, you can try running one of the pangolin examples (such as examples/HelloPangolin) to see if the same issue arrises. Please reopen this if you still have this issue and it is reproduced in one of the samples.

**Comment by chenmozxh** [comment]
> Sorry for the slow reply. I don't believe this is related. As a test, you can try running one of the pangolin examples (such as examples/HelloPangolin) to see if the same issue arrises. Please reopen this if you still have this issue and it is reproduced in one of the samples.

i encounter with the same problem "error: XDG_RUNTIME_DIR not set in the environment", and when i run the cases in examples/BasicOpenGL
