### ISSUE TITLE
Make HWND public

### ISSUE THREAD

**Issue by jc211** [stevenlovegrove/Pangolin#607]
Would it be possible to get an access function to HWND from within WinWindow?

**Comment by stevenlovegrove** [comment]
You could add an accessor here: https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_windowing/include/pangolin/windowing/WinWindow.h#L60 and use a dynamic cast to get a pointer to the WinWindow class from what CreateWindowAndBind() returns (https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_display/include/pangolin/display/display.h#L63)
