### ISSUE TITLE
Rotate and translate a Pangolin::Geometry object

### ISSUE THREAD

**Issue by BertaBescos** [stevenlovegrove/Pangolin#608]
I am using this example ([https://github.com/stevenlovegrove/Pangolin/blob/master/tools/ModelViewer/main.cpp](https://github.com/stevenlovegrove/Pangolin/blob/master/tools/ModelViewer/main.cpp)) to load a .obj file. Has someone managed to render the object rotated and translated?

**Comment by stevenlovegrove** [comment]
My apologies for the slow reply. In this example, a Tree is built where nodes are the renderable objects, and edges are the coordinate transforms. For the demo, a SpinTransform is used here (https://github.com/stevenlovegrove/Pangolin/blob/master/tools/ModelViewer/main.cpp#L128) but you probably want a RigidTransform (https://github.com/stevenlovegrove/Pangolin/blob/master/tools/ModelViewer/rendertree.h#L46) where you can provide the T_pc ("parent from child transform") into the constructor. See https://eigen.tuxfamily.org/dox/group__TutorialGeometry.html for examples on how to create the appropriate kind of transform.
