### ISSUE TITLE
DPI scaling on macOS

### ISSUE THREAD

**Issue by NikolausDemmel** [stevenlovegrove/Pangolin#613]
It appears to me Pangolin doesn't consider the DPI scaling settings ("HiDPI") on macOS.

This means on a laptop with "retina" screen, or with a monitor with high DPI that is used in scaled mode, the GUI elements (widgets) in pangolin are super small and hard to read. See for example below screenshot, where the browser text in the background is normal size suitable for easy reading, and the Pangolin widgets in the foreground are smaller than expected. This is an example with only moderate scaling. The difference can be much larger.

Is there a way to implement this scaling in Pangolin without too much effort? I don't know how the OS handles it, but maybe in opengl you have to manually convert the different pixel sizes. Ideally, for Pangolin window elements and widgets, this should be transparent (IMHO). I.e. if I create a panel with width 300px, I would like it to be 300 "virtual" (scaled) pixels, according to the current OS setting, not 300 actual monitor pixels. (But I have to admit I know too little about how this is actually implemented in the OS).

Not sure how it is handled on other platforms. I would assume also on Linux and Windows one can do similar DPI scaling at the OS level.

<img width="626" alt="Screenshot 2020-06-26 12 01 27" src="https://user-images.githubusercontent.com/479562/85845595-c7a1a300-b7a4-11ea-9bb4-f60d7c7e70ca.png">

**Comment by stevenlovegrove** [comment]
Do you still find this to be an issue? I also use a retina display and quite like the real-estate, but I can imagine this is an accessibility issue if nothing else. I'm not the biggest fan of creating yet another transform the user has to consider with 'virtual pixels', but it would be relatively easy to change the default font size I think. The biggest issue is automatically determining what is a sensible choice - some people have a lower resolution screen plugged into their Retina macbook, for example. The simplest solution would be an environment variable override or similar that the user can use to decide for themselves.

**Comment by NikolausDemmel** [comment]
I still find it a bit of an inconvenience sometimes. But I also agree that other times the extra real-estate is quite nice. In particular for screen sharing on VC it often is too small to be clearly visible.

> The biggest issue is automatically determining what is a sensible choice - some people have a lower resolution screen plugged into their Retina macbook, for example.

There must be some way to query the OS for the current scaling setting. Even with HiDPI the use may choose different scale factors, it doesn't need to be 2x. Not sure what happens when multiple screens with different resolutions/HiDPI settings are attached.

An environment variable for the user to manually set this in situations where it's needed might be a simple compromise.

**Comment by stevenlovegrove** [comment]
I've pushed 53c6d6f93506de1baca1521bae0aff27532e8dcb which supports overriding the default font and/or font size.

See the readme for example usage, e.g.

```
PANGOLIN_WINDOW_URI="default:[default_font_size=20]//" ./some_pangolin_app
```

**Comment by NikolausDemmel** [comment]
Sorry for the late response, I only now got round to trying the new version.

For fonts the added feature works nicely, thanks!

But the original issue was not only about those. I might have missed that your previous response / question was talking specifically about the possibility of adding a variable for font size only, not for scaling all rendered content.

I find also other rendered content besides the fonts, like image views, 2d overlays, etc to be really tiny on a retina display, when the lines with "width = 1" are actually just 1 pixel, instead of 1 "virtual pixel". Is there some way to rescale everything and also have Pangolin's units, e.g. when specifying the width of a panel or an image view, refer to "virtual pixels", not actual pixels. As mentioned, I don't mind setting the scale factor manually as an environment variable if detecting it from the OS isn't easy.
