### ISSUE TITLE
Visual Studio 2019 16.6 does not like mpark variant

### ISSUE THREAD

**Issue by soeroesg** [stevenlovegrove/Pangolin#614]
VS2019 16.6.4 gives many compiler errors with include/mpark/variant.hpp

**Comment by soeroesg** [comment]
I was able to solve the problem by changing 
```
set (CMAKE_CXX_STANDARD 14)
```
to 
```
set (CMAKE_CXX_STANDARD 17)
```

**Comment by trzy** [comment]
Seconded. Can this be turned into a PR or does it adversely impact other platforms?

**Comment by mrsaleh** [comment]
I had the same issue and solved it by changing to 
`set (CMAKE_CXX_STANDARD 17)
`

Did you make the pull request?

**Comment by soeroesg** [comment]
There is already 
https://github.com/stevenlovegrove/Pangolin/pull/471
https://github.com/stevenlovegrove/Pangolin/issues/469

**Comment by stevenlovegrove** [comment]
I've recently made C++17 required and so this issue should be gone. Thanks
