### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by mengdejiang** [stevenlovegrove/Pangolin#616]
/usr/bin/ld: error: can't create dynamic relocation R_X86_64_DTPOFF32 against symbol: guard variable for pangolin::GlSlUtilities::Instance()::instance in readonly segment; recompile object files with -fPIC
>>> defined in CMakeFiles/pangolin.dir/display/image_view.cpp.o
>>> referenced by image_view.cpp
>>>               CMakeFiles/pangolin.dir/display/image_view.cpp.o:(pangolin::ImageView::Render())

**Comment by stevenlovegrove** [comment]
Sorry for the slow response, but do you still have this issue? What platform and compiler version are you using?

**Comment by stevenlovegrove** [comment]
Please reopen if you see this again!
