### ISSUE TITLE
How to get the color information and coordinate information of a 3D point by clicking it in pangolin library?

### ISSUE THREAD

**Issue by PetershengWUHU** [stevenlovegrove/Pangolin#617]
![选区_050](https://user-images.githubusercontent.com/39899668/88751674-a7da1200-d18a-11ea-994c-3371f620701e.png)

**Comment by stevenlovegrove** [comment]
Please see my response https://github.com/stevenlovegrove/Pangolin/issues/622#issuecomment-912795782 about coordinate information. Color is not read by default, but you could also subclass Handler3D and modify the GetPosNormal() method to also read the color in another glReadPixels call. You would need to do some experimentation.
