### ISSUE TITLE
can't find pypangolin.so in build/src

### ISSUE THREAD

**Issue by sconlyshootery** [stevenlovegrove/Pangolin#618]
Aftering finishing building, I only find libpandolin.so in build/src, however pypangolin.so is not generated.

**Comment by tsunghan-mama** [comment]
In `src/CmakeLists.txt:292`: 

```
...
if(BUILD_PANGOLIN_PYTHON AND BUILD_PANGOLIN_GUI AND BUILD_PANGOLIN_VARS AND NOT _WIN_)
...
```

Do you have pybind11 installed before building ?
I guess this might be the reason that `pypangolin.so` is not generated after compile Pangolin.

**Comment by sconlyshootery** [comment]
Yes, pybind11 is already installed.


________________________________
发件人: Tsunghan Wu <notifications@github.com>
发送时间: 2020年8月25日 11:59
收件人: stevenlovegrove/Pangolin
抄送: 舒畅; Author
主题: [美团安全提示：疑似营销邮件] Re: [stevenlovegrove/Pangolin] can't find pypangolin.so in build/src (#618)


In src/CmakeLists.txt:292:

...
if(BUILD_PANGOLIN_PYTHON AND BUILD_PANGOLIN_GUI AND BUILD_PANGOLIN_VARS AND NOT _WIN_)
...


Do you have pybind11 installed before building ?
I guess this might be the reason that pypangolin.so is not generated after compile Pangolin.

―

**Comment by nhulinsky** [comment]
Did this ever get resolved. I have the same problem. pybind11 installed and no pypangolin.so  Help please?

**Comment by stevenlovegrove** [comment]
Sorry for the slow reply. If anyone still experiences this on the master branch, please reopen this issue and post your cmake output, and let me know what platform you're on. Thanks.
