### ISSUE TITLE
this statement may fall through [-Wimplicit-fallthrough=]

### ISSUE THREAD

**Issue by thisisjaskaran** [stevenlovegrove/Pangolin#619]
while doing cmake --build .
after [68%] I get the following warning

/home/jaskaran/Pangolin/src/video/drivers/openni.cpp: In constructor ‘pangolin::OpenNiVideo::OpenNiVideo(pangolin::OpenNiSensorType, pangolin::OpenNiSensorType, pangolin::ImageDim, int)’:
/home/jaskaran/Pangolin/src/video/drivers/openni.cpp:82:28: warning: this statement may fall through [-Wimplicit-fallthrough=]
             depth_to_color = true;
             ~~~~~~~~~~~~~~~^~~~~~
/home/jaskaran/Pangolin/src/video/drivers/openni.cpp:83:9: note: here
         case OpenNiDepth_1mm:

Please help.

**Comment by stevenlovegrove** [comment]
Thanks. This should now be fixed on the current development branch.
