### ISSUE TITLE
ubuntu16.04 -fPIC can not make .so  

### ISSUE THREAD

**Issue by QiukuZ** [stevenlovegrove/Pangolin#620]
/usr/bin/ld: warning: found local symbol '__bss_start' in global part of symbol table in file /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libGL.so
/usr/bin/ld: warning: found local symbol '_end' in global part of symbol table in file /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libGL.so
/usr/bin/ld: warning: found local symbol '_edata' in global part of symbol table in file /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libGL.so
/usr/bin/ld: error: can't create dynamic relocation R_X86_64_TLSLD against symbol: guard variable for pangolin::GlSlUtilities::Instance()::instance in readonly segment; recompile object files with -fPIC
>>> defined in CMakeFiles/pangolin.dir/display/image_view.cpp.o
>>> referenced by image_view.cpp
>>>               CMakeFiles/pangolin.dir/display/image_view.cpp.o:(pangolin::ImageView::Render())

/usr/bin/ld: error: can't create dynamic relocation R_X86_64_DTPOFF32 against symbol: guard variable for pangolin::GlSlUtilities::Instance()::instance in readonly segment; recompile object files with -fPIC
>>> defined in CMakeFiles/pangolin.dir/display/image_view.cpp.o
>>> referenced by image_view.cpp
>>>               CMakeFiles/pangolin.dir/display/image_view.cpp.o:(pangolin::ImageView::Render())

/usr/bin/ld: error: can't create dynamic relocation R_X86_64_TLSLD against symbol: guard variable for pangolin::GlSlUtilities::Instance()::instance in readonly segment; recompile object files with -fPIC
>>> defined in CMakeFiles/pangolin.dir/display/image_view.cpp.o
>>> referenced by image_view.cpp
>>>               CMakeFiles/pangolin.dir/display/image_view.cpp.o:(pangolin::ImageView::Render())

**Comment by QiukuZ** [comment]
how can i solve it

**Comment by zxl19** [comment]
Hi @QiukuZ , I met exactly the same problem. Did you solve it?

**Comment by stevenlovegrove** [comment]
Sorry for the slow reply - is this still an issue? What platform are you on? What is your cmake configure command? Please reopen if you still require help.
