### ISSUE TITLE
I want to calculate the distance on Pangolin's Viewer

### ISSUE THREAD

**Issue by kodama-y** [stevenlovegrove/Pangolin#622]
I want to find the distance between a specific point on Pangolin's Viewer. Is there any way?

![プレゼンテーション1](https://user-images.githubusercontent.com/65335838/95046794-d858a200-071f-11eb-9cca-3d5e5d8f6cbb.jpg)

**Comment by stevenlovegrove** [comment]
Apologies for not seeing this sooner, but depending on how accurate you need, you can do what you want by looking at the Handler3D which is attached to the 3D view you created.

The class has a Selected_P_w() method which will give you the rough coordinates of where you have clicked. You can either check for changes to this value, or you can subclass Handler3D to add some custom logic on clicks.
