### ISSUE TITLE
Can not find "pangolin_export.h"

### ISSUE THREAD

**Issue by dikiee** [stevenlovegrove/Pangolin#63]
I would like to use pangolin on windows,VS2008.

In "platform.h",including
#include pangolin/pangolin_export.h

But I can not find "pangolin_export.h".

**Comment by stevenlovegrove** [comment]
pangolin_export.h is generated by the CMake prebuild system and ends up in a subdirectory of the build folder. In your own project you must either use CMake to find Pangolin (as per the examples), or configure Visual Studio's INCLUDE_PATH to include the correct generated header files (one for pangolin/include and another for *build*/src/include)
