### ISSUE TITLE
Mac Os Big Sur compile error. Undefined symbols for architecture x86_64 

### ISSUE THREAD

**Issue by kir486680** [stevenlovegrove/Pangolin#637]
I am compiling Pangolin with the following commands: ` cmake .. -DBUILD_SHARED_LIBS=OFF` and `than cmake --build .`. 
However, i get the following error 
```
[ 80%] Linking CXX executable VideoViewer
Undefined symbols for architecture x86_64:
  "_libintl_bind_textdomain_codeset", referenced from:
      _PyIntl_bind_textdomain_codeset in libpython3.8.a(_localemodule.o)
  "_libintl_bindtextdomain", referenced from:
      _PyIntl_bindtextdomain in libpython3.8.a(_localemodule.o)
  "_libintl_dcgettext", referenced from:
      _PyIntl_dcgettext in libpython3.8.a(_localemodule.o)
  "_libintl_dgettext", referenced from:
      _PyIntl_dgettext in libpython3.8.a(_localemodule.o)
  "_libintl_gettext", referenced from:
      _PyIntl_gettext in libpython3.8.a(_localemodule.o)
  "_libintl_setlocale", referenced from:
      _PyLocale_setlocale in libpython3.8.a(_localemodule.o)
      _PyLocale_localeconv in libpython3.8.a(_localemodule.o)
  "_libintl_textdomain", referenced from:
      _PyIntl_textdomain in libpython3.8.a(_localemodule.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/VideoViewer/VideoViewer] Error 1
make[1]: *** [tools/VideoViewer/CMakeFiles/VideoViewer.dir/all] Error 2
make: *** [all] Error 2
```
Any clue how to solve it?

I am using MacOS Big Sur

**Comment by kenmaro3** [comment]
@kir486680 
hello, I am facing same compiling issues, if you could share the solution for this,
I would appreciate it. Thanks in advance.

**Comment by tommasocalo** [comment]
me too

**Comment by tommasocalo** [comment]
> @kir486680
> hello, I am facing same compiling issues, if you could share the solution for this,
> I would appreciate it. Thanks in advance.

have you found a solution ?

**Comment by kenmaro3** [comment]
@tommasocalo FYI, after I struggled this, I tried https://github.com/uoip/pangolin this repo
and dealt with this error, https://github.com/uoip/pangolin/issues/35, then built it.
however, segmentation fault as mentioned in https://github.com/uoip/pangolin/issues/26

**Comment by patosai** [comment]
I managed to build this repo by reinstalling brew. My guess is something in the gettext repo changed while upgrading OS X versions. However after building, I'm still getting segmentation faults when the library is loaded.
