### ISSUE TITLE
No rule to make target `/usr/lib/python3.2/config/libpython3.2.so'

### ISSUE THREAD

**Issue by pangfumin** [stevenlovegrove/Pangolin#64]
hi，lovegrove,
thx for your great work!
when I intall Pangolin ,I meet the problem 
make[2]: *** No rule to make target `/usr/lib/python3.2/config/libpython3.2.so', needed by `src/libpangolin.so'.  Stop.
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2

Can you  give me some advice?

**Comment by stevenlovegrove** [comment]
Pangolin/src/CMakeLists.txt,  line 201 is responsible for finding Python:
```find_package(PythonLibs QUIET)```

For you, ${PYTHON_LIBRARY} is being incorrectly populated. You could try re-running pangolin's cmake to see if it gets fixed. Alternatively, you can set the variable manually with cmake-gui or ccmake. If that still fails, you can clear the variable with cmake-gui or ccmake to disable python completely as a workaround.

**Comment by stevenlovegrove** [comment]
Closing. Please re-open if you have more information to provide.
