### ISSUE TITLE
undefined reference error

### ISSUE THREAD

**Issue by jm5948** [stevenlovegrove/Pangolin#643]
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Build type not set (defaults to release)
-DCMAKE_BUILD_TYPE=Debug for debug
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found GLEW: /usr/local/lib/libGLEW.so
-- Eigen Found and Enabled
-- libdc1394 Found and Enabled
-- V4L Found and Enabled
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- libpng Found and Enabled
-- libjpeg Found and Enabled
-- libtiff Found and Enabled
-- libopenexr Found and Enabled
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components: doxygen missing components: dot
-- Configuring done
-- Generating done

'cmake ..' and 'make install' is done
but if i include pangolin/pangolin.h undefined error is occur

tmp/ccUnjWOR.o: In function `main':
hello.c:(.text+0x82): undefined reference to `pangolin::CreateWindowAndBind(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, pangolin::Params const&)'
hello.c:(.text+0xb9): undefined reference to `glEnable'
hello.c:(.text+0x107): undefined reference to `pangolin::ModelViewLookAt(double, double, double, double, double, double, pangolin::AxisDirection)'
hello.c:(.text+0x172): undefined reference to `pangolin::ProjectionMatrix(int, int, double, double, double, double, double, double)'
hello.c:(.text+0x192): undefined reference to `pangolin::OpenGlRenderState::OpenGlRenderState(pangolin::OpenGlMatrix const&, pangolin::OpenGlMatrix const&)'
hello.c:(.text+0x1c0): undefined reference to `pangolin::Handler3D::Handler3D(pangolin::OpenGlRenderState&, pangolin::AxisDirection, float, float)'
hello.c:(.text+0x1c5): undefined reference to `pangolin::CreateDisplay()'
hello.c:(.text+0x25c): undefined reference to `pangolin::View::SetBounds(pangolin::Attach, pangolin::Attach, pangolin::Attach, pangolin::Attach, double)'
hello.c:(.text+0x271): undefined reference to `pangolin::View::SetHandler(pangolin::Handler*)'
hello.c:(.text+0x27d): undefined reference to `pangolin::ShouldQuit()'
hello.c:(.text+0x28e): undefined reference to `glClear'
hello.c:(.text+0x2a7): undefined reference to `pangolin::View::Activate(pangolin::OpenGlRenderState const&) const'
hello.c:(.text+0x2c1): undefined reference to `pangolin::FinishFrame()'
/tmp/ccUnjWOR.o: In function `pangolin::_CheckGlDieOnError(char const*, int)':
hello.c:(.text._ZN8pangolin18_CheckGlDieOnErrorEPKci[_ZN8pangolin18_CheckGlDieOnErrorEPKci]+0x10): undefined reference to `glGetError'
hello.c:(.text._ZN8pangolin18_CheckGlDieOnErrorEPKci[_ZN8pangolin18_CheckGlDieOnErrorEPKci]+0x23): undefined reference to `pangolin::glErrorString(unsigned int)'
/tmp/ccUnjWOR.o: In function `pangolin::GlTexture::~GlTexture()':
hello.c:(.text._ZN8pangolin9GlTextureD2Ev[_ZN8pangolin9GlTextureD5Ev]+0x26): undefined reference to `pangolin::ShouldQuit()'
hello.c:(.text._ZN8pangolin9GlTextureD2Ev[_ZN8pangolin9GlTextureD5Ev]+0x52): undefined reference to `glDeleteTextures'
/tmp/ccUnjWOR.o: In function `pangolin::GlTexture::Bind() const':
hello.c:(.text._ZNK8pangolin9GlTexture4BindEv[_ZNK8pangolin9GlTexture4BindEv]+0x1b): undefined reference to `glBindTexture'
/tmp/ccUnjWOR.o: In function `pangolin::GlTexture::Reinitialise(int, int, int, bool, int, unsigned int, unsigned int, void*)':
hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0x3b): undefined reference to `glDeleteTextures'
hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0x6e): undefined reference to `glGenTextures'
hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0xba): undefined reference to `glTexImage2D'
hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0xd8): undefined reference to `glTexParameteri'
hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0xec): undefined reference to `glTexParameteri'
hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0x102): undefined reference to `glTexParameteri'
hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0x116): undefined reference to `glTexParameteri'
hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0x12a): undefined reference to `glTexParameteri'
/tmp/ccUnjWOR.o:hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0x13e): more undefined references to `glTexParameteri' follow
/tmp/ccUnjWOR.o: In function `pangolin::GlBufferData::Free()':
hello.c:(.text._ZN8pangolin12GlBufferData4FreeEv[_ZN8pangolin12GlBufferData4FreeEv]+0x1a): undefined reference to `__glewDeleteBuffers'
/tmp/ccUnjWOR.o: In function `pangolin::glDrawColouredCube(float, float)':
hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x490): undefined reference to `glVertexPointer'
hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x49a): undefined reference to `glEnableClientState'
hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x4b7): undefined reference to `glColor4f'
hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x4cb): undefined reference to `glDrawArrays'
hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x4df): undefined reference to `glDrawArrays'
hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x4fc): undefined reference to `glColor4f'
hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x510): undefined reference to `glDrawArrays'
hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x524): undefined reference to `glDrawArrays'
hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x541): undefined reference to `glColor4f'
hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x555): undefined reference to `glDrawArrays'
hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x569): undefined reference to `glDrawArrays'
hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x573): undefined reference to `glDisableClientState'
/tmp/ccUnjWOR.o: In function `pangolin::Handler::~Handler()':
hello.c:(.text._ZN8pangolin7HandlerD2Ev[_ZN8pangolin7HandlerD5Ev]+0xb): undefined reference to `vtable for pangolin::Handler'
/tmp/ccUnjWOR.o:(.data.rel+0x0): undefined reference to `vtable for pangolin::Handler'
/tmp/ccUnjWOR.o:(.data.rel+0x8): undefined reference to `vtable for pangolin::HandlerScroll'
/tmp/ccUnjWOR.o: In function `pangolin::HandlerScroll::~HandlerScroll()':
hello.c:(.text._ZN8pangolin13HandlerScrollD2Ev[_ZN8pangolin13HandlerScrollD5Ev]+0xf): undefined reference to `vtable for pangolin::HandlerScroll'
/tmp/ccUnjWOR.o: In function `pangolin::Handler3D::~Handler3D()':
hello.c:(.text._ZN8pangolin9Handler3DD2Ev[_ZN8pangolin9Handler3DD5Ev]+0xf): undefined reference to `vtable for pangolin::Handler3D'
collect2: error: ld returned 1 exit status

What should I do to solve this problem?
help me...

**Comment by stepbystepcode** [comment]
> -- The C compiler identification is GNU 7.5.0 -- The CXX compiler identification is GNU 7.5.0 -- Check for working C compiler: /usr/bin/cc -- Check for working C compiler: /usr/bin/cc -- works -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Detecting C compile features -- Detecting C compile features - done -- Check for working CXX compiler: /usr/bin/c++ -- Check for working CXX compiler: /usr/bin/c++ -- works -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Detecting CXX compile features -- Detecting CXX compile features - done Build type not set (defaults to release) -DCMAKE_BUILD_TYPE=Debug for debug -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so -- Found GLEW: /usr/local/lib/libGLEW.so -- Eigen Found and Enabled -- libdc1394 Found and Enabled -- V4L Found and Enabled -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") -- libpng Found and Enabled -- libjpeg Found and Enabled -- libtiff Found and Enabled -- libopenexr Found and Enabled -- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components: doxygen missing components: dot -- Configuring done -- Generating done
> 
> 'cmake ..' and 'make install' is done but if i include pangolin/pangolin.h undefined error is occur
> 
> tmp/ccUnjWOR.o: In function `main': hello.c:(.text+0x82): undefined reference to `pangolin::CreateWindowAndBind(std::__cxx11::basic_string<char, std::char_traits, std::allocator >, int, int, pangolin::Params const&)' hello.c:(.text+0xb9): undefined reference to `glEnable' hello.c:(.text+0x107): undefined reference to `pangolin::ModelViewLookAt(double, double, double, double, double, double, pangolin::AxisDirection)' hello.c:(.text+0x172): undefined reference to `pangolin::ProjectionMatrix(int, int, double, double, double, double, double, double)' hello.c:(.text+0x192): undefined reference to `pangolin::OpenGlRenderState::OpenGlRenderState(pangolin::OpenGlMatrix const&, pangolin::OpenGlMatrix const&)' hello.c:(.text+0x1c0): undefined reference to `pangolin::Handler3D::Handler3D(pangolin::OpenGlRenderState&, pangolin::AxisDirection, float, float)' hello.c:(.text+0x1c5): undefined reference to `pangolin::CreateDisplay()' hello.c:(.text+0x25c): undefined reference to `pangolin::View::SetBounds(pangolin::Attach, pangolin::Attach, pangolin::Attach, pangolin::Attach, double)' hello.c:(.text+0x271): undefined reference to `pangolin::View::SetHandler(pangolin::Handler*)' hello.c:(.text+0x27d): undefined reference to `pangolin::ShouldQuit()' hello.c:(.text+0x28e): undefined reference to `glClear' hello.c:(.text+0x2a7): undefined reference to `pangolin::View::Activate(pangolin::OpenGlRenderState const&) const' hello.c:(.text+0x2c1): undefined reference to `pangolin::FinishFrame()' /tmp/ccUnjWOR.o: In function `pangolin::_CheckGlDieOnError(char const*, int)': hello.c:(.text._ZN8pangolin18_CheckGlDieOnErrorEPKci[_ZN8pangolin18_CheckGlDieOnErrorEPKci]+0x10): undefined reference to `glGetError' hello.c:(.text._ZN8pangolin18_CheckGlDieOnErrorEPKci[_ZN8pangolin18_CheckGlDieOnErrorEPKci]+0x23): undefined reference to `pangolin::glErrorString(unsigned int)' /tmp/ccUnjWOR.o: In function `pangolin::GlTexture::~GlTexture()': hello.c:(.text._ZN8pangolin9GlTextureD2Ev[_ZN8pangolin9GlTextureD5Ev]+0x26): undefined reference to `pangolin::ShouldQuit()' hello.c:(.text._ZN8pangolin9GlTextureD2Ev[_ZN8pangolin9GlTextureD5Ev]+0x52): undefined reference to `glDeleteTextures' /tmp/ccUnjWOR.o: In function `pangolin::GlTexture::Bind() const': hello.c:(.text._ZNK8pangolin9GlTexture4BindEv[_ZNK8pangolin9GlTexture4BindEv]+0x1b): undefined reference to `glBindTexture' /tmp/ccUnjWOR.o: In function `pangolin::GlTexture::Reinitialise(int, int, int, bool, int, unsigned int, unsigned int, void*)': hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0x3b): undefined reference to `glDeleteTextures' hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0x6e): undefined reference to `glGenTextures' hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0xba): undefined reference to `glTexImage2D' hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0xd8): undefined reference to `glTexParameteri' hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0xec): undefined reference to `glTexParameteri' hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0x102): undefined reference to `glTexParameteri' hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0x116): undefined reference to `glTexParameteri' hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0x12a): undefined reference to `glTexParameteri' /tmp/ccUnjWOR.o:hello.c:(.text._ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv[_ZN8pangolin9GlTexture12ReinitialiseEiiibijjPv]+0x13e): more undefined references to `glTexParameteri' follow /tmp/ccUnjWOR.o: In function `pangolin::GlBufferData::Free()': hello.c:(.text._ZN8pangolin12GlBufferData4FreeEv[_ZN8pangolin12GlBufferData4FreeEv]+0x1a): undefined reference to `__glewDeleteBuffers' /tmp/ccUnjWOR.o: In function `pangolin::glDrawColouredCube(float, float)': hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x490): undefined reference to `glVertexPointer' hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x49a): undefined reference to `glEnableClientState' hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x4b7): undefined reference to `glColor4f' hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x4cb): undefined reference to `glDrawArrays' hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x4df): undefined reference to `glDrawArrays' hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x4fc): undefined reference to `glColor4f' hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x510): undefined reference to `glDrawArrays' hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x524): undefined reference to `glDrawArrays' hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x541): undefined reference to `glColor4f' hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x555): undefined reference to `glDrawArrays' hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x569): undefined reference to `glDrawArrays' hello.c:(.text._ZN8pangolin18glDrawColouredCubeEff[_ZN8pangolin18glDrawColouredCubeEff]+0x573): undefined reference to `glDisableClientState' /tmp/ccUnjWOR.o: In function `pangolin::Handler::~Handler()': hello.c:(.text._ZN8pangolin7HandlerD2Ev[_ZN8pangolin7HandlerD5Ev]+0xb): undefined reference to `vtable for pangolin::Handler' /tmp/ccUnjWOR.o:(.data.rel+0x0): undefined reference to `vtable for pangolin::Handler' /tmp/ccUnjWOR.o:(.data.rel+0x8): undefined reference to `vtable for pangolin::HandlerScroll' /tmp/ccUnjWOR.o: In function `pangolin::HandlerScroll::~HandlerScroll()': hello.c:(.text._ZN8pangolin13HandlerScrollD2Ev[_ZN8pangolin13HandlerScrollD5Ev]+0xf): undefined reference to `vtable for pangolin::HandlerScroll' /tmp/ccUnjWOR.o: In function `pangolin::Handler3D::~Handler3D()': hello.c:(.text._ZN8pangolin9Handler3DD2Ev[_ZN8pangolin9Handler3DD5Ev]+0xf): undefined reference to `vtable for pangolin::Handler3D' collect2: error: ld returned 1 exit status
> 
> What should I do to solve this problem? help me...

Hello, did you solve it in the end? How did you solve it?
