### ISSUE TITLE
Can't build the colour.cpp.o?

### ISSUE THREAD

**Issue by MrL-CV** [stevenlovegrove/Pangolin#645]
https://github.com/stevenlovegrove/Pangolin/blob/86eb4975fc4fc8b5d92148c2e370045ae9bf9f5d/include/pangolin/gl/colour.h#L32

I have to add #include <limits> to the line pointed above and the .o file can be built successfully.
Building CXX object src/CMakeFiles/pangolin.dir/python/pypangolin/colour.cpp.o

**Comment by Tetsujinfr** [comment]
Not sure if you have the same issue as the one I faced, but you may want to look at #660 for a fix (I had to add `#include <limits>`  after the `#include <stdexcept>` line)
