### ISSUE TITLE
Pangolin on M1 macs

### ISSUE THREAD

**Issue by Forkitarm** [stevenlovegrove/Pangolin#647]
Does anyone have this working on M1 mac, compiling works with a few tweaks but then it segfaults on import

**Comment by xingruiy** [comment]
It works on my machine. Maybe something is wrong with Python bindings?

**Comment by stevenlovegrove** [comment]
@Forkitarm sorry for the slow response - it sounds like you're saying that the python bindings segfault? Do the native examples work? What were the tweaks you had to make? I recently fixed a couple of python issues, so you may have better luck now. Please reopen if you still have this issue.

**Comment by amandeepgini** [comment]
It works for main thread but not with Multithreads on M1 & M2 Macs, I have tried on both.

**Comment by stevenlovegrove** [comment]
@amandeepgini This is an issue in general on MacOS. It doesn't like anything GUI related on any thread except the main thread.

**Comment by Gnomalab** [comment]
For me, beyond pangoling essential works on my macbook pro m1 with parallels 18. I have only had problems detecting my Enttec USB, but that is not a problem with beyond. Otherwise, no notable errors.
