### ISSUE TITLE
Pangolin on Windows 7

### ISSUE THREAD

**Issue by AC311** [stevenlovegrove/Pangolin#648]
Good afternoon, there was a problem with a pangolin. I do not know what to do, please help.
![1](https://user-images.githubusercontent.com/81901245/113502780-77c7e780-953f-11eb-8920-ce9e74b723f0.png)
![2](https://user-images.githubusercontent.com/81901245/113502782-78f91480-953f-11eb-92c4-2052ebb9cc0e.png)

**Comment by AC311** [comment]
If possible, please give me step-by-step instructions on how to install pangolin.If possible, please give me step-by-step instructions on how to install pangolin.

**Comment by stevenlovegrove** [comment]
Hi - sorry for the slow response. This is the same as #611 and related to #420 which are no longer relevant in the current build (use scripts/install_dependencies.bash to install required 3rd party libs now)
