### ISSUE TITLE
build error Pangolin/include/pangolin/gl/colour.h:57:18: error: ‘numeric_limits’ is not a member of ‘std’

### ISSUE THREAD

**Issue by Tetsujinfr** [stevenlovegrove/Pangolin#660]
hi

I am on Jetson Xavier NX and I think I had all the main dependencies properly installed.

when trying `cmake --build .` , I encountered the following error at 52% when compilig colour.cpp.o:

> Pangolin/include/pangolin/gl/colour.h:57:18: error: ‘numeric_limits’ is not a member of ‘std’

So I googled it and found [this](https://github.com/onnx/onnx-tensorrt/issues/474) issue thread from the onnx-tensorrt repo:

After adding #include <limits> to colour.h under Pangolin/include/pangolin/gl/ all compiled properly.

Not sure if this error is specific to the jetson platform but that looks like a simple ommission or some regression.

So closing the issue right away but logging it and its solution in case that helps anyone.

**Comment by Faithy3** [comment]
Can this fix be made into a PR? I'm having the same issue on arch linux 5.10.56-1-lts, and building with the patch works perfectly for me.
