### ISSUE TITLE
save file rgba32f rgb32f as open exr format ,wrong...

### ISSUE THREAD

**Issue by tscmga** [stevenlovegrove/Pangolin#664]
i am chinese .. my english is poor ...
i think i am using libopenexr24 ...
save as exr
and... if i set toplinefirst=false. i get wrong image width .. that is 640 widht , output is 7680.
i just set toplinefirst=true ...to fixed it...
another problem is
in file image_io_exr.cpp
becuase slice need stride of a pixel 
    // Memory layout:  The address of pixel (x, y) is
    //
    //  base + (xp / xSampling) * xStride + (yp / ySampling) * yStride

i fix it by change  /*channel_bits[ch]/8,*/ to fmt.bpp in file
        frameBuffer.insert(
            it.name(),
            Imf::Slice(
                it.channel().type,
                (char*)image.ptr + ch_bits/8,
                 fmt.bpp/8,/*channel_bits[ch]/8,*/
                image.pitch

            )
        );

**Comment by tscmga** [comment]
and another problem is ...load text format ply file , just get a run time error .. not support....  it is easy to output more information about which line and which file ..not supoport...or say "txt formt ply format is not supported" .
becuase txt format ply is used in public dataset

**Comment by tscmga** [comment]
void ParsePlyAscii(pangolin::Geometry& /*geom*/, const PlyHeaderDetails& /*ply*/, std::istream& /*is*/)
{
    throw std::runtime_error("ascii ply loading ,Not implemented.");
}

**Comment by tscmga** [comment]
[fbo.exr.zip](https://github.com/stevenlovegrove/Pangolin/files/7070353/fbo.exr.zip)
There is example  Pangolin/examples/HelloPangolinOffscreen/main.cpp
I just modify+ed two lines..
pangolin::GlTexture color_buffer(w,h,GL_RGB32F);
to set color buffer format to float ...
and 
color_buffer.Save("/home/tscmga/fbo.exr",true);
to save as exr format..
..... i am not using exr format now... i just export the data to opencv , convert it to opencv mat ..
I want to render object normal to color buffer , or depth to color buffer . float point ... and save  or preview ...
there are other tools more powerful, but pangolin is fast and simple... 
//--------
i uploaded a fbo.exr.zip , this is the correct result .

`#include <pangolin/pangolin.h>

int main( int /*argc*/, char** /*argv*/ )
{
    static const int w = 640;
    static const int h = 480;

    pangolin::CreateWindowAndBind("Main",w,h,pangolin::Params({{"scheme", "headless"}}));
    glEnable(GL_DEPTH_TEST);

    // Define Projection and initial ModelView matrix
    pangolin::OpenGlRenderState s_cam(
        pangolin::ProjectionMatrix(w,h,420,420,320,240,0.2,100),
        pangolin::ModelViewLookAt(-2,2,-2, 0,0,0, pangolin::AxisY)
    );

    // Create Interactive View in window
    pangolin::Handler3D handler(s_cam);
    pangolin::View& d_cam = pangolin::CreateDisplay()
            .SetBounds(0.0, 1.0, 0.0, 1.0, -float(w)/float(h))
            .SetHandler(&handler);

    pangolin::SaveWindowOnRender("window");

    // create a frame buffer object with colour and depth buffer
    pangolin::GlTexture color_buffer(w,h,GL_RGB32F);
    //pangolin::GlTexture color_buffer(w,h);
    pangolin::GlRenderBuffer depth_buffer(w,h);
    pangolin::GlFramebuffer fbo_buffer(color_buffer, depth_buffer);
    fbo_buffer.Bind();

    // Clear screen and activate view to render into
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    d_cam.Activate(s_cam);

    // Render OpenGL Cube
    pangolin::glDrawColouredCube();

    // Swap frames and Process Events
    pangolin::FinishFrame();

    fbo_buffer.Unbind();
    // download and save the colour buffer
    color_buffer.Save("/home/tscmga/fbo.exr",true);
    //color_buffer.

    pangolin::QuitAll();
    
    return 0;
}
`

**Comment by tscmga** [comment]
gimp opens exr file

**Comment by stevenlovegrove** [comment]
So it's not able to load the file that it has saved. Thanks!

**Comment by stevenlovegrove** [comment]
ffb47995d148bfa63bd56e18a478419304af2f46 fixes your EXR loading issue by adding that type to the list of supported types. You can verify using Pangolins in-built viewer:

./build/VideoViewer fbo.exr

<img width="655" alt="Screen Shot 2021-09-02 at 9 18 41 PM" src="https://user-images.githubusercontent.com/481156/131949935-bbecfb33-4259-4fb0-ace3-e8db69f200b9.png">

Thanks for reporting!
