### ISSUE TITLE
CMake Install routines completely broken

### ISSUE THREAD

**Issue by abougouffa** [stevenlovegrove/Pangolin#667]
Hello,

I'm trying to install `pangolin` in my Linux system, I found the installation process is completely broken!

After preparing a build directory `Pangolin/build` and; 
- running `cmake ..` 
- then `make`, all components are built successfully (after applying the https://github.com/abougouffa/Pangolin/commit/6e96a45127cc9ed797d36f4fb1efe47cde947204 patch), 
- however, the `make install` does not install the libraries and include files as it did before, it installs only the tools present in `Pangolin/tools` sub-directory.
- It looks like all the `components/*/CMakeLists.txt` does not call the CMake's `install(...)`

I think this issue should be fixed quickly as it brokes all projects relaying on this library as a system dependency.

Thanks in advance.

**Comment by stevenlovegrove** [comment]
Okay, I've added support for install again (32c8886e5d48ae3fcc653d8b36e595114e2f58d7).

If you want to help test it, try it out :)

**Comment by abougouffa** [comment]
Thank you, @stevenlovegrove ,

I've just tried it; it works as expected,
Thank you again 🙏🏼
