### ISSUE TITLE
error: ISO C++1z does not allow dynamic exception specifications      const Vec2 & normalizeExc () throw (IEX_NAMESPACE::MathExc);

### ISSUE THREAD

**Issue by bytemani** [stevenlovegrove/Pangolin#668]
Anyone knows what happened? Detailed descriptions are as below, thank you.
Scanning dependencies of target pango_image
[ 10%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/pixel_format.cpp.o
[ 11%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io.cpp.o
[ 11%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_exr.cpp.o
In file included from /usr/include/OpenEXR/ImfHeader.h:51:0,
                 from /usr/include/OpenEXR/ImfInputFile.h:46,
                 from /home/guliang/slam/Pangolin/components/pango_image/src/image_io_exr.cpp:8:
/usr/include/OpenEXR/ImathVec.h:228:34: error: ISO C++1z does not allow dynamic exception specifications
     const Vec2 & normalizeExc () throw (IEX_NAMESPACE::MathExc);
                                  ^~~~~
/usr/include/OpenEXR/ImathVec.h:232:37: error: ISO C++1z does not allow dynamic exception specifications
     Vec2<T>  normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                     ^~~~~
/usr/include/OpenEXR/ImathVec.h:440:34: error: ISO C++1z does not allow dynamic exception specifications
     const Vec3 & normalizeExc () throw (IEX_NAMESPACE::MathExc);
                                  ^~~~~
/usr/include/OpenEXR/ImathVec.h:444:37: error: ISO C++1z does not allow dynamic exception specifications
     Vec3<T>  normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                     ^~~~~
/usr/include/OpenEXR/ImathVec.h:622:37: error: ISO C++1z does not allow dynamic exception specifications
     const Vec4 &    normalizeExc () throw (IEX_NAMESPACE::MathExc);
                                     ^~~~~
/usr/include/OpenEXR/ImathVec.h:626:44: error: ISO C++1z does not allow dynamic exception specifications
     Vec4<T>         normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                            ^~~~~
/usr/include/OpenEXR/ImathVec.h:714:30: error: ISO C++1z does not allow dynamic exception specifications
 Vec2<short>::normalizeExc () throw (IEX_NAMESPACE::MathExc);
                              ^~~~~
/usr/include/OpenEXR/ImathVec.h:723:37: error: ISO C++1z does not allow dynamic exception specifications
 Vec2<short>::normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                     ^~~~~
/usr/include/OpenEXR/ImathVec.h:738:28: error: ISO C++1z does not allow dynamic exception specifications
 Vec2<int>::normalizeExc () throw (IEX_NAMESPACE::MathExc);
                            ^~~~~
/usr/include/OpenEXR/ImathVec.h:747:35: error: ISO C++1z does not allow dynamic exception specifications
 Vec2<int>::normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                   ^~~~~
/usr/include/OpenEXR/ImathVec.h:762:30: error: ISO C++1z does not allow dynamic exception specifications
 Vec3<short>::normalizeExc () throw (IEX_NAMESPACE::MathExc);
                              ^~~~~
/usr/include/OpenEXR/ImathVec.h:771:37: error: ISO C++1z does not allow dynamic exception specifications
 Vec3<short>::normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                     ^~~~~
/usr/include/OpenEXR/ImathVec.h:786:28: error: ISO C++1z does not allow dynamic exception specifications
 Vec3<int>::normalizeExc () throw (IEX_NAMESPACE::MathExc);
                            ^~~~~
/usr/include/OpenEXR/ImathVec.h:795:35: error: ISO C++1z does not allow dynamic exception specifications
 Vec3<int>::normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                   ^~~~~
/usr/include/OpenEXR/ImathVec.h:809:30: error: ISO C++1z does not allow dynamic exception specifications
 Vec4<short>::normalizeExc () throw (IEX_NAMESPACE::MathExc);
                              ^~~~~
/usr/include/OpenEXR/ImathVec.h:818:37: error: ISO C++1z does not allow dynamic exception specifications
 Vec4<short>::normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                     ^~~~~
/usr/include/OpenEXR/ImathVec.h:833:28: error: ISO C++1z does not allow dynamic exception specifications
 Vec4<int>::normalizeExc () throw (IEX_NAMESPACE::MathExc);
                            ^~~~~
/usr/include/OpenEXR/ImathVec.h:842:35: error: ISO C++1z does not allow dynamic exception specifications
 Vec4<int>::normalizedExc () const throw (IEX_NAMESPACE::MathExc);
                                   ^~~~~
/usr/include/OpenEXR/ImathVec.h:1212:26: error: ISO C++1z does not allow dynamic exception specifications
 Vec2<T>::normalizeExc () throw (IEX_NAMESPACE::MathExc)
                          ^~~~~
/usr/include/OpenEXR/ImathVec.h:1249:33: error: ISO C++1z does not allow dynamic exception specifications
 Vec2<T>::normalizedExc () const throw (IEX_NAMESPACE::MathExc)
                                 ^~~~~
/usr/include/OpenEXR/ImathVec.h:1704:26: error: ISO C++1z does not allow dynamic exception specifications
 Vec3<T>::normalizeExc () throw (IEX_NAMESPACE::MathExc)
                          ^~~~~
/usr/include/OpenEXR/ImathVec.h:1743:33: error: ISO C++1z does not allow dynamic exception specifications
 Vec3<T>::normalizedExc () const throw (IEX_NAMESPACE::MathExc)
                                 ^~~~~
/usr/include/OpenEXR/ImathVec.h:2109:26: error: ISO C++1z does not allow dynamic exception specifications
 Vec4<T>::normalizeExc () throw (IEX_NAMESPACE::MathExc)
                          ^~~~~
/usr/include/OpenEXR/ImathVec.h:2150:33: error: ISO C++1z does not allow dynamic exception specifications
 Vec4<T>::normalizedExc () const throw (IEX_NAMESPACE::MathExc)
                                 ^~~~~
In file included from /usr/include/OpenEXR/ImfXdr.h:108:0,
                 from /usr/include/OpenEXR/ImfGenericOutputFile.h:40,
                 from /usr/include/OpenEXR/ImfTiledOutputFile.h:50,
                 from /usr/include/OpenEXR/ImfInputFile.h:48,
                 from /home/guliang/slam/Pangolin/components/pango_image/src/image_io_exr.cpp:8:
/usr/include/OpenEXR/half.h: In constructor ‘half::half(float)’:
/usr/include/OpenEXR/half.h:462:15: warning: ISO C++1z does not allow ‘register’ storage class specifier [-Wregister]
  register int e = (x.i >> 23) & 0x000001ff;
               ^
/usr/include/OpenEXR/half.h:473:19: warning: ISO C++1z does not allow ‘register’ storage class specifier [-Wregister]
      register int m = x.i & 0x007fffff;
                   ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
CMakeFiles/pango_image.dir/build.make:110: recipe for target 'CMakeFiles/pango_image.dir/components/pango_image/src/image_io_exr.cpp.o' failed
make[2]: *** [CMakeFiles/pango_image.dir/components/pango_image/src/image_io_exr.cpp.o] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/pango_image.dir/all' failed
make[1]: *** [CMakeFiles/pango_image.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stevenlovegrove** [comment]
Where did you get your OpenEXR package? It looks to me like it might be old and doesn't like C++17 compilers. The Pangolin CI is successfully building with OpenEXR support (https://github.com/stevenlovegrove/Pangolin/runs/3446076260?check_suite_focus=true#step:8:22) using Ubuntu 20.04. I guess it's also possible that it is the other way around and you're using a newer and more strict compiler?

If you don't care about OpenEXR, you can unblock yourself by setting the OpenEXR Include and lib dirs to "" using cmake before building Pangolin.

**Comment by bytemani** [comment]
> Where did you get your OpenEXR package? It looks to me like it might be old and doesn't like C++17 compilers. The Pangolin CI is successfully building with OpenEXR support (https://github.com/stevenlovegrove/Pangolin/runs/3446076260?check_suite_focus=true#step:8:22) using Ubuntu 20.04. I guess it's also possible that it is the other way around and you're using a newer and more strict compiler?
> 
> If you don't care about OpenEXR, you can unblock yourself by setting the OpenEXR Include and lib dirs to "" using cmake before building Pangolin.

Many thanks. Actually, I'm new in CV and I didn't install OpenEXR by myself. And I'm not sure if the OpenEXR will be used next~~~
My working environment is ubuntu 18.04. I'm running the ORB-SLAM3 code(https://github.com/UZ-SLAMLab/ORB_SLAM3) and the Pangolin should be installed previously.  Maybe other Pangolin version will work well?

**Comment by bytemani** [comment]
@stevenlovegrove

**Comment by stevenlovegrove** [comment]
To disable OpenEXR you could try:

```
mkdir build
cd build
cmake -DOpenEXR_LIBRARY="" ..
```


If you're trying to use pangolin with ORB-SLAM or something, you're probably better off with the 0.6 tag for now.

```git checkout v0.6```

**Comment by bytemani** [comment]
@ok,thank you. I'll have a try with version 0.6.

**Comment by bytemani** [comment]
@stevenlovegrove ok,thank you. I'll have a try with version 0.6.

**Comment by arjunskumar** [comment]
Thanks @stevenlovegrove , it works
