### ISSUE TITLE
Cant build. pybind11 no CMakeList.txt

### ISSUE THREAD

**Issue by RalphCodesTheInternet** [stevenlovegrove/Pangolin#670]
I followed all the steps and prerequisites. When I call cmake I get this error. 

`
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- libpng Found and Enabled
-- libjpeg Found and Enabled
-- libtiff Found and Enabled
-- libopenexr Found and Enabled
-- liblz4 Found and Enabled
-- libzstd Found and Enabled
-- Found Python: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter Development 
CMake Error at components/pango_python/CMakeLists.txt:5 (add_subdirectory):
  The source directory

Pangolin/components/pango_python/pybind11
does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:76 (include)

`

I alos tried using 

`
git submodule init && git submodule update 
`
but it also fails to clone. 

Thanks in advance

**Comment by stevenlovegrove** [comment]
What is the error when attempting to init the submodules?

**Comment by stevenlovegrove** [comment]
(I do need to update the documentation to detail initing the submodules)

**Comment by RalphCodesTheInternet** [comment]
Thanks for the quick reply

When I call submodule init, nothing happens, but when I call update I get this error: 

`Cloning into '/Pangolin/components/pango_python/pybind11'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:pybind/pybind11.git' into submodule path '/Pangolin/components/pango_python/pybind11' failed
Failed to clone 'components/pango_python/pybind11'. Retry scheduled
Cloning into '/Pangolin/components/pango_python/pybind11'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:pybind/pybind11.git' into submodule path '/Pangolin/components/pango_python/pybind11' failed
Failed to clone 'components/pango_python/pybind11' a second time, aborting
`

**Comment by harshalkataria** [comment]
Facing the same issue during git submodule update.

**Comment by stevenlovegrove** [comment]
Ah, there's an easy fix for that!

367a1761d76a719484356644d72d5394dd37e798 updates the submodule location to the more accessible https URL from Github.

Sorry about that! Thanks for reporting!
