### ISSUE TITLE
make error  ubuntu  16.04  error: ‘auto’ parameter not permitted  

### ISSUE THREAD

**Issue by wavelet2008** [stevenlovegrove/Pangolin#671]
In file included from /share/v3/svn/Pangolin/components/pango_core/include/pangolin/utils/signal_slot.h:3:0,
                 from /share/v3/svn/Pangolin/components/pango_packetstream/include/pangolin/log/sync_time.h:29,
                 from /share/v3/svn/Pangolin/components/pango_packetstream/include/pangolin/log/packetstream_reader.h:34,
                 from /share/v3/svn/Pangolin/components/pango_packetstream/src/packetstream_reader.cpp:26:
/share/v3/svn/Pangolin/components/pango_core/include/signals/signals.hpp:257:17: error: ‘auto’ parameter not permitted in this context
   template<auto PMF, class C>
                 ^
/share/v3/svn/Pangolin/components/pango_core/include/signals/signals.hpp:269:17: error: ‘auto’ parameter not permitted in this context
   template<auto func>
                 ^
/share/v3/svn/Pangolin/components/pango_core/include/signals/signals.hpp: In member function ‘fteng::connection_raw fteng::signal<void(A ...)>::connect(C*) const’:
/share/v3/svn/Pangolin/components/pango_core/include/signals/signals.hpp:261:36: error: forming reference to void
    auto& call = calls.emplace_back();
                                    ^
/share/v3/svn/Pangolin/components/pango_core/include/signals/signals.hpp: In lambda function:
/share/v3/svn/Pangolin/components/pango_core/include/signals/signals.hpp:263:101: error: ‘PMF’ was not declared in this scope
    call.func = reinterpret_cast<void*>(+[](void* obj, A ... args) {((*reinterpret_cast<C**>(obj))->*PMF)(args...); });
                                                                                                     ^
/share/v3/svn/Pangolin/components/pango_core/include/signals/signals.hpp: In member function ‘fteng::connection_raw fteng::signal<void(A ...)>::connect() const’:
/share/v3/svn/Pangolin/components/pango_core/include/signals/signals.hpp:272:19: error: ‘func’ was not declared in this scope
    return connect(func);
                   ^
/share/v3/svn/Pangolin/components/pango_core/include/signals/signals.hpp: In member function ‘fteng::connection_raw fteng::signal<void(A ...)>::connect(void (*)(A ...)) const’:
/share/v3/svn/Pangolin/components/pango_core/include/signals/signals.hpp:278:36: error: forming reference to void
    auto& call = calls.emplace_back();

**Comment by shaoxh** [comment]
I have this error when compiling orbslam2. then I notice that pangolin 0.6 is high version for orbslam2. the author have upgrade it to some c++ 17 stander which orbslam2 doesn't comply with. 
I solve this to clone a 0.5 version pangolin.
hope to help you.

**Comment by stevenlovegrove** [comment]
Yes - this is probably easy to fix in orbslam by adding or modifying something like
```
if(NOT CMAKE_CXX_STANDARD)
    set(CMAKE_CXX_STANDARD 17)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
endif()
```
in the root cmake.

**Comment by wenjie710** [comment]
> Yes - this is probably easy to fix in orbslam by adding or modifying something like
> 
> ```
> if(NOT CMAKE_CXX_STANDARD)
>     set(CMAKE_CXX_STANDARD 17)
>     set(CMAKE_CXX_STANDARD_REQUIRED ON)
> endif()
> ```
> 
> in the root cmake.

This caused another bug in make. "error: ISO C++1z does not allow dynamic exception specifications" which is caused because C++ 17 does not support ‘throw’ any more.

**Comment by stevenlovegrove** [comment]
@wenjie710 Where does that `error: ISO C++1z does not allow dynamic exception specifications`  error occur? In OrbSLAM too?

Throw hasn't been removed entirely, just "dynamic exception specifications" on function signatures:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0003r0.html
(these things: https://en.cppreference.com/w/cpp/language/except_spec)

It should be very easy to fix this in code (and it was already deprecated in C++11). I'd recommend raising this issue with the library author.
