### ISSUE TITLE
Please fix includes for GCC 11

### ISSUE THREAD

**Issue by byxrolland** [stevenlovegrove/Pangolin#673]
I tried to install pangonlin from vcpkg, compiling with gcc-11. The building failed with errors like

```txt
 error: 'numeric_limits' is not a member of 'std'
```

I also found that in https://www.gnu.org/software/gcc/gcc-11/porting_to.html, it states

> Header dependency changes
> Some C++ Standard Library headers have been changed to no longer include other headers that they do need to depend on. As such, C++ programs that used standard library components without including the right headers will no longer compile.
> 
> The following headers are used less widely in libstdc++ and may need to be included explicitly when compiled with GCC 11:
> 
> <limits> (for std::numeric_limits)
> <memory> (for std::unique_ptr, std::shared_ptr etc.)
> <utility> (for std::pair, std::tuple_size, std::index_sequence etc.)
> <thread> (for members of namespace std::this_thread.)

Therefore, please add the addtional `#include`s in order to support GCC 11.

**Comment by stevenlovegrove** [comment]
Thanks for raising the issue. Pangolin in contributor lead, so I'll happily take a pull request for the required fixes. Alternatively, you could attach the build output against the master branch and I might be able to see if there are some obvious places where these missing includes need to be added.

**Comment by byxrolland** [comment]
I was trying to install pangolin using vcpkg. Currently, the vcpkg has its own problem installing the package. I'm waiting for them to fix it then I'll try again.

**Comment by stevenlovegrove** [comment]
@byxrolland if you made a vcpkg issue, feel free to link it here for others to track. Thanks

**Comment by byxrolland** [comment]
I installed the recently updated pangolin via vcpkg. I seems the issue has gone. So I think I should close this issue for the time being.
