### ISSUE TITLE
ERROR: pypangolin has an invalid wheel

### ISSUE THREAD

**Issue by RG2806** [stevenlovegrove/Pangolin#679]
I am getting this error:
sudo cmake --build . -t pypangolin_pip_install
[ 10%] Built target pango_core
[ 15%] Built target pango_packetstream
[ 26%] Built target pango_image
[ 35%] Built target pango_opengl
[ 40%] Built target pango_windowing
[ 43%] Built target pango_vars
[ 53%] Built target pango_display
[ 76%] Built target pango_video
[ 80%] Built target pango_plot
[ 98%] Built target pypangolin
[ 98%] Built target pypangolin_wheel
[100%] Installing for selected Python '/usr/bin/python3.8'
Processing ./pypangolin-0.7-cp38-cp38-linux_x86_64.whl
ERROR: pypangolin has an invalid wheel, could not read 'pypangolin-0.7.dist-info/WHEEL' file: KeyError("There is no item named 'pypangolin-0.7.dist-info/WHEEL' in the archive")
make[3]: *** [CMakeFiles/pypangolin_pip_install.dir/build.make:58: CMakeFiles/pypangolin_pip_install] Error 1
make[2]: *** [CMakeFiles/Makefile2:711: CMakeFiles/pypangolin_pip_install.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:718: CMakeFiles/pypangolin_pip_install.dir/rule] Error 2
make: *** [Makefile:268: pypangolin_pip_install] Error 2

**Comment by stevenlovegrove** [comment]
Strange. Can you list the contents of the wheel file that is created, e.g.
```
unzip -Z1 *.whl
```

If there is no WHEEL file there, can you also check `pypangolin-0.7.dist-info` in the build dir (which is the folder the zip is created from) and its contents:
```
find ./pypangolin-0.7.dist-info
cat ./pypangolin-0.7.dist-info/WHEEL
```

The template for the file is https://github.com/stevenlovegrove/Pangolin/blob/master/cmake/wheel-dist-info/WHEEL and it should be getting packaged in https://github.com/stevenlovegrove/Pangolin/blob/master/cmake/MakePythonWheel.cmake#L68 so if you were so inclined you could debug there.

**Comment by RG2806** [comment]
this is the output:
rohan@rohan-Virtual-Machine:~/Pangolin/build$ ls
CMakeCache.txt         include                 libpango_packetstream.so  libpango_windowing.so                      pypangolin-0.7.data
CMakeFiles             libpango_core.so        libpango_plot.so          libtinyobj.so                              pypangolin-0.7.dist-info
cmake_install.cmake    libpango_display.so     libpango_python.so        Makefile                                   tools
cmake_uninstall.cmake  libpango_geometry.so    libpango_scene.so         PangolinConfig.cmake
components             libpango_glgeometry.so  libpango_tools.so         PangolinConfigVersion.cmake
examples               libpango_image.so       libpango_vars.so          PangolinTargets.cmake
fonts.cpp              libpango_opengl.so      libpango_video.so         pypangolin-0.7-cp38-cp38-linux_x86_64.whl
rohan@rohan-Virtual-Machine:~/Pangolin/build$ unzip -Z1 *.whl
pypangolin-0.7.dist-info/
pypangolin-0.7.dist-info/RECORD
pypangolin-0.7.data/
pypangolin-0.7.data/purelib/
pypangolin-0.7.data/purelib/pypangolin.cpython-38-x86_64-linux-gnu.so
rohan@rohan-Virtual-Machine:~/Pangolin/build$ find ./pypangolin-0.7.dist-info
./pypangolin-0.7.dist-info
./pypangolin-0.7.dist-info/RECORD
rohan@rohan-Virtual-Machine:~/Pangolin/build$ cat ./pypangolin-0.7.dist-info/WHEEL
cat: ./pypangolin-0.7.dist-info/WHEEL: No such file or directory
rohan@rohan-Virtual-Machine:~/Pangolin/build$

**Comment by stevenlovegrove** [comment]
You're also missing METADATA and toplevel.txt files which means https://github.com/stevenlovegrove/Pangolin/blob/master/cmake/MakePythonWheel.cmake#L47 is not working for some reason. You could add `message(STATUS "wheel_info_files: ${wheel_info_files}")` to the line below to be sure. You could also add `message(STATUS "GLOB_PATH: ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/wheel-dist-info/*")` somewhere around there to see exactly the path it is trying to use. Once you've added that, re-run cmake and look for those messages.

**Comment by RG2806** [comment]
there is METADATA  top_level.txt  WHEEL in /Pangolin/cmake/wheel-dist-info

**Comment by RG2806** [comment]
i added following lines:
file(GLOB wheel_info_files "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/wheel-dist-info/*" )
message(STATUS "wheel_info_files: ${wheel_info_files}")
message(STATUS "GLOB_PATH: ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/wheel-dist-info/*")
file(WRITE "${wheel_distinfo}/RECORD" "")


and this is output:
rohan@rohan-Virtual-Machine:~/Pangolin/build$ cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
CMake Warning at CMakeLists.txt:75 (message):
  Building Tests requested, but Catch2 library not found.


-- libpng Found and Enabled
-- libjpeg Found and Enabled
-- libtiff Found and Enabled
-- pybind11 v2.7.1 
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
**-- wheel_info_files: 
-- GLOB_PATH: /wheel-dist-info/***
-- Selected Python: '/usr/bin/python3.8'. cmake --build . -t pypangolin_pip_install to use pypangolin module.
-- V4L Found and Enabled
-- Performing Test HAVE_FFMPEG_MAX_ANALYZE_DURATION
-- Performing Test HAVE_FFMPEG_MAX_ANALYZE_DURATION - Success
-- Performing Test HAVE_FFMPEG_AVFORMAT_ALLOC_OUTPUT_CONTEXT2
-- Performing Test HAVE_FFMPEG_AVFORMAT_ALLOC_OUTPUT_CONTEXT2 - Success
-- Performing Test HAVE_FFMPEG_AVPIXELFORMAT
-- Performing Test HAVE_FFMPEG_AVPIXELFORMAT - Success
-- ffmpeg Found and Enabled
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rohan/Pangolin/build

**Comment by stevenlovegrove** [comment]
Okay, so your `${CMAKE_CURRENT_FUNCTION_LIST_DIR}` is EMPTY_STRING. If you read https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_FUNCTION_LIST_DIR.html#variable:CMAKE_CURRENT_FUNCTION_LIST_DIR, `CMAKE_CURRENT_FUNCTION_LIST_DIR` was added in CMake 3.17 but Pangolin only lists cmake min version 3.8. My guess is that your CMake version is between those two numbers. If that's the case you will need to upgrade your cmake.

**Comment by RG2806** [comment]
Yup, cmake version was the problem.
upgrading cmake from **3.16.3 -->3.21.2** 
solved it!!
Thanks

**Comment by boni-hu** [comment]
I meet a same problem, and the cmake version is already 3.21.2, also the METADATA top_level.txt WHEEL in ~/Pangolin/cmake/wheel-dist-info/ already have `
message(STATUS "wheel_info_files: /home/a409_home/users/huboni/Projects/2024_code/Pangolin/cmake/wheel-dist-info/METADATA;/home/a409_home/users/huboni/Projects/2024_code/Pangolin/cmake/wheel-dist-info/WHEEL;/home/a409_home/users/huboni/Projects/2024_code/Pangolin/cmake/wheel-dist-info/top_level.txt")
message(STATUS "GLOB_PATH: /home/a409_home/users/huboni/Projects/2024_code/Pangolin/cmake/wheel-dist-info/*")` .  The output is (base) a409@gpu-server1:~/users/huboni/Projects/2024_code/Pangolin/build$ cmake ..
-- Found Eigen: '/usr/include/eigen3'
-- libpng Found and Enabled
-- libjpeg Found and Enabled
-- libtiff Found and Enabled
-- libopenexr Found and Enabled
-- Found Eigen: '/usr/include/eigen3'
-- pybind11 v2.12.0 
-- Selected Python: '/home/a409_home/anaconda3/envs/pram/bin/python'. cmake --build . -t pypangolin_pip_install to use pypangolin module.
-- libdc1394 Found and Enabled
-- V4L Found and Enabled
-- ffmpeg Found and Enabled: /usr/include/x86_64-linux-gnu;/usr/include/x86_64-linux-gnu;/usr/include/x86_64-linux-gnu;/usr/include/x86_64-linux-gnu;/usr/include/x86_64-linux-gnu
-- Configuring done
-- Generating done
-- Build files have been written to: /home/a409_home/users/huboni/Projects/2024_code/Pangolin/build
