### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by mojovski** [stevenlovegrove/Pangolin#68]
Does Pangolin support Windows?

When I try to build it, I receive
```
`Error	12	error C2784: 'std::_String_iterator<_Mystr> std::operator +(_String_iterator<_Mystr>::difference_type,std::_String_iterator<_Mystr>)' : could not deduce template argument for 'std::_String_iterator<_Mystr>' from 'const std::string'	
D:\cpp\Pangolin\src\utils\threadedfilebuf.cpp	57

```

and many others.

PS: Using Visual Studio 2012, 64 bit.

**Comment by stevenlovegrove** [comment]
It does support Windows. Visual Studio 2013 and 2015 are tested. I built on 64bit VS2015 very recently with no problem. I do not have a Windows build server, so the likelihood that a given commit breaks things is higher than on Linux.

**Comment by mojovski** [comment]
Thank you. 
I can support you with a windows build server if ctest is supported.

**Comment by stevenlovegrove** [comment]
To close this issue, I'm going to designate VS 2013 the minimum supported version.

It's kind to offer a Windows build server - I'm open to suggestions there. Pangolin does not currently have a testing framework. On Linux I simply have compile-time build / fail categories.

**Comment by mojovski** [comment]
yes I saw it. The problem with my servers, is that they are behind a firewall. I guess I will be able to provide a solution in some weeks though. :(

As for windows compatibility, we made it now to compile it under vs2012 using the commits introduced in this fork:
https://github.com/rajputasif/Pangolin_Win7_VS11

Do you think its reasonable to push them into your repository?

Thank you

**Comment by stevenlovegrove** [comment]
VS11 is quite old! Are you sure you wouldn't rather upgrade :)? Visual Studio community edition is free with no restrictions for research. I can't accept your changes as they are, as they would break on other platforms. I may get a chance to sanitise them at some point, though it would be easier if you are able to maintain a proper git fork with correct history - that would make merging in the future much easier.
