### ISSUE TITLE
Error LNK2005: already defined in packet.obj

### ISSUE THREAD

**Issue by TYDinWorld** [stevenlovegrove/Pangolin#680]
Configure -> Generate -> Open Project on CMake GUI from Windows platform.
This will open Visual Studio 19 Pangolin.sln, it defaulty selects "ALL_BUILD", then build.  Got below such error. not sure anyone get the same issue.

Build started...
1>------ Skipped Build: Project: pypangolin_pip_uninstall, Configuration: MinSizeRel x64 ------
1>Project not selected to build for this solution configuration 
2>------ Skipped Build: Project: uninstall, Configuration: MinSizeRel x64 ------
2>Project not selected to build for this solution configuration 
3>------ Build started: Project: pango_image, Configuration: MinSizeRel x64 ------
4>------ Build started: Project: pango_vars, Configuration: MinSizeRel x64 ------
5>------ Build started: Project: pango_packetstream, Configuration: MinSizeRel x64 ------
5>pango_core.lib(pango_core.dll) : error LNK2005: "protected: __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::basic_streambuf<char,struct std::char_traits<char> >(void)" (??0?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAA@XZ) already defined in packet.obj
5>pango_core.lib(pango_core.dll) : error LNK2005: "public: virtual __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::~basic_streambuf<char,struct std::char_traits<char> >(void)" (??1?$basic_streambuf@DU?$char_traits@D@std@@@std@@UEAA@XZ) already defined in packet.obj
5>pango_core.lib(pango_core.dll) : error LNK2005: "protected: virtual __int64 __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::xsgetn(char *,__int64)" (?xsgetn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAA_JPEAD_J@Z) already defined in packet.obj
5>pango_core.lib(pango_core.dll) : error LNK2005: "protected: virtual __int64 __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::xsputn(char const *,__int64)" (?xsputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAA_JPEBD_J@Z) already defined in packet.obj
4>   Creating library D:/winspace/opensource/Pangolin/build/MinSizeRel/pango_vars.lib and object D:/winspace/opensource/Pangolin/build/MinSizeRel/pango_vars.exp
5>libcpmt.lib(cerr.obj) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::_Gndec(void)" (?_Gndec@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAPEADXZ) already defined in pango_core.lib(pango_core.dll)
5>libcpmt.lib(cerr.obj) : error LNK2005: "protected: void __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::_Init(void)" (?_Init@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAXXZ) already defined in pango_core.lib(pango_core.dll)
5>libcpmt.lib(cerr.obj) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::_Pninc(void)" (?_Pninc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAPEADXZ) already defined in pango_core.lib(pango_core.dll)
5>libcpmt.lib(cerr.obj) : error LNK2005: "protected: void __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::gbump(int)" (?gbump@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAXH@Z) already defined in pango_core.lib(pango_core.dll)
5>libcpmt.lib(cerr.obj) : error LNK2005: "protected: void __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::pbump(int)" (?pbump@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAXH@Z) already defined in pango_core.lib(pango_core.dll)
5>libcpmt.lib(locale.obj) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::_Pninc(void)" (?_Pninc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAPEADXZ) already defined in pango_core.lib(pango_core.dll)
5>libcpmt.lib(locale.obj) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sbumpc(void)" (?sbumpc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ) already defined in pango_core.lib(pango_core.dll)
5>libcpmt.lib(locale.obj) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sgetc(void)" (?sgetc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ) already defined in pango_core.lib(pango_core.dll)
5>libcpmt.lib(locale.obj) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputc(char)" (?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z) already defined in pango_core.lib(pango_core.dll)
5>libcpmt.lib(xlocale.obj) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::_Pninc(void)" (?_Pninc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAPEADXZ) already defined in pango_core.lib(pango_core.dll)
5>libcpmt.lib(xlocale.obj) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sbumpc(void)" (?sbumpc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ) already defined in pango_core.lib(pango_core.dll)
5>libcpmt.lib(xlocale.obj) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sgetc(void)" (?sgetc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ) already defined in pango_core.lib(pango_core.dll)
5>libcpmt.lib(xlocale.obj) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputc(char)" (?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z) already defined in pango_core.lib(pango_core.dll)
5>   Creating library D:/winspace/opensource/Pangolin/build/MinSizeRel/pango_packetstream.lib and object D:/winspace/opensource/Pangolin/build/MinSizeRel/pango_packetstream.exp
3>   Creating library D:/winspace/opensource/Pangolin/build/MinSizeRel/pango_image.lib and object D:/winspace/opensource/Pangolin/build/MinSizeRel/pango_image.exp
3>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
5>LINK : warning LNK4217: symbol '??1?$basic_ios@DU?$char_traits@D@std@@@std@@UEAA@XZ (public: virtual __cdecl std::basic_ios<char,struct std::char_traits<char> >::~basic_ios<char,struct std::char_traits<char> >(void))' defined in 'libcpmt.lib(cerr.obj)' is imported by 'packet.obj' in function '"class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pangolin::FormatString<>(char const *)" (??$FormatString@$$V@pangolin@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD@Z)'
5>LINK : warning LNK4286: symbol '??1?$basic_ios@DU?$char_traits@D@std@@@std@@UEAA@XZ (public: virtual __cdecl std::basic_ios<char,struct std::char_traits<char> >::~basic_ios<char,struct std::char_traits<char> >(void))' defined in 'libcpmt.lib(cerr.obj)' is imported by 'packetstream_reader.obj'
5>LINK : warning LNK4286: symbol '??1?$basic_ios@DU?$char_traits@D@std@@@std@@UEAA@XZ (public: virtual __cdecl std::basic_ios<char,struct std::char_traits<char> >::~basic_ios<char,struct std::char_traits<char> >(void))' defined in 'libcpmt.lib(cerr.obj)' is imported by 'playback_session.obj'
4>LINK : warning LNK4217: symbol '?I@VarState@pangolin@@SAAEAV12@XZ (public: static class pangolin::VarState & __cdecl pangolin::VarState::I(void))' defined in 'varstate.obj' is imported by 'vars.obj' in function '"void __cdecl pangolin::LoadJsonFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?LoadJsonFile@pangolin@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)'
4>LINK : warning LNK4217: symbol '?LoadFromFile@VarState@pangolin@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4FileKind@12@@Z (public: void __cdecl pangolin::VarState::LoadFromFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum pangolin::VarState::FileKind))' defined in 'varstate.obj' is imported by 'vars.obj' in function '"void __cdecl pangolin::LoadJsonFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?LoadJsonFile@pangolin@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)'
4>LINK : warning LNK4217: symbol '?SaveToFile@VarState@pangolin@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4FileKind@12@@Z (public: void __cdecl pangolin::VarState::SaveToFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum pangolin::VarState::FileKind))' defined in 'varstate.obj' is imported by 'vars.obj' in function '"void __cdecl pangolin::SaveJsonFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SaveJsonFile@pangolin@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)'
3>LINK : warning LNK4286: symbol '?PixelFormatFromString@pangolin@@YA?AUPixelFormat@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z (struct pangolin::PixelFormat __cdecl pangolin::PixelFormatFromString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &))' defined in 'pixel_format.obj' is imported by 'image_io_tga.obj'
3>LINK : warning LNK4286: symbol '?PixelFormatFromString@pangolin@@YA?AUPixelFormat@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z (struct pangolin::PixelFormat __cdecl pangolin::PixelFormatFromString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &))' defined in 'pixel_format.obj' is imported by 'image_io_bmp.obj'
3>LINK : warning LNK4286: symbol '?PixelFormatFromString@pangolin@@YA?AUPixelFormat@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z (struct pangolin::PixelFormat __cdecl pangolin::PixelFormatFromString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &))' defined in 'pixel_format.obj' is imported by 'image_io_zstd.obj'
4>varstate.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class pangolin::VarValueGeneric> __cdecl pangolin::VarState::GetByName(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_?GetByName@VarState@pangolin@@QEAA?AV?$shared_ptr@VVarValueGeneric@pangolin@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z) referenced in function "private: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl std::_Func_impl_no_alloc<class <lambda_93281d1f9c0c6f9f4892ab4da5733e20>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &>::_Do_call(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?_Do_call@?$_Func_impl_no_alloc@V<lambda_93281d1f9c0c6f9f4892ab4da5733e20>@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@std@@EEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@AEBV32@@Z)
4>D:\winspace\opensource\Pangolin\build\MinSizeRel\pango_vars.dll : fatal error LNK1120: 1 unresolved externals
4>Done building project "pango_vars.vcxproj" -- FAILED.

**Comment by stevenlovegrove** [comment]
Did you manually adjust the cmake configuration to build shared libraries? I'm a bit of a windows n00b and I only have Pangolin building successfully statically which is why I default to that on Windows (https://github.com/stevenlovegrove/Pangolin/blob/master/CMakeLists.txt#L35). I would love to get the dynamic lib version building but I'm not sure what to change or why it behaves differently to Linux and OSX. 

If you don't need shared libs, set BUILD_SHARED_LIBS=OFF. If you do need them, you could help debug what the problem is :D

**Comment by TYDinWorld** [comment]
Yes.  I enabled dynamic lib. Thanks

**Comment by fangxu622** [comment]
The python need the dynamic library on windows.  But set BUILD_SHARED_LIBS=ON. the compile errors
