### ISSUE TITLE
Picture display error

### ISSUE THREAD

**Issue by Divenire1998** [stevenlovegrove/Pangolin#682]
hello, i am using pangolin to display image,but I found that some of the pictures can not display properly,and there would be dislocation of the pictures（picture in Kitti dataset）.The resolution of the pictrue is 1241 * 376.

![image-20210921100257240](https://tuchuang-1998.oss-accelerate.aliyuncs.com/Picgo/image-20210921100257240.png)

The picture in the upper left corner is displayed correctly, the picture in the lower right corner is misplaced.

```c++
   pangolin::View& cv_img_1 = pangolin::Display("image_1")
        .SetBounds(2/3.0f, 1.0f, 0., 1/3.0f, -640/480.)
        .SetLock(pangolin::LockLeft, pangolin::LockTop);
    
    pangolin::View& cv_img_2 = pangolin::Display("image_2")
        .SetBounds(0., 1/3.0f, 1/3.0f, 1.0, -1241/376.)
        .SetLock(pangolin::LockRight, pangolin::LockBottom);
        
 
    pangolin::GlTexture imgTexture1(640, 480, GL_RGB, false, 0, GL_BGR, GL_UNSIGNED_BYTE);
    pangolin::GlTexture imgTexture2(1241, 376, GL_RGB, false, 0, GL_BGR, GL_UNSIGNED_BYTE);
```

```c++
        cv::Mat img1 = 		cv::imread("/home/divenire/Divenire_ws/dataset/tum/rgbd_dataset_freiburg1_desk/rgb/1305031452.791720.png");
        cv::Mat img2 = cv::imread("/home/divenire/Divenire_ws/dataset/KITTI/dataset/sequences/01/image_0/000099.png");

        imgTexture1.Upload(img1.data, GL_BGR, GL_UNSIGNED_BYTE);
        imgTexture2.Upload(img2.data, GL_BGR, GL_UNSIGNED_BYTE);


        cv_img_1.Activate();
        glColor3f(1.0f, 1.0f, 1.0f); 
        imgTexture1.RenderToViewportFlipY(); 
        
        cv_img_2.Activate();
        glColor3f(1.0f, 1.0f, 1.0f); 
        imgTexture2.RenderToViewportFlipY();
```

and here is origin picture to show

![000000](https://tuchuang-1998.oss-accelerate.aliyuncs.com/Picgo/000000.png)

How can I fix this?

**Comment by stevenlovegrove** [comment]
Is your second image actually 1241 pixels wide? Assuming you've entered the correct size, the most likely explanation is that the cv::Mat structure has some padding in the rows causing things to get messed up. You can tell OpenGL about that using the `glPixelStorei` method with parameter `GL_UNPACK_ALIGNMENT` (see https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPixelStore.xhtml) just before the `imgTexture2.Upload(...)` call.

As a sanity check, you could use Pangolins built in viewer to make sure it can load the image
```
./build/tools/VideoViewer/VideoViewer your_image_file.png
```

If you don't need the image as an OpenCV image, you could alternatively use Pangolins loading functions:
```
#include <pangolin/image/image_io.h>
...
pangolin::GlTexture tex(pangolin::LoadImage("your_image_file.png"))

```

**Comment by Divenire1998** [comment]
Thank you for your reply.

After confirming that the resolution of the image is correct, the image is successfully displayed using the built-in image display tool.Finally . I solve the problem by adding  ` glPixelStorei(GL_UNPACK_ALIGNMENT,1);` before`imgTexture2.Upload(...)`.

Thanks for the help :D
