### ISSUE TITLE
Make error during installation

### ISSUE THREAD

**Issue by chapa17** [stevenlovegrove/Pangolin#683]
I am getting an error while I am trying to install Pangolin on jetson board.

![Screenshot from 2021-09-21 09-18-40](https://user-images.githubusercontent.com/74726040/134154267-81e01cee-36f7-4d47-bb57-f8f1b6fe1283.png)
I am not able to interpret the error. It would be a great help if anyone knows it.

Thank you!

When I see the error logs I find the error which states the following

`Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/xxx/Pangolin/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_614df/fast && /usr/bin/make  -f CMakeFiles/cmTC_614df.dir/build.make CMakeFiles/cmTC_614df.dir/build
make[1]: Entering directory '/home/xxx/Pangolin/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_614df.dir/src.c.o
/usr/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_614df.dir/src.c.o -c /home/xxx/Pangolin/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_614df
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_614df.dir/link.txt --verbose=1
/usr/bin/cc CMakeFiles/cmTC_614df.dir/src.c.o -o cmTC_614df 
CMakeFiles/cmTC_614df.dir/src.c.o: In function `main':
src.c:(.text+0x48): undefined reference to `pthread_create'
src.c:(.text+0x50): undefined reference to `pthread_detach'
src.c:(.text+0x58): undefined reference to `pthread_cancel'
src.c:(.text+0x64): undefined reference to `pthread_join'
src.c:(.text+0x74): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_614df.dir/build.make:98: recipe for target 'cmTC_614df' failed
make[1]: *** [cmTC_614df] Error 1
make[1]: Leaving directory '/home/xxx/Pangolin/build/CMakeFiles/CMakeTmp'
Makefile:127: recipe for target 'cmTC_614df/fast' failed
make: *** [cmTC_614df/fast] Error 2

Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/xxx/Pangolin/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_e6be9/fast && /usr/bin/make  -f CMakeFiles/cmTC_e6be9.dir/build.make CMakeFiles/cmTC_e6be9.dir/build
make[1]: Entering directory '/home/xxx/Pangolin/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_e6be9.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create -o CMakeFiles/cmTC_e6be9.dir/CheckFunctionExists.c.o -c /usr/local/share/cmake-3.20/Modules/CheckFunctionExists.c
Linking C executable cmTC_e6be9
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e6be9.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create CMakeFiles/cmTC_e6be9.dir/CheckFunctionExists.c.o -o cmTC_e6be9  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_e6be9.dir/build.make:98: recipe for target 'cmTC_e6be9' failed
make[1]: *** [cmTC_e6be9] Error 1
make[1]: Leaving directory '/home/xxx/Pangolin/build/CMakeFiles/CMakeTmp'
Makefile:127: recipe for target 'cmTC_e6be9/fast' failed
make: *** [cmTC_e6be9/fast] Error 2`

**Comment by chapa17** [comment]
Thank you I got rid of that error but now I am getting error related to openEXR while running make command. Do you have any idea about the same?

<img width="551" alt="Screenshot from 2021-09-27 09-43-34" src="https://user-images.githubusercontent.com/74726040/134866138-bdccf479-f2f5-4f47-a361-0d4ae915a72e.png">

Thank you!

**Comment by chapa17** [comment]
Thank you. I resolved all the errors and it works fine. When I run a test example ./HelloPangolin I get the following message on the command window 

`Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.`

I also see the result window properly. But I am concerned about the message that I get because when I installed Pangolin on Jetson board previously I did not see similar message. 

Thank you.

**Comment by stevenlovegrove** [comment]
> `Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.`

This is generally caused by incorrect, unusual or software OpenGL drivers (e.g. limited GL support in virtual machine or over X forwrding etc).

There are some other issues like this with different causes that you can look at if you like.
https://github.com/stevenlovegrove/Pangolin/issues?q=is%3Aissue+Framebuffer+with+requested+attributes+not+available+
