### ISSUE TITLE
make cmake version dependent on features

### ISSUE THREAD

**Issue by christian-rauch** [stevenlovegrove/Pangolin#684]
The minimum CMake version was bumped to 3.17 in 085e854ae7ca2d435377edcb0a098619e81e6518 to solve an issue with pypangolin (#679). This is quite inconvenient for users of long-term Ubuntu versions since Ubuntu 20.04 LTS only comes with 3.16.3. The reason for this new version is that `${CMAKE_CURRENT_FUNCTION_LIST_DIR}` is used but only defined for newer CMake versions.

To make Pangolin build on Ubuntu LTS, can we implement a workaround for `${CMAKE_CURRENT_FUNCTION_LIST_DIR}` or make the newer version dependant on if `pypangolin` is built or not?

**Comment by stevenlovegrove** [comment]
sorry this broke something for you - I'm surprise 20.04 comes with 3.16. I'm sure we can figure out an alternative to CMAKE_CURRENT_FUNCTION_LIST_DIR
