### ISSUE TITLE
Cmake Error when Linking VideoViewer

### ISSUE THREAD

**Issue by belkahorry** [stevenlovegrove/Pangolin#685]
Ubuntu 20.04 Cmake 3.17.3
Error occurred at 94%
Found a similar one #509 , but not exactly
How can i fix it? thank you

Scanning dependencies of target tinyobj
[  1%] Building CXX object CMakeFiles/tinyobj.dir/components/tinyobj/src/tinyobj.cpp.o
[  2%] Linking CXX shared library libtinyobj.so
[  2%] Built target tinyobj
Scanning dependencies of target pango_core
[  3%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/file_extension.cpp.o
[  3%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/file_utils.cpp.o
[  4%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/sigstate.cpp.o
[  4%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/threadedfilebuf.cpp.o
[  5%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/avx_math.cpp.o
[  6%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/uri.cpp.o
[  6%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/param_set.cpp.o
[  7%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/factory/factory_registry.cpp.o
[  7%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/factory/factory_help.cpp.o
[  8%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/posix/condition_variable.cpp.o
[  8%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/posix/semaphore.cpp.o
[  9%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/posix/shared_memory_buffer.cpp.o
[  9%] Linking CXX shared library libpango_core.so
[  9%] Built target pango_core
Scanning dependencies of target pango_image
[  9%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/pixel_format.cpp.o
[ 10%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io.cpp.o
[ 10%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_exr.cpp.o
[ 11%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_jpg.cpp.o
[ 11%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_lz4.cpp.o
[ 12%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_packed12bit.cpp.o
[ 12%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_pango.cpp.o
[ 13%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_png.cpp.o
[ 14%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_ppm.cpp.o
[ 14%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_raw.cpp.o
[ 15%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_tga.cpp.o
[ 15%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_bmp.cpp.o
[ 16%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_zstd.cpp.o
[ 16%] Linking CXX shared library libpango_image.so
[ 16%] Built target pango_image
[ 17%] Embedding /home/horry/Pangolin/components/pango_opengl/src/fonts/AnonymousPro.ttf into fonts.cpp
Scanning dependencies of target pango_opengl
[ 17%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glchar.cpp.o
[ 18%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/gldraw.cpp.o
[ 18%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glfont.cpp.o
[ 19%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/gltext.cpp.o
[ 19%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glpangoglu.cpp.o
[ 20%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/gltexturecache.cpp.o
[ 20%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/viewport.cpp.o
[ 21%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/opengl_render_state.cpp.o
[ 21%] Building CXX object CMakeFiles/pango_opengl.dir/fonts.cpp.o
[ 22%] Linking CXX shared library libpango_opengl.so
[ 22%] Built target pango_opengl
[ 23%] Creating /home/horry/Pangolin/build/include/pangolin/factory/RegisterFactoriesWindowInterface.h factory registry header
Scanning dependencies of target pango_windowing
[ 23%] Building CXX object CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_x11.cpp.o
[ 24%] Building CXX object CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_headless.cpp.o
[ 24%] Building CXX object CMakeFiles/pango_windowing.dir/components/pango_windowing/src/window.cpp.o
[ 25%] Linking CXX shared library libpango_windowing.so
[ 25%] Built target pango_windowing
Scanning dependencies of target pango_vars
[ 26%] Building CXX object CMakeFiles/pango_vars.dir/components/pango_vars/src/vars.cpp.o
[ 26%] Building CXX object CMakeFiles/pango_vars.dir/components/pango_vars/src/varstate.cpp.o
[ 27%] Linking CXX shared library libpango_vars.so
[ 27%] Built target pango_vars
Scanning dependencies of target pango_display
[ 28%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/display.cpp.o
[ 28%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/process.cpp.o
[ 29%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/pangolin_gl.cpp.o
[ 29%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/handler.cpp.o
[ 30%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/handler_image.cpp.o
[ 30%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/handler_glbuffer.cpp.o
[ 31%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/view.cpp.o
[ 31%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/widgets.cpp.o
[ 32%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/image_view.cpp.o
[ 33%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/ConsoleView.cpp.o
[ 33%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/default_font.cpp.o
[ 34%] Linking CXX shared library libpango_display.so
[ 34%] Built target pango_display
Scanning dependencies of target pango_geometry
[ 34%] Building CXX object CMakeFiles/pango_geometry.dir/components/pango_geometry/src/geometry.cpp.o
[ 35%] Building CXX object CMakeFiles/pango_geometry.dir/components/pango_geometry/src/geometry_obj.cpp.o
[ 35%] Building CXX object CMakeFiles/pango_geometry.dir/components/pango_geometry/src/geometry_ply.cpp.o
[ 36%] Linking CXX shared library libpango_geometry.so
[ 36%] Built target pango_geometry
Scanning dependencies of target pango_glgeometry
[ 36%] Building CXX object CMakeFiles/pango_glgeometry.dir/components/pango_glgeometry/src/glgeometry.cpp.o
[ 37%] Linking CXX shared library libpango_glgeometry.so
[ 37%] Built target pango_glgeometry
Scanning dependencies of target pango_packetstream
[ 38%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/packet.cpp.o
[ 38%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/packetstream.cpp.o
[ 39%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/packetstream_reader.cpp.o
[ 39%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/packetstream_writer.cpp.o
[ 40%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/playback_session.cpp.o
[ 40%] Linking CXX shared library libpango_packetstream.so
[ 40%] Built target pango_packetstream
[ 41%] Creating /home/horry/Pangolin/build/include/pangolin/factory/RegisterFactoriesVideoOutputInterface.h factory registry header
[ 41%] Creating /home/horry/Pangolin/build/include/pangolin/factory/RegisterFactoriesVideoInterface.h factory registry header
Scanning dependencies of target pango_video
[ 41%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/stream_encoder_factory.cpp.o
[ 42%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/video_input.cpp.o
[ 42%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/video_output.cpp.o
[ 43%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/video.cpp.o
[ 43%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/video_help.cpp.o
[ 44%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/test.cpp.o
[ 44%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/images.cpp.o
[ 45%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/images_out.cpp.o
[ 46%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/split.cpp.o
[ 46%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/truncate.cpp.o
[ 47%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/pango.cpp.o
[ 47%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/pango_video_output.cpp.o
[ 48%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/debayer.cpp.o
[ 48%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/shift.cpp.o
[ 49%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/transform.cpp.o
[ 49%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/unpack.cpp.o
[ 50%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/pack.cpp.o
[ 50%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/join.cpp.o
[ 51%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/merge.cpp.o
[ 51%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/json.cpp.o
[ 52%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/thread.cpp.o
[ 52%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/shared_memory.cpp.o
[ 53%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/v4l.cpp.o
[ 53%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/ffmpeg.cpp.o
[ 54%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/ffmpeg_convert.cpp.o
[ 55%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/ffmpeg_output.cpp.o
[ 55%] Linking CXX shared library libpango_video.so
[ 55%] Built target pango_video
Scanning dependencies of target pango_scene
[ 56%] Building CXX object CMakeFiles/pango_scene.dir/components/pango_scene/src/renderable.cpp.o
[ 56%] Linking CXX shared library libpango_scene.so
[ 56%] Built target pango_scene
Scanning dependencies of target pango_plot
[ 57%] Building CXX object CMakeFiles/pango_plot.dir/components/pango_plot/src/datalog.cpp.o
[ 57%] Building CXX object CMakeFiles/pango_plot.dir/components/pango_plot/src/plotter.cpp.o
[ 58%] Linking CXX shared library libpango_plot.so
[ 58%] Built target pango_plot
Scanning dependencies of target pypangolin
[ 58%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin_module.cpp.o
[ 59%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/attach.cpp.o
[ 59%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/colour.cpp.o
[ 60%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/datalog.cpp.o
[ 60%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/display.cpp.o
[ 61%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/gl.cpp.o
[ 61%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/gl_draw.cpp.o
[ 62%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/glsl.cpp.o
[ 62%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/glvbo.cpp.o
[ 63%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/handler.cpp.o
[ 64%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/image.cpp.o
[ 64%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/image_view.cpp.o
[ 65%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/opengl_render_state.cpp.o
[ 65%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/params.cpp.o
[ 66%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/pixel_format.cpp.o
[ 66%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/plotter.cpp.o
[ 67%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/pypangoio.cpp.o
[ 67%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/var.cpp.o
[ 68%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/video.cpp.o
[ 68%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/view.cpp.o
[ 69%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/viewport.cpp.o
[ 69%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/widget.cpp.o
[ 70%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/window.cpp.o
[ 70%] Linking CXX shared module pypangolin-0.7.data/purelib/pypangolin.cpython-38-x86_64-linux-gnu.so
[ 70%] Built target pypangolin
Scanning dependencies of target pango_tools
[ 71%] Building CXX object CMakeFiles/pango_tools.dir/components/pango_tools/src/video_viewer.cpp.o
[ 71%] Linking CXX shared library libpango_tools.so
[ 71%] Built target pango_tools
Scanning dependencies of target pango_python
[ 71%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pyinterpreter.cpp.o
In file included from /home/horry/Pangolin/components/pango_python/src/pyinterpreter.cpp:27:
/home/horry/Pangolin/components/pango_python/include/pangolin/python/pyinterpreter.h:40:7: warning: ‘pangolin::PyInterpreter’ declared with greater visibility than the type of its field ‘pangolin::PyInterpreter::guard’ [-Wattributes]
   40 | class PyInterpreter : public InterpreterInterface
      |       ^~~~~~~~~~~~~
/home/horry/Pangolin/components/pango_python/include/pangolin/python/pyinterpreter.h:40:7: warning: ‘pangolin::PyInterpreter’ declared with greater visibility than the type of its field ‘pangolin::PyInterpreter::pycompleter’ [-Wattributes]
/home/horry/Pangolin/components/pango_python/include/pangolin/python/pyinterpreter.h:40:7: warning: ‘pangolin::PyInterpreter’ declared with greater visibility than the type of its field ‘pangolin::PyInterpreter::pycomplete’ [-Wattributes]
[ 72%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin_embed.cpp.o
[ 72%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/attach.cpp.o
[ 73%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/colour.cpp.o
[ 73%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/datalog.cpp.o
[ 74%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/display.cpp.o
[ 74%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/gl.cpp.o
[ 75%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/gl_draw.cpp.o
[ 76%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/glsl.cpp.o
[ 76%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/glvbo.cpp.o
[ 77%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/handler.cpp.o
[ 77%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/image.cpp.o
[ 78%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/image_view.cpp.o
[ 78%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/opengl_render_state.cpp.o
[ 79%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/params.cpp.o
[ 79%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/pixel_format.cpp.o
[ 80%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/plotter.cpp.o
[ 80%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/pypangoio.cpp.o
[ 81%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/var.cpp.o
[ 81%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/video.cpp.o
[ 82%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/view.cpp.o
[ 82%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/viewport.cpp.o
[ 83%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/widget.cpp.o
[ 83%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/window.cpp.o
[ 84%] Linking CXX shared library libpango_python.so
[ 84%] Built target pango_python
Scanning dependencies of target HelloPangolin
[ 84%] Building CXX object examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/main.cpp.o
[ 85%] Linking CXX executable HelloPangolin
[ 85%] Built target HelloPangolin
Scanning dependencies of target SimpleDisplay
[ 85%] Building CXX object examples/SimpleDisplay/CMakeFiles/SimpleDisplay.dir/main.cpp.o
[ 86%] Linking CXX executable SimpleDisplay
[ 86%] Built target SimpleDisplay
Scanning dependencies of target SimpleMultiDisplay
[ 86%] Building CXX object examples/SimpleMultiDisplay/CMakeFiles/SimpleMultiDisplay.dir/main.cpp.o
[ 87%] Linking CXX executable SimpleMultiDisplay
[ 87%] Built target SimpleMultiDisplay
Scanning dependencies of target SimpleDisplayImage
[ 87%] Building CXX object examples/SimpleDisplayImage/CMakeFiles/SimpleDisplayImage.dir/main.cpp.o
[ 88%] Linking CXX executable SimpleDisplayImage
[ 88%] Built target SimpleDisplayImage
Scanning dependencies of target SimplePlot
[ 88%] Building CXX object examples/SimplePlot/CMakeFiles/SimplePlot.dir/main.cpp.o
[ 89%] Linking CXX executable SimplePlot
[ 89%] Built target SimplePlot
Scanning dependencies of target SimpleVideo
[ 90%] Building CXX object examples/SimpleVideo/CMakeFiles/SimpleVideo.dir/main.cpp.o
[ 90%] Linking CXX executable SimpleVideo
[ 90%] Built target SimpleVideo
Scanning dependencies of target SimpleRecord
[ 90%] Building CXX object examples/SimpleRecord/CMakeFiles/SimpleRecord.dir/main.cpp.o
[ 91%] Linking CXX executable SimpleRecord
[ 91%] Built target SimpleRecord
Scanning dependencies of target HelloPangolinOffscreen
[ 91%] Building CXX object examples/HelloPangolinOffscreen/CMakeFiles/HelloPangolinOffscreen.dir/main.cpp.o
[ 92%] Linking CXX executable HelloPangolinOffscreen
[ 92%] Built target HelloPangolinOffscreen
Scanning dependencies of target SimpleScene
[ 93%] Building CXX object examples/SimpleScene/CMakeFiles/SimpleScene.dir/main.cpp.o
[ 93%] Linking CXX executable SimpleScene
[ 93%] Built target SimpleScene
Scanning dependencies of target VideoViewer
[ 94%] Building CXX object tools/VideoViewer/CMakeFiles/VideoViewer.dir/main.cpp.o
[ 94%] Linking CXX executable VideoViewer
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `keypad@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `mousemask@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `LINES@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `nonl@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `nodelay@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `start_color@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `noecho@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `stdscr@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `init_pair@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `wattrset@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `ungetch@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `endwin@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `ESCDELAY@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `mouseinterval@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `newterm@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `resize_term@NCURSESW6_5.3.20021019'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `noraw@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `COLORS@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `COLS@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `curs_set@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `wmove@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `waddnstr@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `wrefresh@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `wattr_on@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `curscr@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `raw@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `getmouse@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `wgetch@NCURSESW6_5.1.20000708'
/usr/bin/ld: /lib/x86_64-linux-gnu/libcaca.so.0: undefined reference to `initscr@NCURSESW6_5.1.20000708'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/VideoViewer/CMakeFiles/VideoViewer.dir/build.make:124：tools/VideoViewer/VideoViewer] Error 1
make[1]: *** [CMakeFiles/Makefile2:1433：tools/VideoViewer/CMakeFiles/VideoViewer.dir/all] Error 2
make: *** [Makefile:150：all] Error 2

**Comment by stevenlovegrove** [comment]
You need to figure out how libcaca is getting included. Pangolin certainly doesn't intend to link against it. It looks like it's found a funny version of OpenGL or something that does text graphics (did you set something like that up?). I'd recommend examining the GL libraries found using CMake (either cmake-gui or ccmake, your choice).

**Comment by brentyi** [comment]
I had this exact error and it seemed to be caused by an extra copy of ncurses from a miniconda install; temporarily uninstalling the conda one via `conda uninstall --force ncurses` fixed it.

**Comment by sonomag13** [comment]
@brentyi thanks for the response. I think there is a conflict is due to Anaconda. Just to make my life easier, I reinstalled Ubuntu 20, and installed Pangolin without any Anaconda. It works now.

**Comment by haithink** [comment]
> @brentyi thanks for the response. I think there is a conflict is due to Anaconda. Just to make my life easier, I reinstalled Ubuntu 20, and installed Pangolin without any Anaconda. It works now.

Just execute "conda deactivate" in shell, exit conda base environment.

**Comment by qwert12131990** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
