### ISSUE TITLE
cmake error "pybind11::embed"

### ISSUE THREAD

**Issue by Sherlock-hh** [stevenlovegrove/Pangolin#686]
Hi, thanks for your work! but when I tried to cmake, I met some problems , here are the error information:
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
CMake Warning at CMakeLists.txt:75 (message):
  Building Tests requested, but Catch2 library not found.

-- libjpeg Found and Enabled
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9")
-- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython3.6m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- Performing Test HAS_CPP11_FLAG
-- Performing Test HAS_CPP11_FLAG - Success
-- Performing Test HAS_LTO_FLAG
-- Performing Test HAS_LTO_FLAG - Success
-- Selected Python: '/usr/bin/python3.6'. cmake --build . -t pypangolin_pip_install to use pypangolin module.
-- V4L Found and Enabled
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- RealSense2 Found and Enabled
-- Found Threads: TRUE
-- Configuring done
CMake Error at CMakeLists.txt:88 (add_library):
  Target "pango_python" links to target "pybind11::embed" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at examples/HelloPangolin/CMakeLists.txt:5 (add_executable):
  Target "HelloPangolin" links to target "pybind11::embed" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at examples/SimpleDisplay/CMakeLists.txt:5 (add_executable):
  Target "SimpleDisplay" links to target "pybind11::embed" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at tools/VideoViewer/CMakeLists.txt:5 (add_executable):
  Target "VideoViewer" links to target "pybind11::embed" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at tools/VideoConvert/CMakeLists.txt:5 (add_executable):
  Target "VideoConvert" links to target "pybind11::embed" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at tools/VideoJson/CMakeLists.txt:5 (add_executable):
  Target "VideoJsonPrint" links to target "pybind11::embed" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at tools/VideoJson/CMakeLists.txt:8 (add_executable):
  Target "VideoJsonTransform" links to target "pybind11::embed" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at tools/Plotter/CMakeLists.txt:5 (add_executable):
  Target "Plotter" links to target "pybind11::embed" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at tools/ModelViewer/CMakeLists.txt:5 (add_executable):
  Target "ModelViewer" links to target "pybind11::embed" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

any advice you can give I'll be very appreciate it, thanks!

**Comment by stevenlovegrove** [comment]
Hi,

There's probably an issue here https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_python/CMakeLists.txt#L6. If you checked out the submodules (with the recursive checkout), you should be falling into the add_subdirectory, otherwise I guess you're falling into the other way. Perhaps you have an older version of pybind11 installed and you didn't checkout the submodule? If you haven't already, I'd try checking out the pybind11 submodule. If you have, then I don't really have any ideas.

If all fails you could disable python support by using cmake-gui or ccmake to zero out the python directories

**Comment by Sherlock-hh** [comment]
> Hi,
> 
> There's probably an issue here https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_python/CMakeLists.txt#L6. If you checked out the submodules (with the recursive checkout), you should be falling into the add_subdirectory, otherwise I guess you're falling into the other way. Perhaps you have an older version of pybind11 installed and you didn't checkout the submodule? If you haven't already, I'd try checking out the pybind11 submodule. If you have, then I don't really have any ideas.
> 
> If all fails you could disable python support by using cmake-gui or ccmake to zero out the python directories

Thanks for your reply, I tried to reinstall pybind11, and use find_package(pybind11) in the cmakelist, It's solved the problem, but come up the error "could not found "Python.h"" when I was compiled,  then I use update-alternative s install to set the priority of python3 higher than python2, because the cmake info shows it choosed python3, then problem solved.
It looks exactly like you said,  it’s related to the version and add_submodules of pybind and python，Thank you very much!
