### ISSUE TITLE
Ctest does not work

### ISSUE THREAD

**Issue by maghauke** [stevenlovegrove/Pangolin#687]
After folllowing the build instruction:
`

# Get Pangolin
cd ~/your_fav_code_directory
git clone --recursive https://github.com/stevenlovegrove/Pangolin.git
cd Pangolin 

# Install dependencies (as described above, or your preferred method)
./scripts/install_prerequisites.sh recommended

# Configure and build
mkdir build && cd build
cmake ..
cmake --build .

# GIVEME THE PYTHON STUFF!!!! (Check the output to verify selected python version)
cmake --build . -t pypangolin_pip_install

# Run me some tests!
ctest
`

I get the the message when running ctest:

`
*********************************
No test configuration file found!
*********************************
Usage

  ctest [options]

`

Does anyone know why?

**Comment by stevenlovegrove** [comment]
Ah, I bet you're on Ubuntu and I removed catch2 from the recommended packages because it isn't available on 20.04 or before (https://github.com/stevenlovegrove/Pangolin/commit/b5677a023a356b5c6c2c4f610373e677a072cade). I should add that to the readme.

**Comment by stevenlovegrove** [comment]
Please reopen if my assumption is wrong.
best,

**Comment by GasparPizarro** [comment]
I see the same:


    *********************************
    No test configuration file found!
    *********************************
    Usage

      ctest [options]

But doesn't that mean `ctest` is already installed in my system? I can run `man ctest` and everything

**Comment by stevenlovegrove** [comment]
catch2 is called by ctest. Without catch2, ctest wont find any tests. ctest comes with cmake I think, so that will always be there.

**Comment by Prashambhuta** [comment]
I have catch2 on Ubuntu 20.04 as per the instructions in Git Repo. Still running `ctest` shows the same error of **Configuration File Not Found**

**Comment by AbhiKhoyani** [comment]
same error for me as well. I've installed catch2 in windows 10 with vcpkg using install_prerequisite.sh only.

**Comment by Lynx1129** [comment]
> I have catch2 on Ubuntu 20.04 as per the instructions in Git Repo. Still running `ctest` shows the same error of **Configuration File Not Found**

same error, did you solve it?
