### ISSUE TITLE
PANGOLIN_DEPRECATED undefined in glcuda.h

### ISSUE THREAD

**Issue by christian-rauch** [stevenlovegrove/Pangolin#689]
Whenever using the header `glcuda.h` I am getting `error: ‘PANGOLIN_DEPRECATED’ does not name a type` for
https://github.com/stevenlovegrove/Pangolin/blob/39d12a0b1e543b2e57a7db52525b872e93467946/components/pango_opengl/include/pangolin/gl/glcuda.h#L52-L53

 Looking at other examples, it looks like this is a macro that should be used like `PANGOLIN_DEPRECATED("Use <new method> instead.")`.

**Comment by stevenlovegrove** [comment]
Thanks!

**Comment by stevenlovegrove** [comment]
This shows that we don't have any CUDA builds on the CI server. I wonder if github actions supports that....
