### ISSUE TITLE
Pangolin X11: Failed to create an OpenGL context

### ISSUE THREAD

**Issue by YangLiu-DayDreammer** [stevenlovegrove/Pangolin#69]
Hello, I am currently testing a Project ElasticFusion which depends on Pangolin.
But I got a error when debuging it.
Seems 	    pangolin::CreateWindowAndBind("Main", width, height, windowParams); throws the error.

In terminal, is shows 
"terminate called after throwing an instance of 'std::runtime_error'
 what():  Pangolin X11: Failed to create an OpenGL context
Aborted (core dumped)
"
Can you help me?

**Comment by stevenlovegrove** [comment]
It sounds like your environment does not have associated with it a display that supports OpenGL. Are you invoking ElasticFusion from an SSH shell or similar? Make sure something like glxgears works for you first.

**Comment by stevenlovegrove** [comment]
This is related to discussion in #81, which offers a workaround.

**Comment by stevenlovegrove** [comment]
Well, it *may* be related. You could see if 45b38c15fae075aec0e3e865780b5235b4055848 on the devel branch fixes anything.

**Comment by YangLiu-DayDreammer** [comment]
Thank you for reply! I reinstalled everything on my ubuntu 14.04 to make it a clean one. Then I install dependent packages following instructions and that problem gone. Well maybe there is some problem with my OpenGL install.

**Comment by stevenlovegrove** [comment]
Thanks for the update. I'll close this issue for now.
