### ISSUE TITLE
Building on Windows and Eigen

### ISSUE THREAD

**Issue by PNeigel** [stevenlovegrove/Pangolin#692]
Maybe related to #574, but didn't help me.

I cannot configure CMake on Windows because of Eigen. First problem, it is not found, which is understandable since it's a header only library. These two CMakeLists need Eigen3

https://github.com/stevenlovegrove/Pangolin/blob/52c45bae301b08892b8b1afe5ed1f489fdbfc1d9/components/pango_geometry/CMakeLists.txt#L3

https://github.com/stevenlovegrove/Pangolin/blob/52c45bae301b08892b8b1afe5ed1f489fdbfc1d9/components/pango_opengl/CMakeLists.txt#L21

First problem here is that the ```CONFIG``` parameter makes CMake look for ```Eigen3Config.cmake``` or ```eigen3-config.cmake```, which doesn't exist in the eigen3 unpacked source.

If the ```CONFIG``` parameter is changed to ```MODULE``` then find_package would invoke a FindEigen3.cmake, except it doesn't exist. If I rename [FindEigen.cmake](https://github.com/stevenlovegrove/Pangolin/blob/52c45bae301b08892b8b1afe5ed1f489fdbfc1d9/cmake/FindEigen.cmake) into FindEigen3.cmake, then the script is used and (in accordance to #574) the EIGEN_INCLUDE_DIR is actually found and ```Eigen_FIND_VERSION``` is correctly set (in my case to 3.4.90), but CMake now complains that
```CMake Error at examples/BasicOpenGL/CMakeLists.txt:2 (find_package):
Found package configuration file:

  C:/path/deps/Pangolin/build/PangolinConfig.cmake

but it set Pangolin_FOUND to FALSE so package "Pangolin" is considered to
be NOT FOUND.  Reason given by package:

Pangolin could not be found because dependency Eigen3 could not be found.
```

If I then manually just add a variable ```Eigen3_FOUND=1```, then it configures, but actually generating the build files gives me a ton of errors like
```
CMake Error at tools/ModelViewer/CMakeLists.txt:5 (add_executable):
  Target "ModelViewer" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at tools/ModelViewer/CMakeLists.txt:5 (add_executable):
  Target "ModelViewer" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:88 (add_library):
  Target "pango_opengl" links to target "Eigen3::Eigen" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```
That's where I'm currently stuck.

**Comment by PNeigel** [comment]
Okay I resolved it by... actually running CMake on Eigen 🤦‍♂️. The [Eigen webpage](https://eigen.tuxfamily.org/index.php?title=Main_Page) bamboozled me with the following:

> We use the CMake build system, but only to build the documentation and unit-tests, and to automate installation. If you just want to use Eigen, you can use the header files right away. There is no binary library to link to, and no configured header file. Eigen is a pure template library defined in the headers. 

so I thought it's optional, but it creates the needed ```Eigen3Config.cmake``` for
https://github.com/stevenlovegrove/Pangolin/blob/52c45bae301b08892b8b1afe5ed1f489fdbfc1d9/components/pango_geometry/CMakeLists.txt#L3
and 
https://github.com/stevenlovegrove/Pangolin/blob/52c45bae301b08892b8b1afe5ed1f489fdbfc1d9/components/pango_opengl/CMakeLists.txt#L21

**Comment by stevenlovegrove** [comment]
Glad you solved this because I looked at this yesterday and wasn't sure what to suggest!

**Comment by dorioliu** [comment]
@PNeigel  Hello, pNeigel,  excuse me, I saw you solve the cmake issue of Eigen when compiling Pangolin on Windows. What is meaning of " running cmake on Eigen" in your answer, did you mean using Cmake-gui to compile Eigen and then generated Eigen3Config.cmake? Thanks, I also met the same question.
