### ISSUE TITLE
GetFileContents(const std::string) undefined for Windows

### ISSUE THREAD

**Issue by PNeigel** [stevenlovegrove/Pangolin#693]
Is the following function definition excluded from Windows builds on purpose?

https://github.com/stevenlovegrove/Pangolin/blob/52c45bae301b08892b8b1afe5ed1f489fdbfc1d9/components/pango_core/src/file_utils.cpp#L525-L543

Seems like the #endif should come after the bool FileExists() function. Moving it there solved my linking problems.

**Comment by stevenlovegrove** [comment]
Ah, you're right! Thanks! I'll patch that when I next get a chance.
