### ISSUE TITLE
No Target pypangolin_pip_install

### ISSUE THREAD

**Issue by stevenlovegrove** [stevenlovegrove/Pangolin#694]
I want to use import pypangolin in python.But in the past many days, I have been encountering pypangolin has no attribute "CreateWindowsAndBind". I haven't been able to solve it these days
So，I don't know what to do next after **cmake --build .**

**(sdf) zenghui@Ubuntu:~/Pangolin/build$ cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
CMake Warning at CMakeLists.txt:75 (message):
**Building Tests requested, but Catch2 library not found.**

-- V4L Found and Enabled
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zenghui/Pangolin/build
**(sdf) zenghui@Ubuntu:~/Pangolin/build$ cmake --build .**
Scanning dependencies of target tinyobj
[ 0%] Building CXX object CMakeFiles/tinyobj.dir/components/tinyobj/src/tinyobj.cpp.o
[ 1%] Linking CXX shared library libtinyobj.so
[ 1%] Built target tinyobj
Scanning dependencies of target pango_core
[ 2%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/file_extension.cpp.o
[ 2%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/file_utils.cpp.o
[ 3%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/sigstate.cpp.o
[ 4%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/threadedfilebuf.cpp.o
[ 4%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/avx_math.cpp.o
[ 5%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/uri.cpp.o
[ 6%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/param_set.cpp.o
[ 6%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/factory/factory_registry.cpp.o
[ 7%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/factory/factory_help.cpp.o
[ 7%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/posix/condition_variable.cpp.o
[ 8%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/posix/semaphore.cpp.o
[ 9%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/posix/shared_memory_buffer.cpp.o
[ 9%] Linking CXX shared library libpango_core.so
[ 9%] Built target pango_core
Scanning dependencies of target pango_image
[ 10%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/pixel_format.cpp.o
[ 10%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io.cpp.o
[ 11%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_exr.cpp.o
[ 12%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_jpg.cpp.o
[ 12%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_lz4.cpp.o
[ 13%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_packed12bit.cpp.o
[ 14%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_pango.cpp.o
[ 14%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_png.cpp.o
[ 15%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_ppm.cpp.o
[ 16%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_raw.cpp.o
[ 16%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_tga.cpp.o
[ 17%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_bmp.cpp.o
[ 18%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_zstd.cpp.o
[ 18%] Linking CXX shared library libpango_image.so
[ 18%] Built target pango_image
[ 19%] Embedding /home/zenghui/Pangolin/components/pango_opengl/src/fonts/AnonymousPro.ttf into fonts.cpp
Scanning dependencies of target pango_opengl
[ 20%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glchar.cpp.o
[ 20%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/gldraw.cpp.o
[ 21%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glfont.cpp.o
[ 21%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/gltext.cpp.o
[ 22%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glpangoglu.cpp.o
[ 23%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/gltexturecache.cpp.o
[ 23%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/viewport.cpp.o
[ 24%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/opengl_render_state.cpp.o
[ 25%] Building CXX object CMakeFiles/pango_opengl.dir/fonts.cpp.o
[ 25%] Linking CXX shared library libpango_opengl.so
[ 25%] Built target pango_opengl
[ 25%] Creating /home/zenghui/Pangolin/build/include/pangolin/factory/RegisterFactoriesWindowInterface.h factory registry header
Scanning dependencies of target pango_windowing
[ 26%] Building CXX object CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_x11.cpp.o
[ 27%] Building CXX object CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_headless.cpp.o
[ 27%] Building CXX object CMakeFiles/pango_windowing.dir/components/pango_windowing/src/window.cpp.o
[ 28%] Linking CXX shared library libpango_windowing.so
[ 28%] Built target pango_windowing
Scanning dependencies of target pango_vars
[ 28%] Building CXX object CMakeFiles/pango_vars.dir/components/pango_vars/src/vars.cpp.o
[ 29%] Building CXX object CMakeFiles/pango_vars.dir/components/pango_vars/src/varstate.cpp.o
[ 30%] Linking CXX shared library libpango_vars.so
[ 30%] Built target pango_vars
Scanning dependencies of target pango_display
[ 31%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/display.cpp.o
[ 32%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/process.cpp.o
[ 32%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/pangolin_gl.cpp.o
[ 33%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/handler.cpp.o
[ 34%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/handler_image.cpp.o
[ 34%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/handler_glbuffer.cpp.o
[ 35%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/view.cpp.o
[ 36%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/widgets.cpp.o
[ 36%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/image_view.cpp.o
[ 37%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/ConsoleView.cpp.o
[ 38%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/default_font.cpp.o
[ 38%] Linking CXX shared library libpango_display.so
[ 38%] Built target pango_display
Scanning dependencies of target pango_geometry
[ 39%] Building CXX object CMakeFiles/pango_geometry.dir/components/pango_geometry/src/geometry.cpp.o
[ 40%] Building CXX object CMakeFiles/pango_geometry.dir/components/pango_geometry/src/geometry_obj.cpp.o
[ 40%] Building CXX object CMakeFiles/pango_geometry.dir/components/pango_geometry/src/geometry_ply.cpp.o
[ 41%] Linking CXX shared library libpango_geometry.so
[ 41%] Built target pango_geometry
Scanning dependencies of target pango_glgeometry
[ 41%] Building CXX object CMakeFiles/pango_glgeometry.dir/components/pango_glgeometry/src/glgeometry.cpp.o
[ 42%] Linking CXX shared library libpango_glgeometry.so
[ 42%] Built target pango_glgeometry
Scanning dependencies of target pango_packetstream
[ 43%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/packet.cpp.o
[ 44%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/packetstream.cpp.o
[ 44%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/packetstream_reader.cpp.o
[ 45%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/packetstream_writer.cpp.o
[ 46%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/playback_session.cpp.o
[ 46%] Linking CXX shared library libpango_packetstream.so
[ 46%] Built target pango_packetstream
[ 47%] Creating /home/zenghui/Pangolin/build/include/pangolin/factory/RegisterFactoriesVideoOutputInterface.h factory registry header
[ 47%] Creating /home/zenghui/Pangolin/build/include/pangolin/factory/RegisterFactoriesVideoInterface.h factory registry header
Scanning dependencies of target pango_video
[ 48%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/stream_encoder_factory.cpp.o
[ 48%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/video_input.cpp.o
[ 49%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/video_output.cpp.o
[ 50%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/video.cpp.o
[ 50%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/video_help.cpp.o
[ 51%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/test.cpp.o
[ 52%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/images.cpp.o
[ 52%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/images_out.cpp.o
[ 53%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/split.cpp.o
[ 53%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/truncate.cpp.o
[ 54%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/pango.cpp.o
[ 55%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/pango_video_output.cpp.o
[ 55%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/debayer.cpp.o
[ 56%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/shift.cpp.o
[ 57%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/transform.cpp.o
[ 57%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/unpack.cpp.o
[ 58%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/pack.cpp.o
[ 59%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/join.cpp.o
[ 59%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/merge.cpp.o
[ 60%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/json.cpp.o
[ 61%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/thread.cpp.o
[ 61%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/shared_memory.cpp.o
[ 62%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/v4l.cpp.o
[ 63%] Linking CXX shared library libpango_video.so
[ 63%] Built target pango_video
Scanning dependencies of target pango_scene
[ 64%] Building CXX object CMakeFiles/pango_scene.dir/components/pango_scene/src/renderable.cpp.o
[ 64%] Linking CXX shared library libpango_scene.so
[ 64%] Built target pango_scene
Scanning dependencies of target pango_tools
[ 65%] Building CXX object CMakeFiles/pango_tools.dir/components/pango_tools/src/video_viewer.cpp.o
[ 66%] Linking CXX shared library libpango_tools.so
[ 66%] Built target pango_tools
Scanning dependencies of target pango_plot
[ 67%] Building CXX object CMakeFiles/pango_plot.dir/components/pango_plot/src/datalog.cpp.o
[ 68%] Building CXX object CMakeFiles/pango_plot.dir/components/pango_plot/src/plotter.cpp.o
[ 68%] Building CXX object CMakeFiles/pango_plot.dir/components/pango_plot/src/loaders/csv_table_loader.cpp.o
[ 69%] Linking CXX shared library libpango_plot.so
[ 69%] Built target pango_plot
Scanning dependencies of target tutorial_3_gl_intro_classic_triangle_vbo_shader
[ 70%] Building CXX object examples/BasicOpenGL/CMakeFiles/tutorial_3_gl_intro_classic_triangle_vbo_shader.dir/3_gl_intro_classic_triangle_vbo_shader.cpp.o
[ 71%] Linking CXX executable tutorial_3_gl_intro_classic_triangle_vbo_shader
[ 71%] Built target tutorial_3_gl_intro_classic_triangle_vbo_shader
Scanning dependencies of target tutorial_1_gl_intro_pango_triangle
[ 72%] Building CXX object examples/BasicOpenGL/CMakeFiles/tutorial_1_gl_intro_pango_triangle.dir/1_gl_intro_pango_triangle.cpp.o
[ 73%] Linking CXX executable tutorial_1_gl_intro_pango_triangle
[ 73%] Built target tutorial_1_gl_intro_pango_triangle
Scanning dependencies of target tutorial_2_gl_intro_classic_triangle_vbo
[ 73%] Building CXX object examples/BasicOpenGL/CMakeFiles/tutorial_2_gl_intro_classic_triangle_vbo.dir/2_gl_intro_classic_triangle_vbo.cpp.o
[ 74%] Linking CXX executable tutorial_2_gl_intro_classic_triangle_vbo
[ 74%] Built target tutorial_2_gl_intro_classic_triangle_vbo
Scanning dependencies of target tutorial_2_gl_intro_pango_triangle_vbo
[ 75%] Building CXX object examples/BasicOpenGL/CMakeFiles/tutorial_2_gl_intro_pango_triangle_vbo.dir/2_gl_intro_pango_triangle_vbo.cpp.o
[ 75%] Linking CXX executable tutorial_2_gl_intro_pango_triangle_vbo
[ 75%] Built target tutorial_2_gl_intro_pango_triangle_vbo
Scanning dependencies of target tutorial_3_gl_intro_pango_triangle_vbo_shader
[ 75%] Building CXX object examples/BasicOpenGL/CMakeFiles/tutorial_3_gl_intro_pango_triangle_vbo_shader.dir/3_gl_intro_pango_triangle_vbo_shader.cpp.o
[ 76%] Linking CXX executable tutorial_3_gl_intro_pango_triangle_vbo_shader
[ 76%] Built target tutorial_3_gl_intro_pango_triangle_vbo_shader
Scanning dependencies of target tutorial_1_gl_intro_classic_triangle
[ 77%] Building CXX object examples/BasicOpenGL/CMakeFiles/tutorial_1_gl_intro_classic_triangle.dir/1_gl_intro_classic_triangle.cpp.o
[ 77%] Linking CXX executable tutorial_1_gl_intro_classic_triangle
[ 77%] Built target tutorial_1_gl_intro_classic_triangle
Scanning dependencies of target tutorial_5_gl_intro_view_transforms
[ 78%] Building CXX object examples/BasicOpenGL/CMakeFiles/tutorial_5_gl_intro_view_transforms.dir/5_gl_intro_view_transforms.cpp.o
[ 79%] Linking CXX executable tutorial_5_gl_intro_view_transforms
[ 79%] Built target tutorial_5_gl_intro_view_transforms
Scanning dependencies of target tutorial_4_gl_intro_viewport
[ 80%] Building CXX object examples/BasicOpenGL/CMakeFiles/tutorial_4_gl_intro_viewport.dir/4_gl_intro_viewport.cpp.o
[ 80%] Linking CXX executable tutorial_4_gl_intro_viewport
[ 80%] Built target tutorial_4_gl_intro_viewport
Scanning dependencies of target pango_python
[ 80%] Building CXX object CMakeFiles/pango_python.dir/components/pango_core/src/dummy.cpp.o
[ 81%] Linking CXX shared library libpango_python.so
[ 81%] Built target pango_python
Scanning dependencies of target HelloPangolin
[ 81%] Building CXX object examples/HelloPangolin/CMakeFiles/HelloPangolin.dir/main.cpp.o
[ 82%] Linking CXX executable HelloPangolin
[ 82%] Built target HelloPangolin
Scanning dependencies of target SimpleDisplay
[ 82%] Building CXX object examples/SimpleDisplay/CMakeFiles/SimpleDisplay.dir/main.cpp.o
[ 83%] Linking CXX executable SimpleDisplay
[ 83%] Built target SimpleDisplay
Scanning dependencies of target SimpleMultiDisplay
[ 84%] Building CXX object examples/SimpleMultiDisplay/CMakeFiles/SimpleMultiDisplay.dir/main.cpp.o
[ 85%] Linking CXX executable SimpleMultiDisplay
[ 85%] Built target SimpleMultiDisplay
Scanning dependencies of target SimpleDisplayImage
[ 86%] Building CXX object examples/SimpleDisplayImage/CMakeFiles/SimpleDisplayImage.dir/main.cpp.o
[ 86%] Linking CXX executable SimpleDisplayImage
[ 86%] Built target SimpleDisplayImage
Scanning dependencies of target SimplePlot
[ 86%] Building CXX object examples/SimplePlot/CMakeFiles/SimplePlot.dir/main.cpp.o
[ 87%] Linking CXX executable SimplePlot
[ 87%] Built target SimplePlot
Scanning dependencies of target SimpleVideo
[ 88%] Building CXX object examples/SimpleVideo/CMakeFiles/SimpleVideo.dir/main.cpp.o
[ 89%] Linking CXX executable SimpleVideo
[ 89%] Built target SimpleVideo
Scanning dependencies of target SimpleRecord
[ 90%] Building CXX object examples/SimpleRecord/CMakeFiles/SimpleRecord.dir/main.cpp.o
[ 90%] Linking CXX executable SimpleRecord
[ 90%] Built target SimpleRecord
Scanning dependencies of target HelloPangolinOffscreen
[ 90%] Building CXX object examples/HelloPangolinOffscreen/CMakeFiles/HelloPangolinOffscreen.dir/main.cpp.o
[ 91%] Linking CXX executable HelloPangolinOffscreen
[ 91%] Built target HelloPangolinOffscreen
Scanning dependencies of target SimpleScene
[ 92%] Building CXX object examples/SimpleScene/CMakeFiles/SimpleScene.dir/main.cpp.o
[ 92%] Linking CXX executable SimpleScene
[ 92%] Built target SimpleScene
Scanning dependencies of target VideoViewer
[ 92%] Building CXX object tools/VideoViewer/CMakeFiles/VideoViewer.dir/main.cpp.o
[ 93%] Linking CXX executable VideoViewer
[ 93%] Built target VideoViewer
Scanning dependencies of target VideoConvert
[ 93%] Building CXX object tools/VideoConvert/CMakeFiles/VideoConvert.dir/main.cpp.o
[ 94%] Linking CXX executable VideoConvert
[ 94%] Built target VideoConvert
Scanning dependencies of target VideoJsonTransform
[ 95%] Building CXX object tools/VideoJson/CMakeFiles/VideoJsonTransform.dir/main-transform.cpp.o
[ 96%] Linking CXX executable VideoJsonTransform
[ 96%] Built target VideoJsonTransform
Scanning dependencies of target VideoJsonPrint
[ 97%] Building CXX object tools/VideoJson/CMakeFiles/VideoJsonPrint.dir/main-print.cpp.o
[ 97%] Linking CXX executable VideoJsonPrint
[ 97%] Built target VideoJsonPrint
Scanning dependencies of target Plotter
[ 98%] Building CXX object tools/Plotter/CMakeFiles/Plotter.dir/main.cpp.o
[ 99%] Linking CXX executable Plotter
[ 99%] Built target Plotter
Scanning dependencies of target ModelViewer
[100%] Building CXX object tools/ModelViewer/CMakeFiles/ModelViewer.dir/main.cpp.o
[100%] Linking CXX executable ModelViewer
[100%] Built target ModelViewer
**(sdf) zenghui@Ubuntu:~/Pangolin/build$ cmake --build . -t pypangolin_pip_install
make: *** 没有规则可制作目标“pypangolin_pip_install”。 停止。
(sdf) zenghui@Ubuntu:~/Pangolin/build$ sudo cmake --build . -t pypangolin_pip_install
make: *** 没有规则可制作目标“pypangolin_pip_install”。 停止。****

_Originally posted by @novauto-nju in https://github.com/stevenlovegrove/Pangolin/issues/677#issuecomment-939675851_

**Comment by zhijieW94** [comment]
Why I cannot change the PYTHON_DIR by setting -DPYTHON_DIR="/path/to/the/python/version/you/want"? In the cmakecache.txt, I can see that the value of the PYTHON_DIR variable is UNINITIALIZED. It just uses the default python directory. I am working in MacOS.

**Comment by gh279760559** [comment]
Hello, 

I got the same error when trying to build with the target argument
```cmake --build . --target pypangolin_wheel
"make: *** No rule to make target 'pypangolin_wheel'. Stop."```

I notice when using cmake to build with your suggestion `-DPYTHON-DIR="/usr/bin/python3.8"` it said:
```"WARNING: Target "pango_python" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case."```
and 
```"  Manually-specified variables were not used by the project:
    PYTHON-DIR
"```

Did I miss anything? Cheers.

**Comment by gh279760559** [comment]
One add-in: I have tested the executable example `HelloPangolin`. It works with no problem which means it is built successfully but I could not build the python part.

**Comment by ravilakhotia21** [comment]
Anyone able to resolve this ? I have the same issue on Ubuntu 18.04

**Comment by burhanbs** [comment]
clone the project, instead of downloading the zip folder and extracting files.  This error will be resolved...
https://github.com/stevenlovegrove/Pangolin
follow these steps

> Anyone able to resolve this ? I have the same issue on Ubuntu 18.04

**Comment by Camillebzd** [comment]
Hey guys,

I had exactly the same problem and there are some similar issues here. I tried some tricks by modifying directly the cmake and I just got an error telling me that my cmake was too old : "You cannot use the new FindPython module with CMake < 3.12". So the problem comes from the version of cmake itself which is too old but not telling you and it cannot find your python path (at least in my case).

I uninstalled and reinstalled cmake (in version this time 3.22) and 'cmake ..' without even using -DPYTHON-DIR flag it find the python by itself !

Maybe put a message in the README to warn that the cmake version have to be at least 3.12.

Hop it will help !

**Comment by stevenlovegrove** [comment]
To summarize and close this, I think people here have experienced a few issues:
* Pangolin not finding pybind11, which is necessary for Pangolin python support.
* pybind11's python finding ability is better with newer cmake
* There was a cmake version issue which silently stopped Pangolin from setting up the wheel logic (fixed https://github.com/stevenlovegrove/Pangolin/commit/81c58da01752cb84e39eff186a54c2b52286fa8f)

Please also see my comment https://github.com/stevenlovegrove/Pangolin/issues/719#issuecomment-1071475569 for further suggestions.
