### ISSUE TITLE
Hello! Any examples for how to configure KB+M camera control!

### ISSUE THREAD

**Issue by Fredrum** [stevenlovegrove/Pangolin#698]
Hello and thank you very much for this Library I just started trying it for a test project I'm doing!
Are there any examples for how I can customize the camera controls?
I'm from a 3D graphics background and I would love to have something closer to say the 3D app Maya.
The default system spins the world around too much for my liking when I try to change the view. I'm thinking even doing something like make spin around a world up axis might work.

Cheers!

**Comment by stevenlovegrove** [comment]
It sounds like you might prefer to set the 'enforce_up' to Pangolin::AxisY in the constructor for the Handler object:
https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_display/include/pangolin/handler/handler.h#L74

If you want to customize the controls, you can just derive from Handler and use HandlerBase3D as a template.

Best,

**Comment by Fredrum** [comment]
Thank you very much I'll try that one out!
Cheers!
