### ISSUE TITLE
is this pangolin bug on jetson nano or nx?

### ISSUE THREAD

**Issue by jcyhcs** [stevenlovegrove/Pangolin#704]
hi,professor:
i use a project: https://github.com/FangGet/BundleFusion_Ubuntu_Pangolin, i compile and run this code ok on jetson nano,but can't show mesh data with pangoline, so i check its issue,so i find a same question: https://github.com/FangGet/BundleFusion_Ubuntu_Pangolin/issues/6,
with there the author mention that this a bug with pangolin, but he didn't tell what is the bug,
![image](https://user-images.githubusercontent.com/34532224/142345672-bb4f50fa-ebfc-411b-8432-401908673461.png)
so, professor, please look into it, can tell me what is the problem with pangolin?
PLEASE HELP!

**Comment by stevenlovegrove** [comment]
I have no experience with Jetson nano or Bundle Fusion, so I'm afraid you're on your own. It's likely to be a an OpenGL extension being used that is not available on the Jetson. I would recommend you try to recreate a minimal example by finding the section of code that is not working (e.g. trying to draw a triangle or something). Feel free to reopen this commit if you can provide more detailed information or a minimal example which you think is miss-behaving.
