### ISSUE TITLE
"PANGO_DEFAULT_WIN_URI" redefined

### ISSUE THREAD

**Issue by christian-rauch** [stevenlovegrove/Pangolin#709]
There is a compiler error about `PANGO_DEFAULT_WIN_URI`:
```
<command-line>: error: "PANGO_DEFAULT_WIN_URI" redefined [-Werror]
```
that appears multiple times on stdout and prevents Pangolin from compiling.

However, on another system, this just appears as a warning:
```
<command-line>: warning: "PANGO_DEFAULT_WIN_URI" redefined
```

Edit: This is likely from another project defining `-Werror`. So a work-around is to remove this, but it would be better to fix the warnings so that other projects do not encounter this.

**Comment by stevenlovegrove** [comment]
This warning is related to the recent Wayland commits (appearing somewhere between 3c6040894755018932c678b6e0b76c709682af00 and 3b2556754ce41fe6a49e7b740bde411a91334ddc).

Not sure just yet where exactly

**Comment by stevenlovegrove** [comment]
I think it's being first set at https://github.com/stevenlovegrove/Pangolin/blob/ad3b50637d8db8ae4f41341d0e695b711cea056a/components/pango_windowing/CMakeLists.txt#L32 and overridden https://github.com/stevenlovegrove/Pangolin/blob/ad3b50637d8db8ae4f41341d0e695b711cea056a/components/pango_windowing/CMakeLists.txt#L70

**Comment by christian-rauch** [comment]
Shall there be only ever one `PANGO_DEFAULT_WIN_URI`? I added it because I thought it is required to properly register the window factory.

If X11 and Wayland are both build, then we should start Wayland first and fall back to X11. Does this mean we should set `PANGO_DEFAULT_WIN_URI="x11"` if only X11 is build, and `PANGO_DEFAULT_WIN_URI="wayland"` if Wayland-only or Wayland+X11 is build?

What happens if `PANGO_DEFAULT_WIN_URI` is not set at all, or set empty (`PANGO_DEFAULT_WIN_URI=""`)?

**Comment by stevenlovegrove** [comment]
> An alternative would be to set the default to 'default' and make sure all windowing implementations support that as a scheme with the correct priority. The X11 implementation can recognize both 'linux' and 'default' as schemes which can be used for example: https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_windowing/src/display_x11.cpp#L512

That alternative by the way would really just be moving the logic to run-time. I don't think there is any advantage since the build-system already knows what is available.
