### ISSUE TITLE
No build/src/ is created, no libpangolin.so is created

### ISSUE THREAD

**Issue by balamurugan15** [stevenlovegrove/Pangolin#712]
Hi,

I've done 
```
git clone https://github.com/stevenlovegrove/Pangolin.git
cd Pangolin
mkdir build
cd build
cmake ..
make -j
```
Build completes without any error.
But I don't see build/src folder getting created, nor the libpangolin.so file getting created which is what I'm looking for.

How to build the libpangolin.so ?

Thanks

**Comment by stevenlovegrove** [comment]
The library should be found directly in the build folder.

If you can't find it there, please list your platform, build output, and the result of
``` find .```
executed in the build folder.

**Comment by balamurugan15** [comment]
Hi,

I'm building on x86_64. Attaching the build log and the output of `find .` command.

[Pangolin_build.log](https://github.com/stevenlovegrove/Pangolin/files/7597072/Pangolin_build.log)
[Pangolin_find.log](https://github.com/stevenlovegrove/Pangolin/files/7597073/Pangolin_find.log)

I also did a name specific find which returns empty:
```
find . -name libpangolin.so
$
```

**Comment by stevenlovegrove** [comment]
Ah, you're on the latest master branch which no longer builds a single .so, but is now split into multiple components (you can see the different .so's listed).

If you're not using cmake, you will need to select the appropriate .so's to link against based on the functionality you need. If you don't know and don't care, just link against them all.

Alternatively, you can revert to the 0.6 tag which builds a monolithic .so as you were expecting.

**Comment by balamurugan15** [comment]
That's cool, I'll try using v0.6 version because I need a monolithic .so.

Thanks!

**Comment by zhangshengjun2019** [comment]
Did you mean cmake-0.6? I think it's not available now because of the low version.
