### ISSUE TITLE
Unable to open URI | terminate called after throwing an instance of 'pangolin::FactoryRegistry::ParameterMismatchException'

### ISSUE THREAD

**Issue by samirangode** [stevenlovegrove/Pangolin#716]
Hi,
I have been trying to run a personal build and have this error, I tried searching for it and also checked the issues, the closest issue that I got was #709, I changed the CMakeLists.txt to the latest version, that did stop the redefined warnings I got while building pangolin. I hoped that would solve the issue but it still persists.

This is the error I get when I try to run my build. 
`terminate called after throwing an instance of 'pangolin::FactoryRegistry::ParameterMismatchException'
  what():  Unable to open URI
  full_uri: 
  scheme: default
  params:
    HIGHRES = true
    w = 2320
    h = 1080
    window_title = Quadric SLAM
 Unrecognized options for scheme (HIGHRES,)
Aborted (core dumped)`
A little more context: I am working on a slam project and have a pangolin window that shows a TUM Freiburg video with trackers. I am quite certain that the code works because two other members are running the same code and it works for them. I however have messed something up 
Apologies if this is something trivial, I searched a lot for the source of the error but could not find anything. I would appreciate any help.
Thanks,
Sam

**Comment by stevenlovegrove** [comment]
Assuming the pangolin examples work, this is probably an issue that the program you're running (Quadric SLAM) is setting the HIGHRES parameter when opening the Pangolin window, but this is only supported on MacOS. In older versions of Pangolin, there was no check that parameters passed were actually correct and used. Now, to avoid problems with miss-spellings etc they are checked against what is expected for each factory (here the window factory).

So, to solve:
1) Check that the Pangolin examples run - if not, post back here with details of your platform (Win, Linux, MacOs etc)
2) You could downgrade pangolin to 0.5 tag
3) You could find the CreateWindowAndBind() invocation in QuadricSLAM and make the HIGHRES option conditional.

**Comment by samirangode** [comment]
Thank you! It worked, I made HIGH RES optional. Apologies, I was not aware of the OS related difference (I am using Linux).
I'll close this. Again really appreciate it!
