### ISSUE TITLE
Compilation error on swap function

### ISSUE THREAD

**Issue by hbadino** [stevenlovegrove/Pangolin#72]
Steve,

I get this compilation error:

/install/Pangolin/include/pangolin/utils/picojson.h:1099:79: error: ‘void std::swap(pangolin::json::value&, pangolin::json::value&)’ is not declared in ‘std’ template<> inline void swap(pangolin::json::value& x, pangolin::json::value& y)

A least in my system (Ubuntu 14), commenting out the method, solves the problem.

Best,

Hernan

**Comment by stevenlovegrove** [comment]
Thanks Hernan. What compiler are you using?

**Comment by hbadino** [comment]
I'm using g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

On Wed, Jan 27, 2016 at 1:46 AM, Steven Lovegrove <notifications@github.com>
wrote:

> Thanks Hernan. What compiler are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevenlovegrove/Pangolin/issues/72#issuecomment-175437115>
> .
>



-- 
- Hernan

**Comment by MarcGyongyosi** [comment]
I ran into the same issue: my system is ubuntu 14.04 with g++ 4.9.3

**Comment by stevenlovegrove** [comment]
I've just removed the offending specialisation in 17da17ef81bba49a0f93490d7eb86b35b422eac2. It isn't strictly needed anyway.
