### ISSUE TITLE
PANGOLIN_DEPRECATED Error

### ISSUE THREAD

**Issue by beijie001** [stevenlovegrove/Pangolin#722]
OS : Mac OS  version:11.6.1
Pangolin: latest version , branch: master

Compile the project fail, and the error:
Pangolin/components/pango_opengl/include/pangolin/gl/opengl_render_state.h:211:25: error: expected member name or ';' after declaration specifiers
    PANGOLIN_DEPRECATED("Use SetProjectionMatrix() or SetModelViewMatrix() instead.")
                        ^
Pangolin/components/pango_opengl/include/pangolin/gl/opengl_render_state.h:211:25: error: expected ')'
Pangolin/components/pango_opengl/include/pangolin/gl/opengl_render_state.h:211:24: note: to match this '('
    PANGOLIN_DEPRECATED("Use SetProjectionMatrix() or SetModelViewMatrix() instead.")
                       ^
2 warnings and 2 errors generated.

**Comment by beijie001** [comment]
fixed by uninstall the older version pangolin

**Comment by erinline** [comment]
What command did you use to uninstall?

**Comment by beijie001** [comment]
> 

make uninstall?
