### ISSUE TITLE
c++: internal compiler error: Segmentation fault (program cc1plus)

### ISSUE THREAD

**Issue by ahmetsaglam** [stevenlovegrove/Pangolin#723]
I have this error when compiling a ROS package called Hector Mapping. I used to have this error when I was trying to a PCL package and figured out the header file caused the issue, which was pcl_transforms.h. However, I can't find the header caused the fault this time. On my laptop (x86), it compiles without any problem. Do you know what the reason is? I am using gcc and g++ 7.5.0.

c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
ros_ws/hector_slam/hector_mapping/CMakeFiles/hector_mapping.dir/build.make:62: recipe for target 'corridor_navigation/hector_slam/hector_mapping/CMakeFiles/hector_mapping.dir/src/HectorMappingRos.cpp.o' failed
make[2]: *** [ros_ws/hector_slam/hector_mapping/CMakeFiles/hector_mapping.dir/src/HectorMappingRos.cpp.o] Error 4
CMakeFiles/Makefile2:1108: recipe for target 'ros_ws/hector_slam/hector_mapping/CMakeFiles/hector_mapping.dir/all' failed
make[1]: *** [ros_ws/hector_slam/hector_mapping/CMakeFiles/hector_mapping.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stevenlovegrove** [comment]
Does this have anything to do with Pangolin? I don't understand.

If possible, you could consider upgrading your compiler since this is likely a compiler bug. The other possibility is that you're running out of memory or something on your machine / VM.
