### ISSUE TITLE
I am getting this error while compiling Pangolin

### ISSUE THREAD

**Issue by Avi241** [stevenlovegrove/Pangolin#729]
Consolidate compiler generated dependencies of target pango_core
[  1%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/factory/factory_help.cpp.o
[  1%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/posix/condition_variable.cpp.o
[  2%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/posix/semaphore.cpp.o
[  2%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/posix/shared_memory_buffer.cpp.o
[  3%] Linking CXX shared library libpango_core.so
[  6%] Built target pango_core
[  6%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/pixel_format.cpp.o
[  7%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io.cpp.o
[  7%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_exr.cpp.o
[  8%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_jpg.cpp.o
[  8%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_lz4.cpp.o
[  9%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_packed12bit.cpp.o
[  9%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_pango.cpp.o
[ 10%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_png.cpp.o
[ 10%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_ppm.cpp.o
[ 11%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_raw.cpp.o
[ 11%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_tga.cpp.o
[ 12%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_bmp.cpp.o
[ 12%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_zstd.cpp.o
[ 13%] Linking CXX shared library libpango_image.so
[ 13%] Built target pango_image
[ 13%] Embedding /home/arvind/slambook2/3rdparty/Pangolin/components/pango_opengl/src/fonts/AnonymousPro.ttf into fonts.cpp
[ 13%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glchar.cpp.o
[ 14%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/gldraw.cpp.o
[ 14%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glfont.cpp.o
[ 15%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/gltext.cpp.o
[ 15%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glpangoglu.cpp.o
[ 16%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/gltexturecache.cpp.o
[ 16%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/viewport.cpp.o
[ 17%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/opengl_render_state.cpp.o
[ 17%] Building CXX object CMakeFiles/pango_opengl.dir/fonts.cpp.o
[ 18%] Linking CXX shared library libpango_opengl.so
[ 18%] Built target pango_opengl
[ 19%] Generating xdg-shell-client-protocol.h
[ 20%] Generating xdg-shell-protocol.c
[ 20%] Creating /home/arvind/slambook2/3rdparty/Pangolin/build/include/pangolin/factory/RegisterFactoriesWindowInterface.h factory registry header
[ 20%] Building CXX object CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_x11.cpp.o
[ 21%] Building CXX object CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_wayland.cpp.o
[ 21%] Building C object CMakeFiles/pango_windowing.dir/xdg-shell-protocol.c.o
[ 21%] Building CXX object CMakeFiles/pango_windowing.dir/components/pango_windowing/src/window.cpp.o
[ 22%] Linking CXX shared library libpango_windowing.so
[ 22%] Built target pango_windowing
[ 22%] Building CXX object CMakeFiles/pango_vars.dir/components/pango_vars/src/vars.cpp.o
[ 23%] Building CXX object CMakeFiles/pango_vars.dir/components/pango_vars/src/varstate.cpp.o
[ 23%] Linking CXX shared library libpango_vars.so
[ 23%] Built target pango_vars
[ 23%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/display.cpp.o
[ 24%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/process.cpp.o
[ 24%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/pangolin_gl.cpp.o
[ 24%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/handler.cpp.o
[ 25%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/handler_image.cpp.o
[ 25%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/handler_glbuffer.cpp.o
[ 26%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/view.cpp.o
[ 26%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/widgets.cpp.o
[ 27%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/image_view.cpp.o
[ 27%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/ConsoleView.cpp.o
[ 28%] Building CXX object CMakeFiles/pango_display.dir/components/pango_display/src/default_font.cpp.o
[ 28%] Linking CXX shared library libpango_display.so
[ 28%] Built target pango_display
[ 29%] Building CXX object CMakeFiles/pango_plot.dir/components/pango_plot/src/datalog.cpp.o
[ 29%] Building CXX object CMakeFiles/pango_plot.dir/components/pango_plot/src/plotter.cpp.o
[ 30%] Building CXX object CMakeFiles/pango_plot.dir/components/pango_plot/src/loaders/csv_table_loader.cpp.o
[ 30%] Linking CXX shared library libpango_plot.so
[ 30%] Built target pango_plot
[ 30%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/packet.cpp.o
[ 31%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/packetstream.cpp.o
[ 31%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/packetstream_reader.cpp.o
[ 32%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/packetstream_writer.cpp.o
[ 32%] Building CXX object CMakeFiles/pango_packetstream.dir/components/pango_packetstream/src/playback_session.cpp.o
[ 32%] Linking CXX shared library libpango_packetstream.so
[ 32%] Built target pango_packetstream
[ 32%] Creating /home/arvind/slambook2/3rdparty/Pangolin/build/include/pangolin/factory/RegisterFactoriesVideoOutputInterface.h factory registry header
[ 33%] Creating /home/arvind/slambook2/3rdparty/Pangolin/build/include/pangolin/factory/RegisterFactoriesVideoInterface.h factory registry header
[ 34%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/stream_encoder_factory.cpp.o
[ 34%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/video_input.cpp.o
[ 35%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/video_output.cpp.o
[ 35%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/video.cpp.o
[ 36%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/video_help.cpp.o
[ 36%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/test.cpp.o
[ 37%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/images.cpp.o
[ 37%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/images_out.cpp.o
[ 37%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/split.cpp.o
[ 38%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/truncate.cpp.o
[ 38%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/pango.cpp.o
[ 39%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/pango_video_output.cpp.o
[ 39%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/debayer.cpp.o
[ 40%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/shift.cpp.o
[ 40%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/transform.cpp.o
[ 41%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/unpack.cpp.o
[ 41%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/pack.cpp.o
[ 42%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/join.cpp.o
[ 42%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/merge.cpp.o
[ 43%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/json.cpp.o
[ 43%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/thread.cpp.o
[ 44%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/shared_memory.cpp.o
[ 44%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/firewire.cpp.o
[ 44%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/deinterlace.cpp.o
[ 45%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/v4l.cpp.o
[ 45%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/ffmpeg.cpp.o
[ 46%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/ffmpeg_convert.cpp.o
[ 46%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/ffmpeg_output.cpp.o
[ 47%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/realsense2.cpp.o
[ 47%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/openni.cpp.o
[ 48%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/openni2.cpp.o
[ 48%] Linking CXX shared library libpango_video.so
[ 48%] Built target pango_video
[ 49%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pyinterpreter.cpp.o
In file included from /home/arvind/slambook2/3rdparty/Pangolin/components/pango_python/src/pyinterpreter.cpp:27:0:
/home/arvind/slambook2/3rdparty/Pangolin/components/pango_python/include/pangolin/python/pyinterpreter.h:40:7: warning: ‘pangolin::PyInterpreter’ declared with greater visibility than the type of its field ‘pangolin::PyInterpreter::guard’ [-Wattributes]
 class PyInterpreter : public InterpreterInterface
       ^~~~~~~~~~~~~
/home/arvind/slambook2/3rdparty/Pangolin/components/pango_python/include/pangolin/python/pyinterpreter.h:40:7: warning: ‘pangolin::PyInterpreter’ declared with greater visibility than the type of its field ‘pangolin::PyInterpreter::pycompleter’ [-Wattributes]
/home/arvind/slambook2/3rdparty/Pangolin/components/pango_python/include/pangolin/python/pyinterpreter.h:40:7: warning: ‘pangolin::PyInterpreter’ declared with greater visibility than the type of its field ‘pangolin::PyInterpreter::pycomplete’ [-Wattributes]
[ 49%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin_embed.cpp.o
[ 50%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/attach.cpp.o
[ 50%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/colour.cpp.o
[ 51%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/datalog.cpp.o
[ 51%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/display.cpp.o
[ 52%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/gl.cpp.o
[ 52%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/gl_draw.cpp.o
[ 53%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/glsl.cpp.o
[ 53%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/glvbo.cpp.o
[ 54%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/handler.cpp.o
[ 54%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/image.cpp.o
[ 54%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/image_view.cpp.o
[ 55%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/opengl_render_state.cpp.o
[ 55%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/params.cpp.o
[ 56%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/pixel_format.cpp.o
[ 56%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/plotter.cpp.o
[ 57%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/pypangoio.cpp.o
[ 57%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/var.cpp.o
[ 58%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/video.cpp.o
[ 58%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/view.cpp.o
[ 59%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/viewport.cpp.o
[ 59%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/widget.cpp.o
[ 60%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pypangolin/window.cpp.o
[ 60%] Linking CXX shared library libpango_python.so
[ 60%] Built target pango_python
[ 61%] Building CXX object CMakeFiles/tinyobj.dir/components/tinyobj/src/tinyobj.cpp.o
[ 61%] Linking CXX shared library libtinyobj.so
[ 61%] Built target tinyobj
[ 62%] Building CXX object CMakeFiles/pango_scene.dir/components/pango_scene/src/renderable.cpp.o
[ 62%] Linking CXX shared library libpango_scene.so
[ 62%] Built target pango_scene
[ 62%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin_module.cpp.o
[ 63%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/attach.cpp.o
[ 63%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/colour.cpp.o
[ 64%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/datalog.cpp.o
[ 64%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/display.cpp.o
[ 65%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/gl.cpp.o
[ 65%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/gl_draw.cpp.o
[ 66%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/glsl.cpp.o
[ 66%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/glvbo.cpp.o
[ 67%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/handler.cpp.o
[ 67%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/image.cpp.o
[ 68%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/image_view.cpp.o
[ 68%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/opengl_render_state.cpp.o
[ 68%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/params.cpp.o
[ 69%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/pixel_format.cpp.o
[ 69%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/plotter.cpp.o
[ 70%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/pypangoio.cpp.o
[ 70%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/var.cpp.o
[ 71%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/video.cpp.o
[ 71%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/view.cpp.o
[ 72%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/viewport.cpp.o
[ 72%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/widget.cpp.o
[ 73%] Building CXX object CMakeFiles/pypangolin.dir/components/pango_python/src/pypangolin/window.cpp.o
[ 73%] Linking CXX shared module pypangolin-0.7.data/purelib/pypangolin.cpython-36m-x86_64-linux-gnu.so
[ 73%] Built target pypangolin
[ 74%] Building CXX object CMakeFiles/pango_geometry.dir/components/pango_geometry/src/geometry.cpp.o
[ 74%] Building CXX object CMakeFiles/pango_geometry.dir/components/pango_geometry/src/geometry_obj.cpp.o
[ 75%] Building CXX object CMakeFiles/pango_geometry.dir/components/pango_geometry/src/geometry_ply.cpp.o
[ 75%] Linking CXX shared library libpango_geometry.so
[ 75%] Built target pango_geometry
[ 75%] Building CXX object CMakeFiles/pango_tools.dir/components/pango_tools/src/video_viewer.cpp.o
[ 76%] Linking CXX shared library libpango_tools.so
[ 76%] Built target pango_tools
[ 77%] Building CXX object CMakeFiles/pango_glgeometry.dir/components/pango_glgeometry/src/glgeometry.cpp.o
[ 77%] Linking CXX shared library libpango_glgeometry.so
[ 77%] Built target pango_glgeometry
[ 77%] Building CXX object examples/BasicOpenGL/CMakeFiles/tutorial_2_gl_intro_classic_triangle_vbo.dir/2_gl_intro_classic_triangle_vbo.cpp.o
[ 78%] Linking CXX executable tutorial_2_gl_intro_classic_triangle_vbo
../../libpango_windowing.so: undefined reference to `eglCreateWindowSurface'
../../libpango_windowing.so: undefined reference to `eglBindAPI'
../../libpango_windowing.so: undefined reference to `eglCreateContext'
../../libpango_windowing.so: undefined reference to `eglMakeCurrent'
../../libpango_windowing.so: undefined reference to `eglDestroySurface'
../../libpango_windowing.so: undefined reference to `eglGetDisplay'
../../libpango_windowing.so: undefined reference to `eglChooseConfig'
../../libpango_windowing.so: undefined reference to `eglInitialize'
../../libpango_windowing.so: undefined reference to `eglGetConfigs'
../../libpango_windowing.so: undefined reference to `eglDestroyContext'
../../libpango_windowing.so: undefined reference to `eglSwapInterval'
../../libpango_windowing.so: undefined reference to `eglSwapBuffers'
../../libpango_windowing.so: undefined reference to `eglTerminate'
collect2: error: ld returned 1 exit status
examples/BasicOpenGL/CMakeFiles/tutorial_2_gl_intro_classic_triangle_vbo.dir/build.make:106: recipe for target 'examples/BasicOpenGL/tutorial_2_gl_intro_classic_triangle_vbo' failed
make[2]: *** [examples/BasicOpenGL/tutorial_2_gl_intro_classic_triangle_vbo] Error 1
CMakeFiles/Makefile2:1039: recipe for target 'examples/BasicOpenGL/CMakeFiles/tutorial_2_gl_intro_classic_triangle_vbo.dir/all' failed
make[1]: *** [examples/BasicOpenGL/CMakeFiles/tutorial_2_gl_intro_classic_triangle_vbo.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nb-wang** [comment]
I have met the same errors today. Have u fixed it?

**Comment by Avi241** [comment]
There was some problem with my system I was unable to compile any packages. Fresh Ubuntu installation worked for me.

**Comment by nb-wang** [comment]
Thanks for sharing. I will check my system first.
