### ISSUE TITLE
ffmpeg video output not working properly

### ISSUE THREAD

**Issue by mikonse** [stevenlovegrove/Pangolin#730]
Hi there,
I was trying to get the `VideoOutput` utility to work with ffmpeg support to be able to build a simple recording utility for a realsense camera. Unfortunately it seems as though the ffmpeg support is not working properly. When e.g. running the `SimpleRecord` demo in the examples folder I get the error.

```
terminate called after throwing an instance of 'pangolin::FactoryRegistry::NoMatchingSchemeException'
  what():  Unable to open URI
  full_uri: ffmpeg:[fps=30,bps=8388608]//video.avi
  scheme: ffmpeg
  params:
    fps = 30
    bps = 8388608
 No matching scheme.
```

After digging around a bit it seems like the registration for the factory utilities which map the string keys like `ffmpeg` to the respective classes / functions is not working properly as the `TypeRegistry` in https://github.com/stevenlovegrove/Pangolin/blob/bcf41ec8b2853eb132dbe5cbe65ca8eade31846e/components/pango_core/include/pangolin/factory/factory_registry.h#L91 is empty for the VideoOutput type even though pangolin was built with ffmpeg support (which is stated in the cmake output).

**Comment by stevenlovegrove** [comment]
Thanks for pointing this out - I found a silly mistake.
