### ISSUE TITLE
expected primary-expression before ‘)’

### ISSUE THREAD

**Issue by SXHRYU** [stevenlovegrove/Pangolin#731]
Greetings. I was trying to `make install` (in build directory) Pangolin after succesfully building it. But I got the following error and stopped at 25%. 
Latest version of Pangolin (as of 06.02.2022) on Ubuntu 20.04
Error:

Building CXX object CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_x11.cpp.o
/home/slava_ubuntu/IT_stuff/repos/Pangolin/components/pango_core/include/sigslot/signal.hpp:972:34: error: expected primary-expression before ‘)’ token
  972 |         return get_object_ptr(Ptr);                  <-------- **_% this bracket right here (my comment)_**                       
make[2]: *** [CMakeFiles/pango_windowing.dir/build.make:75: CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_x11.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:549: CMakeFiles/pango_windowing.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by stevenlovegrove** [comment]
What compiler are you using? It looks perhaps like it is old?

**Comment by christian-rauch** [comment]
I guess this issue disappeared. The CI is now testing for more compiler variations.
