### ISSUE TITLE
How to solve this problem when bulid libpango_windowing.so

### ISSUE THREAD

**Issue by whang2017** [stevenlovegrove/Pangolin#734]
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglCreateWindowSurface'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglBindAPI'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglCreateContext'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglMakeCurrent'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglDestroySurface'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglGetDisplay'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglChooseConfig'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglInitialize'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglGetConfigs'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglDestroyContext'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglSwapInterval'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglSwapBuffers

**Comment by nb-wang** [comment]
hello, I have met this error either. Have you fixed this error right now?

**Comment by whang2017** [comment]
No yet> hello, I have met this error either. Have you fixed this error right now?

**Comment by whang2017** [comment]
> hello, I have met this error either. Have you fixed this error right now?

No yet

**Comment by nb-wang** [comment]
My laptop did not meet any error, but my desktop computer met this problem. 
I think it may be something wrong with the environment of my desktop.
I'm going to reinstall ubuntu20.04. I will tell you if it works.
ps. i use ubuntu18.04 right now

**Comment by nb-wang** [comment]
It really works! (However I still don't know why)
I upgrade the system to 20.04, and rebuild Pangolin, then it works.
no error!

**Comment by stevenlovegrove** [comment]
Pangolin has a few windowing backends. The Wayland one uses the EGL methods you list, so it looks like a problem with the selected wayland / EGL link library. You can disable wayland in cmake if you encounter this issue, or make sure the required libraries are found by inspecting the cmake output.

**Comment by nb-wang** [comment]
THX!! It alse works for me!



在 2023-10-30 17:36:12，"leon" ***@***.***> 写道：

try “sudo ldconfig” it works for me！
