### ISSUE TITLE
Dependencies for Archlinux

### ISSUE THREAD

**Issue by niu-niu** [stevenlovegrove/Pangolin#736]
Is it possible to add dependencies list for archlinux platform?

**Comment by stevenlovegrove** [comment]
I don't have any experience with archlinux, but If you wanted to create a pull request with the required changes in install_prerequisites.sh I'd consider including them

**Comment by PeterBee97** [comment]
pangolin-git is in AUR already. However the build also fails with ffmpeg 5.0, as mentioned in #737 .

**Comment by PeterBee97** [comment]
I patched the CMakeList.txt to find the ffmpeg4.4 files and it works.

**Comment by christian-rauch** [comment]
@niu-niu You can extend the [install script](https://github.com/stevenlovegrove/Pangolin/blob/master/scripts/install_prerequisites.sh) with an additional package manager. For this, you have to add `pacman` to `MANAGERS=(dnf apt port vcpkg brew)` and then add a new else block with the package list to list of package manager cases:
https://github.com/stevenlovegrove/Pangolin/blob/d64507241dc79ecd98c1dea267d74dac34663629/scripts/install_prerequisites.sh#L114-L123.
