### ISSUE TITLE
libOpenGL.so: undefined reference to `_glapi_tls_Current'

### ISSUE THREAD

**Issue by hbwanghang** [stevenlovegrove/Pangolin#738]
![error](https://user-images.githubusercontent.com/20834302/155869855-59b0bfbd-fa4f-4991-b4dc-860d29d2d77c.png)
How to solve the problem with the picture？

**Comment by stevenlovegrove** [comment]
This seems to be more of a system configuration issue than a Pangolin issue. 

This thread seems related and may help
https://forum.freecadweb.org/viewtopic.php?f=4&t=41985

**Comment by christian-rauch** [comment]
@hbwanghang Can you run `lddtree /lib/x86_64-linux-gnu/libOpenGL.so` and report the output here?

In a working configuration, this should report:
```
$ lddtree /lib/x86_64-linux-gnu/libOpenGL.so
libOpenGL.so => /lib/x86_64-linux-gnu/libOpenGL.so (interpreter => none)
    libGLdispatch.so.0 => /lib/x86_64-linux-gnu/libGLdispatch.so.0
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
            ld-linux-x86-64.so.2 => /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
```

You can see that `libOpenGL.so` links `libGLdispatch.so` and this library defines the symbol `_glapi_tls_Current`:
```
$ nm -D /lib/x86_64-linux-gnu/libGLdispatch.so | grep tls
0000000000000000 D _glapi_tls_Current
```
