### ISSUE TITLE
cannot make rule

### ISSUE THREAD

**Issue by QtEngineer** [stevenlovegrove/Pangolin#741]

**Comment by QtEngineer** [comment]
I run  cmake -DPYTHON_EXECUTABLE=/root/miniconda3/bin/ ..
but WARNING: Target "pango_python" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
and  Unknown argument pypangolin_pip_install

**Comment by stevenlovegrove** [comment]
Thanks for sharing the warning.

PYTHON_EXECUTABLE should point to the actual executable, and not just the folder. That might be part of your problem?

**Comment by QtEngineer** [comment]
> Thanks for sharing the warning.
> 
> PYTHON_EXECUTABLE should point to the actual executable, and not just the folder. That might be part of your problem?
I am so sorry，but it seems that CMAKE ignore the PYTHON_EXECUTABLE：

CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_EXECUTABLE

**Comment by stevenlovegrove** [comment]
Closing as a duplicate of #719
