### ISSUE TITLE
GL/glu.h: No such file or directory

### ISSUE THREAD

**Issue by watarungurunnn** [stevenlovegrove/Pangolin#743]
When I run `cmake --build .`, the error occured. How can I fix this?

```[ 15%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glchar.cpp.o
In file included from /[hoge]/Pangolin/components/pango_opengl/include/pangolin/gl/glplatform.h:59,
                 from /[hoge]/Pangolin/components/pango_opengl/include/pangolin/gl/glchar.h:30,
                 from /[hoge]/Pangolin/components/pango_opengl/src/glchar.cpp:28:
/usr/local/lib/GLEW/include/GL/glew.h:1205:14: fatal error: GL/glu.h: No such file or directory
 1205 | #    include <GL/glu.h>
      |              ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pango_opengl.dir/build.make:80: CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glchar.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:611: CMakeFiles/pango_opengl.dir/all] Error 2

**Comment by stevenlovegrove** [comment]
I'm not sure why GLEW is trying to include GLU, but it looks like you don't have it or it isn't on your system include path.

You could try installing GLU or helping the findpackage(opengl) to find it. Alternatively you could try #defining GLEW_NO_GLU in glplatform.h before glew.h is included.

**Comment by christian-rauch** [comment]
@watarungurunnn Is GLU installed on your system? On Ubuntu/Debian it is in the package `libglu1-mesa-dev`: https://packages.ubuntu.com/focal/amd64/libglu1-mesa-dev/filelist
