### ISSUE TITLE
 Manually-specified variables were not used by the project:

### ISSUE THREAD

**Issue by QtEngineer** [stevenlovegrove/Pangolin#744]
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_EXECUTABLE
I tried to set python including dir manually but this warning accured， and cannot make rule pypangolin_pip_install

**Comment by stevenlovegrove** [comment]
Closing this as you've already captured it #741

**Comment by DTUAqua-ObsTek** [comment]
I also had this problem. [Line 6](https://github.com/stevenlovegrove/Pangolin/blob/5f78f502117b2ff9238ed63768fd859a8fa78ffd/components/pango_python/CMakeLists.txt#L6) of components/pango_python/CMakeLists.txt uses find_package(Python...) to find the Python executable, but the cmake variable expected by this to specify a specific executable path is: `Python_EXECUTABLE` (case sensitive).

Please consider updating the README with this.
