### ISSUE TITLE
Disabling OpenNI and OpenNI2 library requirements for latest version of Pangolin

### ISSUE THREAD

**Issue by Mechazo11** [stevenlovegrove/Pangolin#745]
Hello Mr. @stevenlovegrove

Thank you publishing the Pangolin toolset for data visualization. I am working with a robot localization system and found Pangolin to be an useful alternative to RViz visualization tools for offline data analysis.

However, I could not get the latest version of Pangolin to compile due an error with the OpenNi2 library which as of writing this post, I could not find a solution to. I resorted in using V0.6 which compiled successfully once I had gone in to src/CmakeList.txt and turned of checks for both OpenNI and OpenNI2.

But I could not replicate the same process with the current branch of the software that supports pypangolin. 

How can we turn of checks for OpenNI and OpenNI2 libraries for the latest version of Pangolin?

Thank you for your time.

With best regards,
Azmyin Md. Kamal (Mechazo11)

**Comment by stevenlovegrove** [comment]
If pangolin detects these on your system but you don't need them and you would like to disable them, just set the found library path for these to empty in cmake with cmake-gui or ccmake for example.

**Comment by Mechazo11** [comment]
@stevenlovegrove I solved the issue and thanks for your hint. When I had opened this issue back in March I found that installing an older version and manually deactivating  OpenNNI2 drivers did the job. 

For anyone facing the same issue, these are the commands I used
In your chosen root directory,

`git clone --recursive https://github.com/stevenlovegrove/Pangolin.git`
`cd Pangolin`
`cmake-gui -B build`

From the dialog prompt, unselected BUILD_PANGOLIN_OPENNI and BUILD_PANGOLIN_OPENNI2. For OPENNI_INCLUDE_DIR and OPENNI_LIBRARY, erased all strings i.e set their values to blank

`cmake --build build`

# Test
`cd build/examples/HelloPangolin/`
`./HelloPangolin` [Show a 3D moveable box]
