### ISSUE TITLE
How to render a list of colored 3D points?

### ISSUE THREAD

**Issue by mojovski** [stevenlovegrove/Pangolin#75]
I wonder if there is a helper method in Pangolin, which helps me to render a list of colored 3D points.
Would be great if there is something like 
```
pangolin::glDrawColouredCube();
```
but for 3D points.

**Comment by stevenlovegrove** [comment]
The current way to do this is to create a GLBuffer, upload your points, and use glRenderVbo ( https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/gl/glvbo.h#L46) using the buffer. This is particular efficient if you are rendering the same points many times.

I do have another simpler utility similar to glDrawColouredCube, but it is not factored in yet and will not be as efficient if you are rendering the same points many times. I will try to remember to post here when it makes it in to devel.

**Comment by rajputasif** [comment]
I know how to create native openGL VBO, could you please tell me how I can create pangolin::GLbuffer from GL VBO

Thanks

**Comment by rajputasif** [comment]
I am having trouble creating a pangolin::GLBuffer, plus there is no example which I can use at reference (except for cuda based gl buffer). 

Could you please give a snippet for GLBuffer creation

Thanks

**Comment by stevenlovegrove** [comment]
This sample is untested, but use is along the lines of:

`const size_t num_pts = 1000;`
`float somedata[3*num_pts];`
`// fill in somedata with contiguous 3 vectors representing 3D points`
`// ...`

`// Create pangolin::GlBuffer object encapsulating`
`// GL buffer object (glBufferData/glDeleteBuffers)`
`pangolin::GlBuffer glxyz(pangolin::GlArrayBuffer, num_pts, GL_FLOAT, 3, GL_STATIC_DRAW);`

`// Upload host data to OpenGL Buffer`
`glxyz.Upload(somedata, 3*sizeof(float)*num_pts)`

`// ....`
`// Actually render the points, assuming model-view and `
`// projection matrices have been setup`
`pangolin::RenderVbo(glxyz, GL_POINTS);`

**Comment by rajputasif** [comment]
Bundle of thanks... I will give it a try.

**Comment by rajputasif** [comment]
Thanks a lot, It works :)
just had to use `pangolin::RenderVbo(glxyz);` instead of `pangolin::RenderVbo(glxyz, GL_POINTS)` everything else worked like a charm.

**Comment by stevenlovegrove** [comment]
Great!
