### ISSUE TITLE
Error when running cmake ..  Could not find GLEW

### ISSUE THREAD

**Issue by retoc71586** [stevenlovegrove/Pangolin#751]
Hi I am trying to install Pangolin on my M1 Mac running macOS. I have been able to run the ./scripts/install_prerequisites.sh -m brew all script but when doing make .. it can not find GLEW:
CMake Error at cmake/FindGLEW.cmake:51 (MESSAGE):
  Could not find GLEW
Call Stack (most recent call first):
  components/pango_opengl/CMakeLists.txt:41 (find_package)
  CMakeLists.txt:93 (include)

However brew can find a version: 
Warning: glew 2.2.0_1 is already installed and up-to-date.

What should I do?

**Comment by stevenlovegrove** [comment]
You should check that Pangolin is looking in the directory that brew has installed glew.

Check here:
https://github.com/stevenlovegrove/Pangolin/blob/master/cmake/FindGLEW.cmake#L23

You can update the script or override the location using ccmake or cmake-gui or via a command argument.

**Comment by retoc71586** [comment]
I am reopening this issue because I am having troubles building, as per #753 and I thought this could be the cause to it.
I located GL/Glew.h in three places: 
/opt/homebrew/include/GL/glew.h
/opt/homebrew/Cellar/glew/2.2.0_1/include/GL/glew.h
/opt/local/include/GL/glew.h 

I added them all to cmake/FindGLEW line 23 and afterwards cmake .. run with no problems. However I was wondering how could it be that It did not find it in  /opt/local/include in the first place since it is already present in your code.
Is what I did reasonable in your opinion?

**Comment by retoc71586** [comment]
The final solution guys is to delete everything and install using macports. This way is worked

**Comment by pylnik** [comment]
> You should check that Pangolin is looking in the directory that brew has installed glew.
> 
> Check here: https://github.com/stevenlovegrove/Pangolin/blob/master/cmake/FindGLEW.cmake#L23
> 
> You can update the script or override the location using ccmake or cmake-gui or via a command argument.

Alternative you can edit the file:
`<path_to>\Pangolin\components\pango_opengl\CMakeLists.txt`

First you have to locate where package manager has stored glew binaries/includes. For me with vcpkg it is:
`<path_to>/vcpkg/packages/glew_x64-windows`

Then add the path to look for glew for before the line
`    find_package(GLEW REQUIRED QUIET)`

The result would be:
```
    list(APPEND CMAKE_PREFIX_PATH "<path_to>/vcpkg/packages/glew_x64-windows")
    find_package(GLEW REQUIRED QUIET)

```

**Comment by Nacriema** [comment]
In my case just use `brew install glew`.
