### ISSUE TITLE
Can not build clang: error: linker command failed

### ISSUE THREAD

**Issue by retoc71586** [stevenlovegrove/Pangolin#753]
Thanks for the fast reply on my previous issue. After successfully executing cmake .. I run cmake --build . and got the following error:

`ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed`

`[ 16%] Linking CXX shared library libpango_image.dylib
ld: warning: ignoring file /opt/local/lib/libIlmImf.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
referenced from:
      typeinfo for pangolin::StdIStream in image_io_exr.cpp.o
`

How can I specify that it needs to build for arm64 and not x86?

Thanks for the help

**Comment by retoc71586** [comment]
I am doubting the possibility to actually install Pangolin on M1, did someone succeed in this?

**Comment by stevenlovegrove** [comment]
I have a Macbook M1 max myself and don't have any issues building (I never install, so could be bugs there). I use Macports and the default Apple Clang. You're not using a Rosetta terminal or anything are you?

**Comment by retoc71586** [comment]
I have tried both with rosetta on the terminal and without but I get that same error. It looks to me as if there is some wrong reference, as if it downloaded for arm but tries to build for x86. I have also tried to uninstall all the dependencies and re-download them using the rosetta terminal but the result is the same.
How do you use Macports? Because for the installation script I think it required to use brew.
Thanks

**Comment by retoc71586** [comment]
If there is a way to list the required dependencies I could just try to install them by hand trough Macports, where can I see them?

**Comment by retoc71586** [comment]
The final solution guys is to delete everything and install using macports. This way is worked

**Comment by heyitsR1** [comment]
try re-naming your file and check for duplicates.
