### ISSUE TITLE
use of undeclared identifier 'ImageFileTypeBmp'

### ISSUE THREAD

**Issue by AmirHossein-nr** [stevenlovegrove/Pangolin#755]
Hi ! I am trying to use pangolin on my mac. my OS is 'Mac Os Monterey 12.3.1' . when i clone the repo and run 'install_prerequisites.sh' , then i try to build with cmake , but i get these errors : 

[  6%] Built target pango_core
Consolidate compiler generated dependencies of target pango_image
[  7%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io.cpp.o
In file included from /Users/tapsi/Downloads/Pangolin-test/components/pango_image/src/image_io.cpp:28:
In file included from /usr/local/include/pangolin/image/image_io.h:30:
In file included from /usr/local/include/pangolin/platform.h:30:
/usr/local/include/pangolin/config.h:48:9: warning: 'HAVE_PNG' macro redefined [-Wmacro-redefined]
#define HAVE_PNG
        ^
<command line>:4:9: note: previous definition is here
#define HAVE_PNG 1
        ^
In file included from /Users/tapsi/Downloads/Pangolin-test/components/pango_image/src/image_io.cpp:28:
In file included from /usr/local/include/pangolin/image/image_io.h:30:
In file included from /usr/local/include/pangolin/platform.h:30:
/usr/local/include/pangolin/config.h:49:9: warning: 'HAVE_JPEG' macro redefined [-Wmacro-redefined]
#define HAVE_JPEG
        ^
<command line>:1:9: note: previous definition is here
#define HAVE_JPEG 1
        ^
In file included from /Users/tapsi/Downloads/Pangolin-test/components/pango_image/src/image_io.cpp:28:
In file included from /usr/local/include/pangolin/image/image_io.h:30:
In file included from /usr/local/include/pangolin/platform.h:30:
/usr/local/include/pangolin/config.h:50:9: warning: 'HAVE_TIFF' macro redefined [-Wmacro-redefined]
#define HAVE_TIFF
        ^
<command line>:5:9: note: previous definition is here
#define HAVE_TIFF 1
        ^
In file included from /Users/tapsi/Downloads/Pangolin-test/components/pango_image/src/image_io.cpp:28:
In file included from /usr/local/include/pangolin/image/image_io.h:30:
In file included from /usr/local/include/pangolin/platform.h:30:
/usr/local/include/pangolin/config.h:51:9: warning: 'HAVE_OPENEXR' macro redefined [-Wmacro-redefined]
#define HAVE_OPENEXR
        ^
<command line>:3:9: note: previous definition is here
#define HAVE_OPENEXR 1
        ^
In file included from /Users/tapsi/Downloads/Pangolin-test/components/pango_image/src/image_io.cpp:28:
In file included from /usr/local/include/pangolin/image/image_io.h:30:
In file included from /usr/local/include/pangolin/platform.h:30:
/usr/local/include/pangolin/config.h:52:9: warning: 'HAVE_ZSTD' macro redefined [-Wmacro-redefined]
#define HAVE_ZSTD
        ^
<command line>:6:9: note: previous definition is here
#define HAVE_ZSTD 1
        ^
In file included from /Users/tapsi/Downloads/Pangolin-test/components/pango_image/src/image_io.cpp:28:
In file included from /usr/local/include/pangolin/image/image_io.h:30:
In file included from /usr/local/include/pangolin/platform.h:30:
/usr/local/include/pangolin/config.h:53:9: warning: 'HAVE_LZ4' macro redefined [-Wmacro-redefined]
#define HAVE_LZ4
        ^
<command line>:2:9: note: previous definition is here
#define HAVE_LZ4 1
        ^
In file included from /Users/tapsi/Downloads/Pangolin-test/components/pango_image/src/image_io.cpp:28:
In file included from /usr/local/include/pangolin/image/image_io.h:30:
In file included from /usr/local/include/pangolin/platform.h:30:
/usr/local/include/pangolin/config.h:58:9: warning: '_OSX_' macro redefined [-Wmacro-redefined]
#define _OSX_
        ^
<command line>:7:9: note: previous definition is here
#define _OSX_ 1
        ^
/Users/tapsi/Downloads/Pangolin-test/components/pango_image/src/image_io.cpp:95:10: error: use of undeclared identifier 'ImageFileTypeBmp'
    case ImageFileTypeBmp:
         ^
/Users/tapsi/Downloads/Pangolin-test/components/pango_image/src/image_io.cpp:113:10: error: use of undeclared identifier 'ImageFileTypeBmp'
    case ImageFileTypeBmp:
         ^
/Users/tapsi/Downloads/Pangolin-test/components/pango_image/src/image_io.cpp:120:10: error: use of undeclared identifier 'ImageFileTypeArw'
    case ImageFileTypeArw:
         ^
/Users/tapsi/Downloads/Pangolin-test/components/pango_image/src/image_io.cpp:151:10: error: use of undeclared identifier 'ImageFileTypeBmp'
    case ImageFileTypeBmp:
         ^
/Users/tapsi/Downloads/Pangolin-test/components/pango_image/src/image_io.cpp:168:10: error: use of undeclared identifier 'ImageFileTypeBmp'
    case ImageFileTypeBmp:
         ^
7 warnings and 5 errors generated.
make[2]: *** [CMakeFiles/pango_image.dir/components/pango_image/src/image_io.cpp.o] Error 1
make[1]: *** [CMakeFiles/pango_image.dir/all] Error 2
make: *** [all] Error 2

**Comment by christian-rauch** [comment]
Are you trying to compile and install pangolin multiple times? You message is referring to `/usr/local/include/pangolin/config.h` but your source is at `/Users/tapsi/Downloads/Pangolin-test`. Does this work on Ubuntu?

In future, please use the markdown code formatting for raw error messages etc. It makes it much easier to read.

**Comment by AmirHossein-nr** [comment]
I think you're right. Firstly I tried installing pangolin with macports . `sudo port install Pangolin`. But I couldn't run my library (ORB_SLAM3) with it. so I tried cloning the latest version of pangolin from github and compiling it manually .
How can I fixs this problem now ?

**Comment by christian-rauch** [comment]
You have to remove/uninstall one or the other. So of the `port` version does not work, you probably have to uninstall this version.
