### ISSUE TITLE
catch mouse event

### ISSUE THREAD

**Issue by qq1962572025** [stevenlovegrove/Pangolin#758]
I want to update the points under the guide of mouse events, such as click, select, double click and move. What can I do to catch them?

**Comment by PuYuuu** [comment]
I'm also curious about how to implement it.

**Comment by stevenlovegrove** [comment]
You should add a handler to the view. Just implement https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_display/include/pangolin/handler/handler.h#L56 or subclass https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_display/include/pangolin/handler/handler.h#L72 for example and put the logic in your custom implementation.

**Comment by PuYuuu** [comment]
> You should add a handler to the view. Just implement https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_display/include/pangolin/handler/handler.h#L56 or subclass https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_display/include/pangolin/handler/handler.h#L72 for example and put the logic in your custom implementation.

Sorry for late reply. I have realized my idea according to your advice, thanks!
