### ISSUE TITLE
Which g++ is suitable

### ISSUE THREAD

**Issue by QinHarry** [stevenlovegrove/Pangolin#76]
Hello,

Thanks for your work.
I try this for ORB_SLAM2 by g++-4.8.2, g++-4.9.3 and g++-5.3.0, and only g++-4.9.3 can build successful, and then there is std::run_timer. There is some g++ version request?

**Comment by stevenlovegrove** [comment]
What platform are you on? What is the precise compile error output?

Also, where does the std::runtime_error originate for g++4.9.3

**Comment by stevenlovegrove** [comment]
Is your error related to issue #72 ?

**Comment by stevenlovegrove** [comment]
Closing until further info.
