### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by erinline** [stevenlovegrove/Pangolin#763]
I looked through the old issues and have not seen a straightforward or working command. I need to reinstall because my paths are all mixed up, as I've tried several times to install this package for orb_slam ROS.

From inside the `Pangolin/build` directory, I ran `cmake_uninstall.cmake` and the output is:
```
erinline@erinline-linux:~/src/tello_orb_test/Pangolin/build$ ./cmake_uninstall.cmake 
./cmake_uninstall.cmake: line 2: syntax error near unexpected token `FATAL_ERROR'
./cmake_uninstall.cmake: line 2: `  message(FATAL_ERROR "Cannot find install manifest: /home/erinline/src/tello_orb_test/Pangolin/build/install_manifest.txt")'
```
What am I missing? Thanks!

**Comment by john-liu2039** [comment]
In your build directory, `sudo make uninstall` will uninstall the pangolin.

**Comment by AndrewJSong** [comment]
v0.8 can use your build file to unintstall. but it's not work for v0.6 v0.7,there is not the uninstall file.
v8 in your build folder: `sudo make uninstall`
