### ISSUE TITLE
New build commands in README.md do not work in ubuntu 18.04

### ISSUE THREAD

**Issue by Daniel-Reyes** [stevenlovegrove/Pangolin#765]
I tried the updated commands and the build did not start, specifically:

```
cmake -B build
cmake --build build
```
As workaround I successfully build the code with the old instructions before commit 6655b6284d226ed10ca70a80a46f9fb87d233b2c
Perhaps a specific version of cmake is required or additional steps are needed. Please revise it.

**Comment by christian-rauch** [comment]
Yes, I noticed recently that this does not work with CMake 3.10 in Ubuntu 18.04. For those older versions, you have to use the previous cmake instructions that create the build directory manually.

Note that Ubuntu 18.04 will go out of standard support in less than a year. I recommend switching to newer Ubuntu versions for newer projects.

**Comment by christian-rauch** [comment]
Ubuntu 18.04 is EOL. I am going to close this as EOL distributions are not supported as they cannot be tested natively on the CI. As a workaround for this particular issue, issue the "old" way of creating the build directory manually.
