### ISSUE TITLE
Camera can't work when I use Shaders

### ISSUE THREAD

**Issue by FurrySoM** [stevenlovegrove/Pangolin#783]
Hi,I'm new for OpenGL, I'm working in a Simple Program that Show the point receive from UDP and I can display Point with their own color and move camera to change visual without using shader, but I need shader to change their Attribute Overall Situation, And when I use Shader Program, the visual frozen, camera stuck.

Here are some code:

GLSL:
`const char *vertexShaderSource ="#version 330 core\n"`
`   "layout (location = 0) in vec3 aPos;\n"`
`    "layout (location = 1) in vec3 aColor;\n"`
`    "out vec4 ourColor;\n"`
`    "uniform float aAlpha;\n"`
`    "uniform int aPointSize;\n"`
`    "void main()\n"`
`    "{\n"`
`    "   gl_Position = vec4 (aPos, 1.0f);\n"`
`    "   ourColor = vec4(aColor, aAlpha);\n"`
`    "   gl_PointSize =  aPointSize;\n"`
`    "}\0";`

`const char *fragmentShaderSource = "#version 330 core\n"`
`    "in vec4 ourColor;\n"`
`    // "layout(location = 1) out vec4 gl_FragColor;\n"`
`    "void main()\n"`
`    "{\n"`
`    "   gl_FragColor = ourColor;\n"`
`    "}\n\0";`

Initialize:
`pangolin::CreateWindowAndBind("Main",1920,1080);`
`glEnable(GL_DEPTH_TEST);`
`    glEnable(GL_BLEND);`
`    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);`
`    const int UI_WIDTH = 20* pangolin::default_font().MaxWidth();`
    
`    glEnable(GL_PROGRAM_POINT_SIZE);`

`    pangolin::OpenGlRenderState s_cam(`
`        pangolin::ProjectionMatrix(1920,1080,420,420,320,240,0.2,10000),`
`        pangolin::ModelViewLookAt(-1,1,-1, 0,0,0, pangolin::AxisY)`
`    );`

`    pangolin::Handler3D handler(s_cam);`
`    pangolin::View& d_cam = pangolin::CreateDisplay()`
`            .SetBounds(0.0, 1.0, 0.0, 1.0, -1920.0f/1080.0f)`
`            .SetHandler(&handler);`
`    pangolin::CreatePanel("ui")`
`            .SetBounds(0.0, 1.0, 0.0,  pangolin::Attach::Pix(UI_WIDTH));`

the Point maybe display in openGL normally, I'm not sure, but the problem is camera,I can see the point between (-1.0f,-1.0f,0.0f) (1.0f,1.0f,0.0f),but I can't see the point have z-axis.

**Comment by stevenlovegrove** [comment]
When you use a shader, you have to take care of the view transform yourself explicitly. i.e. you will need to send the transform into the shader as a uniform and use it to transform the aPos before assigning to gl_Position in your code.

As an aside, you may find the OpenGL tutorials I recently added useful https://github.com/stevenlovegrove/Pangolin/tree/master/examples/BasicOpenGL though it doesn't yet provide an example of sending in the view transform as a uniform.
