### ISSUE TITLE
Segmentation Fault on pangolin::Var<bool> 

### ISSUE THREAD

**Issue by AndrewGeorgis** [stevenlovegrove/Pangolin#785]
The system breaks with a segmentation error in the Viewer class at the  the pangolin::Var<bool> menuFollowCamera("menu.Follow Camera",true,true); command  when I build the ORB-SLAM2 and running the  mono tum example , but it works well when I run the SimpleDisplay example.. The details from the gdb are:
![Screenshot from 2022-07-24 16-32-38](https://user-images.githubusercontent.com/50524921/180658213-1c77061c-de26-4912-9e57-b8b218549c0f.png)

I am running on Ubuntu 22.04 with Intel i5-12600K with Mesa Intel® Graphics (ADL-S GT1) and I am using Pangolin-0.5 (I tried Pangolin-0.6, 0.7 and latest version but I had the same results).

I can't understand this behavior. Any help?

**Comment by stevenlovegrove** [comment]
This looks like it should be raised against orb-slam2, not Pangolin. If you can recreate a minimal case with Pangolin only, please reopen this issue. Thanks!
