### ISSUE TITLE
Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY)

### ISSUE THREAD

**Issue by hcp6897** [stevenlovegrove/Pangolin#788]
When execute the compile command: cmake -B build, I encounter with the following errors.

CMake Error at /usr/local/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.21/Modules/FindOpenGL.cmake:443 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  components/pango_opengl/CMakeLists.txt:41 (find_package)
  CMakeLists.txt:114 (include)

Have installed the libs:

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
cmake is already the newest version (3.22.1-1ubuntu1).
g++ is already the newest version (4:11.2.0-1ubuntu1).
libjpeg-dev is already the newest version (8c-2ubuntu10).
libpng-dev is already the newest version (1.6.37-3build5).
libwayland-dev is already the newest version (1.20.0-1).
libxkbcommon-dev is already the newest version (1.4.0-1).
wayland-protocols is already the newest version (1.25-1).
libc++-dev is already the newest version (1:14.0-55~exp2).
libeigen3-dev is already the newest version (3.4.0-2ubuntu2).
libglew-dev is already the newest version (2.2.0-4).
ninja-build is already the newest version (1.10.1-1).
libegl1-mesa-dev is already the newest version (22.0.5-0ubuntu0.1).
libgl1-mesa-dev is already the newest version (22.0.5-0ubuntu0.1).
libavcodec-dev is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
libavdevice-dev is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
libavformat-dev is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
libavutil-dev is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
libswscale-dev is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

**Comment by mserkantan** [comment]
Hi! I've had the same issue.

I fixed it by installing the following libraries (Ubuntu 22.04)

sudo apt install libglew-dev
sudo apt-get install libegl1-mesa-dev

Cheers.

**Comment by Schweizliu** [comment]
hello！ I've had the same issue.But I can't solve this problem by using two commands. （Ubuntu20.04）
sudo apt install libglew-dev
sudo apt-get install libegl1-mesa-dev
How did you finally solve it？
