### ISSUE TITLE
failed to compile on Mac M2 

### ISSUE THREAD

**Issue by barakdiker123** [stevenlovegrove/Pangolin#789]
<command-line>: note: this is the location of the previous definition
/opt/local/include/pangolin/config.h:54: warning: "HAVE_OPENEXR" redefined
   54 | #define HAVE_OPENEXR
      |
<command-line>: note: this is the location of the previous definition
/opt/local/include/pangolin/config.h:59: warning: "_OSX_" redefined
   59 | #define _OSX_
      |
<command-line>: note: this is the location of the previous definition
/Users/barakdiker/install_from_git/Pangolin/components/pango_image/include/pangolin/image/pixel_format.h:62:21: error: expected unqualified-id before string constant
   62 | PANGOLIN_DEPRECATED("Use PixelFormat instead")
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/barakdiker/install_from_git/Pangolin/components/pango_image/include/pangolin/image/pixel_format.h:62:21: error: expected ')' before string constant
   62 | PANGOLIN_DEPRECATED("Use PixelFormat instead")
      |                    ~^~~~~~~~~~~~~~~~~~~~~~~~~
      |                     )
/Users/barakdiker/install_from_git/Pangolin/components/pango_image/include/pangolin/image/pixel_format.h:64:21: error: expected unqualified-id before string constant
   64 | PANGOLIN_DEPRECATED("Use PixelFormatFromString instead")
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/barakdiker/install_from_git/Pangolin/components/pango_image/include/pangolin/image/pixel_format.h:64:21: error: expected ')' before string constant
   64 | PANGOLIN_DEPRECATED("Use PixelFormatFromString instead")
      |                    ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     )
cc1plus: note: unrecognized command-line option '-Wno-deprecated-register' may have been intended to silence earlier diagnostics
make[2]: *** [CMakeFiles/pango_image.dir/components/pango_image/src/pixel_format.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by pra-dan** [comment]
Do you install JAVA on your mac? I installed using brew and still get 
```console
% ./scripts/install_prerequisites.sh recommended
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
```

**Comment by stevenlovegrove** [comment]
@barakdiker123
It looks like the Pangolin build environment is picking up previously installed headers in /opt/local?

@pra-dan 
Also, Java isn't required. It looks like ./scripts/install_prerequisites.sh is referring to an executable that your system thinks belongs to Java. Use the -m option to specify the package manager to use explicitly (you probably want port or brew for macos depending on which one you like to use).

For reference, I build Pangolin on an M1 mac, so there shouldn't be any large issues on an M2.

**Comment by barakdiker123** [comment]
@stevenlovegrove 
I am so sorry , the fix was really easy , the problem was that  OpenEXR_INCLUDE_DIR  took from brew 
and  OpenEXR_LIBRARY was taken from macport 
I entered 
ccmake .
 OpenEXR_INCLUDE_DIR              /opt/local/include/OpenEXR
 OpenEXR_LIBRARY                  /opt/local/lib/libIlmImf.dylib
and it worked 

I am sorry for the trouble I am newbi
