### ISSUE TITLE
pangolin/gl.h not found

### ISSUE THREAD

**Issue by theSage21** [stevenlovegrove/Pangolin#79]
I installed pangolin to finally install https://github.com/jserv/lsd_slam.

After installing Pangolin, on compiling lsd_slam, I am faced with an error

```
In file included from /home/arjoonn/temp/lsd_slam/lsd_slam_core/src/GUI.cpp:8:0:
/home/arjoonn/temp/lsd_slam/lsd_slam_core/src/GUI.h:14:25: fatal error: pangolin/gl.h: No such file or directory
compilation terminated.
```

How do I proceed?

**Comment by stevenlovegrove** [comment]
There are two possibilities. a) Pangolin didn't install correctly, or b) the application didn't find and use Pangolin correctly. I didn't think LSD_SLAM used Pangolin - are you using mp3guys fork? You should check that pangolin/gl.h exists where you think Pangolin is installed, and make sure that Pangolins include path is making it into the application.

**Comment by stevenlovegrove** [comment]
Closing until further info.
