### ISSUE TITLE
update vcpkg version to latest version

### ISSUE THREAD

**Issue by wholesomemoon** [stevenlovegrove/Pangolin#790]
Hi, I tried to use pangolin with vcpkg, but there has been no update since version 0.6. Does pangolin have any plans to update the vcpkg version to the latest 0.8 version? I'll be glad to have a reply.

**Comment by christian-rauch** [comment]
`vcpkg` is a submodule. Do you mean that the submodule should be updated? Are you encountering issues that get fixes with a newer `vcpkg`?
