### ISSUE TITLE
Can't show text using GlFont

### ISSUE THREAD

**Issue by ghost** [stevenlovegrove/Pangolin#796]
Hello, I recently tried to show a text message on Pangolin use the API GlFont, but it always fails to display, I don't know what the problem is, I pasted the code at the end of the article. Sorry to interrupt your time, thanks for your help!

**Comment by SEUleaderYang** [comment]
`
pangolin::CreateWindowAndBind("CG_Course", 1024, 768);
    glEnable(GL_DEPTH_TEST);
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

    pangolin::OpenGlRenderState s_cam(
            pangolin::ProjectionMatrix(1024, 768, 500, 500, 512, 389, 0.1, 1000),
            pangolin::ModelViewLookAt(0, -0.1, -1.8, 0, 0, 0, 0.0, -1.0, 0.0)
    );

    pangolin::View &d_cam = pangolin::CreateDisplay()
            .SetBounds(0.0, 1.0, 0.0, 1.0, -1024.0f / 768.0f)
            .SetHandler(new pangolin::Handler3D(s_cam));

    while (pangolin::ShouldQuit() == false) {
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
        d_cam.Activate(s_cam);
        glClearColor(0.0f, 0.0f, 0.0f, 1.0f);//设置背景颜色

        glLineWidth(2);
        glBegin(GL_TRIANGLES);//绘制三角形
        glColor3f(1.0, 0.0, 0.0);
        glVertex3f(0,1,1);
        glVertex3f(0,0,0);
        glVertex3f(1,0,1);
        glEnd();

        pangolin::GlFont * text_font = new pangolin::GlFont("/usr/share/fonts/truetype/fonts-beng-extra/JamrulNormal.ttf", 50.0);


        glColor3f(0.0,0.0,1.0);
        text_font->Text("123456789").Draw(4, 1, 1);

        glColor3f(0.0,1.0,0.0);
        text_font->Text("00000000").Draw(5, 1, 1);

        pangolin::FinishFrame();
        usleep(5000);   // sleep 5 ms
    }
`

**Comment by NikolausDemmel** [comment]
You might be rendering out of the display. Try something like

```
text_font->Text("00000000").Draw(5, 50);
```

Also, you have a big memory leak since you allocate a new font object in every loop iteration. You should do that outside the loop and also make sure to deallocate, e.g. with a `unique_ptr`.

You can also try with the default font if your font doesn't work:

```
pangolin::default_font().Text("foobar").Draw(5, 50);
```
