### ISSUE TITLE
Mac build is broken

### ISSUE THREAD

**Issue by mudit1729** [stevenlovegrove/Pangolin#797]
/Users/muditj/Desktop/development/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:59:5: **error: use of undeclared identifier 'AV_PIX_FMT_XVMC_MPEG2_MC'
    TEST_PIX_FMT_RETURN(XVMC_MPEG2_MC);**
    ^
/Users/muditj/Desktop/development/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:38:39: note: expanded from macro 'TEST_PIX_FMT_RETURN'
#define TEST_PIX_FMT_RETURN(fmt) case AV_PIX_FMT_##fmt: return #fmt;
                                      ^
<scratch space>:57:1: note: expanded from here
AV_PIX_FMT_XVMC_MPEG2_MC
^
In file included from /Users/muditj/Desktop/development/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:37:
In file included from /Users/muditj/Desktop/development/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg.h:32:
/Users/muditj/Desktop/development/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:60:5: **error: use of undeclared identifier 'AV_PIX_FMT_XVMC_MPEG2_IDCT'
    TEST_PIX_FMT_RETURN(XVMC_MPEG2_IDCT);
    ^**
/Users/muditj/Desktop/development/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:38:39: note: expanded from macro 'TEST_PIX_FMT_RETURN'

**Comment by mudit1729** [comment]
Commenting out those two lines is the work around for now.

**Comment by NikolausDemmel** [comment]
Should be fixed by #798. Please try latest `master`.
