### ISSUE TITLE
runtime error when using orb slam v2

### ISSUE THREAD

**Issue by jhz-linhe** [stevenlovegrove/Pangolin#80]
I am trying orb slam v2, encountering below error when launching.
Parallels ubuntu 14.04 virtual machine on Mac, 8G Memory, 4 Cores. 

terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Unable to retrieve framebuffer options
Aborted (core dumped)

Thank you all in advance for any help!

**Comment by stevenlovegrove** [comment]
This would appear to be a duplicate of issue #74
