### ISSUE TITLE
  Error in CUDA project using Eigen

### ISSUE THREAD

**Issue by XiaoHan-Git** [stevenlovegrove/Pangolin#814]
Hi, I tried to include the Pangolin header file in a CUDA project using the Eigen library, and an error occurred.
In gl/glsl.h header file, it seems required to avoid using Eigen in CUDA.
`
#ifdef HAVE_GLES
    #define GLhandleARB GLuint
#endif

#if defined(HAVE_EIGEN) && !defined(__CUDACC__) //prevent including Eigen in cuda files
#define USE_EIGEN
#endif

#ifdef USE_EIGEN
#include <Eigen/Core>
#endif // USE_EIGEN
`

What can I do to use pangolin? Thank you for your reply.

**Comment by stevenlovegrove** [comment]
Nowadays I think Eigen plays relatively nicely with Cuda, so it's possible you can just remove that guard and let Eigen get included. Otherwise, you can extend the guard to wherever the error is assuming Eigen is available.

**Comment by XiaoHan-Git** [comment]
Thank you for your reply and close the question
