### ISSUE TITLE
Python executable environment variable wrong in README.md

### ISSUE THREAD

**Issue by DocGarbanzo** [stevenlovegrove/Pangolin#823]
It looks like the CMake environment variable for determining the python executable path is called `Python_EXECUTABLE`. Can you please update the README.md accordingly, like:

``cmake -DPython_EXECUTABLE=`which python3` `` instead of ``cmake -DPYTHON_EXECUTABLE=`which python3` ``

**Comment by sisuy** [comment]
Hi, have you fixed this problem? When I tried to change the path of python into python3 by using `cmake -DPYTHON_EXECUTABLE=`which python3``
it outputs:
`CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.
CMake Error at CMakeLists.txt:15 (message):
  Source build detected: please use a subdir.  You may remove
  'CMakeCache.txt' and 'CMakeFiles'.
-- Configuring incomplete, errors occurred!`

I just considerate if it's correct to use `cmake -DPYTHON_EXECUTABLE="which python3"` to change the python path.

**Comment by stevenlovegrove** [comment]
Updated in #786. Thanks!
