### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0

### ISSUE THREAD

**Issue by Xu-ht** [stevenlovegrove/Pangolin#824]
I built Pangolin with the following command
```
cmake -B build
cmake --build build
```
Then I installed pypangolin by
```
cmake --build build -t pypangolin_pip_install
```
When I tried to import pypangolin I recieved the ImportError
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0
```
I did all above in a conda environment with Python 3.8.15. My system is WSL2, Ubuntu 20.04.
I'll be gratefull if someone can give me any advice!!

**Comment by frischzenger** [comment]
i meet the same problem, have you solved it ?

**Comment by Xu-ht** [comment]
> 
Sorry I haven't found a solution yet.

**Comment by frischzenger** [comment]
i have solved this problem by add:
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libffi.so.7

**Comment by Xu-ht** [comment]
> i have solved this problem by add: export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libffi.so.7
It works for me too! Thanks a lot!
