### ISSUE TITLE
Quit mechanism?

### ISSUE THREAD

**Issue by nrhine1** [stevenlovegrove/Pangolin#83]
Is there a quitting mechanism implemented? None of the examples seem to demonstrate programmatically closing a window (and then opening a new one). I tried calling the `PangolinGl::~PangolinGl()` destructor (via delete), which is called properly, but my window remains. The `PangolinGl::Quit()` method sets a flag, which seems to be around only for API-user purposes - no aspect of the system seems to be monitoring this flag.

Something like the opposite of `CreateWindowAndBind` is what I'm looking for.

Thanks

**Comment by stevenlovegrove** [comment]
Good question - no, closing a window programmatically without terminating the application isn't something that I've thought about much. That being said, removing the PangolinGl context from the ContextMap (causing destruction) should be all that's needed. If destruction of PangolinGl doesn't work for you, there may be a problem with the PangolinPlatformDeinit for your platform. Which platform are you using?

**Comment by nrhine1** [comment]
Thanks for your reply. Erasing the context from the ContextMap didn't invoke destruction of the window, but using `glutDestroyWindow(int window_id)` does (both from the same point in the code). I'm on ubuntu 14.04. I ended up pursuing a different route rather than resetting the window.

**Comment by stevenlovegrove** [comment]
Pangolin supports native X11 windowing on Linux, in case you choose to avoid glut in the future. I've just pushed f5fff6815ab817e83687494f71b2b3f0d46b479e which ensures glutDestroyWindow is called on PangolinGl destruction when glut is being used.
