### ISSUE TITLE
OpenNI: Unsupported Platform

### ISSUE THREAD

**Issue by chaiein** [stevenlovegrove/Pangolin#84]
error: #error OpenNI Platform Abstraction Layer - Unsupported Platform!
  #error OpenNI Platform Abstraction Layer - Unsupported Platform!

On building pangolin it shows the above error.  How to resolve this issue in linux

**Comment by eyolla** [comment]
Hi, 
its is because Openni explicitly not supporting visual studio 2008 or later.
Go to openni folder: program files\openni\include\XnPlatform.h
locate the platform identifier section of the code and remove the second option for > MSVC 2008 or simply remove this part of the code:
@
#if _MSC_VER > 1600 // After MSVC8 (2010)
    #error Xiron Platform Abstraction Layer - Win32 - Microsoft Visual Studio versions above 2010 (10.0) are not supported!
 #endif
@

**Comment by chaiein** [comment]
But i am building on Linux.Not visual studio not Windows.

**Comment by stevenlovegrove** [comment]
Firstly, I would recommend to use the OpenNI2 fork from occipital, if you're not already (https://github.com/occipital/OpenNI2/commits/develop). It has more features than the original OpenNI library and it is well tested within Pangolin right now.

Whatever version of OpenNI that you're currently using is possibly expecting a platform macro (LINUX, I think) to be defined by the user API. If you don't want to try OpenNI2, then you should try adding that definition to Pangolin (or looking in the source of OpenNI for which definition it is testing on).

**Comment by stevenlovegrove** [comment]
I tried adding a definition which may help you in commit 607d76915880c0c1bf64f2c83ceefb586fd2650b. I'll close for now, but reopen if you want to provide more details.

**Comment by umbraclet16** [comment]
I encountered the same errors.
Firstly I installed OpenNI2 with synaptic, it didn't work;
then I tried the fork from occipital, error occured during compilation...
So I gave up and commented out `find_package(OpenNI QUIET)` and `find_package(OpenNI2 QUIET)` blocks in *src/CMakeLists.txt* to **"blank out it's include and library directories"** as said in README.md.
Building succeded, but will this cause any problems?

**Comment by stevenlovegrove** [comment]
By "blank out it's include and library directories", I really mean to set the corresponding variables to the empty string using ccmake, or cmake-gui, but what you did is fine too. Those libraries are only necessary if you plan to use a Primesense / Kinect camera.
