### ISSUE TITLE
ctest does not work on Ubuntu 18.04!

### ISSUE THREAD

**Issue by milan-r-shah** [stevenlovegrove/Pangolin#847]
After following these steps:
```
# Get Pangolin
cd ~/your_fav_code_directory
git clone --recursive https://github.com/stevenlovegrove/Pangolin.git
cd Pangolin

# Install dependencies (as described above, or your preferred method)
./scripts/install_prerequisites.sh recommended

# with Ninja for faster builds (sudo apt install ninja-build)
cmake -B build -GNinja

# GIVEME THE PYTHON STUFF!!!! (Check the output to verify selected python version)
cmake --build build -t pypangolin_pip_install
```

when I try to run `ctest`, I'm getting an error:
```
<my_fav_code_dir>/Pangolin$ ctest
*********************************
No test configuration file found!
*********************************
Usage

  ctest [options]
```
---
- I'm on Ubuntu 18.04:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

- I do have `ctest` installed:
```
$ which ctest
/usr/local/bin/ctest
$ ctest --version
ctest version 3.24.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

- `cmake` info:
```
$ which cmake
/usr/local/bin/cmake
$ cmake --version
cmake version 3.24.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by stevenlovegrove** [comment]
Pangolin uses the Catch2 library for tests, though in honesty the code coverage is quite low so it isn't going to be super informative for you. If you really want to run tests, you need to make sure that the CMake script can find your Catch2 install. I can't remember, but perhaps it isn't available in apt in 18.04 and might need to be installed manually

**Comment by milan-r-shah** [comment]
> ... but perhaps it isn't available in apt in 18.04 and might need to be installed manually

It is available on 18.4 (or at least I have it on my machine):
```
$ which ctest
/usr/local/bin/ctest
$ ctest --version
ctest version 3.24.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by christian-rauch** [comment]
You have to enable and build the tests (`cmake -B build -G Ninja -D BUILD_TESTS=ON && cmake --build build`) and run `ctest` from within the build folder, i.e. `cd build && ctest`.

**Comment by christian-rauch** [comment]
I added the testing instructions to the README and the CI is now also running the tests: https://github.com/stevenlovegrove/Pangolin/pull/904. The tests are only supported on Ubuntu 22.04.
