### ISSUE TITLE
How can I check Pangolin has been installed properly if ctest is not working?

### ISSUE THREAD

**Issue by milan-r-shah** [stevenlovegrove/Pangolin#849]
I followed the instructions for installing Pangolin. However, I'm not sure whether it got installed properly or not because `ctest` is not working. I have created an issue for that: https://github.com/stevenlovegrove/Pangolin/issues/847

So, for some reason, if `ctest` is a whole other issue then how can I check whether Pangolin has been installed properly or not?

For context, I'm trying to build https://github.com/raulmur/ORB_SLAM2/ which has a dependency on Pangolin. Currently, I'm having issues building that repo. So, want to make sure it's not because of Pangolin.

**Comment by stevenlovegrove** [comment]
The best way is to run the Pangolin examples. If Pangolin builds and the examples run, it should be good to go
