### ISSUE TITLE
windows platform with build_shared_library problem

### ISSUE THREAD

**Issue by albanjiang** [stevenlovegrove/Pangolin#851]
use cmake with build_shared_library
pango_vars project with preprocessor definitions : pango_vars_EXPORTS
![image](https://user-images.githubusercontent.com/3388033/227696705-fb8a4dec-c273-423b-9ad0-b424c61f24de.png)
but in header file: only pango_core_EXPORTS
![image](https://user-images.githubusercontent.com/3388033/227696741-a0422f03-6231-4f2c-84af-f18d57c6d48f.png) 
mismatch!

**Comment by albanjiang** [comment]
tag v0.8

**Comment by christian-rauch** [comment]
Can you be more concrete about what issue you are facing? 

The file is generated via `GenerateExportHeader` in the `pango_core` component: https://github.com/stevenlovegrove/Pangolin/blob/v0.9.1/components/pango_core/CMakeLists.txt#L55-L70. Other components, such as `pango_vars`, do not generate such export headers.
