### ISSUE TITLE
Snap window to certain position

### ISSUE THREAD

**Issue by Mechazo11** [stevenlovegrove/Pangolin#857]
Hi @stevenlovegrove,

Thank you very much for creating this wonderful visualization tool. I was wondering is there a way to snap a Pangolin view window to a certain location of the screen? Something equivalent to OpenCV's https://docs.opencv.org/3.4/d7/dfc/group__highgui.html#ga8d86b207f7211250dbe6e28f76307ffb?

I am in need to open two separate Pangolin windows but they appear randomly at certain locations. I want them to take up fixed position everytime they are initialized.

With best,
@Mechazo11

**Comment by stevenlovegrove** [comment]
`CreateWindowAndBind(...)` returns a reference to a `WindowInterface` (see https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_display/include/pangolin/display/display.h#L63) which you can use to call `Move(...)` (https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_windowing/include/pangolin/windowing/window.h#L99)

e.g.
```
auto win = pangolin::CreateWindowAndBind("Main",640,480);
win.Move(30,40);
...
```

I can't say it is very well used, so the likelihood of finding a bug is moderate :D

**Comment by Mechazo11** [comment]
> `CreateWindowAndBind(...)` returns a reference to a `WindowInterface` (see https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_display/include/pangolin/display/display.h#L63) which you can use to call `Move(...)` (https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_windowing/include/pangolin/windowing/window.h#L99)
> 
> e.g.
> 
> ```
> auto win = pangolin::CreateWindowAndBind("Main",640,480);
> win.Move(30,40);
> ...
> ```
> 
> I can't say it is very well used, so the likelihood of finding a bug is moderate :D

Thanks for the heads up, I will try it out and let you know whether any error message or unwarranted behavior is observed

**Comment by Mechazo11** [comment]
Hi, I am getting this error when I tried `auto win = ...` as suggested

```
/home/icore_base/catkin_ws/src/orb_slam3_ros/orb_slam3/src/Viewer.cc:212:10: error: cannot declare variable ‘win’ to be of abstract type ‘pangolin::WindowInterface’
  212 |     auto win = pangolin::CreateWindowAndBind(mpSystem->mnAgentName,640,480); //* Controls the size of the pangolin window
```

**Comment by stevenlovegrove** [comment]
I had a mistake in my sample. I meant `auto& win = ...` since it is returning a reference.

**Comment by Mechazo11** [comment]
@stevenlovegrove the code works now, I was able to move the two instances of Pangolin window to locations where I wanted them to be. 

This is how I have integrated @stevenlovegrove suggested code in my project

```
//* MULTI-AGENT, show unique name of the agent
    //pangolin::CreateWindowAndBind(mpSystem->mnAgentName,640,480); // Original version
    
    // EXPERIMENTAL, based on teh suggestion given by @stevenlovegrove here
    // https://github.com/stevenlovegrove/Pangolin/issues/857
    auto &win = pangolin::CreateWindowAndBind(mpSystem->mnAgentName,640,480); //* Controls the size of the pangolin window
    
    //* MULTI-AGENT, HARDCODED, only works in 1920 x 1080 monitor
    if(mpSystem->mnAgentName.compare("/robot0")==0){
        win.Move(0,0); // Top left
    }

    if(mpSystem->mnAgentName.compare("/robot1")==0){
        win.Move(720,0); // Middle left
    }
```

Thank you very much for your help.
