### ISSUE TITLE
Import error for "import pypangolin"

### ISSUE THREAD

**Issue by AllenIsaacJose** [stevenlovegrove/Pangolin#863]
Python 3.8.16 (default, Mar  2 2023, 03:21:46) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypangolin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0

Anyone got similar error?

**Comment by MohitBurkule** [comment]
Have the same error here, did you manage to get it running?

**Comment by TriniKiskadee** [comment]
I'm getting this error
```
import pypangolin as pangolin
ImportError: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_once_init_leave_pointer
```

**Comment by christian-rauch** [comment]
After building the wheel file (`cmake --build build -t pypangolin_wheel`), I can execute the examples without issues.

How are you building the wheel file? Can you provide details on how to reproduce the issue?
