### ISSUE TITLE
py:module_ has not been declared 

### ISSUE THREAD

**Issue by mgrallos** [stevenlovegrove/Pangolin#869]
/home/asimov-hawks/tellovisual_ws/src/Pangolin/components/pango_python/src/pyinterpreter.cpp:61:27: error: ‘py::module_’ has not been declared
   61 |     auto pypangolin = py::module_::import("pypangolin");
      |                           ^~~~~~~
/home/asimov-hawks/tellovisual_ws/src/Pangolin/components/pango_python/src/pyinterpreter.cpp:63:20: error: ‘py::module_’ has not been declared
   63 |     auto sys = py::module_::import("sys");

**Comment by TheSeanParker** [comment]
could you  show your code?maybe somebody will know the specify problem

**Comment by TheSeanParker** [comment]
> /home/asimov-hawks/tellovisual_ws/src/Pangolin/components/pango_python/src/pyinterpreter.cpp:61:27: error: ‘py::module_’ has not been declared 61 | auto pypangolin = py::module_::import("pypangolin"); | ^~~~~~~ /home/asimov-hawks/tellovisual_ws/src/Pangolin/components/pango_python/src/pyinterpreter.cpp:63:20: error: ‘py::module_’ has not been declared 63 | auto sys = py::module_::import("sys");

could you show your code?maybe somebody will know the specify problem

**Comment by wangfei-tech** [comment]
@mgrallos Is your problem solved? @TheSeanParker I followed the steps in the readme，I also encountered the same problem. The environment I use is ubuntu20.04 installed in the vmware16.0pro.My problem is:
```
cmake --build build
[ 80%] Built target tinyobj
[ 80%] Built target pango_core
[ 80%] Built target pango_image
[ 80%] Built target pango_opengl
[ 80%] Built target pango_windowing
[ 80%] Built target pango_vars
[ 80%] Built target pango_display
[ 80%] Built target pango_geometry
[ 80%] Built target pango_glgeometry
[ 80%] Built target pango_packetstream
[ 80%] Built target pango_video
[ 80%] Built target pango_scene
[ 80%] Built target pango_plot
[ 80%] Built target pypangolin
[ 80%] Built target pango_tools
[ 80%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pyinterpreter.cpp.o
/home/wf/slam_in_autonomous_driving/thirdparty/Pangolin/components/pango_python/src/pyinterpreter.cpp: In constructor ‘pangolin::PyInterpreter::PyInterpreter()’:
/home/wf/slam_in_autonomous_driving/thirdparty/Pangolin/components/pango_python/src/pyinterpreter.cpp:61:27: error: ‘py::module_’ has not been declared
   61 |     auto pypangolin = py::module_::import("pypangolin");
      |                           ^~~~~~~
/home/wf/slam_in_autonomous_driving/thirdparty/Pangolin/components/pango_python/src/pyinterpreter.cpp:63:20: error: ‘py::module_’ has not been declared
   63 |     auto sys = py::module_::import("sys");
      |                    ^~~~~~~
make[2]: *** [CMakeFiles/pango_python.dir/build.make:63: CMakeFiles/pango_python.dir/components/pango_python/src/pyinterpreter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:794: CMakeFiles/pango_python.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by wangfei-tech** [comment]
> 

I have already solved this problem, I use the zip file given to me by others, and then decompress it, and the problem does not appear after following the readme operation.

**Comment by wangfei-tech** [comment]
> @mgrallos Is your problem solved? @TheSeanParker I followed the steps in the readme，I also encountered the same problem. The environment I use is ubuntu20.04 installed in the vmware16.0pro.My problem is:
> 
> ```
> cmake --build build
> [ 80%] Built target tinyobj
> [ 80%] Built target pango_core
> [ 80%] Built target pango_image
> [ 80%] Built target pango_opengl
> [ 80%] Built target pango_windowing
> [ 80%] Built target pango_vars
> [ 80%] Built target pango_display
> [ 80%] Built target pango_geometry
> [ 80%] Built target pango_glgeometry
> [ 80%] Built target pango_packetstream
> [ 80%] Built target pango_video
> [ 80%] Built target pango_scene
> [ 80%] Built target pango_plot
> [ 80%] Built target pypangolin
> [ 80%] Built target pango_tools
> [ 80%] Building CXX object CMakeFiles/pango_python.dir/components/pango_python/src/pyinterpreter.cpp.o
> /home/wf/slam_in_autonomous_driving/thirdparty/Pangolin/components/pango_python/src/pyinterpreter.cpp: In constructor ‘pangolin::PyInterpreter::PyInterpreter()’:
> /home/wf/slam_in_autonomous_driving/thirdparty/Pangolin/components/pango_python/src/pyinterpreter.cpp:61:27: error: ‘py::module_’ has not been declared
>    61 |     auto pypangolin = py::module_::import("pypangolin");
>       |                           ^~~~~~~
> /home/wf/slam_in_autonomous_driving/thirdparty/Pangolin/components/pango_python/src/pyinterpreter.cpp:63:20: error: ‘py::module_’ has not been declared
>    63 |     auto sys = py::module_::import("sys");
>       |                    ^~~~~~~
> make[2]: *** [CMakeFiles/pango_python.dir/build.make:63: CMakeFiles/pango_python.dir/components/pango_python/src/pyinterpreter.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:794: CMakeFiles/pango_python.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> ```
I have already solved this problem, I use the zip file given to me by others, and then decompress it, and the problem does not appear after following the readme operation.

**Comment by TangMinLeo** [comment]
> 

what zip file you used to solve this problem? can you share it ?

**Comment by TangMinLeo** [comment]
@wangfei-tech what zip file you used to solve this problem? can you share it ?

**Comment by ue007** [comment]
@wangfei-tech what zip file you used to solve this problem? can you share it ?

**Comment by qwert12131990** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ue007** [comment]
sudo git submodule update --init

**Comment by iphylq** [comment]
you should update your pybind11 to v2.11 or before, i just use v2.11 to work good.

**Comment by furkansariyildiz** [comment]
> I solved the problem by replacing the version of Pangolin. The initial version I had was 0.8, and I replaced it with version 0.6, which didn't have this issue.

Yea, it is removing error when i try to **_colcon build --symlink-install --packages-select pangolin_**

**Comment by ErnestF22** [comment]
Had the same compilation error while building version 0.9.1 of Pangolin (SDV-LOAM dependency) on Ubuntu 20.04. Made it work by using Pangolin 0.6.

**Comment by christian-rauch** [comment]
Is this still an issue on the current `master` (i.e. with https://github.com/stevenlovegrove/Pangolin/pull/906)? The CI builds the `pango_python` component without an issue: https://github.com/stevenlovegrove/Pangolin/actions/runs/7820164725/job/21334232895.

**Comment by zhaoxiaoxin** [comment]
参考博客 https://www.jianshu.com/p/fc61bf01a3d9 可以解决这个问题
