### ISSUE TITLE
error: could not find git for clone of __glew

### ISSUE THREAD

**Issue by SkyRiderMike** [stevenlovegrove/Pangolin#87]
Hello! I am trying to build Pangolin under windows environment..But After running with CMake, it shows out the result : error: could not find git for clone of __glew .

What should I do about this ? Many THanks!

**Comment by SkyRiderMike** [comment]
Hello...Is there anyone to answer me ?

**Comment by SkyRiderMike** [comment]
OK...I solved it by myself...Downloading a github program and use git hub shell to build it..success!

**Comment by stevenlovegrove** [comment]
I'm sorry I missed your issue. I'm glad you managed to solve it.

For others, if you don't have git on your Windows environment and don't want to install it, you can also obtain and build the repositories yourself (via zip file from github.com for example) and disable the options BUILD_EXTERN_GLEW, BUILD_EXTERN_LIBPNG and BUILD_EXTERN_JPEG with CMake.
