### ISSUE TITLE
When I make install the Pangolin

### ISSUE THREAD

**Issue by fit1999123** [stevenlovegrove/Pangolin#874]
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglCreateWindowSurface'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglBindAPI'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglCreateContext'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglMakeCurrent'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglDestroySurface'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglGetDisplay'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglChooseConfig'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglInitialize'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglGetConfigs'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglDestroyContext'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglSwapInterval'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglSwapBuffers'
/usr/bin/ld: ../../libpango_windowing.so: undefined reference to `eglTerminate'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/BasicOpenGL/CMakeFiles/tutorial_3_gl_intro_classic_triangle_vbo_shader.dir/build.make:94: examples/BasicOpenGL/tutorial_3_gl_intro_classic_triangle_vbo_shader] Error 1
make[1]: *** [CMakeFiles/Makefile2:960: examples/BasicOpenGL/CMakeFiles/tutorial_3_gl_intro_classic_triangle_vbo_shader.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by christian-rauch** [comment]
Interesting that CMake did not complain about missing packages beforehand. Can you provide details on your setup and how you compiled Pangolin? Did you run `./scripts/install_prerequisites.sh` beforehand to install the required packages?
