### ISSUE TITLE
Not able to install Pangolin

### ISSUE THREAD

**Issue by PrashnikB** [stevenlovegrove/Pangolin#877]
Getting the following error

(base) PS C:\Users\Administrator\Pangolin\build> cmake -DPython_EXECUTABLE=/path/to/python ..
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:3 (project):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
(base) PS C:\Users\Administrator\Pangolin\build> cmake -DPython_EXECUTABLE=`which python3`
CMake Error: The source directory "C:/Users/Administrator/Pangolin/build/python3`" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by christian-rauch** [comment]
You have to install a compiler. Windows builds are now enabled on the CI again to make sure they build with the specified dependencies.
