### ISSUE TITLE
How to get Realsense working on macOS

### ISSUE THREAD

**Issue by crosswick** [stevenlovegrove/Pangolin#879]
Hi all,

I've read the README a couple of times but can't figure this out on my own... how do I get my D405 Realsense camera to basically work?

I've followed the Building instructions with this dependency installation method:
`./scripts/install_prerequisites.sh -m brew all`

There are no errors during the build process; I am able to run 
`./VideoViewer test:// `
with no issue.

However if I try to run
`./VideoViewer realsense://` 
I get:
`libc++abi: terminating with uncaught exception of type pangolin::FactoryRegistry::NoMatchingSchemeException: Unable to open URI
  full_uri: realsense://
  scheme: realsense
  params:
 No matching scheme.`

Also, I notice that the build/components director only has a `pango_python` folder... so perhaps a whole bunch of components, including the realsense stuff is not being built? I could not find how to configure this in any of the CMakeLists.txt.

Could anyone give me some advice please? Perhaps @jstraub? Thanks in advance.

**Comment by crosswick** [comment]
Ah, I just noticed that in `install_prerequisites.sh`, there is no entry for realsense or librealsense in the brew manager section...

**Comment by crosswick** [comment]
Got it to work:

- added `PKGS_ALL+=(openni2 realsense2)` to the brew part of install_prerequisites.sh
- ran VideoViewer as root, because USB weirdness in macOS Monterey
- applied [this patch](https://github.com/stevenlovegrove/Pangolin/issues/461#issuecomment-463161375)

**Comment by christian-rauch** [comment]
I am going to close this. You can send a PR to have this enabled and checked on the CI.
