### ISSUE TITLE
Bunch of errors when trying to add Pangolin to this 3D camera app

### ISSUE THREAD

**Issue by crosswick** [stevenlovegrove/Pangolin#887]
Hi - I would like to use this existing app to get a point cloud stream from my Revopoint POP 3, and do some processing on it using Pangolin and Cilantro:

https://github.com/Revopoint/3DViewer

However each time I do a minimal inclusion of Pangolin in the relevant CMakeLists.txt of this project, I get a whole bunch of errors, like for instance:

```
In file included from /usr/local/Cellar/qt@5/5.15.10_1/lib/QtWidgets.framework/Headers/QDialog:                    ~~~~~~~~~~~~~~~~~~~~~~~~~^1:
In file included from 
error: /usr/local/Cellar/qt@5/5.15.10_1/lib/QtWidgets.framework/Headers/qdialog.h:43/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/type_traits:
:error: 
no template named 'is_trivial_v' in namespace 'std'; did you mean 'is_trivial'?3728In file included from :/usr/local/include/QtWidgets/qtwidgetsglobal.h50
:7:                     ~~~~~^7 :

expected '(' for function-style cast or type constructionIn file included from /usr/local/include/QtGui/qtguiglobal.h
```

Perhaps somebody could help me figure out what's going on here, please? Seems like some kind of Qt conflict. Or perhaps a matter of conflicting C++ standards?

**Comment by crosswick** [comment]
Meanwhile it seems it may be a conflict between versions 5 and 6 of Qt on my system; still investigating

**Comment by stevenlovegrove** [comment]
I'm sorry no-one had any suggestions for you on this. I hope you figured it out. Since this is quite old and very user / machine / version dependent, I'll close the issue out.
