### ISSUE TITLE
how does use pycharm to add package about pangolin or pypangolin?

### ISSUE THREAD

**Issue by lingtaochen1999** [stevenlovegrove/Pangolin#890]
I want to use it from [deepsdf](https://github.com/facebookresearch/DeepSDF), but it's a problem to add package about pangolin or pypangolin.

```
import ctypes
import deep_sdf.data
import sys

import OpenGL.GL as gl
import pypangolin as pango
```

question is no module named 'pypangolin' and no way to install or add package

**Comment by stevenlovegrove** [comment]
My apologies for the terribly slow reply. I hope you figured it out.

For anyone else, the Pangolin README has some info on compiling with Python support. If that information doesn't let you run the Pangolin python examples correctly, feel free to submit a new issue.

For anyone else trying to run DeepSDF, you could try a snapshot of Pangolin that coincides with the release of that repo or look through some of the issues posted over there which have some answers.
