### ISSUE TITLE
pangolin display distortion

### ISSUE THREAD

**Issue by Jack1412** [stevenlovegrove/Pangolin#891]
From the figure, the blue box was originally a standard cube, but from the viewer, it appears to have been deformed![image](https://github.com/stevenlovegrove/Pangolin/assets/32595707/1a5651d1-ac8b-4fcc-b052-f1bfb367afea)

My question is how to restore the distortion. When I drag and rotate or translate, the shape can maintain its original shape. Thanks!

**Comment by Jack1412** [comment]
My guess is to ajust camera ProjectionMatrix, but I don't know how to do it
![image](https://github.com/stevenlovegrove/Pangolin/assets/32595707/0409670b-58e1-4118-b9fe-e34d80ebf291)

**Comment by christian-rauch** [comment]
My guess would also be that you have to adjust the projection matrix. What is your `WIN_WIDTH` and `WIN_HEIGHT`? Is the centre (`u0`, `v0`) really in the centre?

Take a look at the `SimpleDisplay` example and maybe start from there: https://github.com/stevenlovegrove/Pangolin/blob/099f298d785b757c8691b88a90210d99c5fcf143/examples/SimpleDisplay/main.cpp#L22-L25

Also take a look at https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_opengl/src/opengl_render_state.cpp for alternative projection matrices.
