### ISSUE TITLE
Encountering Build Issues with UVC

### ISSUE THREAD

**Issue by half-potato** [stevenlovegrove/Pangolin#90]
I followed the directions but make -j spit out an error:

`/home/amai/Pangolin-Devel/src/video/drivers/uvc.cpp: In member function ‘void pangolin::UvcVideo::InitDevice(int, int, const char*, int, int, int, int)’:
/home/amai/Pangolin-Devel/src/video/drivers/uvc.cpp:157:11: error: ‘uvc_format_desc_t’ does not name a type
     const uvc_format_desc_t* uvc_fmt = uvc_get_format_descs(devh_);
           ^
/home/amai/Pangolin-Devel/src/video/drivers/uvc.cpp:158:12: error: ‘uvc_fmt’ was not declared in this scope
     while( uvc_fmt->bFormatIndex != ctrl_.bFormatIndex && uvc_fmt ) {
            ^
/home/amai/Pangolin-Devel/src/video/drivers/uvc.cpp:162:8: error: ‘uvc_fmt’ was not declared in this scope
     if(uvc_fmt) {
        ^
make[2]: *** [src/CMakeFiles/pangolin.dir/video/drivers/uvc.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2`

I've installed libuvc from scratch and have tried both the master and devel branch.

**Comment by half-potato** [comment]
I fixed this by modifying Pangolin/CMakeModules/Finduvc.cmake and commenting out the whole IF DEF section and adding SET(uvc_FOUND FALSE). However, if there was a work around that enables UVC as well, that would be great.

**Comment by extr15** [comment]
May try `cmake -DBUILD_PANGOLIN_LIBUVC=OFF ..`
