### ISSUE TITLE
wayland-util.h: No such file or directory

### ISSUE THREAD

**Issue by adizhol-str** [stevenlovegrove/Pangolin#907]
```
/Pangolin/build/xdg-shell-protocol.c:33:10: fatal error: wayland-util.h: No such file or directory
   33 | #include "wayland-util.h"
      |
```

WSL version: 2.0.14.0 
Ubuntu 22.04 

I ran the suggested lines in the README
```
./scripts/install_prerequisites.sh recommended
cmake -B build -GNinja
cmake --build build
```

I also tried to install wayland and wayland-dev manually, but the error still exists.
the .h file exists on my machine: /usr/include/wayland-util.h

**Comment by christian-rauch** [comment]
That header is part of the package [`libwayland-dev`](https://packages.ubuntu.com/jammy/amd64/libwayland-dev/filelist) which is in the `PKGS_REQUIRED` of the [installation script](https://github.com/stevenlovegrove/Pangolin/blob/v0.9.1/scripts/install_prerequisites.sh#L122).

Can you run the script again, check for errors and do a clean build? If you install the package after CMake caches all configurations, then they may not get updated.

Even if the Wayland dependencies are not installed, CMake should ignore the missing packages and skip over the Wayland build.

In the relevant CMake section, `WAYLAND_CLIENT_FOUND` should be false when `wayland-client` is not found:
https://github.com/stevenlovegrove/Pangolin/blob/7364b59a58045d1c429b146e44f6f088fd1cc518/components/pango_windowing/CMakeLists.txt#L34-L75

However, having found `wayland-client` means that the `wayland-client.pc` from the `libwayland-dev` should be there and hence the headers from the same package should be there too.

Do you see a reason why the `wayland-client.pc` would be anywhere in the pkg-config search paths but the headers from the same package not when dealing with Ubuntu on WSL?

**Comment by adizhol-str** [comment]
This is also probably relevant to #908. Running the examples in WSL Ubuntu 22.04 pangolin seg faults (after installing wayland-dev). So maybe should be a way to disable wayland in the project.
So to sum-up, after installing wayland-dev, build completes, but seg-faults on Ubuntu WSL. Setting WAYLAND_DISPLAY=0 solves the crush.

**Comment by christian-rauch** [comment]
According to the CMake excerpt above, the Wayland windowing interface is automatically deactivated when the dependencies are not found. That is the same behaviour as for other features. E.g. the `X11Window` interface will not be built if the X11 development libraries and headers are unavailable. There are no options to turn those features on or off explicitly.

**Comment by mjunsen123** [comment]
I met the same issue, it works when I build v0.6 instead of the latest tag

**Comment by eleboss** [comment]
comment the cmake file also helps the build. tested under ubuntu 22.04
