### ISSUE TITLE
Need help with framebuffer

### ISSUE THREAD

**Issue by IamRam3** [stevenlovegrove/Pangolin#909]
```
Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.
```
in jetson agx orin this is displayed when I try to run orbslam3 with the docker image.
But in jetson nano
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Unable to retrieve framebuffer options
```
this is coming with the same docker image that I used on jetson agx orin

**Comment by christian-rauch** [comment]
Can you provide a backtrace via gdb?

Does https://github.com/stevenlovegrove/Pangolin/pull/389 fix the issue?

**Comment by IamRam3** [comment]
sorry, I couldn't be able to backtrace as the processes(rviz and orbslam3) processes are keep getting close within seconds due to the above error. And I failed to mention in the first comment that, "qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual." these errors are coming along with the errors in jetson nano.

and I don't know how to follow #389. So, I have tried to build my application on your "x11_egl" branch. But it failed.

**Comment by christian-rauch** [comment]
> I couldn't be able to backtrace as the processes(rviz and orbslam3) processes are keep getting close within seconds due to the above error.

I don't see how Pangolin is related to RViz. I meant you should provide a gdb backtrace of whatever process is using Pangolin and crashing in order to determine where the issue is coming from.

> and I don't know how to follow #389. So, I have tried to build my application on your "x11_egl" branch. But it failed.

This is a PR whose branch you can check out and build according to the Pangolin instructions. Can you provide details why the built did not work?

**Comment by IamRam3** [comment]
Actually I found the cause, that the processes mentioned above couldn't be able to locate OpenGL libraries.
orbslam3 algorithm uses pangolin. Since both Pangolin and rviz are dependent on OpenGL. They stopped execution. 

Thank you for the kind replies
