### ISSUE TITLE
Got error when building uvc.cpp

### ISSUE THREAD

**Issue by skylook** [stevenlovegrove/Pangolin#91]
I have built & installed libuvc successfully, but when I build Pangolin, I still got errors bellow.
Any suggestions?

Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/uvc.cpp.o
Building C object src/CMakeFiles/pangolin.dir/fonts.c.o
/home/skylook/Develop/AR/Pangolin/src/video/drivers/uvc.cpp: In member function ‘void pangolin::UvcVideo::InitDevice(int, int, const char*, int, int, int, int)’:
/home/skylook/Develop/AR/Pangolin/src/video/drivers/uvc.cpp:157:11: error: ‘uvc_format_desc_t’ does not name a type
     const uvc_format_desc_t* uvc_fmt = uvc_get_format_descs(devh_);
           ^
/home/skylook/Develop/AR/Pangolin/src/video/drivers/uvc.cpp:158:12: error: ‘uvc_fmt’ was not declared in this scope
     while( uvc_fmt->bFormatIndex != ctrl_.bFormatIndex && uvc_fmt ) {
            ^
/home/skylook/Develop/AR/Pangolin/src/video/drivers/uvc.cpp:162:8: error: ‘uvc_fmt’ was not declared in this scope
     if(uvc_fmt) {
        ^
make[2]: *** [src/CMakeFiles/pangolin.dir/video/drivers/uvc.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2

**Comment by stevenlovegrove** [comment]
Sounds like a Pangolin / libuvc version mismatch. You can try the devel branch of pangolin and the latest from https://github.com/ktossell/libuvc

**Comment by half-potato** [comment]
You could also do a quick fix and remove UVC support: https://github.com/stevenlovegrove/Pangolin/issues/90 

I tried devel Pangolin and building libuvc from source and it didn't work.

**Comment by stevenlovegrove** [comment]
I've just checked - I'm at libuvc SHA e71bcbe119798b150fa9eefa2a5745288fd3a2eb. If anyone wants to disable libuvc in Pangolin, you can set uvc_LIBRARIES to the empty string using ccmake / cmake-gui. I'll keep this issue open to remind me to try the latest version of libuvc at some point in the future.

As an alternative, on Linux, you can use the v4l:// scheme in Pangolin to open most uvc cameras.

**Comment by apatzer** [comment]
If you're on Mac OSX, solving this issue is as simple as
```
brew reinstall libuvc --HEAD
```

**Comment by ahundt** [comment]
@apatzer  I can confirm this fix works

**Comment by stevenlovegrove** [comment]
Great. So in summary - update to the latest libuvc. Closing this for now.
