### ISSUE TITLE
Build failed on ubuntu20.04

### ISSUE THREAD

**Issue by northpoleforce** [stevenlovegrove/Pangolin#913]
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```
run `./scripts/install_prerequisites.sh recommended`
show `E: Unable to locate package catch2`

**Comment by northpoleforce** [comment]
I search `catch2` in ubuntu, but found it only available after `ubuntu22.04` version
https://packages.ubuntu.com/search?keywords=catch2&searchon=names&suite=all&section=all

**Comment by christian-rauch** [comment]
The [CI](https://github.com/stevenlovegrove/Pangolin/blob/52e84ae29b76929d69cff818d05ec5516270d8ca/.github/workflows/build.yml#L19-L24) only tests the latest Ubuntu LTS version (22.04). `catch2` is only required for the tests. If you have to build on Ubuntu 20.04, you can remove it temporarily from the script and build without tests.

**Comment by northpoleforce** [comment]
> The [CI](https://github.com/stevenlovegrove/Pangolin/blob/52e84ae29b76929d69cff818d05ec5516270d8ca/.github/workflows/build.yml#L19-L24) only tests the latest Ubuntu LTS version (22.04). `catch2` is only required for the tests. If you have to build on Ubuntu 20.04, you can remove it temporarily from the script and build without tests.

Yes, I build it successfully in this way. Thank you very much.🥰
