### ISSUE TITLE
Cannot open include file: 'pangolin/pangolin_export.h': No such File or Directory

### ISSUE THREAD

**Issue by twistxj** [stevenlovegrove/Pangolin#915]
I am compiling o n windows.  I am not using vs. I am just running the cmake —build . Command and I get that error. The file is where it is supposed to be. I am running it in  git bash.

**Comment by christian-rauch** [comment]
That header file used to be auto-generated on Windows and removed recently via 1bb1c59200187c103b9149269a84c093ea1b59fc in https://github.com/stevenlovegrove/Pangolin/pull/906. You should not see this issue on the newest master. How are you using Pangolin? Are you using a release build or a tagged version? Can you try on the current master?

**Comment by twistxj** [comment]
I am in the master branch. I am using it as depicted in this repo through python. But just to be clear I am having issues even installing pangolin. I haven’t even gotten a chance to use it as I get this error during the make build phase of the installation. 

https://github.com/uoip/stereo_msckf

**Comment by christian-rauch** [comment]
Are you also on the latest commit (52e84ae29b76929d69cff818d05ec5516270d8ca)? The repo does not contain any references to this file (`pangolin_export.h`) anymore.

Could you also provide a more detailed log to see where this header is imported?

**Comment by christian-rauch** [comment]
> i believe i am in the latest. Here is what git shows :
> commit 3ac794aff96c3db103ec2bbc298ab013eaf6f6e8 (HEAD -> master, origin/master, origin/HEAD)
> Merge: 015f3bf bb51f61
> Author: uoip [tinyfeimi@gmail.com](mailto:tinyfeimi@gmail.com)
> Date: Wed Jan 24 01:01:31 2018 +0800

There is no such commit in the Pangolin repo and even if there were, it would be more than 6 years old. You may use a Pangolin fork from someone else. Please only report issues to this repo if you use a stable release or the current master from this repo. Try again with the upstream repo (i.e. this one you are reporting the issue to).
