### ISSUE TITLE
cmake --build . error

### ISSUE THREAD

**Issue by Shanzhaguoo** [stevenlovegrove/Pangolin#920]
```
[ 19%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_tiff.cpp.o
[ 20%] Linking CXX shared library libpango_image.so
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libjpeg.a(jcapimin.c.o): relocation R_X86_64_PC32 against symbol `jpeg_natural_order' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/pango_image.dir/build.make:327: libpango_image.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:722: CMakeFiles/pango_image.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

I met a problem like this when I use the command"cmake --build .", could you told me how to solve it?

**Comment by christian-rauch** [comment]
The error message says `recompile with -fPIC`, but we already compile with [`CMAKE_POSITION_INDEPENDENT_CODE ON`](https://github.com/stevenlovegrove/Pangolin/blob/775f0c0d512a6042fae4aacf3cfdb77ae021db31/CMakeLists.txt#L22).

Are you using the latest Pangolin version? Did you follow the build instructions? Can you provide details on how you compile?
