### ISSUE TITLE
'GL/glew.h' file not found

### ISSUE THREAD

**Issue by GHFlibrary** [stevenlovegrove/Pangolin#922]
When using macbook m2 air configuration ORB - SLAM2 
```
/usr/local/include/pangolin/gl/glplatform. H: return: fatal error: 'gl/glew. H file not found 
#include <GL/glew.h> 
```
Please help me solve this thorny problem. Thank you

**Comment by christian-rauch** [comment]
Did you install all dependencies, especially GLEW, via `./scripts/install_prerequisites.sh`?
