### ISSUE TITLE
Getting error while compiling

### ISSUE THREAD

**Issue by SANGEERTH-P** [stevenlovegrove/Pangolin#929]
Dear sir
I am trying to install pangolin for doing some project suggested in [this](https://github.com/gaoxiang12/slambook2/tree/master/3rdparty) repository. I checked out that particular commit number and I am trying to compile the file. I am getting the following error while I am running the command 'make'.
![Screenshot from 2024-05-16 09-09-58](https://github.com/stevenlovegrove/Pangolin/assets/75566116/9ff11204-350a-4a10-9c25-ee464a2d98c6)
Can you please help me sort out this issue.

**Comment by christian-rauch** [comment]
Did you follow the installation instructions and installed all the dependencies? It looks like EGL (`libegl1-mesa-dev`) is missing.
