### ISSUE TITLE
Font rendering issue after update

### ISSUE THREAD

**Issue by mateosss** [stevenlovegrove/Pangolin#939]
When updating from 86eb4975 to one of the latest master commits 9d8fef79 in my project fonts look off. What could be the reason?

![before](https://github.com/stevenlovegrove/Pangolin/assets/5622899/cbe4c70a-a84c-4ead-b76d-949f335a4595)

![after](https://github.com/stevenlovegrove/Pangolin/assets/5622899/c4326cf6-bc80-4f03-b0a2-09b8697a50bb)

**Comment by christian-rauch** [comment]
There are 4 years of updates between these two commits. You would need to do a git bisect to find the commit that introduced the font rendering issue.

**Comment by christian-rauch** [comment]
After a git bisect I found that the last good commit is 3a1d89eb and that the next commit cba1ef20 introduces the issue.

| good (3a1d89eb)  | bad (cba1ef20) |
| ------------- | ------------- |
| ![pangolin_good_3a1d89eb](https://github.com/stevenlovegrove/Pangolin/assets/8226248/279e8b9c-a67c-4d28-a207-87a4ddff7023)  | ![pangolin_bad_cba1ef20](https://github.com/stevenlovegrove/Pangolin/assets/8226248/fe32c8a7-ed00-462c-b31c-700ccb8bd7c3) |
