### ISSUE TITLE
ERROR: Failed building wheel for pyopengl-accelerate

### ISSUE THREAD

**Issue by TheBigCodeman** [stevenlovegrove/Pangolin#941]
I get when I run (I am using Mac Mini M1)

```
cmake --build build -t pypangolin_pip_install
```

I have tried both 

```cmake -B build``` and ```cmake -B build -GNinja```

ERROR: Failed building wheel for pyopengl-accelerate
Failed to build pyopengl-accelerate
ERROR: Could not build wheels for pyopengl-accelerate, which is required to install pyproject.toml-based projects
ninja: build stopped: subcommand failed.

**Comment by christian-rauch** [comment]
The CI shows that `cmake --build build -t pypangolin_wheel` works: https://github.com/stevenlovegrove/Pangolin/actions/runs/9419601590/job/25949711735

Can you build the wheel by `cmake --build build -t pypangolin_wheel` and then install it manually via `pip install`?
