### ISSUE TITLE
vcpkg pangolin build failure on Windows. 

### ISSUE THREAD

**Issue by sai-yeswanth-g** [stevenlovegrove/Pangolin#944]
I tried to install pangolin using vcpkg but without adding 
`#include <cstdint>` 
to 
`components\pango_image\src\image_io_bmp.cpp`
`components\pango_image\src\image_io_jpg.cpp`
`components\pango_image\src\image_io_bmp.cpp`
I can't install pangolin. 
otherwise the build process complains uint8_t, uint16_t and  uint32_t are not declared. 
i'm using msys64 with gcc 14.0

**Comment by christian-rauch** [comment]
What exactly fails in vcpkg? The CI pipeline for Windows passes. Can you reproduce this on the CI?

**Comment by sai-yeswanth-g** [comment]
> What exactly fails in vcpkg? The CI pipeline for Windows passes. Can you reproduce this on the CI?

the symbols mentioned are reported as undefined. I have to use mingw and also new to using vcpkg. sorry that I can not provide any additional information. by  including library that contains those headers, the error goes away.

**Comment by christian-rauch** [comment]
Can you reproduce this on the CI and create a PR for it? Otherwise, I would close this issue unless more data on this can be gathered to reproduce.

**Comment by sai-yeswanth-g** [comment]
> Can you reproduce this on the CI and create a PR for it? Otherwise, I would close this issue unless more data on this can be gathered to reproduce.

I'm able to build it using Cl and I saw in the readme that mingw is not supported. I'm trying to use this with godot engine and many modules and libraries are compiled with mingw, so I had to make those changes to build it using mingw. thanks for your time.

**Comment by christian-rauch** [comment]
So, this is related to MinGW and not vcpkg? This could explain why you see the issue. The CI does not test the Windows builds with MinGW. Can you send a PR with the MinGW build on Windows and your fixes?

**Comment by sai-yeswanth-g** [comment]
> So, this is related to MinGW and not vcpkg? This could explain why you see the issue. The CI does not test the Windows builds with MinGW. Can you send a PR with the MinGW build on Windows and your fixes?

I can try, I'm still learning things and would need some time to properly do that.

**Comment by christian-rauch** [comment]
I am going to close this as there does not seem to be too much interest in supporting MinGW on Windows. If it helps, you can still send a PR with your fixes. Just note, that MinGW support could then break any time later.
