### ISSUE TITLE
Compile pangolin with android on ubuntu

### ISSUE THREAD

**Issue by FangGet** [stevenlovegrove/Pangolin#95]
when I compile pangolin with android like:
CMAKE -D ANDROID=1 ..
it works fine and build file had generated successfully. But when excute"make -j"，it 
reminds me errors like "<android/log.h> was not found".
I have set environment variable ANDROID_SDK and ANDROID_NDK.
That's why? thanks.

**Comment by stevenlovegrove** [comment]
You will need to provide cmake with a toolchain file in order to use the NDK toolchain. I haven't tried this for some time (so you make have to make some small code fixes), but I was using the android-cmake instructions (https://github.com/taka-no-me/android-cmake). This toolchain will define ANDROID automatically and Pangolin should generate some APK's and extra make targets for pushing and running on device through ADB.

**Comment by jhz-jkyang** [comment]
why when I compile pangolin for android on ubuntu ,there are some errors like this:
error: pangolin/gl/gl_es_compat.h: No such file or directory. I find this file in include/pangolin/gl/compat/ and I move this file to include/pangolin/gl/ then when I make I got some warnings like this warning: "GL_COLOR_ATTACHMENT0_EXT" redefined

**Comment by jhz-jkyang** [comment]
@FangGet do you compile success?

**Comment by stevenlovegrove** [comment]
@jhz-jkyang When I was building Pangolin on Android, Android did not support the same OpenGL calls, so I built a small compatibility layer to work in OpenGL-ES. If GL_COLOR_ATTACHMENT0_EXT is being redefined, it means that the wrong OpenGL API is somehow getting included by mistake by some header, or OpenGL-ES now defines some extra things that were originally omitted. Are there many errors in compilation? I would expect that you may need to make some changes to gl_es_compat.h

**Comment by jhz-jkyang** [comment]
@stevenlovegrove My android version is 4.4.2 and it use OpenGL-ES2. I fond that when compile with HAVE_GLES_2 = 1 there will be errors witch I said

**Comment by FangGet** [comment]
yesterday I restarted my step to compile pangolin to Android,and after some revisions of CMakeList and source file, I finally complete it successfully and an ".so" file has been  @jhz-jkyang . I'd like to know how should I use it in android? @stevenlovegrove  just keep it the same as how it's used in other C++ project or something else?

**Comment by FangGet** [comment]
I get it when I import examples at Eclipse!! @stevenlovegrove

**Comment by stevenlovegrove** [comment]
You should theoretically be able to keep it the same. On Android, you should hopefully see some special make targets for creating the APK, and even launching it on your device via ADB. Try the pangolin sample 'HelloPangolin' first. If that doesn't work, nothing will.
`make HelloPangolin-run`

**Comment by FangGet** [comment]
yeah,I had tried it last night and it works well, thank you very much! There are some differences between normal opengl and opengl es:
1. All variables with a "BGR" string like "GL_BGRA" and "GL_BGR8" don't exist in GLES/GLES2
2. You CMakeList make GLES and GLES2 mutually exclusive while both of them should be used.
Thanks again.

**Comment by stevenlovegrove** [comment]
Great! I'm happy it is working for you. I guess you're on the master branch? There is a change to windowing that may have broken it on the devel branch. It should be relatively easy to update though.

**Comment by FangGet** [comment]
yes, on master branch,thanks again!👍

**Comment by fszeliga** [comment]
hey, i was just wondering if you recently tried to compile pangolin on android? would like to know if it works properly, and the overall overhead to get it running before i get my hands dirty with android and ndk :D

**Comment by stevenlovegrove** [comment]
The status hasn't really changed from the conversation above, though the devel branch windowing changes are now in master. I don't think it should be too difficult to get it working again on Android, but there is no way that it will build out of the box right now, sorry!

If you like, you could try starting from a commit dated around Aug 8th 2016 :)

**Comment by xinliangyu** [comment]
@stevenlovegrove  when i compile pangolin on arm platform with tina linux, which has opengles library.
how should i select android or linux path in cmakelist file?

**Comment by stevenlovegrove** [comment]
See my comment above (https://github.com/stevenlovegrove/Pangolin/issues/95#issuecomment-205946963) - follow directions from https://github.com/taka-no-me/android-cmake to use android toolchain file.

**Comment by xinliangyu** [comment]
@FangGet  你好，我现在需要在linux的编译服务器上，用交叉编译器生成适合于运行在arm平台linux系统平板上，其中系统自带了的opengles和libmali的链接库。在编译的过程中根据编译器识别出系统为linux的，然后没有选择依赖opengles库，而我本地也没有glew和glut库，所以出现缺少依赖库的问题，我尝试逐个添加依赖库，后期发现依赖太多，实现较难。不知道你有没有好的建议？

**Comment by FangGet** [comment]
try provide standalone toolchain file to compile? For your case, you may need to provide a arm-linux-toolchain for it compile with Linux, try download one and run with:
cmake -DCMAKE_TOOLCHAIN_FILE=/path/to/your/toolchain/ ..
BTW, please use English for this repo @xinliangyu

**Comment by xinliangyu** [comment]
@FangGet  thanks for your reply。
Actually I'm  using a arm-linux  toolchain for my platform to cross compiling.  
And I add the following information to my cmakelist file:

SET(CMAKE_C_COMPILER "/home/XL/tina3/prebuilt/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/bin/arm-openwrt-linux-gcc")
SET(CMAKE_CXX_COMPILER "/home/XL/tina3/prebuilt/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/bin/arm-openwrt-linux-g++")
SET( CMAKE_CXX_FLAGS "-std=c++11 -O3")
SET(OPENGL_gl_LIBRARY "/home/XL/tina3/package/libs/mali400-um/R16/fbdev/lib/libEGL.so")

So which path I should select in cmakelist? android or linux?
if(ANDROID OR IOS)	
     set(HAVE_GLES 1)
     option(BUILD_FOR_GLES_2 "Build for OpenGL ES 2 instead of ES 1" ON )
     if(BUILD_FOR_GLES_2)
         set(HAVE_GLES_2 1)
     endif()
 endif()

src/cmakelist
if(BUILD_PANGOLIN_GUI)
    if( ANDROID  )
        # Android specific display code
        list(APPEND HEADERS ${INCDIR}/display/device/display_android.h )
        list(APPEND SOURCES display/device/display_android.cpp )

        if(HAVE_GLES_2)
            list(APPEND LINK_LIBS "-lEGL;-lGLESv2" )
        else()
            list(APPEND LINK_LIBS "-lEGL;-lGLESv1_CM" )
        endif()
    elseif( IOS )
        list(APPEND LINK_LIBS "-framework OpenGLES" )
        list(APPEND HEADERS "${INCDIR}/ios/PangolinAppDelegate.h" "${INCDIR}/ios/PangolinViewController.h" )
        list(APPEND SOURCES "ios/PangolinAppDelegate.mm" "ios/PangolinViewController.mm" )
    else()
        find_package(OpenGL REQUIRED QUIET)
        list(APPEND USER_INC  "${OPENGL_INCLUDE_DIR}" )
        list(APPEND LINK_LIBS "${OPENGL_LIBRARIES}" )

        if(NOT BUILD_EXTERN_GLEW)
            find_package(GLEW REQUIRED QUIET)
        endif()
        if(GLEW_FOUND)
            list(APPEND USER_INC  "${GLEW_INCLUDE_DIR}" )
            list(APPEND LINK_LIBS "${GLEW_LIBRARY}" )
            set(HAVE_GLEW 1)
        endif()
    endif()

    if( HAVE_GLES_2 )
        # Add Pangolins backwards compat layer.
        list(APPEND HEADERS ${INCDIR}/gl2engine.h )
        list(APPEND SOURCES gl2engine.cpp)
    endif()
endif()

**Comment by xinliangyu** [comment]
@stevenlovegrove   thanks youre reply. I have read  (#95 (comment))  and  https://github.com/taka-no-me/android-cmake，but still have some questions to make pangolin.
First, I  have a arm-linux toolchain for cross compiling for the platform.
Second, my platform is armv7 which the system is linux, instead of android, and have opengles and mali libraries.
So, I change my cmakelist with the following messages.
SET(CMAKE_C_COMPILER "/home/XL/tina3/prebuilt/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/bin/arm-openwrt-linux-gcc")
SET(CMAKE_CXX_COMPILER "/home/XL/tina3/prebuilt/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/bin/arm-openwrt-linux-g++")
SET( CMAKE_CXX_FLAGS "-std=c++11 -O3")
SET(OPENGL_gl_LIBRARY "/home/XL/tina3/package/libs/mali400-um/R16/fbdev/lib/libEGL.so")

Now my question is which path  should I select?
if(ANDROID OR IOS)	
     set(HAVE_GLES 1)
     option(BUILD_FOR_GLES_2 "Build for OpenGL ES 2 instead of ES 1" ON )
     if(BUILD_FOR_GLES_2)
         set(HAVE_GLES_2 1)
     endif()
 endif()

and in src/cmakelist file 
if(BUILD_PANGOLIN_GUI)
    if( ANDROID  )
        # Android specific display code
        list(APPEND HEADERS ${INCDIR}/display/device/display_android.h )
        list(APPEND SOURCES display/device/display_android.cpp )

        if(HAVE_GLES_2)
            list(APPEND LINK_LIBS "-lEGL;-lGLESv2" )
        else()
            list(APPEND LINK_LIBS "-lEGL;-lGLESv1_CM" )
        endif()
    elseif( IOS )
        list(APPEND LINK_LIBS "-framework OpenGLES" )
        list(APPEND HEADERS "${INCDIR}/ios/PangolinAppDelegate.h" "${INCDIR}/ios/PangolinViewController.h" )
        list(APPEND SOURCES "ios/PangolinAppDelegate.mm" "ios/PangolinViewController.mm" )
    else()
        find_package(OpenGL REQUIRED QUIET)
        list(APPEND USER_INC  "${OPENGL_INCLUDE_DIR}" )
        list(APPEND LINK_LIBS "${OPENGL_LIBRARIES}" )

        if(NOT BUILD_EXTERN_GLEW)
            find_package(GLEW REQUIRED QUIET)
        endif()
        if(GLEW_FOUND)
            list(APPEND USER_INC  "${GLEW_INCLUDE_DIR}" )
            list(APPEND LINK_LIBS "${GLEW_LIBRARY}" )
            set(HAVE_GLEW 1)
        endif()
    endif()

    if( HAVE_GLES_2 )
        # Add Pangolins backwards compat layer.
        list(APPEND HEADERS ${INCDIR}/gl2engine.h )
        list(APPEND SOURCES gl2engine.cpp)
    endif()
endif()

**Comment by stevenlovegrove** [comment]
@xinliangyu please expect to have to make some code changes for a new platform. Even the Android code path is probably broken a little. The difference between the Android and Linux path is really about how the event loop is driven and which GL API is used. For Android is uses the Android NDK to create a render context and and OpenGL ES for rendering. For Linux, is uses X11 to create windows and desktop OpenGL for rendering. If you have neither android or X11, you'll need to role something yourself by creating the gl binding (https://github.com/stevenlovegrove/Pangolin/tree/master/src/display/device)
