### ISSUE TITLE
Compiling Pandolin for Windows

### ISSUE THREAD

**Issue by jshtok** [stevenlovegrove/Pangolin#97]
Hi Steven,

I am trying to build the Pandolin on Windows as a Visual Studio project, and I run into multiple problems. I've disabled some parts of the code related to video drivers (I guess they are Linux-specific), but many more errors are coming. Is there a hope to to that at all?

Thanks,
Joseph

**Comment by stevenlovegrove** [comment]
@jshtok Yes - Pangolin does build on Windows. I'd recommend trying to build the devel branch if you haven't already. I've tested it recently with Visual Studio 2015. If errors persist, paste the output here.

**Comment by stevenlovegrove** [comment]
Closing for now. Please reopen if you have more feedback.

**Comment by HiOtto** [comment]
@stevenlovegrove I used cmake-gui compiling the devel branch with VS2010, turning BUILD_PANGOLIN_GUI and BUILD_PANGOLIN_VIDEO off, BUILD_PANGOLIN_VARS on, closing all automatically download with only glew pre-installed, CPP11_NO_BOOST on, BUILD_EXAMPLES off. 

CMAKE Results:
Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
Performing Test COMPILER_HAS_DEPRECATED_ATTR
Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
Performing Test COMPILER_HAS_DEPRECATED
Performing Test COMPILER_HAS_DEPRECATED - Success
Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
Configuring done
Generating done

Then things went wrong with VS2010:
ClCompile:
1>  threadedfilebuf.cpp
1>F:\Pangolin-devel\include\pangolin/compat/thread.h(34): fatal error C1083: Cannot open include file:“thread”: No such file or directory
1>  packetstream.cpp
1>F:\Pangolin-devel\include\pangolin/compat/thread.h(34): fatal error C1083: Cannot open include file:“thread”: No such file or directory

I doubt if there it something relevant to boost? Or I turned off some necessary options incorrectly?

**Comment by stevenlovegrove** [comment]
VS 2010 is a very old compiler and I wouldn't be confident that it supports C++11's <thread> header. Your options are to use Boost instead, upgrade to a more recent (free) Visual Studio, or to remove threadedfilebuf.cpp from CMakelists (you probably don't need it if you've disabled BUILD_PANGOLIN_VIDEO).

**Comment by HiOtto** [comment]
VS2010 does not support C++11，and I passed installation with Boost by adding a template:
namespace std
{
	template<typename T> bool isfinite(T arg)
	{
		return arg == arg && 
			arg != std::numeric_limits<T>::infinity() &&
			arg != -std::numeric_limits<T>::infinity();
	}
}

BTW， compiler reminds me it can't find a boost lib when I'm using pangolin:
1>LINK : fatal error LNK1104: cannot open file “libboost_thread-vc100-mt-sgd-1_50.lib”

I did "runtimelink=shared" with boost installation, aka, there should be “libboost_thread-vc100-mt-gd-1_50.lib”, not  “libboost_thread-vc100-mt-sgd-1_50.lib” in the $EVN{BOOST_ROOT}/lib dir. 

How should I do to change the pangolin's link mode to Boost?

**Comment by HiOtto** [comment]
PS: 
I changed my pangolin-using project to use MTd.  From the Property Pages select Configuration Properties ==> C/C++ ==> Code Generation ==> Runtime Library ==> Multi-threaded (/MT).

**Comment by HiOtto** [comment]
Well, I fixed this buy adding boost-binaries of "sgd" version .....
But in your ${CMAKE_INSTALL_PREFIX}/lib/cmake/PangolinTargets-debug.cmake:
set_target_properties(pangolin PROPERTIES
             ...........
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG
 "C:/Program Files/Boost/lib/boost_thread-vc100-mt-gd-1_50.lib;
  C:/Program Files/Boost/lib/boost_filesystem-vc100-mt-gd-1_50.lib;
  C:/Program Files/Boost/lib/boost_system-vc100-mt-gd-1_50.lib;
  C:/Program Files/Boost/lib/boost_chrono-vc100-mt-gd-1_50.lib;
  C:/Program Files/Boost/lib/boost_date_time-vc100-mt-gd-1_50.lib;
              .............    "
  )

They're all "gd" version ...... I'm feel pulzzed ......
