### ISSUE TITLE
build support for iOS

### ISSUE THREAD

**Issue by wenjunqwq** [stevenlovegrove/Pangolin#98]
Hello,

How can i build Pangolin for iOS?
Any instructions for this?

**Comment by stevenlovegrove** [comment]
Sorry for overlooking this question. I have not built for iOS for a couple of years now, so I expect some small code changes may be required in Pangolin to restore compatibility. You will need an iOS cmake toolchain configuration file, similar to https://code.google.com/archive/p/ios-cmake. Check out the wiki for ios-cmake for instructions.
